### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by avlemos** [PhilJay/MPAndroidChart#1000]
java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
            at com.github.mikephil.charting.renderer.LineChartRenderer.drawLinear(LineChartRenderer.java:295)
            at com.github.mikephil.charting.renderer.LineChartRenderer.drawDataSet(LineChartRenderer.java:121)
            at com.github.mikephil.charting.renderer.LineChartRenderer.drawData(LineChartRenderer.java:98)
            at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:230)

**Comment by PhilJay** [comment]
Are you adding data dynamically while rendering?

**Comment by avlemos** [comment]
yes, I am.

**Comment by PhilJay** [comment]
Are you calling `notifyDataSetChanged()` on the chart after adding?
Read this: https://github.com/PhilJay/MPAndroidChart/wiki/Dynamic-&-Realtime-Data

**Comment by avlemos** [comment]
I am:

mChart.moveViewToX(data.getXValCount() - 501);
mChart.notifyDataSetChanged();
mChart.invalidate();

**Comment by PhilJay** [comment]
moveViewToX will invalidate already, therefore you need to call notifyDataSetChanged() before

**Comment by avlemos** [comment]
so like this?

mChart.notifyDataSetChanged();
mChart.moveViewToX(data.getXValCount() - 501);
//mChart.invalidate();


ok, thanks

**Comment by PhilJay** [comment]
Yes, exactly!

**Comment by esfahanpayamak94** [comment]
اصفهان پیامک به عنوان فعال در زمینه [طراحی سایت در اصفهان](http://www.esfahanpayamak.com/webDesign) اهمیت این موضوع را به خوبی درک کرده و لذا از تکنولوژی های مدرن در طراحی های خود استفاده می نماید.
