### ISSUE TITLE
Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference

### ISSUE THREAD

**Issue by spierckel** [PhilJay/MPAndroidChart#1024]
Sometimes when I load my HorizontalBarChart It throw me an exception but not every time. 
I already made the check if there is at list one element in the chart before adding it.

This is the exception : 

    java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
       at com.github.mikephil.charting.data.ChartData.calcXValAverageLength(ChartData.java:158)
       at com.github.mikephil.charting.data.ChartData.init(ChartData.java:142)
       at com.github.mikephil.charting.data.ChartData.<init>(ChartData.java:102)
       at com.github.mikephil.charting.data.BarLineScatterCandleData.<init>(BarLineScatterCandleData.java:27)
       at com.github.mikephil.charting.data.BarData.<init>(BarData.java:35)
       at spierki.worldwidetalk.fragment.WordsErrorFragment.setData(WordsErrorFragment.java:115)
       at spierki.worldwidetalk.fragment.WordsErrorFragment.onCreateView(WordsErrorFragment.java:79)
       at android.support.v4.app.Fragment.performCreateView(Fragment.java:1789)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:955)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
       at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:458)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:211)
       at android.app.ActivityThread.main(ActivityThread.java:5373)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)

Thanks in advance

**Comment by PhilJay** [comment]
You probably added a null value to your x-values array. Provide "" instead.
