### ISSUE TITLE
Crash on LegendRenderer

### ISSUE THREAD

**Issue by viper123** [PhilJay/MPAndroidChart#1039]
Hello , we are having a crash from an application that is currently in production. It is more likely that we are doing something wrong with the Legend, but we don't know for sure and we are having a lot of charts in our application. Can you give us some pointers about this  crash?

java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
       at com.github.mikephil.charting.renderer.LegendRenderer.renderLegend(LegendRenderer.java:239)
       at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:256)
       at android.view.View.draw(View.java:15397)
       at android.view.View.getDisplayList(View.java:14291)
       at android.view.View.getDisplayList(View.java:14333)
       at android.view.View.draw(View.java:15111)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3318)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3155)
       at android.view.View.getDisplayList(View.java:14286)
       at android.view.View.getDisplayList(View.java:14333)
       at android.view.View.draw(View.java:15111)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3318)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3155)
       at android.view.View.draw(View.java:15400)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at android.widget.ScrollView.draw(ScrollView.java:2186)
       at android.view.View.getDisplayList(View.java:14291)
       at android.view.View.getDisplayList(View.java:14333)
       at android.view.View.draw(View.java:15111)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3318)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3155)
       at android.view.View.draw(View.java:15400)
       at android.support.v4.view.ViewPager.draw(ViewPager.java:2257)
       at android.view.View.getDisplayList(View.java:14291)
       at android.view.View.getDisplayList(View.java:14333)
       at android.view.View.draw(View.java:15111)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3318)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3155)
       at android.view.View.getDisplayList(View.java:14286)
       at android.view.View.getDisplayList(View.java:14333)
       at android.view.View.draw(View.java:15111)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3318)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3155)
       at android.view.View.getDisplayList(View.java:14286)
       at android.view.View.getDisplayList(View.java:14333)
       at android.view.View.draw(View.java:15111)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3318)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3155)
       at android.view.View.getDisplayList(View.java:14286)
       at android.view.View.getDisplayList(View.java:14333)
       at android.view.View.draw(View.java:15111)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3318)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3155)
       at android.view.View.getDisplayList(View.java:14286)
       at android.view.View.getDisplayList(View.java:14333)
       at android.view.View.draw(View.java:15111)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3318)
       at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1089)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3155)
       at android.view.View.draw(View.java:15400)
       at android.view.View.getDisplayList(View.java:14291)
       at android.view.View.getDisplayList(View.java:14333)
       at android.view.View.draw(View.java:15111)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3318)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3155)
       at android.view.View.draw(View.java:15400)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at android.view.View.getDisplayList(View.java:14291)
       at android.view.View.getDisplayList(View.java:14333)
       at android.view.View.draw(View.java:15111)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3318)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3155)
       at android.view.View.getDisplayList(View.java:14286)
       at android.view.View.getDisplayList(View.java:14333)
       at android.view.View.draw(View.java:15111)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3318)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3155)
       at android.view.View.draw(View.java:15400)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2583)
       at android.view.View.getDisplayList(View.java:14291)
       at android.view.View.getDisplayList(View.java:14333)
       at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1585)
       at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1457)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2779)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2645)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2213)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1256)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6635)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:813)
       at android.view.Choreographer.doCallbacks(Choreographer.java:613)
       at android.view.Choreographer.doFrame(Choreographer.java:583)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:799)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5593)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by PhilJay** [comment]
Are you adding data dynamically? Which version of the library are you using?

**Comment by viper123** [comment]
Yes, the data is added dynamically. Version : 2.1.3

**Comment by PhilJay** [comment]
Update to 2.1.4, and read [this](https://github.com/PhilJay/MPAndroidChart/wiki/Dynamic-&-Realtime-Data) - especially the last paragraphs.

**Comment by viper123** [comment]
I knew about all of that, I am using this library for almost a year. I fixed the issue creating the legend custom, not letting the legend to be self generated based on DataSets.
