### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference

### ISSUE THREAD

**Issue by ratnesh-ray** [PhilJay/MPAndroidChart#1054]
Sometimes when I load my Chart It throws an exception but not every time. Cant replicate the problem properly.

This is the exception :

java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
at com.github.mikephil.charting.d.f.a(Unknown Source)
	at com.github.mikephil.charting.d.f.a(Unknown Source)
	at com.github.mikephil.charting.d.f.<init>(Unknown Source)
	at com.github.mikephil.charting.d.l.<init>(Unknown Source)
	at com.beta.android.beewise.mainScreens.a.d.S(Unknown Source)
	at com.beta.android.beewise.mainScreens.a.d.T(Unknown Source)
	at com.beta.android.beewise.mainScreens.a.d.a(Unknown Source)
	at android.support.v4.app.Fragment.b(Unknown Source)
	at android.support.v4.app.w.a(Unknown Source)
	at android.support.v4.app.w.a(Unknown Source)
	at android.support.v4.app.e.run(Unknown Source)
	at android.support.v4.app.w.e(Unknown Source)
	at android.support.v4.app.w.b(Unknown Source)
	at android.support.v4.app.ae.b(Unknown Source)
	at android.support.v4.view.ViewPager.a(Unknown Source)
	at android.support.v4.view.ViewPager.c(Unknown Source)
	at android.support.v4.view.ViewPager.onMeasure(Unknown Source)
	at android.view.View.measure(View.java:17565)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
	at android.view.View.measure(View.java:17565)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
	at android.view.View.measure(View.java:17565)
	at android.support.v4.widget.DrawerLayout.onMeasure(Unknown Source)
	at android.view.View.measure(View.java:17565)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
	at android.view.View.measure(View.java:17565)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
	at android.support.v7.internal.widget.ActionBarOverlayLayout.onMeasure(Unknown Source)
	at android.view.View.measure(View.java:17565)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
	at android.view.View.measure(View.java:17565)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
	at android.view.View.measure(View.java:17565)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2615)
	at android.view.View.measure(View.java:17565)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2045)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1196)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1409)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1084)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5990)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:550)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:746)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5343)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by PhilJay** [comment]
Don't add `null` values to your x-values array.

**Comment by Agtmwgam** [comment]
do you had solved it? I alway get this question?
Unbelievable!!!

**Comment by SmallRoach** [comment]
Me too！how to do solved it? Please tell  me,  thank you!

**Comment by liuzhidanlilinxiang** [comment]
Me too,had you solved it?

**Comment by MingxuanChen** [comment]
me too

**Comment by ayulittlerain** [comment]
me too

**Comment by kouhengsheng** [comment]
me too

**Comment by max2416227158** [comment]
me too

**Comment by zhaoch2014** [comment]
me too

**Comment by icewating1991** [comment]
me too

**Comment by s1118124** [comment]
me too

**Comment by auranga** [comment]
me too

**Comment by geekykant** [comment]
me too :(

**Comment by Catherineliujj** [comment]
> do you had solved it? I alway get this question?
> Unbelievable!!!

u r so cute!!  and I love conan too!!  also i meet this problem!!

**Comment by xiaomengzi123** [comment]
me too，求解
