### ISSUE TITLE
java.lang.NullPointerException when loading chart

### ISSUE THREAD

**Issue by ratnesh-ray** [PhilJay/MPAndroidChart#1055]
Sometimes when I load my Chart It crashes, not always though

This is the exception :

java.lang.NullPointerException
	at com.github.mikephil.charting.d.f.a(Unknown Source)
	at com.github.mikephil.charting.d.f.a(Unknown Source)
	at com.github.mikephil.charting.d.f.<init>(Unknown Source)
	at com.github.mikephil.charting.d.l.<init>(Unknown Source)
	at com.beta.android.beewise.mainScreens.a.d.S(Unknown Source)
	at com.beta.android.beewise.mainScreens.a.d.T(Unknown Source)
	at com.beta.android.beewise.mainScreens.a.d.a(Unknown Source)
	at android.support.v4.app.Fragment.b(Unknown Source)
	at android.support.v4.app.w.a(Unknown Source)
	at android.support.v4.app.w.a(Unknown Source)
	at android.support.v4.app.e.run(Unknown Source)
	at android.support.v4.app.w.e(Unknown Source)
	at android.support.v4.app.w.b(Unknown Source)
	at android.support.v4.app.ae.b(Unknown Source)
	at android.support.v4.view.ViewPager.a(Unknown Source)
	at android.support.v4.view.ViewPager.c(Unknown Source)
	at android.support.v4.view.ViewPager.onMeasure(Unknown Source)
	at android.view.View.measure(View.java:16831)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1410)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
	at android.view.View.measure(View.java:16831)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	at android.view.View.measure(View.java:16831)
	at android.support.v4.widget.DrawerLayout.onMeasure(Unknown Source)
	at android.view.View.measure(View.java:16831)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	at android.view.View.measure(View.java:16831)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
	at android.support.v7.internal.widget.ActionBarOverlayLayout.onMeasure(Unknown Source)
	at android.view.View.measure(View.java:16831)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	at android.view.View.measure(View.java:16831)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1410)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
	at android.view.View.measure(View.java:16831)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2586)
	at android.view.View.measure(View.java:16831)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2191)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1354)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1537)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1251)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6379)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
	at android.view.Choreographer.doCallbacks(Choreographer.java:591)
	at android.view.Choreographer.doFrame(Choreographer.java:561)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
	at android.os.Handler.handleCallback(Handler.java:730)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5493)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1209)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1025)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by PhilJay** [comment]
Is the code somehow obfuscated? I cannot do anything with that error message.
Which version of the lib are you using?

**Comment by ratnesh-ray** [comment]
Yes, the bug is on production and I failed replicating it on local.
Using version 2.1.0

**Comment by PhilJay** [comment]
update to 2.1.4
