### ISSUE TITLE
Touch on an empty space causes ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by aint** [PhilJay/MPAndroidChart#1168]
![2015-11-01 20 45 44](https://cloud.githubusercontent.com/assets/3179252/10870778/b471c3d2-80db-11e5-9389-2809fc3f5354.png)
When I touch on the empty space (highlighted in red) I get the following stack trace
```java
java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
at com.github.mikephil.charting.highlight.BarHighlighter.getClosestStackIndex(BarHighlighter.java:136)
at com.github.mikephil.charting.highlight.BarHighlighter.getStackedHighlight(BarHighlighter.java:106)
at com.github.mikephil.charting.highlight.BarHighlighter.getHighlight(BarHighlighter.java:37)
at com.github.mikephil.charting.charts.BarChart.getHighlightByTouchPoint(BarChart.java:99)
at com.github.mikephil.charting.charts.BarLineChartBase.getDataSetByTouchPoint(BarLineChartBase.java:1231)
at com.github.mikephil.charting.listener.BarLineChartTouchListener.saveTouchStart(BarLineChartTouchListener.java:248)
at com.github.mikephil.charting.listener.BarLineChartTouchListener.onTouch(BarLineChartTouchListener.java:93)
at com.github.mikephil.charting.charts.BarLineChartBase.onTouchEvent(BarLineChartBase.java:661)
at android.view.View.dispatchTouchEvent(View.java:7149)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2178)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1911)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2184)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1883)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2184)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1883)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2184)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1883)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2184)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1883)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2184)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1883)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2184)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1883)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2184)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1883)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2184)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1883)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2184)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1883)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2184)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1883)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2184)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1883)
at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1959)
at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1399)
at android.app.Activity.dispatchTouchEvent(Activity.java:2428)
at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1907)
at android.view.View.dispatchPointerEvent(View.java:7329)
at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3280)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3219)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4265)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4244)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4341)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:171)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:125)
at android.os.Looper.loop(Looper.java:124)
at android.app.ActivityThread.main(ActivityThread.java:5059)
```

```java
List<BarEntry> yValues = new ArrayList<>();
yValues.add(new BarEntry(new float[]{ -1000, 750, 250, 2000, 3000 }, 0));
...
mChart.invalidate();
```

**Comment by aint** [comment]
It still occurs in in 2.1.6.
```java
java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
at com.github.mikephil.charting.highlight.BarHighlighter.getClosestStackIndex(BarHighlighter.java:136)
at com.github.mikephil.charting.highlight.BarHighlighter.getStackedHighlight(BarHighlighter.java:106)
at com.github.mikephil.charting.highlight.BarHighlighter.getHighlight(BarHighlighter.java:37)
at com.github.mikephil.charting.charts.BarChart.getHighlightByTouchPoint(BarChart.java:99)
at com.github.mikephil.charting.charts.BarLineChartBase.getDataSetByTouchPoint(BarLineChartBase.java:1243)
at com.github.mikephil.charting.listener.BarLineChartTouchListener.saveTouchStart(BarLineChartTouchListener.java:248)
at com.github.mikephil.charting.listener.BarLineChartTouchListener.onTouch(BarLineChartTouchListener.java:93)
at com.github.mikephil.charting.charts.BarLineChartBase.onTouchEvent(BarLineChartBase.java:663)
at android.view.View.dispatchTouchEvent(View.java:7149)
...
```

**Comment by PhilJay** [comment]
Ok now it should be completely fixed :-)

**Comment by aint** [comment]
Thanks.
