### ISSUE TITLE
pls hlep me, i'm get java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by jaycho19** [PhilJay/MPAndroidChart#1221]
E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.ArrayIndexOutOfBoundsException
            at android.graphics.Canvas.drawLines(Native Method)
            at com.github.mikephil.charting.renderer.LineChartRenderer.drawLinear(LineChartRenderer.java:331)
            at com.github.mikephil.charting.renderer.LineChartRenderer.drawDataSet(LineChartRenderer.java:121)
            at com.github.mikephil.charting.renderer.LineChartRenderer.drawData(LineChartRenderer.java:98)
            at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:224)
            at android.view.View.draw(View.java:10978)
            at android.view.ViewGroup.drawChild(ViewGroup.java:2887)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
            at android.view.ViewGroup.drawChild(ViewGroup.java:2885)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
            at android.view.View.draw(View.java:10981)
            at android.widget.FrameLayout.draw(FrameLayout.java:450)
            at android.view.ViewGroup.drawChild(ViewGroup.java:2887)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
            at android.view.ViewGroup.drawChild(ViewGroup.java:2885)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
            at android.view.View.draw(View.java:10981)
            at android.widget.FrameLayout.draw(FrameLayout.java:450)
            at android.view.ViewGroup.drawChild(ViewGroup.java:2887)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
            at android.view.View.draw(View.java:10981)
            at android.support.v7.internal.widget.ActionBarOverlayLayout.draw(ActionBarOverlayLayout.java:500)
            at android.view.ViewGroup.drawChild(ViewGroup.java:2887)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
            at android.view.ViewGroup.drawChild(ViewGroup.java:2885)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
            at android.view.ViewGroup.drawChild(ViewGroup.java:2885)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
            at android.view.View.draw(View.java:10981)
            at android.widget.FrameLayout.draw(FrameLayout.java:450)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2126)
            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2026)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1634)
            at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2442)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4424)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by PhilJay** [comment]
no chance to do anything without code
