### ISSUE TITLE
NullPointerException with onDraw in BarLineChartBase

### ISSUE THREAD

**Issue by Mogmi95** [PhilJay/MPAndroidChart#1225]
Hi,

I'm displaying some graphs in a fragment (4 of them), and I see a lot of crashes with various devices.

The crash is as follow :

Fatal Exception: java.lang.NullPointerException
       at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:198)
       at android.view.View.draw(View.java:11022)
       at android.view.View.getDisplayList(View.java:10461)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
       at android.view.View.getDisplayList(View.java:10459)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
       at android.view.View.getDisplayList(View.java:10459)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
       at android.view.View.getDisplayList(View.java:10459)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
       at io.codetail.widget.RevealFrameLayout.drawChild(RevealFrameLayout.java:112)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
       at android.view.View.getDisplayList(View.java:10459)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
       at android.view.View.getDisplayList(View.java:10459)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
       at android.view.View.getDisplayList(View.java:10459)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
       at android.view.View.getDisplayList(View.java:10459)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
       at android.view.View.getDisplayList(View.java:10459)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
       at android.view.View.getDisplayList(View.java:10459)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
       at android.view.View.getDisplayList(View.java:10459)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
       at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1229)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
       at android.view.View.getDisplayList(View.java:10459)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
       at android.view.View.draw(View.java:11025)
       at android.widget.FrameLayout.draw(FrameLayout.java:452)
       at android.view.View.getDisplayList(View.java:10461)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
       at android.view.View.getDisplayList(View.java:10459)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
       at android.view.View.getDisplayList(View.java:10459)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
       at android.view.View.getDisplayList(View.java:10459)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
       at android.view.View.draw(View.java:11025)
       at android.widget.FrameLayout.draw(FrameLayout.java:452)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2164)
       at android.view.View.getDisplayList(View.java:10461)
       at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:912)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:1976)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1694)
       at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2581)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4697)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:554)
       at dalvik.system.NativeStart.main(NativeStart.java)

I can't manage to reproduce it myself.

**Comment by PhilJay** [comment]
Are you using the latest version?
Are you using a custom `Renderer` (via `setRenderer(...)`) object that can be null?

**Comment by Mogmi95** [comment]
Yes, I'm using version 2.1.6.
I'm not using any custom Renderer either.

The graphs are in a Fragment. It is possible that they try to update while the Fragment is going to be destroyed, but I really can't reproduce it here...

**Comment by PhilJay** [comment]
Well its a weird error because the exception occurs at a stage in code where the object cannot be null without external influence.
