### ISSUE TITLE
ArrayOutOfBoundsException

### ISSUE THREAD

**Issue by sivipi** [PhilJay/MPAndroidChart#1263]
Hi there,
I have seen this issue had happened before in Bar Charts and now I have the same issue with LineChart.

I am adding data dynamically, fast, reading from a live source of data (via usb) drawing the chart as it goes.

thanks,

Sivan

12-09 10:05:01.120 22000-22000/com.vayyar.walabotapp1 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.vayyar.walabotapp1, PID: 22000
                                                                        java.lang.ArrayIndexOutOfBoundsException: length=1500; index=1500
                                                                            at com.github.mikephil.charting.buffer.LineBuffer.lineTo(LineBuffer.java:36)
                                                                            at com.github.mikephil.charting.buffer.LineBuffer.feed(LineBuffer.java:53)
                                                                            at com.github.mikephil.charting.renderer.LineChartRenderer.drawLinear(LineChartRenderer.java:301)
                                                                            at com.github.mikephil.charting.renderer.LineChartRenderer.drawDataSet(LineChartRenderer.java:124)
                                                                            at com.github.mikephil.charting.renderer.LineChartRenderer.drawData(LineChartRenderer.java:101)
                                                                            at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:247)
                                                                            at android.view.View.draw(View.java:16178)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:15174)
                                                                            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                            at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
                                                                            at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
                                                                            at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
                                                                            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2615)
                                                                            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2434)
                                                                            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2067)
                                                                            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                                            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                            at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by kekenny** [comment]
I also have this problem now. 
My code is below.
                              
      int index = macActivity.getBleService().getArrayOfHrmBleList().get(i).getRecord_heart_array_list().size();
      Entry entry_hr = new Entry(Float.parseFloat(heart_rate), index);

      long now_time = System.currentTimeMillis();
                                    macActivity.getBleService().getArrayOfHrmBleList().get(i).addRecordHeartRate(entry_hr, now_time);
                                    macActivity.getBleService().getArrayOfHrmBleList().get(i).getLineDataSet().notifyDataSetChanged();

      chart_benchmark.notifyDataSetChanged();
      chart_benchmark.invalidate();

I have multiple linedatasets and I add data into these linedatasets dynamically and quickly.
Before refresh the chart, I also notifyDataSetChanged with chart and linedataset.
I still can not avoid this issue.

Currently I only can add try catch in com.github.mikephil.charting.renderer.LineChartRenderer.
It will not to draw while this issue is catched.

    @Override
    public void drawData(Canvas c) {

        try {
            int width = (int) mViewPortHandler.getChartWidth();
            int height = (int) mViewPortHandler.getChartHeight();

            if (mDrawBitmap == null
                    || (mDrawBitmap.get().getWidth() != width)
                    || (mDrawBitmap.get().getHeight() != height)) {

                if (width > 0 && height > 0) {

                    mDrawBitmap = new WeakReference<Bitmap>(Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_4444));
                    mBitmapCanvas = new Canvas(mDrawBitmap.get());
                } else
                    return;
            }

            mDrawBitmap.get().eraseColor(Color.TRANSPARENT);

            LineData lineData = mChart.getLineData();

            for (ILineDataSet set : lineData.getDataSets()) {

                if (set.isVisible() && set.getEntryCount() > 0)
                    drawDataSet(c, set);
            }

            c.drawBitmap(mDrawBitmap.get(), 0, 0, mRenderPaint);
        }catch (Exception ex){
            Log.d("TAG", ex.toString());
        }
    }
