### ISSUE TITLE
UnsupportedOperationException in BarLineChart

### ISSUE THREAD

**Issue by JumpMaster** [PhilJay/MPAndroidChart#1265]
Hi,

If this isn't enough information to look into the issue feel free to close this issue.  This log was sent to the Play Store but the user has contacted me directly.  The users setup works fine on my Nexus 5X but is crashing with the below stack trace on their S2.  Any feedback on how to help resolve the issue would be great.  My app is currently in beta so I'm trying to remove as many bugs as possible.

Thanks,
Kev

java.lang.UnsupportedOperationException
	at android.view.GLES20Canvas.clipPath(GLES20Canvas.java:424)
	at com.github.mikephil.charting.renderer.LineChartRenderer.drawFilledPath(LineChartRenderer.java:370)
	at com.github.mikephil.charting.renderer.LineChartRenderer.drawLinearFill(LineChartRenderer.java:356)
	at com.github.mikephil.charting.renderer.LineChartRenderer.drawLinear(LineChartRenderer.java:342)
	at com.github.mikephil.charting.renderer.LineChartRenderer.drawDataSet(LineChartRenderer.java:124)
	at com.github.mikephil.charting.renderer.LineChartRenderer.drawData(LineChartRenderer.java:101)
	at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:247)
	at android.view.View.draw(View.java:11184)
	at android.view.View.getHardwareLayer(View.java:10422)
	at android.view.ViewGroup.drawChild(ViewGroup.java:2868)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2494)
	at android.view.View.draw(View.java:11187)
	at android.view.View.getDisplayList(View.java:10623)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2602)
	at android.view.View.getDisplayList(View.java:10586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2602)
	at android.view.View.getDisplayList(View.java:10586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2602)
	at android.view.View.getDisplayList(View.java:10586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2602)
	at android.view.View.getDisplayList(View.java:10586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2602)
	at android.view.View.getDisplayList(View.java:10586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2602)
	at android.view.View.getDisplayList(View.java:10586)
	at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:878)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2092)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1816)
	at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2628)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4511)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:976)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:743)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by xizzhu** [comment]
Duplicated with https://github.com/PhilJay/MPAndroidChart/issues/1100

**Comment by PhilJay** [comment]
Fixed: 0d1894770ce889a20a3d90108b5a72818a5d0bca
