### ISSUE TITLE
java.lang.NegativeArraySizeException

### ISSUE THREAD

**Issue by leijdekkers** [PhilJay/MPAndroidChart#1268]
Hi

I upgraded from MPAndroid v2.1.0 to v2.1.6  and i get now this runtime error in a combined chart consisting of LineData and CandleData. Any idea what goes wrong? Was working before in V2.1.0

Thanks Peter

  java.lang.NegativeArraySizeException: -2
                                                                          at com.github.mikephil.charting.utils.Transformer.generateTransformedValuesCandle(Transformer.java:183)
                                                                          at com.github.mikephil.charting.renderer.CandleStickChartRenderer.drawValues(CandleStickChartRenderer.java:246)
                                                                          at com.github.mikephil.charting.renderer.CombinedChartRenderer.drawValues(CombinedChartRenderer.java:90)
                                                                          at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:271)
                                                                          at android.view.View.draw(View.java:16472)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:15402)
                                                                          at android.view.View.getDisplayList(View.java:15424)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3693)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3672)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:15362)
                                                                          at android.view.View.getDisplayList(View.java:15424)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3693)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3672)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:15362)
                                                                          at android.view.View.getDisplayList(View.java:15424)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3693)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3672)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:15362)
                                                                          at android.view.View.getDisplayList(View.java:15424)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3693)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3672)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:15362)
                                                                          at android.view.View.getDisplayList(View.java:15424)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3693)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3672)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:15362)
                                                                          at android.view.View.getDisplayList(View.java:15424)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3693)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3672)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:15362)
                                                                          at android.view.View.getDisplayList(View.java:15424)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3693)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3672)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:15362)
                                                                          at android.view.View.getDisplayList(View.java:15424)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3693)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3672)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:15362)
                                                                          at android.view.View.getDisplayList(View.java:15424)
                                                                          at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:310)
                                                                          at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:316)
                                                                          at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:355)
                                                                          at android.view.ViewRootImpl.draw(ViewRootImpl.java:2889)
                                                                          at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2683)
                                                                          at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2270)
                                                                          at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1264)
                                                                          at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6944)
                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:590)
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:560)
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)

**Comment by leijdekkers** [comment]
Ok i solved it by forcing both sets to have exactly the same number of items in their dataset. I think there is a bug in the Candle class since i tested it with the Bar set  using different dataset sizes and no problem. Maybe something to check?

**Comment by ErfanThinker** [comment]
I've having the same problem

**Comment by Jur4s** [comment]
Got the same issue :
java.lang.NegativeArraySizeException: -2
at com.github.mikephil.charting.utils.Transformer.generateTransformedValuesLine(Transformer.java:181)
at com.github.mikephil.charting.renderer.LineChartRenderer.drawValues(LineChartRenderer.java:570)
at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:272)
at android.view.View.draw(View.java:16178)
at android.view.View.updateDisplayListIfDirty(View.java:15174)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
at android.view.View.updateDisplayListIfDirty(View.java:15134)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
at android.view.View.updateDisplayListIfDirty(View.java:15134)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
at android.view.View.updateDisplayListIfDirty(View.java:15134)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
at android.view.View.updateDisplayListIfDirty(View.java:15134)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
at android.view.View.updateDisplayListIfDirty(View.java:15134)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
at android.view.View.updateDisplayListIfDirty(View.java:15134)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
at android.view.View.updateDisplayListIfDirty(View.java:15134)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
at android.view.View.updateDisplayListIfDirty(View.java:15134)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
at android.view.View.updateDisplayListIfDirty(View.java:15134)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
at android.view.View.updateDisplayListIfDirty(View.java:15134)
at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:2615)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2434)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2067)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
at android.view.Choreographer.doCallbacks(Choreographer.java:670)
at android.view.Choreographer.doFrame(Choreographer.java:606)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by ErfanThinker** [comment]
refer to #2074

**Comment by Jur4s** [comment]
@ErfanThinker thx, didn't see this thread. It's resolved my problem.
