### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method setData

### ISSUE THREAD

**Issue by tahaa7** [PhilJay/MPAndroidChart#1284]
When trying to draw a graph, I get the following error in Android Studio:

FATAL EXCEPTION: main
                                                                                 Process: ilj.tel.fer.hr.smarthomemonitor, PID: 10455
                                                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{ilj.tel.fer.hr.smarthomemonitor/ilj.tel.fer.hr.smarthomemonitor.TempOnlyIndoorActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.github.mikephil.charting.charts.LineChart.setData(com.github.mikephil.charting.data.ChartData)' on a null object reference
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2305)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2367)
                                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:148)
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5274)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
                                                                                  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.github.mikephil.charting.charts.LineChart.setData(com.github.mikephil.charting.data.ChartData)' on a null object reference
                                                                                     at ilj.tel.fer.hr.smarthomemonitor.TempOnlyIndoorActivity.mainActivity(TempOnlyIndoorActivity.java:175)
                                                                                     at ilj.tel.fer.hr.smarthomemonitor.TempOnlyIndoorActivity.onCreate(TempOnlyIndoorActivity.java:69)
                                                                                     at android.app.Activity.performCreate(Activity.java:5977)
                                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2258)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2367) 
                                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:148) 
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                     at android.os.Looper.loop(Looper.java:135) 
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5274) 
                                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909) 
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704) 

I have attached a zip file containing my TempOnlyIndoor class as well as my JsonStringFetcher class.

Please help, I'm stuck with this error. I have verified that all the data in the dataSet is good, so it's not an issue with fetching anything from the server.

**Comment by PhilJay** [comment]
Your app crashes because your `LineChart` object is null. Make sure you either have set it up correctly in xml or that you create a `LineChart` object at some point in code.

**Comment by chandu4271** [comment]
include this line   XAxis xAxis = chart.getXAxis(); 

before following code 
xAxis.setValueFormatter(new MyValueFormatter() {
            private final SimpleDateFormat mFormat = new SimpleDateFormat("dd MMM HH:mm", Locale.ENGLISH);

            @Override
            public String getFormattedValue(float value) {

                long millis = TimeUnit.SECONDS.toMillis((long) value);
                return mFormat.format(new Date(millis));
            }
        });

**Comment by zafar786** [comment]
CombinedData data = new CombinedData();
 
switch(data)
{
// Only for BarChart 
case BarChart
   LineData ld = new LineData();
        ld.clearValues();
        chartData.setData(ld);
        chartData.setData(barData);
break;

// Only for LineChart 
case LineChart
    BarData bd = new BarData();
        bd.clearValues();
        chartData.setData(bd);
        chartData.setData(lineData);
break;

// Both the Chart (Line & Bar Chart)
case BothChart 
 chartData.setData(lineData);
 chartData.setData(barData);
}

**Comment by jackDante** [comment]
Remember to edit the correct name of your Activity in:
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.**activity_accelerometer**);

otherwise you have a FATAL EXCEPTION!!!

**Comment by tensorfoo** [comment]
Just ran into this too. I've copied pasted the XML out of the example webpage, if it's null it's because the library is buggy.
