### ISSUE TITLE
Crash after adding BarEntry to BarDataSet and invalidating chart

### ISSUE THREAD

**Issue by torfinnberset** [PhilJay/MPAndroidChart#1370]
After displaying the chart (works ok), appending a BarEntry to my BarDataSet (which is in a CombinedDataSet with a LineDataSet), redrawing the plot causes the following crash. Appending Entry's to the LineDataSet does not cause any problems. 

```
01-14 15:54:18.653 17947-17947/life.bloom.tesora E/AndroidRuntime: FATAL EXCEPTION: main
Process: life.bloom.tesora, PID: 17947
java.lang.ArrayIndexOutOfBoundsException: length=1444; index=1444
    at com.github.mikephil.charting.buffer.BarBuffer.addBar(BarBuffer.java:38)
    at com.github.mikephil.charting.buffer.BarBuffer.feed(BarBuffer.java:83)
    at com.github.mikephil.charting.renderer.BarChartRenderer.drawDataSet(BarChartRenderer.java:97)
    at com.github.mikephil.charting.renderer.BarChartRenderer.drawData(BarChartRenderer.java:74)
    at com.github.mikephil.charting.renderer.CombinedChartRenderer.drawData(CombinedChartRenderer.java:83)
    at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:247)
    at life.bloom.tesora.ui.view.TesoraChart.onDraw(TesoraChart.java:338)
    at android.view.View.draw(View.java:15478)
    at android.view.View.getDisplayList(View.java:14372)
    at android.view.View.getHardwareLayerDisplayList(View.java:14399)
    at android.view.View.getHardwareLayer(View.java:14125)
    at android.view.View.getDisplayList(View.java:14337)
    at android.view.View.getDisplayList(View.java:14414)
    at android.view.View.draw(View.java:15192)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3323)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3159)
    at android.view.View.draw(View.java:15481)
    at android.view.View.getDisplayList(View.java:14372)
    at android.view.View.getDisplayList(View.java:14414)
    at android.view.View.draw(View.java:15192)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3323)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3159)
    at android.view.View.getDisplayList(View.java:14367)
    at android.view.View.getDisplayList(View.java:14414)
    at android.view.View.draw(View.java:15192)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3323)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3159)
    at android.view.View.getDisplayList(View.java:14367)
    at android.view.View.getDisplayList(View.java:14414)
    at android.view.View.draw(View.java:15192)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3323)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3159)
    at android.view.View.getDisplayList(View.java:14367)
    at android.view.View.getDisplayList(View.java:14414)
    at android.view.View.draw(View.java:15192)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3323)
    at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1229)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3159)
    at android.view.View.getDisplayList(View.java:14367)
    at android.view.View.getDisplayList(View.java:14414)
    at android.view.View.draw(View.java:15192)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3323)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3159)
    at android.view.View.draw(View.java:15481)
    at android.widget.FrameLayout.draw(FrameLayout.java:472)
    at android.view.View.getDisplayList(View.java:14372)
    at android.view.View.getDisplayList(View.java:14414)
    at android.view.View.draw(View.java:15192)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3323)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3159)
    at android.view.View.getDisplayList(View.java:14367)
    at android.view.View.getDisplayList(View.java:14414)
    at android.view.View.draw(View.java:15192)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3323)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3159)
    at android.view.View.getDisplayList(View.java:14367)
    at android.view.View.getDisplayList(View.java:14414)
    at android.view.View.draw(View.java:15192)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3323)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3159)
    at android.view.View.getDisplayList(View.java:14367)
    at android.view.View.getDisplayList(View.java:14414)
    at android.view.View.draw(View.java:15192)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3323)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3159)
    at android.view.View.draw(View.java:15481)
    at android.widget.FrameLayout.draw(FrameLayout.java:472)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(Phone
```

**Comment by PhilJay** [comment]
Are you calling `notifyDataChanged()` on the `data` object?

**Comment by torfinnberset** [comment]
Hey @PhilJay, I was calling notifyDataChanged() on the dataset, but not notifyDataSetChanged() on the Chart (not at the right time, anyway). That part seemed to have solved it, thanks for the hint!

**Comment by torfinnberset** [comment]
Actually, the issue was twofold, I also had to run `addEntry` and `notifyDataSetChanged` on the UI thread

**Comment by richard110110** [comment]
> Hey @PhilJay, I was calling notifyDataChanged() on the dataset, but not notifyDataSetChanged() on the Chart (not at the right time, anyway). That part seemed to have solved it, thanks for the hint!

thanks! you solved my issues!
