### ISSUE TITLE
Weird bug coming from Crash and ANRs

### ISSUE THREAD

**Issue by Virthuss** [PhilJay/MPAndroidChart#1385]
Hi, This bug is coming from my crash & ANR reports.  It seems to have a link with this library.

java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
	at java.util.ArrayList.get(ArrayList.java:308)
	at com.github.mikephil.charting.data.DataSet.getColor(DataSet.java:681)
	at com.github.mikephil.charting.renderer.BarChartRenderer.initBuffers(BarChartRenderer.java:128)
                                                           drawData
                                                           drawDataSet
                                                           prepareBarHighlight
                                                           drawValue
                                                           drawHighlighted
                                                           getTransformedValues
	at com.github.mikephil.charting.renderer.BarChartRenderer.initBuffers(BarChartRenderer.java:75)
                                                           drawData
                                                           drawDataSet
                                                           prepareBarHighlight
                                                           drawValue
                                                           drawHighlighted
                                                           getTransformedValues
	at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:230)
	at android.view.View.draw(View.java:15321)
	at android.view.View.updateDisplayListIfDirty(View.java:14257)
	at android.view.View.getDisplayList(View.java:14279)
	at android.view.View.draw(View.java:15049)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
	at android.view.View.updateDisplayListIfDirty(View.java:14252)
	at android.view.View.getDisplayList(View.java:14279)
	at android.view.View.draw(View.java:15049)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
	at android.view.View.draw(View.java:15324)
	at android.view.View.updateDisplayListIfDirty(View.java:14257)
	at android.view.View.getDisplayList(View.java:14279)
	at android.view.View.draw(View.java:15049)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
	at android.view.View.updateDisplayListIfDirty(View.java:14252)
	at android.view.View.getDisplayList(View.java:14279)
	at android.view.View.draw(View.java:15049)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
	at android.view.View.updateDisplayListIfDirty(View.java:14252)
	at android.view.View.getDisplayList(View.java:14279)
	at android.view.View.draw(View.java:15049)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
	at android.view.View.draw(View.java:15324)
	at android.widget.FrameLayout.draw(FrameLayout.java:598)
	at android.widget.ScrollView.draw(ScrollView.java:1689)
	at android.view.View.updateDisplayListIfDirty(View.java:14257)
	at android.view.View.getDisplayList(View.java:14279)
	at android.view.View.draw(View.java:15049)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
	at android.view.View.draw(View.java:15324)
	at android.view.View.updateDisplayListIfDirty(View.java:14257)
	at android.view.View.getDisplayList(View.java:14279)
	at android.view.View.draw(View.java:15049)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
	at android.view.View.draw(View.java:15324)
	at android.view.View.updateDisplayListIfDirty(View.java:14257)
	at android.view.View.getDisplayList(View.java:14279)
	at android.view.View.draw(View.java:15049)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
	at android.view.View.updateDisplayListIfDirty(View.java:14252)
	at android.view.View.getDisplayList(View.java:14279)
	at android.view.View.draw(View.java:15049)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
	at android.view.View.updateDisplayListIfDirty(View.java:14252)
	at android.view.View.getDisplayList(View.java:14279)
	at android.view.View.draw(View.java:15049)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
	at android.view.View.updateDisplayListIfDirty(View.java:14252)
	at android.view.View.getDisplayList(View.java:14279)
	at android.view.View.draw(View.java:15049)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
	at android.view.View.updateDisplayListIfDirty(View.java:14252)
	at android.view.View.getDisplayList(View.java:14279)
	at android.view.View.draw(View.java:15049)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
	at android.view.View.updateDisplayListIfDirty(View.java:14252)
	at android.view.View.getDisplayList(View.java:14279)
	at android.view.View.draw(View.java:15049)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
	at android.view.View.updateDisplayListIfDirty(View.java:14252)
	at android.view.View.getDisplayList(View.java:14279)
	at android.view.View.draw(View.java:15049)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
	at android.view.View.draw(View.java:15324)
	at android.widget.FrameLayout.draw(FrameLayout.java:598)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2653)
	at android.view.View.updateDisplayListIfDirty(View.java:14257)
	at android.view.View.getDisplayList(View.java:14279)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:273)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:279)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:318)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2540)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2356)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1986)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1065)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5901)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:550)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:211)
	at android.app.ActivityThread.main(ActivityThread.java:5389)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)

**Comment by PhilJay** [comment]
This looks like there are no colors in the color array of your dataset?
Could it (somehow) be the case that this happens in your app?

**Comment by Virthuss** [comment]
I'm unable to reproduce this bug, it occures on some of my customer 's phone as it going back through google analytics and google play developper console many time.

Any idea of where this can come from?
