### ISSUE TITLE
NullPointerException in PieChart - drawHole 

### ISSUE THREAD

**Issue by ajrulez** [PhilJay/MPAndroidChart#1404]
Thanks for the library, it is a life saver.

I have currently about 600k users using my app which uses MPAndroidChart. About 100 of these users are getting random NullPointerException in PieChart - drawHole. Granted 100 isn't that big of a number relative to 600k total users, but if possible I'd like to get to the bottom of it.

Since I am using the .aar file instead of importing the source code in my app, I am unable to fix it, or at least catch the exception on my end. Can you point me to the call that invokes onDraw for a PieChart so i can put a try-catch around it? Is it invalidate()?

Here's the stack trace:
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Canvas.drawCircle(float, float, float, android.graphics.Paint)' on a null object reference
       at com.github.mikephil.charting.renderer.PieChartRenderer.drawHole(SourceFile:277)
       at com.github.mikephil.charting.renderer.PieChartRenderer.drawExtras(SourceFile:250)
       at com.github.mikephil.charting.charts.PieChart.onDraw(SourceFile:122)
       at android.view.View.draw(View.java:16068)
       at android.view.View.updateDisplayListIfDirty(View.java:14999)
       at android.view.View.getDisplayList(View.java:15022)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3662)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3641)
       at android.view.View.updateDisplayListIfDirty(View.java:14959)
       at android.view.View.getDisplayList(View.java:15022)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3662)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3641)
       at android.view.View.updateDisplayListIfDirty(View.java:14959)
       at android.view.View.getDisplayList(View.java:15022)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3662)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3641)
       at android.view.View.updateDisplayListIfDirty(View.java:14959)
       at android.view.View.getDisplayList(View.java:15022)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3662)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3641)
       at android.view.View.updateDisplayListIfDirty(View.java:14959)
       at android.view.View.getDisplayList(View.java:15022)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3662)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3641)
       at android.view.View.updateDisplayListIfDirty(View.java:14959)
       at android.view.View.getDisplayList(View.java:15022)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3662)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3641)
       at android.view.View.updateDisplayListIfDirty(View.java:14959)
       at android.view.View.getDisplayList(View.java:15022)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3662)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3641)
       at android.view.View.updateDisplayListIfDirty(View.java:14959)
       at android.view.View.getDisplayList(View.java:15022)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3662)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3641)
       at android.view.View.updateDisplayListIfDirty(View.java:14959)
       at android.view.View.getDisplayList(View.java:15022)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3662)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3641)
       at android.view.View.updateDisplayListIfDirty(View.java:14959)
       at android.view.View.getDisplayList(View.java:15022)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3662)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3641)
       at android.view.View.updateDisplayListIfDirty(View.java:14959)
       at android.view.View.getDisplayList(View.java:15022)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:275)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:281)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:320)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2745)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2577)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2169)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1180)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6563)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
       at android.view.Choreographer.doCallbacks(Choreographer.java:590)
       at android.view.Choreographer.doFrame(Choreographer.java:560)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5835)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**Comment by PhilJay** [comment]
Yes, `invalidate()` calls the onDraw method.

Which version of the library are you using?

Are you using custom `Paint` objects?

**Comment by ajrulez** [comment]
Sorry, didn't get notified that you had responded to my query. I am using v2.1.5.
Thanks for this awesome library.

**Comment by crobertsbmw** [comment]
For what it's worth, I am having this same issue.

**Comment by crobertsbmw** [comment]
I am having this same issue and wrapping my call to `invalidate()` in a `try catch` block isn't catching the exception. This crash is affecting more than 50% of my users.

**Comment by sratanjee** [comment]
What was the resolution here? I'm seeing the same issue as well and I'm using v2.2.4

**Comment by crobertsbmw** [comment]
I still need a resolution.

**Comment by PhilJay** [comment]
@all which library version are you using?

**Comment by crobertsbmw** [comment]
I'm currently updating from 2.1.5 to 2.2.5. Trying to figure out where happened the BarData class went.

**Comment by crobertsbmw** [comment]
@PhilJay Seriously, where did the BarData(xVals, dataSets); constructor go?

**Comment by sratanjee** [comment]
2.2.5, mine has nothing to do with invalidate in first run and open crashes everytime and stacktrace shows:

java.lang.NullPointerException
                                                                   at com.github.mikephil.charting.renderer.PieChartRenderer.drawHole(PieChartRenderer.java:478)
                                                                   at com.github.mikephil.charting.renderer.PieChartRenderer.drawExtras(PieChartRenderer.java:457)
                                                                   at com.github.mikephil.charting.charts.PieChart.onDraw(PieChart.java:128)

**Comment by PhilJay** [comment]
Please show some code how you create the chart in .xml and your activity or fragment of how you setup the chart.

@crobertsbmw No idea what you mean, it's still there: https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartLib/src/com/github/mikephil/charting/data/BarData.java#L36-56

**Comment by crobertsbmw** [comment]
I'm getting this same error on all my charts that it can't resolve the Constructor for the BarData(xVals, dataSets), LineData(xVals, dataSets), etc.

![screen shot 2016-06-14 at 9 01 51 am](https://cloud.githubusercontent.com/assets/5834142/16045605/c75b731e-320e-11e6-8630-8745d33af49e.png)

**Comment by sratanjee** [comment]
In XML:

<com.github.mikephil.charting.charts.PieChart
                android:layout_width="match_parent"
                android:id="@+id/delivered_pie"
                android:layout_margin="40dip"
                android:minHeight="50dp"
                android:minWidth="50dp"
                android:layout_height="match_parent"
                android:layout_centerInParent="true">
            </com.github.mikephil.charting.charts.PieChart>

**Comment by crobertsbmw** [comment]
`    <com.github.mikephil.charting.charts.PieChart
        android:id="@+id/chart"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_weight="1"
        android:layout_margin="20dp" />`

**Comment by sratanjee** [comment]
In code:

PieDataSet dataSet = new PieDataSet(yVals1, "Election Results");
        dataSet.setSliceSpace(1f);
        dataSet.setSelectionShift(0f);

      ..... Set colors in here....
      
        PieData data = new PieData(xVals, dataSet);
        data.setValueFormatter(new PercentFormatter());
        data.setValueTextSize(0f);
        data.setValueTextColor(Color.BLACK);
        data.setDrawValues(false);
        chart.setData(data);
        chart.getLegend().setEnabled(false);
        chart.setDrawSliceText(false);
        chart.setUsePercentValues(false);

        // undo all highlights
        chart.highlightValues(null);
        chart.invalidate();
    }

    @Override
    public void onActivityCreated(Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);

        deliveredPie.setUsePercentValues(false);
        deliveredPie.setDescription("");
        deliveredPie.setDragDecelerationFrictionCoef(0.95f);
        deliveredPie.setDrawHoleEnabled(true);
        deliveredPie.setHoleColor(getResources().getColor(R.color.background));
        deliveredPie.setTransparentCircleColor(Color.WHITE);
        deliveredPie.setTransparentCircleAlpha(110);
        deliveredPie.setHoleRadius(90f);
        deliveredPie.setTransparentCircleRadius(0f);
        deliveredPie.setDrawCenterText(true);
        deliveredPie.setRotationAngle(0);
        deliveredPie.setRotationEnabled(false);
        deliveredPie.setRotationAngle(270f);

        deliveredPie.setMinimumWidth(50);
        deliveredPie.setMinimumHeight(50);

**Comment by crobertsbmw** [comment]
I just changed BarData to construct with a BarDataSet instead of an ArrayList<BarDataSet>, because I only had one set anyway, and that seemed to fix my secondary issue. Sorry about that.

**Comment by crobertsbmw** [comment]
`<com.github.mikephil.charting.charts.PieChart`
        `android:id="@+id/chart"`
        `android:layout_width="match_parent"`
        `android:layout_height="match_parent"`
        `android:layout_weight="1"`
        `android:layout_margin="20dp" />`

And my fragment has : 

`private void layoutGraph(){`
`    ArrayList<Entry> entries = new ArrayList<>();`
`    ArrayList<String> xVals = new ArrayList<>();`
`    `
`    for (int i=0; i < problems.size(); i++){`
`        Entry entry = new Entry((float)problems.get(i), i);`
`        entries.add(entry);`
`        xVals.add(""+i);`
`    }`

`    PieDataSet set = new PieDataSet(entries, "Sessions");`
`    set.setHighlightEnabled(true);`
`    set.setAxisDependency(YAxis.AxisDependency.LEFT);`

`    set.setColors(new int[]{`
`            R.color.lightRed,`
`            R.color.white,`
`            ...`
`            }, getContext());`


`    set.setDrawValues(false);`

`    PieData data = new PieData(xVals, set);`
`    pieChart.setData(data);`
`    pieChart.getLegend().setEnabled(false);`
`    pieChart.setDescription("");`
`    pieChart.setDrawSliceText(false);`
`    pieChart.setTouchEnabled(false);`

`    pieChart.setHoleColor(R.color.mantisGray);`
`    pieChart.setTransparentCircleColor(R.color.mantisGray);`
`    pieChart.setHoleColorTransparent(true);`
`    pieChart.setHoleRadius(25);`
`    pieChart.setTransparentCircleRadius(30);`
`    pieChart.setTransparentCircleAlpha(100);`

`    pieChart.notifyDataSetChanged(); // let the chart know it's data changed`
`    try {`
`        pieChart.invalidate(); // refreshe`
`    }catch(NullPointerException e){`
`        DataController.mixpanel("Pie Chart threw drawing exception", null);`
`        Toast.makeText(getContext(),"An error occurred rendering the Pie Chart", Toast.LENGTH_LONG).show();`
`    }`
`}`
