### ISSUE TITLE
java.lang.UnsupportedOperationException On ICS

### ISSUE THREAD

**Issue by Mbt925** [PhilJay/MPAndroidChart#1413]
When opening "Line Chart" Example on ICS, i get:

java.lang.UnsupportedOperationException
android.view.GLES20Canvas.clipPath(GLES20Canvas.java:408)
                                                                             at com.github.mikephil.charting.renderer.LineChartRenderer.drawFilledPath(LineChartRenderer.java:366)
                                                                             at com.github.mikephil.charting.renderer.LineChartRenderer.drawLinearFill(LineChartRenderer.java:352)
                                                                             at com.github.mikephil.charting.renderer.LineChartRenderer.drawLinear(LineChartRenderer.java:339)
                                                                             at com.github.mikephil.charting.renderer.LineChartRenderer.drawDataSet(LineChartRenderer.java:122)
                                                                             at com.github.mikephil.charting.renderer.LineChartRenderer.drawData(LineChartRenderer.java:101)
                                                                             at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:247)

**Comment by PhilJay** [comment]
http://stackoverflow.com/questions/8895677/work-around-canvas-clippath-that-is-not-supported-in-android-any-more/8895894#8895894

In short: You need to disable hardware acceleration for devices lower than API 18.

`chart.setHardWareAccelerationEnabled(...)`
