### ISSUE TITLE
App crashes aftew a few seconds using LineChart

### ISSUE THREAD

**Issue by eldivino87** [PhilJay/MPAndroidChart#1433]
I'm using a LineChart and I followed the tutorial to represent real time data [(Link)](https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/RealtimeLineChartActivity.java) 

When I run my app, after 1 or 2 seconds, it crashes.

Follow the error message. I guess the error regards the CircleBuffer drawing. If yes, can I hide it in some way?

FATAL EXCEPTION: main
                                                              Process: sbs.goselfie, PID: 19322
                                                              java.lang.NullPointerException: Attempt to invoke virtual method 'void com.github.mikephil.charting.buffer.CircleBuffer.setPhases(float, float)' on a null object reference
                                                                  at com.github.mikephil.charting.renderer.LineChartRenderer.drawCircles(LineChartRenderer.java:502)
                                                                  at com.github.mikephil.charting.renderer.LineChartRenderer.drawExtras(LineChartRenderer.java:469)
                                                                  at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:265)
                                                                  at android.view.View.draw(View.java:15308)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:14235)
                                                                  at android.view.View.getDisplayList(View.java:14257)
                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3392)
                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3371)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:14195)
                                                                  at android.view.View.getDisplayList(View.java:14257)
                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3392)
                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3371)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:14195)
                                                                  at android.view.View.getDisplayList(View.java:14257)
                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3392)
                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3371)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:14195)
                                                                  at android.view.View.getDisplayList(View.java:14257)
                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3392)
                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3371)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:14195)
                                                                  at android.view.View.getDisplayList(View.java:14257)
                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3392)
                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3371)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:14195)
                                                                  at android.view.View.getDisplayList(View.java:14257)
                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3392)
                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3371)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:14195)
                                                                  at android.view.View.getDisplayList(View.java:14257)
                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3392)
                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3371)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:14195)
                                                                  at android.view.View.getDisplayList(View.java:14257)
                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3392)
                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3371)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:14195)
                                                                  at android.view.View.getDisplayList(View.java:14257)
                                                                  at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:278)
                                                                  at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:284)
                                                                  at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:323)
                                                                  at android.view.ViewRootImpl.draw(ViewRootImpl.java:2579)
                                                                  at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2393)
                                                                  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2023)
                                                                  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1085)
                                                                  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5991)
                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                  at android.view.Choreographer.doFrame(Choreographer.java:550)
                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:135)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5430)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
                                                              	at com.andro

**Comment by eldivino87** [comment]
EDIT:
I hide circles using set.setDrawCircles(false);

But now, the error regards the LineBuffer

Follow the error code:

FATAL EXCEPTION: main
                                                              Process: sbs.goselfie, PID: 21553
                                                              java.lang.NullPointerException: Attempt to invoke virtual method 'void com.github.mikephil.charting.buffer.LineBuffer.setPhases(float, float)' on a null object reference
                                                                  at com.github.mikephil.charting.renderer.LineChartRenderer.drawLinear(LineChartRenderer.java:295)
                                                                  at com.github.mikephil.charting.renderer.LineChartRenderer.drawDataSet(LineChartRenderer.java:122)
                                                                  at com.github.mikephil.charting.renderer.LineChartRenderer.drawData(LineChartRenderer.java:101)
                                                                  at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:247)
                                                                  at android.view.View.draw(View.java:15308)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:14235)
                                                                  at android.view.View.getDisplayList(View.java:14257)
                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3392)
                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3371)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:14195)
                                                                  at android.view.View.getDisplayList(View.java:14257)
                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3392)
                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3371)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:14195)
                                                                  at android.view.View.getDisplayList(View.java:14257)
                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3392)
                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3371)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:14195)
                                                                  at android.view.View.getDisplayList(View.java:14257)
                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3392)
                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3371)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:14195)
                                                                  at android.view.View.getDisplayList(View.java:14257)
                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3392)
                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3371)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:14195)
                                                                  at android.view.View.getDisplayList(View.java:14257)
                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3392)
                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3371)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:14195)
                                                                  at android.view.View.getDisplayList(View.java:14257)
                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3392)
                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3371)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:14195)
                                                                  at android.view.View.getDisplayList(View.java:14257)
                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3392)
                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3371)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:14195)
                                                                  at android.view.View.getDisplayList(View.java:14257)
                                                                  at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:278)
                                                                  at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:284)
                                                                  at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:323)
                                                                  at android.view.ViewRootImpl.draw(ViewRootImpl.java:2579)
                                                                  at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2393)
                                                                  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2023)
                                                                  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1085)
                                                                  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5991)
                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                  at android.view.Choreographer.doFrame(Choreographer.java:550)
                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:135)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5430)

**Comment by PhilJay** [comment]
I need to see how you setup your chart and how you add data to answer that.

**Comment by eldivino87** [comment]
My class when I manage the data:

```
private class AudioListenTask implements Runnable {

        byte[] buffer = new byte[10240];
        State state;

        @Override
        public void run() {

            Microphone microphone = new Microphone();
            microphone.init();
            long currentTime;
            List<Long> beepCount = new ArrayList<Long>();

            while (mRecord) {
                try {
                    final int size = microphone.record();
                    shortToBytes(size, microphone.getBuffer());
                    currentTime = System.currentTimeMillis();
                    if (size > 0) {
                        addEntry();
                        // ... other operations
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
            try {
                microphone.stop();
            } catch (IOException e) {
                // nothing to do
            }
        }

        // ... other methods        

    }
```

In `onCreate()` method:

        mChart = (LineChart) findViewById(R.id.chart);

        mChart.setDescription("");
        mChart.setNoDataTextDescription("No data");

        // Enable Touch gestures
        mChart.setTouchEnabled(true);
        mChart.setDragEnabled(true);
        mChart.setScaleEnabled(true);
        mChart.setDrawGridBackground(false);

        // Enable Pinch zoom to avoid scaling X and Y axis separately
        mChart.setPinchZoom(true);

        // Alternative background color
        mChart.setBackgroundColor(Color.TRANSPARENT);

        // Data
        LineData data = new LineData();
        data.setValueTextColor(Color.WHITE);

        // Add empty data
        mChart.setData(data);

        // Axis
        XAxis xl = mChart.getXAxis();
        xl.setTextColor(Color.WHITE);
        xl.setDrawGridLines(false);
        xl.setAvoidFirstLastClipping(true);
        xl.setSpaceBetweenLabels(5);
        xl.setEnabled(true);

        YAxis leftAxis = mChart.getAxisLeft();
        leftAxis.setTextColor(Color.WHITE);
        //leftAxis.setAxisMaxValue(100f);
        //leftAxis.setAxisMinValue(0f);
        leftAxis.setStartAtZero(false);
        leftAxis.setDrawGridLines(true);

        YAxis rightAxis = mChart.getAxisRight();
        rightAxis.setEnabled(false);`

These are the other methods like your tutorial:

```
private void addEntry() {

        LineData data = mChart.getData();

        if (data != null) {

            ILineDataSet set = data.getDataSetByIndex(0);
            // set.addEntry(...); // can be called as well

            if (set == null) {
                set = createSet();
                data.addDataSet(set);
            }

            // add a new x-value first
            data.addXValue("");
            //data.addEntry(new Entry((float) myAbsSignal, set.getEntryCount()), 0);
            data.addEntry(new Entry((float) (Math.random() * 40) + 30f, set.getEntryCount()), 0);

            // let the chart know it's data has changed
            mChart.notifyDataSetChanged();

            // limit the number of visible entries
            mChart.setVisibleXRangeMaximum(500);
            // mChart.setVisibleYRange(30, AxisDependency.LEFT);

            // move to the latest entry and automatically refresh the chart calling invalidate() method
            mChart.moveViewToX(data.getXValCount() - 501);
            // mChart.moveViewTo(data.getXValCount()-7, 55f, AxisDependency.LEFT);
        }
    }
```

```
    private LineDataSet createSet() {

        LineDataSet set = new LineDataSet(null, "Dynamic Data");
        set.setAxisDependency(YAxis.AxisDependency.LEFT);
        //set.setColor(ColorTemplate.getHoloBlue());
        set.setDrawCircles(false);
        //set.setCircleColor(Color.WHITE);
        set.setLineWidth(1f);
        //set.setCircleRadius(4f);
        //set.setFillAlpha(65);
        //set.setFillColor(ColorTemplate.getHoloBlue());
        //set.setHighLightColor(Color.rgb(244, 117, 117));
        //set.setValueTextColor(Color.WHITE);
        //set.setValueTextSize(9f);
        //set.setDrawValues(false);
        return set;
    }
```

If you need other info, don't esitate to ask them :)

**Comment by eldivino87** [comment]
Any news? I have no workarounds or solutions...

**Comment by Noires** [comment]
I had the same issue as you, so maybe my solution can help you out here. The only difference might be that i used the MPChart component for Xamarin. 

I had to move the following lines, so that they would be executed over the UIThread via RunOnUiThread() in C#. So basically everything in the thread for addEntry() should only affect the data and not the component itself.

`mChart.NotifyDataSetChanged();
// limit the number of visible entries
mChart.SetVisibleXRangeMaximum(120);
//set.SetDrawCircles(false);
mChart.MoveViewToX(data.XValCount - 121);
`

So hopefully that gives you the right hint to solve the issue for you.
