### ISSUE TITLE
Memory Leaks Suspect 

### ISSUE THREAD

**Issue by admentPL** [PhilJay/MPAndroidChart#145]
I have been experiencing OOM exception in my app, which is using graph and pie charts, on multiple screen rotation. At first I suspected it was my fault but I have analyzed my app with DDMS heap dump and MAT tool and Leak Suspect report pointed to PieChart objects. I have then decided to check the MPAndroidChart sample app and the Leak Suspect report pointed a couple of problems. However I am not able to crash the sample app by rotating the screen (although it does not consume any other memory apart from charts which might be the cause). Can you analyze the lib with MAT and check the Leak Suspect report?

**Comment by jemshit** [comment]
@PhilJay i still get same error with PieChart, library version v2.1.0

**Comment by jemshit** [comment]
@PhilJay i tried using android:largeHeap="true" in manifest. now i monitor memory usage. If i open activity with 2 pieCharts, memory usage +10MB. If i close it doesnt free. Then if i open again, it increases +10mb again, if i close and open again, it increases +10mb .....

**Comment by jemshit** [comment]
Problem is on `mDrawBitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_4444);` in PieChartRenderer.java, `createBitmap` gets MBs of memory(depends on pixels) and it is not released. This guy says he didn't find way to solve this with `createBitmap`: http://stackoverflow.com/a/8527745/3736955 . If you can find other option doing same job without using `createBitmap`, thats better.

From this answer from other library on github (4th answer by alexvasilkov https://github.com/alexvasilkov/FoldableLayout/issues/10), "It looks like without Bitmap.recycle() GC will need 2 passes before it will release bitmap memory, but if you'll use Bitmap.recycle() GC will need only 1 pass to clear up bitmap memory." 

Try calling both `recycle` and `gc` : 
```java
System.gc();
mDrawBitmap.recycle();
mDrawBitmap= null;
mDrawBitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_4444);
```

**Comment by jemshit** [comment]
Currently i am using `  System.gc();System.gc();` (2 times) in my OnCreate() of activity and this does trick.

**Comment by mmarklar** [comment]
I'm seeing the same issue with LineCharts. I have 3 different LineCharts in different fragments and after about 5-6 rotations they cause an OOM exception. Calling System.gc(); twice as proposed by @jemshit does not fix it. Here is my stacktrace:

Process: net.marklar.rxctest, PID: 7454
    java.lang.OutOfMemoryError: Failed to allocate a 4286964 byte allocation with 168740 free bytes and 164KB until OOM
            at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
            at android.graphics.Bitmap.nativeCreate(Native Method)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:812)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:789)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:756)
            at com.github.mikephil.charting.charts.Chart.onSizeChanged(Chart.java:1518)
            at android.view.View.sizeChange(View.java:15786)
            at android.view.View.setFrame(View.java:15751)
            at android.view.View.layout(View.java:15667)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1626)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
            at android.view.Choreographer.doCallbacks(Choreographer.java:580)
            at android.view.Choreographer.doFrame(Choreographer.java:550)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by kristijanexads** [comment]
Same issue happens to me @jemshit , but System.gc() called twice doesn't help. Anyone have a solution on that?

**Comment by jaredsburrows** [comment]
What version?

**Comment by alexsullivan114** [comment]
It's happening to me on 2.2.4. Haven't gotten any OOM exceptions but if you look at the memory monitor in Android Studio each rotation results in a dramatic increase in the amount of memory retained.
