### ISSUE TITLE
NullPointerException when chart tries to highlight in bar chart

### ISSUE THREAD

**Issue by daveamol** [PhilJay/MPAndroidChart#1535]
```
Process: com..... , PID: 23804
java.lang.NullPointerException: Attempt to read from null array
at com.github.mikephil.charting.highlight.BarHighlighter.getStackedHighlight(BarHighlighter.java:108)
at com.github.mikephil.charting.highlight.BarHighlighter.getHighlight(BarHighlighter.java:37)
at com.github.mikephil.charting.charts.BarChart.getHighlightByTouchPoint(BarChart.java:97)
at com.github.mikephil.charting.listener.BarLineChartTouchListener.performHighlightDrag(BarLineChartTouchListener.java:382)
at com.github.mikephil.charting.listener.BarLineChartTouchListener.onTouch(BarLineChartTouchListener.java:157)
 at com.github.mikephil.charting.charts.BarLineChartBase.onTouchEvent(BarLineChartBase.java:663)
 at android.view.View.dispatchTouchEvent(View.java:8388)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2424)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2158)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2314)
at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1692)
at android.app.Activity.dispatchTouchEvent(Activity.java:2739)
at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2275)
at android.view.View.dispatchPointerEvent(View.java:8578)
at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4021)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3887)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3449)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3502)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3468)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3578)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3476)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3635)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3449)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3502)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3468)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3476)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3449)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5701)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5675)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5646)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootI
```

This happens If a bar entry is added with no Y values. Basically I supplied an empty array to a bar entry. When the graph tries to highlight the corresponding bar for it the activity crashes. 

Since the graph accepts empty bar entries, then it should just try not to highlight an empty entry I assume but instead it crashes. Is there a way I can work around this other than just disabling the highlighting feature ?

**Comment by PhilJay** [comment]
Yes you can work around this, just don't add an empty array.

Anyways, I will try to fix it.

**Comment by dGorod** [comment]
@PhilJay the same situation happens with LineChart :( (version 3.0.0-beta)
