### ISSUE TITLE
IndexOutOfBoundsException in drawCubicFill() since 2.2.3

### ISSUE THREAD

**Issue by techee** [PhilJay/MPAndroidChart#1536]
I'm getting an IndexOutOfBoundsException in 2.2.3 - see the stack trace blow. This seems to be related to the following pull request:

https://github.com/PhilJay/MPAndroidChart/pull/1516

```
03-02 17:44:31.767 5948-5948/net.techet.netanalyzer.an E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: net.techet.netanalyzer.an, PID: 5948
                                                                         java.lang.IndexOutOfBoundsException: Invalid index 52, size is 45
                                                                             at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                             at java.util.ArrayList.get(ArrayList.java:308)
                                                                             at com.github.mikephil.charting.data.DataSet.getEntryForIndex(DataSet.java:250)
                                                                             at com.github.mikephil.charting.renderer.LineChartRenderer.drawCubicFill(LineChartRenderer.java:260)
                                                                             at com.github.mikephil.charting.renderer.LineChartRenderer.drawCubic(LineChartRenderer.java:232)
                                                                             at com.github.mikephil.charting.renderer.LineChartRenderer.drawDataSet(LineChartRenderer.java:125)
                                                                             at com.github.mikephil.charting.renderer.LineChartRenderer.drawData(LineChartRenderer.java:108)
                                                                             at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:249)
                                                                             at android.view.View.draw(View.java:16184)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15180)
                                                                             at android.view.View.draw(View.java:15954)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                             at android.view.View.draw(View.java:15954)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                             at android.view.View.draw(View.java:15954)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                             at android.view.View.draw(View.java:15954)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                             at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1369)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                             at android.view.View.draw(View.java:16187)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15180)
                                                                             at android.view.View.draw(View.java:15954)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                             at android.view.View.draw(View.java:15954)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                             at android.view.View.draw(View.java:15954)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                             at android.view.View.draw(View.java:15954)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                             at android.view.View.draw(View.java:15954)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                             at android.view.View.draw(View.java:16187)
                                                                             at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2690)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15180)
                                                                             at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
                                                                             at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
                                                                             at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
                                                                             at android.view.ViewRootImpl.draw(ViewRootImpl.java:2615)
                                                                             at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2434)
                                                                             at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2067)
                                                                             at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                                             at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                                             at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                             at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                             at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                         	at android.view.Choreographer$FrameDisplayEventReceiver
```

**Comment by ixig** [comment]
Just saw this ... I just filled #1541, with steps to reproduce.

I found it crashes if BOTH .setDrawCubic and .setDrawFilled are ENABLED, but not if only one is enabled.

**Comment by DropArtDev** [comment]
Same for me. @PhilJay please fix this.

**Comment by cgathergood** [comment]
+1

**Comment by spamwax** [comment]
The thing that's interesting is that in the example app, one can enable both cubic option as well as `.setDrawFilled` and the app doesn't crash. I am not sure what triggers the crash in the apps that we write.

**Comment by danielgindi** [comment]
Does this happen on `master`? Or just 2.2.3?

**Comment by mat90c** [comment]
+1 same issue with v2.2.3

**Comment by vnd-ranga** [comment]
Set these property false  in line chart and zooming work smoothly
 barDataSet1.setDrawCubic(false);
        barDataSet1.setDrawFilled(false);

**Comment by danielgindi** [comment]
2.2.3 is not relevant. It is fixed later, and we will release soon.
