### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()

### ISSUE THREAD

**Issue by yashthakerlearns** [PhilJay/MPAndroidChart#1557]
@PhilJay plz help
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
                                                     at com.github.mikephil.charting.data.ChartData.calcXValMaximumLength(ChartData.java:159)
                                                     at com.github.mikephil.charting.data.ChartData.init(ChartData.java:142)
                                                     at com.github.mikephil.charting.data.ChartData.<init>(ChartData.java:104)
                                                     at com.github.mikephil.charting.data.BarLineScatterCandleBubbleData.<init>(BarLineScatterCandleBubbleData.java:29)
                                                     at com.github.mikephil.charting.data.BarData.<init>(BarData.java:37)
                                                     at com.github.mikephil.charting.data.realm.implementation.RealmBarData.<init>(RealmBarData.java:18)
                                                     at com.example.yash.resourcify.BarChartSales.onCreate(BarChartSales.java:50)
                                                     at android.app.Activity.performCreate(Activity.java:5933)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360) 
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:144) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:135) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5221) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:372)

**Comment by PhilJay** [comment]
Don't provide "null" strings to the chart library at any point.

**Comment by yashthakerlearns** [comment]
Thanks for the reply @PhilJay
