### ISSUE TITLE
java.lang.IllegalArgumentException: One or more of the DataSet Entry arrays are longer than the x-values array of this ChartData object.

### ISSUE THREAD

**Issue by yashthakerlearns** [PhilJay/MPAndroidChart#1566]
Caused by: java.lang.IllegalArgumentException: One or more of the DataSet Entry arrays are longer than the x-values array of this ChartData object.
                                                     at com.github.mikephil.charting.data.ChartData.checkLegal(ChartData.java:182)
                                                     at com.github.mikephil.charting.data.ChartData.init(ChartData.java:138)
                                                     at com.github.mikephil.charting.data.ChartData.<init>(ChartData.java:104)
                                                     at com.github.mikephil.charting.data.BarLineScatterCandleBubbleData.<init>(BarLineScatterCandleBubbleData.java:29)
                                                     at com.github.mikephil.charting.data.BarData.<init>(BarData.java:37)
                                                     at com.github.mikephil.charting.data.realm.implementation.RealmBarData.<init>(RealmBarData.java:18)
                                                     at com.example.yash.resourcify.BarChartSales.onCreate(BarChartSales.java:71)
                                                     at android.app.Activity.performCreate(Activity.java:5933)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360) 

If I call build() then and only then this exception arises. If I do not call it,bars in chart are small in size and unusual.
Plz help @PhilJay and take a look at my another question on stackoverflow.here it is http://stackoverflow.com/questions/35891250/need-help-in-better-chart-visualization-mpandroidchart plz help

**Comment by PhilJay** [comment]
Well the error message pretty much says it all.
You are adding more entries than x-values.

Also, take a look at this: https://github.com/PhilJay/MPAndroidChart/wiki/Realm.io-database-integration#troubleshooting

**Comment by KimmiDhingra1991** [comment]
@PhilJay , I am also getting same error, Say we have x-values=10
And entries =20

But all these entries has their x-index is from 0 to 9
Can say, first 10 entries has x index=3, next 8 has x index=5, and next two has x index=7
So its a genuine case
But the app crashed.
Please suggest What should I do, to handle this case

**Comment by niihelium** [comment]
It's really strange behaviour, because app crashes even if entries have indices within xMin and xMax. If there any workaround? In sources: 
/**
     * constructor for chart data
     * 
     * @param xVals The values describing the x-axis. Must be at least as long
     *            as the highest xIndex in the Entry objects across all
     *            DataSets.
*/

This is defenetly a bug, because all x indices lies within xVals. Maybe you should approximate somehow dataset to fit it in xVals, or filter only one yVal per x cell.
