### ISSUE TITLE
IndexOutOfBoundsException when cubic drawing is turned on.

### ISSUE THREAD

**Issue by spamwax** [PhilJay/MPAndroidChart#1602]
Working with a `LineChart` the exception happens when `set1.setDrawCubic(true);` is used and the chart is double-clicked or pinch/zoom gesture is performed.
Disabling the cubic option solves the issue.
Here is snippet of stacktrace:

FATAL EXCEPTION: main
                                                                            java.lang.IndexOutOfBoundsException: Invalid index 32, size is 30
                                                                                at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:251)
                                                                                at java.util.ArrayList.get(ArrayList.java:304)
                                                                                at com.github.mikephil.charting.data.DataSet.getEntryForIndex(DataSet.java:250)
                                                                                at com.github.mikephil.charting.renderer.LineChartRenderer.drawCubicFill(LineChartRenderer.java:260)
                                                                                at com.github.mikephil.charting.renderer.LineChartRenderer.drawCubic(LineChartRenderer.java:232)
                                                                                at com.github.mikephil.charting.renderer.LineChartRenderer.drawDataSet(LineChartRenderer.java:125)
                                                                                at com.github.mikephil.charting.renderer.LineChartRenderer.drawData(LineChartRenderer.java:108)
                                                                                at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:249)
                                                                                at android.view.View.draw(View.java:10978)
                                                                                at android.view.ViewGroup.drawChild(ViewGroup.java:2887)

I am using `v2.2.3` and the crash is reproducible on `API-{15, 16, 19, 23}`. I haven't tested on other versions.

I am working on setting up a mini-project to show the crash and will update the ticket accordingly. Please let me know if any additional info is needed.

**Comment by spamwax** [comment]
Closing the ticket as it's been already reported in issue #1539
