### ISSUE TITLE
saveToPath() causes - IllegalArgumentException: bitmap size exceeds 32 bits

### ISSUE THREAD

**Issue by KeithKirk** [PhilJay/MPAndroidChart#1625]
We have MPAndroidChart in a production app and our crash logger reported the following uncaught exception.
```
Fatal Exception: java.lang.IllegalArgumentException: bitmap size exceeds 32 bits
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:908)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:879)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:846)
       at com.github.mikephil.charting.charts.Chart.getChartBitmap(Chart.java:1481)
       at com.github.mikephil.charting.charts.Chart.saveToPath(Chart.java:1511)
```
MPAndroidChart version: 2.1.6
Android Version: 5.1.1
Device Manufacturer: Samsung
Device Model: SM-G361F

I realise that this is most likely an issue on that particular model or device but I thought I'd report it in case it's an easy fix.

For the moment we're just going to wrap saveToPath in a try-catch and update the charts library version.

**Comment by PhilJay** [comment]
Take a look at this: http://stackoverflow.com/a/15008630/1590502

In short: `Bitmap` has a maximum size. It is usually equal to the maximum width and height of the device screen. A potential issue here could be that your view is bigger that the device screen and therefore this method crashes.
