### ISSUE TITLE
Problem in mChart.setOnChartValueSelectedListener

### ISSUE THREAD

**Issue by kamal250** [PhilJay/MPAndroidChart#1627]
I have added fragment change logic in mChart.setOnChartValueSelectedListener.

**At same time, if I use below code in mChart.setOnClickListener, it is working properly.**

**Here is my sample code:**

mChart.setOnChartValueSelectedListener(new OnChartValueSelectedListener() {
            @Override
            public void onValueSelected(Entry e, int dataSetIndex, Highlight h) {
                String xAxisValue = mChart.getData().getXVals().get(e.getXIndex());

                Log.d("test", "xAxisValue: " + xAxisValue);

                String check_tab = SPUtiles.getStringValue(BTConstants.CHECK_TAB, "day");
                Utils.getXValue=xAxisValue;
                if (check_tab.equals("year")) {
                    mActivity.barClick(R.id.rb_history_tab_month, 2);
                } else if (check_tab.equals("month")) {
                    mActivity.barClick(R.id.rb_history_tab_week, 2);
                } else if (check_tab.equals("week")) {
                    mActivity.barClick(R.id.rb_history_tab_day, 2);
                }
            }

            @Override
            public void onNothingSelected() {

            }
        });

And when I use this, application gets crashed.

**Here is my logcat:**

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.VelocityTracker.computeCurrentVelocity(int, float)' on a null object reference
at com.github.mikephil.charting.listener.BarLineChartTouchListener.onTouch(BarLineChartTouchListener.java:171)
at com.github.mikephil.charting.charts.BarLineChartBase.onTouchEvent(BarLineChartBase.java:640)
at android.view.View.dispatchTouchEvent(View.java:8393)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2426)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2158)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2314)
at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1692)
at android.app.Activity.dispatchTouchEvent(Activity.java:2749)
at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2275)
at android.view.View.dispatchPointerEvent(View.java:8583)
at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4091)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3957)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3509)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3562)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3536)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3695)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3509)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3562)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3528)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3536)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3509)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5806)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5745)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5716)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5896)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:143)
at android.os.Looper.loop(Looper.java:122)
at android.app.ActivityThread.main(ActivityThread.java:5314)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)

**Comment by PhilJay** [comment]
This crash relates to the `VelocityTracker.obtain()`method.
I am not sure if it is an Android issue or it's related to your setup (using both onClick and library listener), but it's not a library issue.

**Comment by rferbesa** [comment]
I'm having the same issue. @kamal250 did you find a solution to this?

**Comment by kamal250** [comment]
@rferbesa, As far as I remember, we have used mChart.setOnClickListener inside mchart.setOnChartValueSelectedListener.

**Comment by rferbesa** [comment]
Thank you @kamal250 ! And could you remember how do you get the bar clicked inside the onClickListener? because its only argument is a View.

**Comment by kamal250** [comment]
@rferbesa, We have get xAxisValue inside onValueSelected of mChart.setOnChartValueSelectedListener method.

` @Override
    public void onValueSelected(Entry e, int dataSetIndex, final Highlight h) {
        
        final String xAxisValue = mChart.getData().getXVals().get(e.getXIndex());
		
		mChart.setOnClickListener(new View.OnClickListener() {
		    @Override
		    public void onClick(View v) {}
		});
    }
});`

By this way, we have solved the issue. Hope this will be helpful to you.
