### ISSUE TITLE
java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by nicofossa** [PhilJay/MPAndroidChart#1701]
A lot of users of my app signaled a crash due to this problem:
`java.lang.UnsupportedOperationException
at android.view.GLES20Canvas.clipPath(GLES20Canvas.java:412)
at com.github.mikephil.charting.renderer.LineRadarRenderer.drawFilledPath(LineRadarRenderer.java:50)
at com.github.mikephil.charting.renderer.LineChartRenderer.drawLinearFill(LineChartRenderer.java:381)
at com.github.mikephil.charting.renderer.LineChartRenderer.drawLinear(LineChartRenderer.java:362)
at com.github.mikephil.charting.renderer.LineChartRenderer.drawDataSet(LineChartRenderer.java:129)
at com.github.mikephil.charting.renderer.LineChartRenderer.drawData(LineChartRenderer.java:108)
at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:249)
at android.view.View.draw(View.java:11108)
at android.view.View.getDisplayList(View.java:10547)
at android.view.ViewGroup.drawChild(ViewGroup.java:2957)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2596)
at android.view.View.getDisplayList(View.java:10545)
at android.view.ViewGroup.drawChild(ViewGroup.java:2957)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2596)
at android.view.View.draw(View.java:11111)
at android.widget.FrameLayout.draw(FrameLayout.java:462)
at android.view.View.getDisplayList(View.java:10547)
at android.view.ViewGroup.drawChild(ViewGroup.java:2957)
at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:3838)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2596)
at android.view.View.draw(View.java:11111)
at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3308)
at android.view.View.getDisplayList(View.java:10547)
at android.view.ViewGroup.drawChild(ViewGroup.java:2957)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2596)
at android.view.View.getDisplayList(View.java:10545)
at android.view.ViewGroup.drawChild(ViewGroup.java:2957)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2596)
at android.view.View.draw(View.java:11111)
at android.support.v4.view.ViewPager.draw(ViewPager.java:2336)
at android.view.View.getDisplayList(View.java:10547)
at android.view.ViewGroup.drawChild(ViewGroup.java:2957)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2596)
at android.view.View.getDisplayList(View.java:10545)
at android.view.ViewGroup.drawChild(ViewGroup.java:2957)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2596)
at android.view.View.getDisplayList(View.java:10545)
at android.view.ViewGroup.drawChild(ViewGroup.java:2957)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2596)
at android.view.View.getDisplayList(View.java:10545)
at android.view.ViewGroup.drawChild(ViewGroup.java:2957)
at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1373)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2596)
at android.view.View.getDisplayList(View.java:10545)
at android.view.ViewGroup.drawChild(ViewGroup.java:2957)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2596)
at android.view.View.draw(View.java:11111)
at android.widget.FrameLayout.draw(FrameLayout.java:462)
at android.view.View.getDisplayList(View.java:10547)
at android.view.ViewGroup.drawChild(ViewGroup.java:2957)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2596)
at android.view.View.getDisplayList(View.java:10545)
at android.view.ViewGroup.drawChild(ViewGroup.java:2957)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2596)
at android.view.View.getDisplayList(View.java:10545)
at android.view.ViewGroup.drawChild(ViewGroup.java:2957)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2596)
at android.view.View.getDisplayList(View.java:10545)
at android.view.ViewGroup.drawChild(ViewGroup.java:2957)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2596)
at android.view.View.draw(View.java:11111)
at android.widget.FrameLayout.draw(FrameLayout.java:462)
at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2131)
at android.view.View.getDisplayList(View.java:10547)
at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:842)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:1914)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1638)
at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2446)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4448)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:823)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:590)
at dalvik.system.NativeStart.main(Native Method)`

Is this normal?

**Comment by xizzhu** [comment]
See https://github.com/PhilJay/MPAndroidChart/issues/1413

**Comment by nicofossa** [comment]
I think it should be solved from the library code itself... Normally apps are quite faster with Hardware acceleration enabled. I solved in my app in this way:
`if (Build.VERSION.SDK_INT < Build.VERSION_CODES.JELLY_BEAN_MR2
                && Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB) {
            lineChart.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
        }`

**Comment by PhilJay** [comment]
Update to the latest version.
