### ISSUE TITLE
Crashes with index out of bound exception when getting the xAxis labels 

### ISSUE THREAD

**Issue by Seichis** [PhilJay/MPAndroidChart#1708]
> FATAL EXCEPTION: main
                                                                     Process: webinar.pubnub.insitu, PID: 4238
                                                                     java.lang.IndexOutOfBoundsException: Invalid index 8, size is 8
                                                                         at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                         at java.util.ArrayList.get(ArrayList.java:308)
                                                                         at com.github.mikephil.charting.renderer.XAxisRenderer.drawLabels(XAxisRenderer.java:165)
                                                                         at com.github.mikephil.charting.renderer.XAxisRenderer.renderAxisLabels(XAxisRenderer.java:100)
                                                                         at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:267)
                                                                         at android.view.View.draw(View.java:16184)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15180)
                                                                         at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15140)
                                                                         at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15140)
                                                                         at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15140)
                                                                         at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15140)
                                                                         at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15140)
                                                                         at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15140)
                                                                         at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15140)
                                                                         at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15140)
                                                                         at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15140)
                                                                         at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15140)
                                                                         at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
                                                                         at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
                                                                         at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
                                                                         at android.view.ViewRootImpl.draw(ViewRootImpl.java:2623)
                                                                         at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2442)
                                                                         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2075)
                                                                         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1115)
                                                                         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6023)
                                                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                         at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                         at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

I plot a Bubble plot and this does not happen all the time.When I disable the labels it is fine. It seems I have messed up something when setting up the plot. Any quick help pls?

**Comment by Seichis** [comment]
I had messed up the labels. I am closing it

**Comment by surfer190** [comment]
@Seichis Please add a bit more information. So this is an error with your development and not the package? Nonetheless I think you should outline what you did to fix it.

**Comment by tahagit** [comment]
> @Seichis Please add a bit more information. So this is an error with your development and not the package? Nonetheless I think you should outline what you did to fix it.

yessss , i have this problem too.
