### ISSUE TITLE
Exception in BarLineChartBase while adding MarkerView to highlight

### ISSUE THREAD

**Issue by BalalakshmiSadhasivam** [PhilJay/MPAndroidChart#1750]
I am getting NullPointerException while adding MarkerView if there is no highlight information.

```
java.lang.NullPointerException: Attempt to read from field 'float com.github.mikephil.charting.highlight.Range.to' on a null object reference
                                                                         at com.github.mikephil.charting.charts.BarLineChartBase.getMarkerPosition(BarLineChartBase.java:600)
                                                                         at com.github.mikephil.charting.charts.Chart.drawMarkers(Chart.java:683)
                                                                         at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:275)
                                                                         at android.view.View.draw(View.java:16184)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15180)
                                                                         at android.view.View.draw(View.java:15954)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                         at android.view.View.draw(View.java:16187)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15180)
                                                                         at android.view.View.draw(View.java:15954)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                         at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:3838)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                         at android.view.View.draw(View.java:16187)
                                                                         at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3308)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15180)
                                                                         at android.view.View.draw(View.java:15954)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                         at android.view.View.draw(View.java:15954)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                         at android.view.View.draw(View.java:15954)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                         at android.view.View.draw(View.java:16187)
                                                                         at android.support.v4.view.ViewPager.draw(ViewPager.java:2336)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15180)
                                                                         at android.view.View.draw(View.java:15954)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                         at android.view.View.draw(View.java:16187)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15180)
                                                                         at android.view.View.draw(View.java:15954)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                         at android.view.View.draw(View.java:16187)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15180)
                                                                         at android.view.View.draw(View.java:15954)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                         at android.view.View.draw(View.java:16187)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15180)
                                                                         at android.view.View.draw(View.java:15954)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                         at android.view.View.draw(View.java:15954)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                         at android.view.View.draw(View.java:15954)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                         at android.view.View.draw(View.java:15954)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                         at android.view.View.draw(View.java:15954)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                         at android.view.View.draw(View.java:16187)
                                                                     	at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.

```

**Comment by PhilJay** [comment]
Should be fixed in the new release.

**Comment by cuddle-puneet** [comment]
This issue happens especially if all the BarEntry objects within a BarDataSet contain float[] but just single value within those float[]. I tried to simulate the issue in your MPAndroidChartLibrary code in StackedBarNegativeActivity and was able to simulate the same.
`// IMPORTANT: When using negative values in stacked bars, always make sure the negative values are in the array first
        ArrayList<BarEntry> yValues = new ArrayList<BarEntry>();
        yValues.add(new BarEntry(new float[]{ -10 }, 0));
        yValues.add(new BarEntry(new float[]{ -12 }, 1));
        yValues.add(new BarEntry(new float[]{ -15 }, 2));
        yValues.add(new BarEntry(new float[]{ -17 }, 3));
        BarDataSet set = new BarDataSet(yValues, "Age Distribution");`

If in such a scenario, an attempt to draw the marker view throws the above mentioned exception.
