### ISSUE TITLE
HorizontalBarChart: IndexOutOfBoundsException when plotting BarData without entries

### ISSUE THREAD

**Issue by jan-glx** [PhilJay/MPAndroidChart#1777]
When you set the data of a bar chart, but the data is actually empty, containing no data, in particular no `xVals` the application will crash with:
```
java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
at java.util.ArrayList.get(ArrayList.java:308)
at com.github.mikephil.charting.renderer.XAxisRendererHorizontalBarChart.drawLabels(XAxisRendererHorizontalBarChart.java:127)
at com.github.mikephil.charting.renderer.XAxisRendererHorizontalBarChart.renderAxisLabels(XAxisRendererHorizontalBarChart.java:68)
at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:267)
at android.view.View.draw(View.java:16178)
...
```
instead of showing "no data" or something... not difficult to work around but ...

To reproduce, use something along the lines:
````
HorizontalBarChart chart = (HorizontalBarChart) findViewById(R.id.chart);
ArrayList<BarEntry> yVals1 = new ArrayList<>();
ArrayList<String> xVals = new ArrayList<>();
BarDataSet set1 = new BarDataSet(yVals1, "DataSet 1");
ArrayList<IBarDataSet> dataSets = new ArrayList<IBarDataSet>();
dataSets.add(set1);
chart.setData(new BarData(xVals, dataSets));
chart.notifyDataSetChanged(); // let the chart know it's data changed
chart.invalidate();
````
````
    <com.github.mikephil.charting.charts.HorizontalBarChart
        android:id="@+id/chart"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />
````

**Comment by surfer190** [comment]
Yeah it seems this was introduced in the last 5 or 6 months. We really need to get this sorted

All I did was update to the latest MPChart library (`compile 'com.github.PhilJay:MPAndroidChart:v2.2.4'`) with no code changes.
However my analytics show this as a new error that hasn't been seen before. So a breaking change has been introduced. @jan-glx lets look at a way to resolve this.

Here is my stack trace:

```
Fatal Exception: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
       at java.util.ArrayList.get(ArrayList.java:308)
       at com.github.mikephil.charting.renderer.XAxisRenderer.drawLabels(XAxisRenderer.java:165)
       at com.github.mikephil.charting.renderer.XAxisRenderer.renderAxisLabels(XAxisRenderer.java:100)
       at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:267)
       at android.view.View.draw(View.java:14528)
       at android.view.View.getDisplayList(View.java:13412)
       at android.view.View.getDisplayList(View.java:13454)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3091)
       at android.view.View.getDisplayList(View.java:13350)
       at android.view.View.getDisplayList(View.java:13454)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3091)
       at android.view.View.getDisplayList(View.java:13350)
       at android.view.View.getDisplayList(View.java:13454)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3091)
       at android.view.View.getDisplayList(View.java:13350)
       at android.view.View.getDisplayList(View.java:13454)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3091)
       at android.view.View.getDisplayList(View.java:13350)
       at android.view.View.getDisplayList(View.java:13454)
       at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1622)
       at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1488)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2458)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2317)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1940)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1035)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5847)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:780)
       at android.view.Choreographer.doCallbacks(Choreographer.java:593)
       at android.view.Choreographer.doFrame(Choreographer.java:562)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:766)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5336)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:681)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by PhilJay** [comment]
Thanks for the report, this will be fixed in the next release.

**Comment by PhilJay** [comment]
I have investigated this. In my latest code this should no longer occur, since bardata is no longer dependant on x-axis labels.

**Comment by surfer190** [comment]
Thanks Phil, appreciate it.
