### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by x952576** [PhilJay/MPAndroidChart#1866]
Caused by: java.lang.IllegalArgumentException: RealmDemoData is not part of the schema for this Realm
                                                                                        at io.realm.internal.modules.CompositeMediator.getMediator(CompositeMediator.java:122)
                                                                                        at io.realm.internal.modules.CompositeMediator.getTableName(CompositeMediator.java:79)
                                                                                        at io.realm.Realm.getTable(Realm.java:1279)
                                                                                        at io.realm.Realm.clear(Realm.java:1162)
                                                                                        at com.xxmassdeveloper.mpchartexample.realm.RealmBaseActivity.writeToDB(RealmBaseActivity.java:110)
                                                                                        at com.xxmassdeveloper.mpchartexample.realm.RealmDatabaseActivityLine.onResume(RealmDatabaseActivityLine.java:47)

**Comment by x952576** [comment]
why

**Comment by Noires** [comment]
This is not related to MPAndroidChart, your issue is connected to Realm.io and your Schema.
Next time if you ask a question, give more informations about your problem and check carefully what is the real reason behind.
