### ISSUE TITLE
java.lang.IllegalArgumentException: bitmap size exceeds 32bits in Chart.onSizeChanged

### ISSUE THREAD

**Issue by zholmes1** [PhilJay/MPAndroidChart#220]
A user of my application is getting this error. They are on a Galaxy Note 3. Any ideas?

```
java.lang.IllegalArgumentException: bitmap size exceeds 32bits
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:903)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:880)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:847)
	at com.github.mikephil.charting.charts.Chart.onSizeChanged(SourceFile:2356)
	at android.view.View.sizeChange(View.java:15763)
	at android.view.View.setFrame(View.java:15736)
	at android.view.View.layout(View.java:15644)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
	at android.view.View.layout(View.java:15648)
	at android.view.ViewGroup.layout(ViewGroup.java:4856)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	at android.view.View.layout(View.java:15648)
	at android.view.ViewGroup.layout(ViewGroup.java:4856)
	at android.support.v4.view.ViewPager.onLayout(SourceFile:1589)
	at android.view.View.layout(View.java:15648)
	at android.view.ViewGroup.layout(ViewGroup.java:4856)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
	at android.view.View.layout(View.java:15648)
	at android.view.ViewGroup.layout(ViewGroup.java:4856)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	at android.view.View.layout(View.java:15648)
	at android.view.ViewGroup.layout(ViewGroup.java:4856)
	at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:429)
	at android.view.View.layout(View.java:15648)
	at android.view.ViewGroup.layout(ViewGroup.java:4856)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
	at android.view.View.layout(View.java:15648)
	at android.view.ViewGroup.layout(ViewGroup.java:4856)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	at android.view.View.layout(View.java:15648)
	at android.view.ViewGroup.layout(ViewGroup.java:4856)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2245)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1967)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1199)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6383)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:803)
	at android.view.Choreographer.doCallbacks(Choreographer.java:603)
	at android.view.Choreographer.doFrame(Choreographer.java:573)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:789)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:157)
	at android.app.ActivityThread.main(ActivityThread.java:5293)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:126)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by katmitchell** [comment]
I have also seen this error on my MotoX. My BarChart was wrapped in a RelativeLayout and the error occurred when the keyboard was opened. The previous calls to onSizeChanged had a height of 432, but when the keyboard opens in this case, height has a value of 16777204.

**Comment by PhilJay** [comment]
This should be fixed in the next update!

Best regards,
Phil
