### ISSUE TITLE
Error adding Bar in v3.0-beta1

### ISSUE THREAD

**Issue by cpboyd** [PhilJay/MPAndroidChart#2245]
After adding data to a Bar chart in v3.0-beta1, I get the following error:
```
java.lang.ArrayIndexOutOfBoundsException: length=4; index=4
      at com.github.mikephil.charting.buffer.BarBuffer.addBar(BarBuffer.java:37)
      at com.github.mikephil.charting.buffer.BarBuffer.feed(BarBuffer.java:80)
      at com.github.mikephil.charting.renderer.BarChartRenderer.drawDataSet(BarChartRenderer.java:103)
      at com.github.mikephil.charting.renderer.BarChartRenderer.drawData(BarChartRenderer.java:78)
      at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:243)
      at android.view.View.draw(View.java:16184)
      at android.view.View.updateDisplayListIfDirty(View.java:15180)
      at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
      at android.view.View.updateDisplayListIfDirty(View.java:15140)
      at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
      at android.view.View.updateDisplayListIfDirty(View.java:15140)
      at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
      at android.view.View.updateDisplayListIfDirty(View.java:15140)
      at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
      at android.view.View.updateDisplayListIfDirty(View.java:15140)
      at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
      at android.view.View.updateDisplayListIfDirty(View.java:15140)
      at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
      at android.view.View.updateDisplayListIfDirty(View.java:15140)
      at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
      at android.view.View.updateDisplayListIfDirty(View.java:15140)
      at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
      at android.view.View.updateDisplayListIfDirty(View.java:15140)
      at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
      at android.view.View.updateDisplayListIfDirty(View.java:15140)
      at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
      at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
      at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
      at android.view.ViewRootImpl.draw(ViewRootImpl.java:2615)
      at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2434)
      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2067)
      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
      at android.view.Choreographer.doCallbacks(Choreographer.java:670)
      at android.view.Choreographer.doFrame(Choreographer.java:606)
      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
      at android.os.Handler.handleCallback(Handler.java:739)
      at android.os.Handler.dispatchMessage(Handler.java:95)
      at android.os.Looper.loop(Looper.java:148)
      at android.app.ActivityThread.main(ActivityThread.java:5417)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

The issue seems to be that the buffer array doesn't increase in size after adding a new value.

**Comment by cpboyd** [comment]
Code to reproduce:

I'm using `pushEntry()` to add new entries to the chart.
```java
private BarData createBarData(BarEntry e) {
    List<BarEntry> entries = new ArrayList<>();
    entries.add(e);

    BarDataSet set = new BarDataSet(entries, "DataSet");
    set.setValueTextColor(Color.WHITE);
    BarData data = new BarData(set);

    data.setBarWidth(1);
    return data;
}

private void pushEntry(BarChart chart, BarEntry e) {
    final BarData data = chart.getData();
    if (data != null) {
        IBarDataSet set = data.getDataSetByIndex(0);
        set.addEntry(e);
    } else {
        chart.setData(createBarData(e));
    }
}
```

**Comment by cpboyd** [comment]
Ah.

I missed the `chart.notifyDataSetChanged();`, but I was getting this error using `((DataSet)set).setValues(values);` and `setValues()` does call the DataSet's `notifyDataSetChanged();` 

Either way, I'll close this issue as adding the notifyDataSetChanged() on the chart-level works.
