### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by huhuanhuan** [PhilJay/MPAndroidChart#2253]
hello when I use MPAndroidchart 
  java.lang.OutOfMemoryError: Failed to allocate a 3240012 byte allocation with 2370308 free bytes and 2MB until OOM
                                                                            at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                            at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                            at android.graphics.Bitmap.createBitmap(Bitmap.java:939)
                                                                            at android.graphics.Bitmap.createBitmap(Bitmap.java:912)
                                                                            at android.graphics.Bitmap.createBitmap(Bitmap.java:879)
                                                                            at com.github.mikephil.charting.renderer.LineChartRenderer.drawData(LineChartRenderer.java:88)
                                                                            at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:247)

**Comment by huhuanhuan** [comment]
why
