### ISSUE TITLE
Wrong dataSetIndex in a custom value formatter

### ISSUE THREAD

**Issue by AlaaAlShammaa** [PhilJay/MPAndroidChart#2263]
I'm trying to set labels to a barchart view. This is my code: 
```java
package com.example.alaashammaa.charts;

import android.graphics.Color;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;


import com.github.mikephil.charting.charts.BarChart;
import com.github.mikephil.charting.components.AxisBase;
import com.github.mikephil.charting.components.Legend;
import com.github.mikephil.charting.components.XAxis;
import com.github.mikephil.charting.components.YAxis;
import com.github.mikephil.charting.data.BarData;
import com.github.mikephil.charting.data.BarDataSet;
import com.github.mikephil.charting.data.BarEntry;
import com.github.mikephil.charting.formatter.AxisValueFormatter;
import com.github.mikephil.charting.interfaces.datasets.IBarDataSet;
import com.github.mikephil.charting.interfaces.datasets.IDataSet;
import com.github.mikephil.charting.utils.ColorTemplate;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class MainActivity extends AppCompatActivity {
    private BarChart mChart;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        final String[] arr = {"20141", "20142", "20151", "20152", "20153", "20161"};
        mChart = (BarChart) findViewById(R.id.chart1);
        mChart.setDescription("");
        XAxis xAxis = mChart.getXAxis();
        YAxis leftAxis = mChart.getAxisLeft();
        YAxis rightAxis = mChart.getAxisRight();
        xAxis.setDrawGridLines(false);
        xAxis.setDrawAxisLine(true);
        xAxis.setCenterAxisLabels(true);
        xAxis.setLabelCount(6);
        xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);
        Legend legend = mChart.getLegend();
        legend.setPosition(Legend.LegendPosition.BELOW_CHART_LEFT);
        legend.setWordWrapEnabled(true);


        leftAxis.setDrawZeroLine(false);
        rightAxis.setDrawZeroLine(false);
        leftAxis.setDrawLabels(false); // no axis labels
        leftAxis.setDrawAxisLine(false); // no axis line
        leftAxis.setDrawGridLines(false);
        mChart.getAxisRight().setEnabled(false);
        xAxis.setDrawLabels(true);

        final List<BarEntry> entries = new ArrayList<>();
        entries.add(new BarEntry(0, 30f,arr[0]));
        entries.add(new BarEntry(1, 80f,arr[1]));
        entries.add(new BarEntry(2, 60f,arr[2]));
        entries.add(new BarEntry(3, 50f,arr[3]));
        entries.add(new BarEntry(4, 70f,arr[4]));
        entries.add(new BarEntry(5, 60f,arr[5]));
        mChart.getXAxis().setValueFormatter(new AxisValueFormatter() {
            @Override
            public String getFormattedValue(float value, AxisBase axis) {
                int idx = (int) value;
                if(idx >= 0 && idx<=5) {
                    return entries.get(idx).getData().toString();
                }
                return "";
            }

            @Override
            public int getDecimalDigits() {
                return 0;
            }
        });
        xAxis.setGranularity(1f);
        xAxis.setGranularityEnabled(true);
        BarDataSet set = new BarDataSet(entries, "BarDataSet");
        BarData data = new BarData(set);
        data.setBarWidth(0.9f); // set custom bar width
        mChart.setData(data);
        mChart.setPinchZoom(false);
        mChart.setTouchEnabled(false);
        mChart.setFitBars(true); // make the x-axis fit exactly all bars
        mChart.invalidate(); // refresh
    }

}
```

The problem is that i'm getting an index of -1 and 6! 
also the labels don't go below (centered) the bars.
This is the error i'm getting:
`
<b>
java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
                                                                                  at java.util.ArrayList.get(ArrayList.java:310)
                                                                                  at com.example.alaashammaa.charts.MainActivity$1.getFormattedValue(MainActivity.java:65)
                                                                                  at com.github.mikephil.charting.components.AxisBase.getFormattedLabel(AxisBase.java:451)
                                                                                  at com.github.mikephil.charting.components.AxisBase.getLongestLabel(AxisBase.java:437)
                                                                                  at com.github.mikephil.charting.renderer.XAxisRenderer.computeSize(XAxisRenderer.java:78)
                                                                                  at com.github.mikephil.charting.renderer.XAxisRenderer.computeAxisValues(XAxisRenderer.java:73)
                                                                                  at com.github.mikephil.charting.renderer.XAxisRenderer.computeAxis(XAxisRenderer.java:66)
                                                                                  at com.github.mikephil.charting.charts.BarLineChartBase.notifyDataSetChanged(BarLineChartBase.java:339)
                                                                                  at com.github.mikephil.charting.charts.Chart.onSizeChanged(Chart.java:1727)
                                                                                  at com.github.mikephil.charting.charts.BarLineChartBase.onSizeChanged(BarLineChartBase.java:1563)
                                                                                  at android.view.View.sizeChange(View.java:18114)
                                                                                  at android.view.View.setFrame(View.java:18076)
                                                                                  at android.view.View.layout(View.java:17991)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5817)
                                                                                  at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
                                                                                  at android.view.View.layout(View.java:17995)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5817)
                                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                                  at android.view.View.layout(View.java:17995)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5817)
                                                                                  at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:433)
                                                                                  at android.view.View.layout(View.java:17995)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5817)
                                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                                  at android.view.View.layout(View.java:17995)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5817)
                                                                                  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
                                                                                  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                                  at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                                  at android.view.View.layout(View.java:17995)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5817)
                                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                                  at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:3146)
                                                                                  at android.view.View.layout(View.java:17995)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5817)
                                                                                  at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2759)
                                                                                  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2460)
                                                                                  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1528)
                                                                                  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7564)
                                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
                                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                                  at android.view.Choreographer.doFrame(Choreographer.java:622)
                                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:7331)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
</b>`

**Comment by sanjhi** [comment]
Hi, 
Have you got the solution? If yes then please share as I am also having the trouble and cant see any way out. :(

**Comment by lmdiloveu** [comment]
![image](https://user-images.githubusercontent.com/8290718/50394848-3c081a00-079b-11e9-817b-33508a890054.png)
