### ISSUE TITLE
DefaultAxisValueFormatter OutOfMemory Exception

### ISSUE THREAD

**Issue by zkdzegede** [PhilJay/MPAndroidChart#2286]
```
java.lang.OutOfMemoryError: Failed to allocate a 38189038 byte allocation with 16732064 free bytes and 28MB until OOM
                                                                   at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:95)
                                                                   at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:146)
                                                                   at java.lang.StringBuffer.append(StringBuffer.java:219)
                                                                   at com.github.mikephil.charting.formatter.DefaultAxisValueFormatter.<init>(DefaultAxisValueFormatter.java:35)
                                                                   at com.github.mikephil.charting.components.AxisBase.getValueFormatter(AxisBase.java:482)
                                                                   at com.github.mikephil.charting.components.AxisBase.getFormattedLabel(AxisBase.java:451)
                                                                   at com.github.mikephil.charting.components.AxisBase.getLongestLabel(AxisBase.java:437)
                                                                   at com.github.mikephil.charting.renderer.XAxisRenderer.computeSize(XAxisRenderer.java:78)
                                                                   at com.github.mikephil.charting.renderer.XAxisRenderer.computeAxisValues(XAxisRenderer.java:73)
                                                                   at com.github.mikephil.charting.renderer.XAxisRenderer.computeAxis(XAxisRenderer.java:66)
                                                                   at com.github.mikephil.charting.charts.BarLineChartBase.notifyDataSetChanged(BarLineChartBase.java:339)
```

This line sets mAxis.mDecimals to the maximum int, because log(0) is negative infinity.

https://github.com/PhilJay/MPAndroidChart/blob/63684f02ca686d38b835f39fc86a5263f86034a3/MPChartLib/src/main/java/com/github/mikephil/charting/renderer/AxisRenderer.java#L242

This causes a very large format to be parsed for the String formatter in DefaultAxisValueFormatter

```
public DefaultAxisValueFormatter(int digits) {
        this.digits = digits;

        StringBuffer b = new StringBuffer();
        for (int i = 0; i < digits; i++) {
            if (i == 0)
                b.append(".");
            b.append("0");
        }

        mFormattedStringCache = new FormattedStringCache.PrimFloat(new DecimalFormat("###,###,###,##0" + b.toString()));
    }
```

**Comment by zkdzegede** [comment]
It seems like other parts of the AxisRenderer handles interval of 0.0, but that one line with the log10 check only checks if interval < 1, but doesn't account for the 0 value...

**Comment by zkdzegede** [comment]
I found the workaround of 

```
axis.setGranularityEnabled(true);
axis.setGranularity(0.00001f);
```
