### ISSUE TITLE
 java.lang.OutOfMemoryError in PieChartRenderer.drawData() method

### ISSUE THREAD

**Issue by sanjaymajoka** [PhilJay/MPAndroidChart#2534]
Please answer it?

Fatal Exception: java.lang.OutOfMemoryError
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:697)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:674)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:641)
       at com.github.mikephil.charting.renderer.PieChartRenderer.drawData(MyApplication:119)
       at com.github.mikephil.charting.charts.PieChart.onDraw(MyApplication:123)
       at android.view.View.draw(View.java:13952)
       at android.view.View.getDisplayList(View.java:12846)
       at android.view.View.getDisplayList(View.java:12888)
       at android.view.View.draw(View.java:13665)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3087)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2924)
       at android.view.View.getDisplayList(View.java:12841)
       at android.view.View.getDisplayList(View.java:12888)
       at android.view.View.draw(View.java:13665)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3087)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2924)
       at android.view.View.getDisplayList(View.java:12841)
       at android.view.View.getDisplayList(View.java:12888)
       at android.view.View.draw(View.java:13665)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3087)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2924)
       at android.view.View.draw(View.java:13955)
       at android.widget.FrameLayout.draw(FrameLayout.java:467)
       at android.view.View.getDisplayList(View.java:12846)
       at android.view.View.getDisplayList(View.java:12888)
       at android.view.View.draw(View.java:13665)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3087)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2924)
       at android.view.View.draw(View.java:13955)
       at android.view.View.getDisplayList(View.java:12846)
       at android.view.View.getDisplayList(View.java:12888)
       at android.view.View.draw(View.java:13665)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3087)
       at android.widget.ListView.drawChild(ListView.java:3331)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2924)
       at android.widget.AbsListView.dispatchDraw(AbsListView.java:2357)
       at android.widget.ListView.dispatchDraw(ListView.java:3326)
       at android.view.View.draw(View.java:13955)
       at android.widget.AbsListView.draw(AbsListView.java:3697)
       at android.view.View.getDisplayList(View.java:12846)
       at android.view.View.getDisplayList(View.java:12888)
       at android.view.View.draw(View.java:13665)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3087)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2924)
       at android.view.View.draw(View.java:13955)
       at android.view.View.getDisplayList(View.java:12846)
       at android.view.View.getDisplayList(View.java:12888)
       at android.view.View.draw(View.java:13665)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3087)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2924)
       at android.view.View.draw(View.java:13955)
       at android.support.v4.view.ViewPager.draw(MyApplication:2341)
       at android.view.View.getDisplayList(View.java:12846)
       at android.view.View.getDisplayList(View.java:12888)
       at android.view.View.draw(View.java:13665)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3087)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2924)
       at android.view.View.getDisplayList(View.java:12841)
       at android.view.View.getDisplayList(View.java:12888)
       at android.view.View.draw(View.java:13665)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3087)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2924)
       at android.view.View.getDisplayList(View.java:12841)
       at android.view.View.getDisplayList(View.java:12888)
       at android.view.View.draw(View.java:13665)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3087)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2924)
       at android.view.View.getDisplayList(View.java:12841)
       at android.view.View.getDisplayList(View.java:12888)
       at android.view.View.draw(View.java:13665)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3087)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2924)
       at android.view.View.draw(View.java:13955)
       at android.widget.FrameLayout.draw(FrameLayout.java:467)
       at android.view.View.getDisplayList(View.java:12846)
       at android.view.View.getDisplayList(View.java:12888)
       at android.view.View.draw(View.java:13665)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3087)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2924)
       at android.view.View.getDisplayList(View.java:12841)
       at android.view.View.getDisplayList(View.java:12888)
       at android.view.View.draw(View.java:13665)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3087)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2924)
       at android.view.View.getDisplayList(View.java:12841)
       at android.view.View.getDisplayList(View.java:12888)
       at android.view.View.draw(View.java:13665)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3087)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2924)
       at android.view.View.getDisplayList(View.java:12841)
       at android.view.View.getDisplayList(View.java:12888)
       at android.view.View.draw(View.java:13665)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3087)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2924)
       at android.view.View.draw(View.java:13955)
       at android.widget.FrameLayout.draw(FrameLayout.java:467)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2224)
       at android.view.View.getDisplayList(View.java:12846)
       at android.view.View.getDisplayList(View.java:12888)
       at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1411)
       at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1359)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2367)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2239)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1872)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1004)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5481)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
       at android.view.Choreographer.doCallbacks(Choreographer.java:562)
       at android.view.Choreographer.doFrame(Choreographer.java:532)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
       at android.os.Handler.handleCallback(Handler.java:730)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5163)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)

How to handle it? Please answer it?

**Comment by srinivas3120** [comment]
@sanjaymajoka whats the solution for this?

**Comment by malwinder-s** [comment]
Getting this issue. What is solution for it?
