### ISSUE TITLE
Looks like mEntries in AxisBase is not reset correctly?

### ISSUE THREAD

**Issue by GuangHongLi** [PhilJay/MPAndroidChart#2645]
hi Philipp,

Thank your wonderful lib fiirst and Happy New Year!

Recently, I'm studying MPChart and trying draw a customize candlestick chart.
What I'm doing is: show all day values of one year, and there is an item to allow showing month value.
I display the day values by default, once the month item is checked, only the month values are displayed.
Now the issue is: After I display day values(234 records) first and change X Axis progress serveral times, when I select to display month values(12 records), the app is corrupted. The following is the stack when the issue happened. Then I set several breakpoints, and I found mEntries in AxisBase looks like not reset when display month values, here is the snapshot the mEntries ：
mEntries = (float[9]@4565)
0=0.0, 1=2.0, 2=4.0, 3=6.0, 4=8.0, 5=10.0, 6=180.0, 7=140.0, 8=80.0

I customize the label to date string, and only six lables are displayed. Looks like the mEntries are not reset when candlestick data are reset. I also call the setLableCount with one int parameter to 6, but when the issue occured, mEntries is again set to 9 elements.

Now I have  a workaround is to call setLabelCount with two parameters and set "force" to true.
but always 6 lables are displayed even only few data are displayed.

My question is :   Is there a function to reset the mEntries in XAxis after dataset is changed?
Thank your time in Advance!

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: guanghong.studio.balancetrack, PID: 3036
                  java.lang.IndexOutOfBoundsException: Invalid index 180, size is 12
                      at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                      at java.util.ArrayList.get(ArrayList.java:308)
                      at guanghong.studio.balancetrack.DateXAxisFormatter.getFormattedValue(DateXAxisFormatter.java:24)
                      at com.github.mikephil.charting.components.AxisBase.getFormattedLabel(AxisBase.java:472)
                      at com.github.mikephil.charting.components.AxisBase.getLongestLabel(AxisBase.java:458)
                      at com.github.mikephil.charting.renderer.XAxisRenderer.computeSize(XAxisRenderer.java:79)
                      at com.github.mikephil.charting.renderer.XAxisRenderer.computeAxisValues(XAxisRenderer.java:74)
                      at com.github.mikephil.charting.renderer.XAxisRenderer.computeAxis(XAxisRenderer.java:67)
                      at com.github.mikephil.charting.charts.BarLineChartBase.notifyDataSetChanged(BarLineChartBase.java:329)
                      at com.github.mikephil.charting.charts.Chart.setData(Chart.java:304)

**Comment by 603530013** [comment]
maybe you can try chart.invalidate();

**Comment by mouss-delta** [comment]
Hi I have exactly the same error. Did you manage to fix it?
