### ISSUE TITLE
CombinedChart highlight ArrayIndexOutOfBounds

### ISSUE THREAD

**Issue by entrpn** [PhilJay/MPAndroidChart#2696]
I have registered an OnChartValueSelectedListener for multiple charts. One of those charts is a CombinedChart.

When onValueSelected is called, I  am calling 

`chart.highlightValue(h,false);`

If I call highlightValue on CombinedChart I get:

01-10 00:09:24.878 25284 25284 E MessageQueue-JNI: java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
01-10 00:09:24.878 25284 25284 E MessageQueue-JNI: 	at java.util.ArrayList.get(ArrayList.java:310)
01-10 00:09:24.878 25284 25284 E MessageQueue-JNI: 	at com.github.mikephil.charting.data.CombinedData.getEntryForHighlight(CombinedData.java:185)
01-10 00:09:24.878 25284 25284 E MessageQueue-JNI: 	at com.github.mikephil.charting.charts.Chart.highlightValue(Chart.java:634)
0

Thanks.

**Comment by entrpn** [comment]
Ok, another observation.

Highlight.getDataSetIndex() for single charts is -1. Looking at the ChartData class:

`ChartData.getEntryForHighlight(Highlight highlight)`

returns mDataSet.get(highlight.getDataSetIndex()).getEntryForXValue(highlight.getX(), highlight.getY());

since index is -1, it returns ArrayIndexOutOfBounds.

Am I doing something wrong?

Thanks.

**Comment by bbrosius** [comment]
I just ran across this too. For some reason the library is using DataIndex not DataSetIndex. On your highlight object callSetDataIndex(index). I'm setting it to my dataset index and it seems to be working. But it's a little odd.

**Comment by zhangshuliang** [comment]
I met the same problem, has anyone solved it?
