### ISSUE TITLE
NullPointException

### ISSUE THREAD

**Issue by DreamerLeon** [PhilJay/MPAndroidChart#2779]
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.github.mikephil.charting.buffer.BarBuffer.setPhases(float, float)' on a null object reference
	at com.github.mikephil.charting.renderer.BarChartRenderer.drawDataSet(BarChartRenderer.java:135)
	at com.github.mikephil.charting.renderer.BarChartRenderer.drawData(BarChartRenderer.java:78)
	at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:229)
	at android.view.View.draw(View.java:16201)
	at android.view.View.updateDisplayListIfDirty(View.java:15198)
	at android.view.View.draw(View.java:15971)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.updateDisplayListIfDirty(View.java:15193)
	at android.view.View.draw(View.java:15971)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.updateDisplayListIfDirty(View.java:15193)
	at android.view.View.draw(View.java:15971)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.updateDisplayListIfDirty(View.java:15193)
	at android.view.View.draw(View.java:15971)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.updateDisplayListIfDirty(View.java:15193)
	at android.view.View.draw(View.java:15971)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.updateDisplayListIfDirty(View.java:15193)
	at android.view.View.draw(View.java:15971)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.draw(View.java:16204)
	at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2690)
	at android.view.View.updateDisplayListIfDirty(View.java:15198)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:282)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:288)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:323)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2642)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2461)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2094)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1134)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6045)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
	at android.view.Choreographer.doCallbacks(Choreographer.java:672)
	at android.view.Choreographer.doFrame(Choreographer.java:608)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5438)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by KORuL** [comment]
I got the same error in the latest version

**Comment by almic** [comment]
Should be fixed in the latest commit, until a new release is created you can just use the latest `-SNAPSHOT` version like this

```gradle
dependencies {
    implementation 'com.github.philjay:mpandroidchart:-SNAPSHOT'
}
```

**Comment by chjan** [comment]
3 years later. I get the same error. It is not notorious, it is sometimes
