### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference

### ISSUE THREAD

**Issue by evelynray** [PhilJay/MPAndroidChart#2898]
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
                      at com.github.mikephil.charting.utils.Utils.drawXAxisValue(Utils.java:546)
                      at com.github.mikephil.charting.renderer.XAxisRenderer.drawLabel(XAxisRenderer.java:231)
                      at com.github.mikephil.charting.renderer.XAxisRenderer.drawLabels(XAxisRenderer.java:225)
                      at com.github.mikephil.charting.renderer.XAxisRenderer.renderAxisLabels(XAxisRenderer.java:130)
                      at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:249)
                      at android.view.View.draw(View.java:16178)
                      at android.view.View.updateDisplayListIfDirty(View.java:15174)
                      at android.view.View.draw(View.java:15948)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                      at android.view.View.updateDisplayListIfDirty(View.java:15169)
                      at android.view.View.draw(View.java:15948)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                      at android.view.View.updateDisplayListIfDirty(View.java:15169)
                      at android.view.View.draw(View.java:15948)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                      at android.view.View.updateDisplayListIfDirty(View.java:15169)
                      at android.view.View.draw(View.java:15948)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                      at android.view.View.draw(View.java:16181)
                      at android.support.v4.view.ViewPager.draw(ViewPager.java:2447)
                      at android.view.View.updateDisplayListIfDirty(View.java:15174)
                      at android.view.View.draw(View.java:15948)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                      at android.view.View.updateDisplayListIfDirty(View.java:15169)
                      at android.view.View.draw(View.java:15948)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                      at android.view.View.updateDisplayListIfDirty(View.java:15169)
                      at android.view.View.draw(View.java:15948)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                      at android.view.View.updateDisplayListIfDirty(View.java:15169)
                      at android.view.View.draw(View.java:15948)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                      at android.view.View.updateDisplayListIfDirty(View.java:15169)
                      at android.view.View.draw(View.java:15948)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                      at android.view.View.updateDisplayListIfDirty(View.java:15169)
                      at android.view.View.draw(View.java:15948)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                      at android.view.View.updateDisplayListIfDirty(View.java:15169)
                      at android.view.View.draw(View.java:15948)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                      at android.view.View.updateDisplayListIfDirty(View.java:15169)
                      at android.view.View.draw(View.java:15948)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                      at android.view.View.draw(View.java:16181)
                      at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2690)
                      at android.view.View.updateDisplayListIfDirty(View.java:15174)
                      at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
                      at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
                      at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
                      at android.view.ViewRootImpl.draw(ViewRootImpl.java:2615)
                  	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2

I am sure I don't have anything such as .lenght() nor null in my codes, so what could be the problem?

**Comment by Rohitsaxena** [comment]
@evelynray would you able to solve this. I am still facing the same..

**Comment by almic** [comment]
@Rohitsaxena I think @evelynray was returning `null` objects in his value formatter, which is obviously a big no-no for Strings as an empty `""` string works fine. Please make sure you aren't doing that, and also make sure your library is the latest release version, as similar errors to this may have been patched already.

**Comment by chinakaifa** [comment]
请问解决了吗，我用的MPChart库implementation ("com.github.PhilJay:MPAndroidChart:v3.0.2")

**Comment by invweb** [comment]
Formatter has a method: getAxisLabel, I assume it should not return null, otherwise there will be a similar error

**Comment by chinakaifa** [comment]
好的谢谢🙏

---- Replied Message ----
| From | Vasilii ***@***.***> |
| Date | 11/10/2024 21:59 |
| To | PhilJay/MPAndroidChart ***@***.***> |
| Cc | chinakaifa ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [PhilJay/MPAndroidChart] java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference (#2898) |

Formatter has a method: getAxisLabel, I assume it should not return null, otherwise there will be a similar error
