### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1

### ISSUE THREAD

**Issue by krishnameena** [PhilJay/MPAndroidChart#2902]
I have 1 item in my list but still IAxisValueFormatter is returning value as -1 and getting following error  

```
FATAL EXCEPTION: main
                                                                  Process: in.qikcircle.owner, PID: 3473
                                                                  java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
                                                                      at java.util.ArrayList.get(ArrayList.java:310)
                                                                      at in.qikcircle.owner.activities.RevenueActivity$13.getFormattedValue(RevenueActivity.java:547)
                                                                      at com.github.mikephil.charting.components.AxisBase.getFormattedLabel(AxisBase.java:472)
                                                                      at com.github.mikephil.charting.components.AxisBase.getLongestLabel(AxisBase.java:458)
                                                                      at com.github.mikephil.charting.renderer.XAxisRenderer.computeSize(XAxisRenderer.java:79)
                                                                      at com.github.mikephil.charting.renderer.XAxisRenderer.computeAxisValues(XAxisRenderer.java:74)
                                                                      at com.github.mikephil.charting.renderer.XAxisRenderer.computeAxis(XAxisRenderer.java:67)
                                                                      at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:202)
                                                                      at android.view.View.draw(View.java:16199)
                                                                      at android.view.View.updateDisplayListIfDirty(View.java:15196)
                                                                      at android.view.View.draw(View.java:15969)
                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
                                                                      at android.view.View.updateDisplayListIfDirty(View.java:15191)
                                                                      at android.view.View.draw(View.java:15969)
                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
                                                                      at android.view.View.draw(View.java:16202)
                                                                      at android.widget.ScrollView.draw(ScrollView.java:1715)
                                                                      at android.view.View.updateDisplayListIfDirty(View.java:15196)
                                                                      at android.view.View.draw(View.java:15969)
                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
                                                                      at android.view.View.updateDisplayListIfDirty(View.java:15191)
                                                                      at android.view.View.draw(View.java:15969)
                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
                                                                      at android.view.View.updateDisplayListIfDirty(View.java:15191)
                                                                      at android.view.View.draw(View.java:15969)
                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
                                                                      at android.view.View.updateDisplayListIfDirty(View.java:15191)
                                                                      at android.view.View.draw(View.java:15969)
                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
                                                                      at android.view.View.updateDisplayListIfDirty(View.java:15191)
                                                                      at android.view.View.draw(View.java:15969)
                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
                                                                      at android.view.View.updateDisplayListIfDirty(View.java:15191)
                                                                      at android.view.View.draw(View.java:15969)
                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
                                                                      at android.view.View.draw(View.java:16202)
                                                                      at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2690)
                                                                      at android.view.View.updateDisplayListIfDirty(View.java:15196)
                                                                      at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
                                                                      at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
                                                                      at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
                                                                      at android.view.ViewRootImpl.draw(ViewRootImpl.java:2627)
                                                                      at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2446)
                                                                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2079)
                                                                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1119)
                                                                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6060)
                                                                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                      at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                      at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                      at android.os.Handler.handleCallback(Handler.java:746)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                  	at java.l
```

**Comment by mfc850585476** [comment]
try  IndexAxisValueFormatter.
https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartLib/src/main/java/com/github/mikephil/charting/formatter/IndexAxisValueFormatter.java
