### ISSUE TITLE
java.lang.IndexOutOfBoundsException when following tutorial

### ISSUE THREAD

**Issue by Sparker0i** [PhilJay/MPAndroidChart#2908]
I am trying to follow the tutorial given [here](https://github.com/PhilJay/MPAndroidChart/wiki/Getting-Started). But I get a IndexOutOfBoundsException even when I populate my data into a List. The following code is being used inside a fragment

    View rootView;
    Handler handler;
    LineChart chart;
    List<Entry> temperatures;
    LineDataSet dataSet;
    List<Entry> entries = new ArrayList<Entry>(10);

    @Override
     public View onCreateView(LayoutInflater inflater, ViewGroup container,
                                 Bundle savedInstanceState) {
            // Inflate the layout for this fragment
            rootView = inflater.inflate(R.layout.fragment_graphs, container, false);
            Log.i("Loaded" , "Fragment");
            chart = (LineChart) rootView.findViewById(R.id.chart);
            temperatures = new ArrayList<>();
            function();
            return rootView;
    }

    public void function() {
        getTemperatures();
        loadChart();
    }

    public void getTemperatures() {
        Bundle bundle = this.getArguments();
        JSONObject str;
        JSONArray list;
        Temperature[] x = new Temperature[10];
        if (bundle != null)
        try {
            str = new JSONObject(bundle.getString("json" , null));
            list = str.getJSONArray("list");
            for (int i = 0; i < 10; ++i) {
                //SimpleDateFormat simpleDateformat = new SimpleDateFormat("E" , Locale.US);
                long day = list.getJSONObject(i).getLong("dt");
                long temp = list.getJSONObject(i).getLong("day");
                x[i] = new Temperature(day , temp);
            }
            for (Temperature data : x) {

                // turn your data into Entry objects
                entries.add(new Entry(data.getDate(), data.getTemp()));
            }
        }
        catch (JSONException ex) {
            ex.printStackTrace();
        }
    }

    public void loadChart() {
        dataSet = new LineDataSet(entries, "Label"); // add entries to dataset
        dataSet.setColor(Color.parseColor("#FF0000"));
        dataSet.setValueTextColor(Color.parseColor("#FFFFFF"));
        LineData lineData = new LineData(dataSet);
        chart.setData(lineData);
        chart.invalidate();
    }

Here is the crash log that appears for me.

`
    03-10 03:02:00.282 29477-29477/com.a5corp.weather E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.a5corp.weather, PID: 29477
                                                                    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
                                                                        at java.util.ArrayList.get(ArrayList.java:411)
                                                                        at com.github.mikephil.charting.data.DataSet.getEntryForIndex(DataSet.java:286)
                                                                        at com.github.mikephil.charting.utils.Transformer.generateTransformedValuesLine(Transformer.java:184)
                                                                        at com.github.mikephil.charting.renderer.LineChartRenderer.drawValues(LineChartRenderer.java:545)
                                                                        at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:261)
                                                                        at android.view.View.draw(View.java:17189)
                                                                        at android.view.View.updateDisplayListIfDirty(View.java:16171)
                                                                        at android.view.View.draw(View.java:16955)
                                                                        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                        at android.view.View.updateDisplayListIfDirty(View.java:16166)
                                                                        at android.view.View.draw(View.java:16955)
                                                                        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                        at android.view.View.draw(View.java:17192)
                                                                        at android.view.View.updateDisplayListIfDirty(View.java:16171)
                                                                        at android.view.View.draw(View.java:16955)
                                                                        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                        at android.view.View.draw(View.java:17192)
                                                                        at android.view.View.updateDisplayListIfDirty(View.java:16171)
                                                                        at android.view.View.draw(View.java:16955)
                                                                        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                        at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1223)
                                                                        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                        at android.view.View.draw(View.java:17192)
                                                                        at android.view.View.updateDisplayListIfDirty(View.java:16171)
                                                                        at android.view.View.draw(View.java:16955)
                                                                        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                        at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1379)
                                                                        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                        at android.view.View.draw(View.java:17192)
                                                                        at android.view.View.updateDisplayListIfDirty(View.java:16171)
                                                                        at android.view.View.draw(View.java:16955)
                                                                        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                        at android.view.View.updateDisplayListIfDirty(View.java:16166)
                                                                        at android.view.View.draw(View.java:16955)
                                                                        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                        at android.view.View.updateDisplayListIfDirty(View.java:16166)
                                                                        at android.view.View.draw(View.java:16955)
                                                                        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                        at android.view.View.updateDisplayListIfDirty(View.java:16166)
                                                                        at android.view.View.draw(View.java:16955)
                                                                        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                        at android.view.View.updateDisplayListIfDirty(View.java:16166)
                                                                        at android.view.View.draw(View.java:16955)
                                                                        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                        at android.view.View.draw(View.java:17192)
                                                                        at com.android.internal.policy.DecorView.draw(DecorView.java:753)
                                                                        at android.view.View.updateDisplayListIfDirty(View.java:16171)
                                                                        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
                                                                        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
                                                                        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
                                                                        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2800)
                                                                        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
                                                                        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
                                                                        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6343)
03-10 03:02:00.282 29477-29477/com.a5corp.weather E/AndroidRuntime:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                        at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                        at android.os.Handler.handleCallback(Handler.java:751)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6126)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
`

What I can say is that code execution does reach loadChart() method

**Comment by Jetz72** [comment]
Looks like you're never giving your fragment an arguments bundle containing the JSON string. So the try block in getTemperatures never happens, the array of entries remains empty, the LineDataSet gets created with no data, and MPAndroidChart doesn't like it when told to render a LineDataSet with no entries. 
#2455 is the underlying issue.

**Comment by Sparker0i** [comment]
Indeed that was the issue @Jetz72 . Thanks for letting me know that. I've fixed it as well
