### ISSUE TITLE
  java.lang.NullPointerException: Attempt to invoke interface method 'int com.github.mikephil.charting.interfaces.datasets.IDataSet.getEntryIndex(com.github.mikephil.charting.data.Entry)

### ISSUE THREAD

**Issue by neocameback** [PhilJay/MPAndroidChart#2917]
Hi @PhilJay I got this error when using Line chart.
Could you or someone check out for the problem. 

I think the problem is in these lines of your Chart class

`IDataSet set = mData.getDataSetByIndex(highlight.getDataSetIndex());

   Entry e = mData.getEntryForHighlight(mIndicesToHighlight[i]);
   int entryIndex = set.getEntryIndex(e);`

Where we can't get data set from input data.

Here is my code.

`Process: com.gemvietnam.canhbaochitieu, PID: 25781
                                                                               java.lang.NullPointerException: Attempt to invoke interface method 'int com.github.mikephil.charting.interfaces.datasets.IDataSet.getEntryIndex(com.github.mikephil.charting.data.Entry)' on a null object reference
                                                                                   at com.github.mikephil.charting.charts.Chart.drawMarkers(Chart.java:731)
                                                                                   at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:268)
                                                                                   at android.view.View.draw(View.java:16201)
                                                                                   at android.view.View.updateDisplayListIfDirty(View.java:15198)
                                                                                   at android.view.View.draw(View.java:15971)`

`mLineChart.resetTracking();

//    int max = 1;
    ArrayList<ILineDataSet> dataSets = new ArrayList<>();
    List<THLKLineChartLegend> chartLegends = new ArrayList<>();
    List<String> dates = new ArrayList<>();

    // Build x Axis values
    Map<String, Integer> xAxisValues = Charts.getDateMapLine(accDivPlanChart.getLines(), dates);

    if (accDivPlanChart.getLines() != null && !accDivPlanChart.getLines().isEmpty()) {
      for (int z = 0; z < accDivPlanChart.getLines().size(); z++) {
        // Data for 1 line
        LChartLine chartLine = accDivPlanChart.getLines().get(z);
        ArrayList<Entry> values = new ArrayList<>();

        // Legend info
        String infoString = "";
        if (chartLine.getInfoList() != null) {

          for (LChartLineInfo info : chartLine.getInfoList()) {
            infoString += info.getKey() + " " + info.getValue() + ",";
          }

          infoString = infoString.substring(0, infoString.length() - 1);
        }

        // Add points to line
        List<LChartLinePoint> points = chartLine.getPoints();
        if (points != null && !points.isEmpty()) {
          for (int i = 0; i < points.size(); i++) {
            LChartLinePoint point = chartLine.getPoints().get(i);
            if (point == null) {
              continue;
            }

            float xValue = xAxisValues.containsKey(point.getDate()) ? xAxisValues.get(point.getDate()) : 0;
            if (StringUtils.isEmpty(point.getValue())) {
              values.add(new Entry(0, 0));
            } else {
              values.add(new Entry(xValue, Float.parseFloat(point.getValue())));
            }
          }
        } else {
          values.add(new Entry(0, 0));
        }

        // Data set
        LineDataSet d = new LineDataSet(values, "DataSet " + (z + 1));

        d.setDrawValues(false);
        d.setLineWidth(1.5f);
        d.setCircleRadius(2f);

        int color = getColor(chartLine.getColor(), z);

        d.setColor(color);
        d.setCircleColor(color);
        dataSets.add(d);

        chartLegends.add(new THLKLineChartLegend(chartLine.getTitle(), infoString)
            .setColor(color));
      }
    }

    // x axis
    XAxis xAxis = mLineChart.getXAxis();
    xAxis.setDrawLabels(true);

//    IAxisValueFormatter xAxisFormatter = new DayAxisValueFormatter(0, dates);
//    xAxis.setValueFormatter(xAxisFormatter);

    int max = dates.size();
    xAxis.setAxisMinimum(0f);
    xAxis.setAxisMaximum(max);
    xAxis.setLabelCount(max + 1, true);

    configureChartYAxisLabels(mLineChart, dates);
    // Y axis
    mLineChart.getAxisLeft().setValueFormatter(new IAxisValueFormatter() {

      @Override
      public String getFormattedValue(float value, AxisBase axis) {
        return NumberUtils.getCommonFormat().format(value);
      }
    });

    LineData data = new LineData(dataSets);

    mLineChart.setData(data);
    mLineChart.invalidate();
`

Thanks in advance.

**Comment by khan-tm** [comment]
Any update? :confused:

**Comment by JacobJust** [comment]
I have seen the same issue, but I´m not able to reproduce it. 
I created a PR to fix it: https://github.com/PhilJay/MPAndroidChart/pull/3145

When waiting for a merge, I made a subclass of linechart, where I override drawMarkers, with the code from my PR.
