### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: length=4480; index=4480  at com.github.mikephil.charting.buffer.BarBuffer.addBar(BarBuffer.java:37)

### ISSUE THREAD

**Issue by panmin** [PhilJay/MPAndroidChart#2940]
`03-19 23:09:19.601 18322 18322 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=4480; index=4480

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at com.github.mikephil.charting.buffer.BarBuffer.addBar(BarBuffer.java:37)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at com.github.mikephil.charting.buffer.HorizontalBarBuffer.feed(HorizontalBarBuffer.java:87)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at com.github.mikephil.charting.renderer.HorizontalBarChartRenderer.drawDataSet(HorizontalBarChartRenderer.java:109)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at com.github.mikephil.charting.renderer.BarChartRenderer.drawData(BarChartRenderer.java:78)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:229)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.View.draw(View.java:16186)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15109)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.View.getDisplayList(View.java:15132)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15069)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.View.getDisplayList(View.java:15132)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15069)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.View.getDisplayList(View.java:15132)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15069)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.View.getDisplayList(View.java:15132)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15069)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.View.getDisplayList(View.java:15132)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15069)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.View.getDisplayList(View.java:15132)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15069)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.View.getDisplayList(View.java:15132)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15069)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.View.getDisplayList(View.java:15132)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15069)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.View.getDisplayList(View.java:15132)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15069)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.View.getDisplayList(View.java:15132)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15069)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.View.getDisplayList(View.java:15132)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15069)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.View.getDisplayList(View.java:15132)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:275)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:281)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:320)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2751)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2584)

03-19 23:09:19.601 18322 18322 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootI`

**Comment by monicager** [comment]
I had this same issue, and this happend when you dont call chart.notifyDataSetChanged(); after you add data to your chart.

**Comment by Mooreel** [comment]
Same issue

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.householder, PID: 17559
    java.lang.ArrayIndexOutOfBoundsException: length=24; index=24
        at com.github.mikephil.charting.buffer.BarBuffer.addBar(BarBuffer.java:37)
        at com.github.mikephil.charting.buffer.BarBuffer.feed(BarBuffer.java:123)
        at com.github.mikephil.charting.renderer.BarChartRenderer.drawDataSet(BarChartRenderer.java:142)
        at com.github.mikephil.charting.renderer.BarChartRenderer.drawData(BarChartRenderer.java:80)
        at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:232)
        at android.view.View.draw(View.java:15231)
        at android.view.View.updateDisplayListIfDirty(View.java:14167)
        at android.view.View.getDisplayList(View.java:14189)
        at android.view.View.draw(View.java:14959)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
        at android.view.View.updateDisplayListIfDirty(View.java:14162)
        at android.view.View.getDisplayList(View.java:14189)
        at android.view.View.draw(View.java:14959)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
        at android.view.View.updateDisplayListIfDirty(View.java:14162)
        at android.view.View.getDisplayList(View.java:14189)
        at android.view.View.draw(View.java:14959)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
        at android.view.View.draw(View.java:15234)
        at android.widget.FrameLayout.draw(FrameLayout.java:598)
        at android.widget.ScrollView.draw(ScrollView.java:1689)
        at android.view.View.updateDisplayListIfDirty(View.java:14167)
        at android.view.View.getDisplayList(View.java:14189)
        at android.view.View.draw(View.java:14959)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
        at android.view.View.updateDisplayListIfDirty(View.java:14162)
        at android.view.View.getDisplayList(View.java:14189)
        at android.view.View.draw(View.java:14959)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
        at android.view.View.draw(View.java:15234)
        at androidx.viewpager.widget.ViewPager.draw(ViewPager.java:2426)
        at android.view.View.updateDisplayListIfDirty(View.java:14167)
        at android.view.View.getDisplayList(View.java:14189)
        at android.view.View.draw(View.java:14959)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
        at android.view.View.updateDisplayListIfDirty(View.java:14162)
        at android.view.View.getDisplayList(View.java:14189)
        at android.view.View.draw(View.java:14959)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2023)
        at android.view.View.draw(View.java:15234)
        at android.view.View.updateDisplayListIfDirty(View.java:14167)
        at android.view.View.getDisplayList(View.java:14189)
        at android.view.View.draw(View.java:14959)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
        at android.view.View.updateDisplayListIfDirty(View.java:14162)
        at android.view.View.getDisplayList(View.java:14189)
        at android.view.View.draw(View.java:14959)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
        at android.view.View.updateDisplayListIfDirty(View.java:14162)
        at android.view.View.getDisplayList(View.java:14189)
        at android.view.View.draw(View.java:14959)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
        at android.view.View.updateDisplayListIfDirty(View.java:14162)
        at android.view.View.getDisplayList(View.java:14189)
        at android.view.View.draw(View.java:14959)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
    	at android.vi

**Comment by AvgoustisFakiris** [comment]
Same here when I update data and Im using 
        chart.notifyDataSetChanged();
        chart.invalidate();

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: gr.hua.www.v2of2, PID: 10322
    java.lang.ArrayIndexOutOfBoundsException: length=16; index=16
        at com.github.mikephil.charting.buffer.BarBuffer.addBar(BarBuffer.java:37)
        at com.github.mikephil.charting.buffer.BarBuffer.feed(BarBuffer.java:80)
        at com.github.mikephil.charting.renderer.BarChartRenderer.drawDataSet(BarChartRenderer.java:144)
        at com.github.mikephil.charting.renderer.BarChartRenderer.drawData(BarChartRenderer.java:82)
        at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:237)
        at android.view.View.draw(View.java:19314)
        at android.view.View.updateDisplayListIfDirty(View.java:18250)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4252)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4232)
        at android.view.View.updateDisplayListIfDirty(View.java:18209)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4252)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4232)
        at android.view.View.updateDisplayListIfDirty(View.java:18209)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4252)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4232)
        at android.view.View.updateDisplayListIfDirty(View.java:18209)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4252)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4232)
        at android.view.View.updateDisplayListIfDirty(View.java:18209)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4252)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4232)
        at android.view.View.updateDisplayListIfDirty(View.java:18209)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4252)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4232)
        at android.view.View.updateDisplayListIfDirty(View.java:18209)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:684)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:690)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:804)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3199)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2997)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2526)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1515)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7266)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:981)
        at android.view.Choreographer.doCallbacks(Choreographer.java:790)
        at android.view.Choreographer.doFrame(Choreographer.java:721)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:967)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by Mooreel** [comment]
Same issue ... and it seems the outofbounds is completely random. Sometimes with index 12, then 32 etc...

**Comment by itedevelopers** [comment]
Same issue. Any solution?

**Comment by GaganKainth** [comment]
One reason for this is not calling `notifyDataChanged()` on the `data` object as mentioned by @PhilJay [here](https://github.com/PhilJay/MPAndroidChart/issues/1370).
