### ISSUE TITLE
Runtime Error: Binary XML file line #116: Error inflating class com.github.mikephil.charting.charts.LineChart

### ISSUE THREAD

**Issue by Ishpreet** [PhilJay/MPAndroidChart#296]
Hi I am getting following runtime error when I am using LineChart.
D/Error﹕ ERR: exClass=java.lang.NullPointerException
D/Error﹕ ERR: exMsg=Attempt to invoke virtual method 'float com.github.mikephil.charting.renderer.Transformer.getScaleX()' on a null object reference
D/Error﹕ ERR: file=BarLineChartBase.java
D/Error﹕ ERR: class=com.github.mikephil.charting.charts.BarLineChartBase
D/Error﹕ ERR: method=getScaleX line=1622
D/Error﹕ ERR: stack=android.view.InflateException: Binary XML file line #116: Error inflating class com.github.mikephil.charting.charts.LineChart
            at android.view.LayoutInflater.createView(LayoutInflater.java:633)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
            at com.equinox.damir.ishpreet.myliftlogger.MyRecyclerAdapter.onCreateViewHolder(MyRecyclerAdapter.java:79)
            at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:4121)
            at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3431)
            at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3340)
            at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1810)
            at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1306)
            at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1269)
            at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:523)
            at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:1988)
            at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2237)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:543)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:890)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.

**Comment by Ishpreet** [comment]
Issue resolved after changing jar to version 1.7.3

**Comment by yusnerqui** [comment]
Me está susediendo algo muy parecido, uso eclipse, descargue un .jar, y a la hora de inflar el xml me dice que no encuentra la clase <com.xxx.xxx.xx, el modo de importar que usé fue los encontrado por esta página, copie el .jard para mi carpeta lib y le di clic derecho build path/ add build path, además di clic derecho en el proyecto y me fui al menu propiedades/ android build path y en library verifiqué que se encuentra la librería. espero que mi español pueda ser entendido y me puedan ayudar. Saludos

**Comment by pdcmailid** [comment]
unable to inflate xml containing com.github.mikephil.charting.charts.LineChart
follwing is my log 
i am using version 'com.github.PhilJay:MPAndroidChart:v2.1.6' in android studio by using dependancy
Please help me stuck from 2 days


09-30 11:04:24.753 8122-8122/savvytekmate.dev.com.jaccha_baccha E/UncaughtException: java.lang.RuntimeException: Unable to start activity ComponentInfo{savvytekmate.dev.com.jaccha_baccha/savvytekmate.dev.com.jaccha_baccha.activities.BlankActivityForFragment}: android.view.InflateException: Binary XML file line #13: Error inflating class com.github.mikephil.charting.charts.LineChart
                                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
                                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                         at android.os.Looper.loop(Looper.java:135)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                                      Caused by: android.view.InflateException: Binary XML file line #13: Error inflating class com.github.mikephil.charting.charts.LineChart
                                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:757)
                                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                                         at savvytekmate.dev.com.jaccha_baccha.fragments.parenting_fragment.growth_chart.MonthVsHeadCircumFragment.onCreateView(MonthVsHeadCircumFragment.java:73)
                                                                                         at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)
                                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
                                                                                         at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                                         at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                                                                                         at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                                                                                         at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                                                         at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                                                         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
                                                                                         at android.support.v4.app.Fragment.performStart(Fragment.java:2214)
                                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1340)
                                                                                         at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                                         at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:2907)
                                                                                         at android.support.v4.app.FragmentController.dispatchStart(FragmentController.java:212)
                                                                                         at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:613)
                                                                                         at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
                                                                                         at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236)
                                                                                         at android.app.Activity.performStart(Activity.java:6006)
                                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2288)
                                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                         at android.os.Looper.loop(Looper.java:135) 
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                                         at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
                                                                                      Caused by: java.lang.ClassNotFoundException: Didn't find class "com.github.mikephil.charting.charts.LineChart" on path: DexPathList[[zip file "/data/app/savvytekmate.dev.com.jaccha_baccha-1/base.apk", zip file "/data/app/savvytekmate.dev.com.jaccha_baccha-1/split_lib_dependencies_apk.apk", zip file "/data/app/savvytekmate.dev.com.jaccha_baccha-1/split_lib_slice_0_apk.apk", zip file "/data/app/savvytekmate.dev.com.jaccha_baccha-1/split_lib_slice_1_apk.apk", zip file "/data/app/savvytekmate.dev.com.jaccha_baccha-1/split_lib_slice_2_apk.apk", zip file "/data/app/savvytekmate.dev.com.jaccha_baccha-1/split_lib_slice_3_apk.apk", zip file "/data/app/savvytekmate.dev.com.jaccha_baccha-1/split_lib_slice_4_apk.
09-30 11:04:24.975 8122-8122/savvytekmate.dev.com.jaccha_baccha E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                  Process: savvytekmate.dev.com.jaccha_baccha, PID: 8122
                                                                                  java.lang.RuntimeException: Unable to start activity ComponentInfo{savvytekmate.dev.com.jaccha_baccha/savvytekmate.dev.com.jaccha_baccha.activities.BlankActivityForFragment}: android.view.InflateException: Binary XML file line #13: Error inflating class com.github.mikephil.charting.charts.LineChart
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                                                      at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                      at android.os.Looper.loop(Looper.java:135)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                                   Caused by: android.view.InflateException: Binary XML file line #13: Error inflating class com.github.mikephil.charting.charts.LineChart
                                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:757)
                                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                                      at savvytekmate.dev.com.jaccha_baccha.fragments.parenting_fragment.growth_chart.MonthVsHeadCircumFragment.onCreateView(MonthVsHeadCircumFragment.java:73)
                                                                                      at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)
                                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
                                                                                      at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                                      at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                                                                                      at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                                                                                      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                                                      at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                                                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
                                                                                      at android.support.v4.app.Fragment.performStart(Fragment.java:2214)
                                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1340)
                                                                                      at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                                      at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:2907)
                                                                                      at android.support.v4.app.FragmentController.dispatchStart(FragmentController.java:212)
                                                                                      at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:613)
                                                                                      at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
                                                                                      at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236)
                                                                                      at android.app.Activity.performStart(Activity.java:6006)
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2288)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                                                      at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                      at android.os.Looper.loop(Looper.java:135) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                                      at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
                                                                                   Caused by: java.lang.ClassNotFoundException: Didn't find class "com.github.mikephil.charting.charts.LineChart" on path: DexPathList[[zip file "/data/app/savvytekmate.dev.com.jaccha_baccha-1/base.apk", zip file "/data/app/savvytekmate.dev.com.jaccha_baccha-1/split_lib_dependencies_apk.apk", zip file "/data/app/savvytekmate.dev.com.jaccha_baccha-1/split_lib_slice_0_apk.apk", zip file "/data/app/savvytekmate.dev.com.jaccha_baccha-1/split_lib_slice_1_apk.apk", zip file "/data/app/savvytekmate.dev.com.jaccha_baccha-1/split_lib_slice_2_apk.apk", zip file "/data/app/savvytekmate.dev.com.jaccha_baccha-1/split_lib_slice_3_apk.apk", zip fi
