### ISSUE TITLE
Crash on RealTime graph

### ISSUE THREAD

**Issue by gerominoapps** [PhilJay/MPAndroidChart#2962]
Hi phil

First of all amazing Job!! 

I am experiencing a crash working with the Latest Version V3.0.2 (It also happened on older versions)
it happen after 2 minuets of adding Entries.

Thanks!

Crash Log:

java.lang.IndexOutOfBoundsException: Index: 0, Size: 1
                                                                          at java.util.ArrayList.get(ArrayList.java:411)
                                                                          at com.github.mikephil.charting.renderer.LegendRenderer.renderLegend(LegendRenderer.java:377)
                                                                          at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:266)
                                                                          at android.view.View.draw(View.java:18313)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:17291)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:17254)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:17254)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:17254)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:17254)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:17254)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:17254)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:17254)
                                                                          at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:666)
                                                                          at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:672)
                                                                          at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:780)
                                                                          at android.view.ViewRootImpl.draw(ViewRootImpl.java:3093)
                                                                          at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2889)
                                                                          at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2483)
                                                                          at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1490)
                                                                          at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7027)
                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:702)
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:638)
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
                                                                          at android.os.Handler.handleCallback(Handler.java:751)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6688)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by Jetz72** [comment]
Seems like an issue with synchronization. Only way I could see that problem with that array is if notifyDataSetChanged was called as it was rendering.  Do you have a thread responsible for updating the data on the graph that might happen concurrently with the graph being drawn? You may want to try posting the data and update notice as a Runnable over to the UI thread instead.

**Comment by gerominoapps** [comment]
I have checked this issue and you are right. The events sent by the Library are not sent by a Handler and I receive them not in the UI Thread. 
But don't you think you need to protect your code from such a scenario?

**Comment by Jetz72** [comment]
Not really my code, I'm just here because I like solving problems. In Android, methods that affect the content of views directly will often have problems if done from anywhere other than the UI thread. Attempting to synchronize the operations wouldn't help unless you wrapped large portions of the code, and doing that would drag down the rendering thread as it's waiting for everything to be updated, which should have been done on the UI thread. There may be a few ways to make developers more aware of it, but the general issue "Don't touch the UI outside of the UI thread" probably isn't going away.

**Comment by gerominoapps** [comment]
Thanks for the help!
I agree with you, still It will be nice if you can through a
CalledFromWrongThreadException in this case to make developers aware.
In my case it would have saved me an hour ;)


*Gal Rom, Native Development Expert*
https://www.geromino-apps.com <http://www.geromino-apps.com>

**Comment by 4sskick** [comment]
is there any solved for this one?
I'm using latest version of this library

**Comment by Jetz72** [comment]
> is there any solved for this one?
> I'm using latest version of this library

From what I can see and recall, the solution was:

>You may want to try posting the data and update notice as a Runnable over to the UI thread instead.

Changing the data and calling notifyDataSetChanged on a separate thread while the UI is in the middle of drawing caused this issue. Gotta either find some way to synchronize them or run the update on the UI thread to ensure there isn't a race condition.

**Comment by 4sskick** [comment]
> > is there any solved for this one?
> > I'm using latest version of this library
> 
> From what I can see and recall, the solution was:
> 
> > You may want to try posting the data and update notice as a Runnable over to the UI thread instead.
> 
> Changing the data and calling notifyDataSetChanged on a separate thread while the UI is in the middle of drawing caused this issue. Gotta either find some way to synchronize them or run the update on the UI thread to ensure there isn't a race condition.

https://github.com/PhilJay/MPAndroidChart/issues/2992#issuecomment-292855646 this solved my problem for temporary. Btw I will try your suggestion
