### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by fayduan** [PhilJay/MPAndroidChart#2992]
- Version:3.0.2
When I draw realtime entry, it often crash like below, it seems like that something wrong in `BarLineChartBase` 

FATAL EXCEPTION: main
                                                                   Process: xxx, PID: 9130
                                                                   java.lang.IndexOutOfBoundsException: Index: 0, Size: 1
                                                                       at java.util.ArrayList.get(ArrayList.java:411)
                                                                       at com.github.mikephil.charting.renderer.LegendRenderer.renderLegend(LegendRenderer.java:377)
                                                                       at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:266)
                                                                       at android.view.View.draw(View.java:17189)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16171)
                                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16134)
                                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16134)
                                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16134)
                                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16134)
                                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16134)
                                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16134)
                                                                       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
                                                                       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
                                                                       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
                                                                       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2800)
                                                                       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
                                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
                                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6343)
                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                       at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6126)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by kexuejin** [comment]
Version:3.0.1 is ok,update to 3.0.2 have the same problem

**Comment by fayduan** [comment]
This is a error related to legend, I disabled it for a temporary fix.
`mChart.getLegend().setEnabled(false);`

**Comment by MGaetan89** [comment]
This is a duplicate of #2962

**Comment by PankajDandriyal** [comment]
> 
> 
> This is a error related to legend, I disabled it for a temporary fix.
> 
> > `mChart.getLegend().setEnabled(false);`
Did u find a proper Solution @fayduan ??

**Comment by sandip93291** [comment]
@fayduan thanks
