### ISSUE TITLE
java.lang.NegativeArraySizeException Transformer.generateTransformedValuesLine

### ISSUE THREAD

**Issue by fabiolanza** [PhilJay/MPAndroidChart#3001]
Hi,

I am having a strange issue in my chart. It looks that the when trying to set the minimum and maximum values the range is being wrongly calculated. Min being the greater value and max being the lesser, the range is becoming negative.

Please see the screenshot from public void set(BarLineScatterCandleBubbleDataProvider chart, IBarLineScatterCandleBubbleDataSet dataSet):
<img width="1062" alt="screen shot 2017-04-09 at 22 38 03" src="https://cloud.githubusercontent.com/assets/1178093/24840839/92d62276-1d75-11e7-9eba-addd92be803c.png">

Another dataset, which generated count = -36 (generateTransformedValuesLine in Transformer.java):
```
DataSet, label: Temperature, entries: 20
Entry, x: 8539469.0 y: 23.0 Entry, x: 8539449.0 y: 22.0 Entry, x: 8539429.0 y: 23.0 Entry, x: 8539409.0 y: 20.0 Entry, x: 8539389.0 y: 22.0 Entry, x: 8539369.0 y: 22.0 Entry, x: 8539349.0 y: 23.0 Entry, x: 8539329.0 y: 22.0 Entry, x: 8539309.0 y: 20.0 Entry, x: 8539289.0 y: 21.0 Entry, x: 8539269.0 y: 22.0 Entry, x: 8539249.0 y: 24.0 Entry, x: 8539229.0 y: 23.0 Entry, x: 8539209.0 y: 22.0 Entry, x: 8539189.0 y: 22.0 Entry, x: 8539169.0 y: 23.0 Entry, x: 8539149.0 y: 20.0 Entry, x: 8539129.0 y: 20.0 Entry, x: 8539109.0 y: 20.0 Entry, x: 8539089.0 y: 24.0 
```

Which fails: valuePointsForGenerateTransformedValuesLine = new float[count]; --> since it tries to create an array with negative size...

Would you be able to shed any light on the possible cause of the issue?

Thank you!

This is the crash:
 ```
--------- beginning of crash
04-09 21:51:59.392 7822-7822/it.bitrack.fabio.bitrack E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: it.bitrack.fabio.bitrack, PID: 7822
                                                                        java.lang.NegativeArraySizeException: -36
                                                                            at com.github.mikephil.charting.utils.Transformer.generateTransformedValuesLine(Transformer.java:178)
                                                                            at com.github.mikephil.charting.renderer.LineChartRenderer.drawValues(LineChartRenderer.java:545)
                                                                            at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:261)
                                                                            at android.view.View.draw(View.java:17185)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16167)
                                                                            at android.view.View.draw(View.java:16951)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16162)
                                                                            at android.view.View.draw(View.java:16951)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16162)
                                                                            at android.view.View.draw(View.java:16951)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                            at android.view.View.draw(View.java:17188)
                                                                            at android.widget.ScrollView.draw(ScrollView.java:1722)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16167)
                                                                            at android.view.View.draw(View.java:16951)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16162)
                                                                            at android.view.View.draw(View.java:16951)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16162)
                                                                            at android.view.View.draw(View.java:16951)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                            at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1379)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                            at android.view.View.draw(View.java:17188)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16167)
                                                                            at android.view.View.draw(View.java:16951)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16162)
                                                                            at android.view.View.draw(View.java:16951)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16162)
                                                                            at android.view.View.draw(View.java:16951)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16162)
                                                                            at android.view.View.draw(View.java:16951)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16162)
                                                                            at android.view.View.draw(View.java:16951)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                            at android.view.View.draw(View.java:17188)
                                                                            at com.android.internal.policy.DecorView.draw(DecorView.java:753)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16167)
                                                                            at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
                                                                            at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
                                                                            at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
                                                                            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2800)
                                                                            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
                                                                            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
                                                                            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
04-09 21:51:59.392 7822-7822/it.bitrack.fabio.bitrack E/AndroidRuntime:     at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                            at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                            at android.os.Handler.handleCallback(Handler.java:751)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by fabiolanza** [comment]
@PhilJay any chance you could give a look at this? Tomorrow I have an important presentation at work and should have this working :(. Thank you so much.

**Comment by fabiolanza** [comment]
This topic fixed my issue!

https://github.com/PhilJay/MPAndroidChart/issues/2074#issuecomment-238458565
