### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isMutable()' on a null object reference 

### ISSUE THREAD

**Issue by durgatjb** [PhilJay/MPAndroidChart#3007]
I got the below exception and the app crashed. I have used Line chart with date (X axis) and float values using this library.

```
# OS Version: 7.1.2
# Device: Nexus 6P
# RAM Free: 39.6%
# Disk Free: 33.5%

#0. Crashed: main: 0 0 0x0000000000000000
       at android.graphics.Canvas.<init>(Canvas.java:130)
       at com.github.mikephil.charting.renderer.LineChartRenderer.drawData(LineChartRenderer.java:84)
       at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:227)
       at android.view.View.draw(View.java:17185)
       at android.view.View.updateDisplayListIfDirty(View.java:16167)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.updateDisplayListIfDirty(View.java:16162)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4248)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.draw(View.java:17188)
       at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3657)
       at android.view.View.updateDisplayListIfDirty(View.java:16167)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.updateDisplayListIfDirty(View.java:16162)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.draw(View.java:17188)
       at android.support.v4.widget.NestedScrollView.draw(NestedScrollView.java:1768)
       at android.view.View.updateDisplayListIfDirty(View.java:16167)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.updateDisplayListIfDirty(View.java:16162)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1195)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.draw(View.java:17188)
       at android.view.View.updateDisplayListIfDirty(View.java:16167)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.updateDisplayListIfDirty(View.java:16162)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1195)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.draw(View.java:17188)
       at android.view.View.updateDisplayListIfDirty(View.java:16167)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1379)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.draw(View.java:17188)
       at android.view.View.updateDisplayListIfDirty(View.java:16167)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.updateDisplayListIfDirty(View.java:16162)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.updateDisplayListIfDirty(View.java:16162)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.updateDisplayListIfDirty(View.java:16162)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.updateDisplayListIfDirty(View.java:16162)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.draw(View.java:17188)
       at com.android.internal.policy.DecorView.draw(DecorView.java:754)
       at android.view.View.updateDisplayListIfDirty(View.java:16167)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2800)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6338)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
       at android.view.Choreographer.doCallbacks(Choreographer.java:686)
       at android.view.Choreographer.doFrame(Choreographer.java:621)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6121)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

--

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isMutable()' on a null object reference
       at android.graphics.Canvas.<init>(Canvas.java:130)
       at com.github.mikephil.charting.renderer.LineChartRenderer.drawData(LineChartRenderer.java:84)
       at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:227)
       at android.view.View.draw(View.java:17185)
       at android.view.View.updateDisplayListIfDirty(View.java:16167)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.updateDisplayListIfDirty(View.java:16162)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4248)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.draw(View.java:17188)
       at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3657)
       at android.view.View.updateDisplayListIfDirty(View.java:16167)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.updateDisplayListIfDirty(View.java:16162)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.draw(View.java:17188)
       at android.support.v4.widget.NestedScrollView.draw(NestedScrollView.java:1768)
       at android.view.View.updateDisplayListIfDirty(View.java:16167)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.updateDisplayListIfDirty(View.java:16162)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1195)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.draw(View.java:17188)
       at android.view.View.updateDisplayListIfDirty(View.java:16167)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.updateDisplayListIfDirty(View.java:16162)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1195)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.draw(View.java:17188)
       at android.view.View.updateDisplayListIfDirty(View.java:16167)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1379)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.draw(View.java:17188)
       at android.view.View.updateDisplayListIfDirty(View.java:16167)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.updateDisplayListIfDirty(View.java:16162)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.updateDisplayListIfDirty(View.java:16162)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.updateDisplayListIfDirty(View.java:16162)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.updateDisplayListIfDirty(View.java:16162)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.draw(View.java:17188)
       at com.android.internal.policy.DecorView.draw(DecorView.java:754)
       at android.view.View.updateDisplayListIfDirty(View.java:16167)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2800)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6338)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
       at android.view.Choreographer.doCallbacks(Choreographer.java:686)
       at android.view.Choreographer.doFrame(Choreographer.java:621)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6121)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

#0. Crashed: main: 0 0 0x0000000000000000
       at android.graphics.Canvas.<init>(Canvas.java:130)
       at com.github.mikephil.charting.renderer.LineChartRenderer.drawData(LineChartRenderer.java:84)
       at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:227)
       at android.view.View.draw(View.java:17185)
       at android.view.View.updateDisplayListIfDirty(View.java:16167)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.updateDisplayListIfDirty(View.java:16162)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4248)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.draw(View.java:17188)
       at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3657)
       at android.view.View.updateDisplayListIfDirty(View.java:16167)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.updateDisplayListIfDirty(View.java:16162)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.draw(View.java:17188)
       at android.support.v4.widget.NestedScrollView.draw(NestedScrollView.java:1768)
       at android.view.View.updateDisplayListIfDirty(View.java:16167)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.updateDisplayListIfDirty(View.java:16162)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1195)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.draw(View.java:17188)
       at android.view.View.updateDisplayListIfDirty(View.java:16167)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.updateDisplayListIfDirty(View.java:16162)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1195)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.draw(View.java:17188)
       at android.view.View.updateDisplayListIfDirty(View.java:16167)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1379)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.draw(View.java:17188)
       at android.view.View.updateDisplayListIfDirty(View.java:16167)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.updateDisplayListIfDirty(View.java:16162)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.updateDisplayListIfDirty(View.java:16162)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.updateDisplayListIfDirty(View.java:16162)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.updateDisplayListIfDirty(View.java:16162)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.draw(View.java:17188)
       at com.android.internal.policy.DecorView.draw(DecorView.java:754)
       at android.view.View.updateDisplayListIfDirty(View.java:16167)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2800)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6338)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
       at android.view.Choreographer.doCallbacks(Choreographer.java:686)
       at android.view.Choreographer.doFrame(Choreographer.java:621)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6121)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by wryday** [comment]
Same issue with slightly different line numbers:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isMutable()' on a null object reference
       at android.graphics.Canvas.(Canvas.java)
       at com.github.mikephil.charting.renderer.LineChartRenderer.drawData(SourceFile:86)
       at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(SourceFile:231)
```

**Comment by wouterdevos** [comment]
@wryday Same issue over here.

**Comment by toidv** [comment]
I faced this issue too, please help to check
```
FATAL EXCEPTION: main
                                                                     Process: com.enzan.mt.lms.tg01, PID: 7006
                                                                     java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isMutable()' on a null object reference
                                                                         at android.graphics.Canvas.<init>(Canvas.java:130)
                                                                         at com.github.mikephil.charting.renderer.PieChartRenderer.drawData(PieChartRenderer.java:136)
                                                                         at com.github.mikephil.charting.charts.PieChart.onDraw(PieChart.java:126)
```

**Comment by AleksandrKrasnoperov** [comment]
+

**Comment by chrisbln** [comment]
Same issue in PieChartRenderer:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isMutable()' on a null object reference
       at android.graphics.Canvas.(Canvas.java:130)
       at com.github.mikephil.charting.renderer.PieChartRenderer.drawData(PieChartRenderer.java:136)
       at com.github.mikephil.charting.charts.PieChart.onDraw(PieChart.java:126)
```

**Comment by gkgio** [comment]
+1

**Comment by StefanoGR** [comment]
+1

**Comment by imrankhanluhar** [comment]
same issues here also

**Comment by HashamHk** [comment]
Having same issue but slightly different
`E/AndroidRuntime(15975): FATAL EXCEPTION: main
E/AndroidRuntime(15975): Process: com.example.hotel_booking, PID: 15975
E/AndroidRuntime(15975): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.drawable.Drawable.isProjected()' on a null object reference
E/AndroidRuntime(15975):        at android.graphics.drawable.LayerDrawable.isProjected(LayerDrawable.java:420)
E/AndroidRuntime(15975):        at android.view.View.invalidateInternal(View.java:15633)
E/AndroidRuntime(15975):        at android.view.View.invalidate(View.java:15564)
E/AndroidRuntime(15975):        at android.view.View.setFrame(View.java:19885)
E/AndroidRuntime(15975):        at android.view.View.layout(View.java:19778)
E/AndroidRuntime(15975):        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
E/AndroidRuntime(15975):        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
E/AndroidRuntime(15975):        at android.view.View.layout(View.java:19781)
E/AndroidRuntime(15975):        at android.view.ViewGroup.layout(ViewGroup.java:6144)
E/AndroidRuntime(15975):        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1816)
E/AndroidRuntime(15975):        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1660)
E/AndroidRuntime(15975):        at android.widget.LinearLayout.onLayout(LinearLayout.java:1569)
E/AndroidRuntime(15975):        at android.view.View.layout(View.java:19781)
E/AndroidRuntime(15975):        at android.view.ViewGroup.layout(ViewGroup.java:6144)
E/AndroidRuntime(15975):        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
E/AndroidRuntime(15975):        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
E/AndroidRuntime(15975):        at com.android.internal.policy.DecorView.onLayout(DecorView.java:888)
E/AndroidRuntime(15975):        at android.view.View.layout(View.java:19781)
E/AndroidRuntime(15975):        at android.view.ViewGroup.layout(ViewGroup.java:6144)
E/AndroidRuntime(15975):        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2674)
E/AndroidRuntime(15975):        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2377)
E/AndroidRuntime(15975):        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1515)
E/AndroidRuntime(15975):        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7266)
E/AndroidRuntime(15975):        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:981)
E/AndroidRuntime(15975):        at android.view.Choreographer.doCallbacks(Choreographer.java:790)
E/AndroidRuntime(15975):        at android.view.Choreographer.doFrame(Choreographer.java:721)
E/AndroidRuntime(15975):        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:967)
E/AndroidRuntime(15975):        at android.os.Handler.handleCallback(Handler.java:808)
E/AndroidRuntime(15975):        at android.os.Handler.dispatchMessage(Handler.java:101)
E/AndroidRuntime(15975):        at android.os.Looper.loop(Looper.java:166)
E/AndroidRuntime(15975):        at android.app.ActivityThread.main(ActivityThread.java:7425)
E/AndroidRuntime(15975):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15975):        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
E/AndroidRuntime(15975):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
`

**Comment by GeeRajasekaran** [comment]
Still Facing same issue any input for fix

E/AndroidRuntime(19282): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isMutable()' on a null object reference
E/AndroidRuntime(19282): 	at android.graphics.Canvas.<init>(Canvas.java:113)
E/AndroidRuntime(19282): 	at com.google.maps.api.android.lib6.impl.a.a(:com.google.android.gms.policy_maps_core_dynamite@233610105@233610102065.573949206.573949206:3)
E/AndroidRuntime(19282): 	at com.google.maps.api.android.lib6.phoenix.cb.run(:com.google.android.gms.policy_maps_core_dynamite@233610105@233610102065.573949206.573949206:9)
E/AndroidRuntime(19282): 	at android.os.Handler.handleCallback(Handler.java:958)
E/AndroidRuntime(19282): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(19282): 	at android.os.Looper.loopOnce(Looper.java:205)
E/AndroidRuntime(19282): 	at android.os.Looper.loop(Looper.java:294)
E/AndroidRuntime(19282): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/AndroidRuntime(19282): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19282): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/AndroidRuntime(19282): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
D/TrafficStats(19282): tagSocket(190) with statsTag=0xffffffff, statsUid=-1
I/Process (19282): Sending signal. PID: 19282 SIG: 9
