### ISSUE TITLE
PointerIndex out of range error (Multitouch zooming error, I think)

### ISSUE THREAD

**Issue by BrandonBahret** [PhilJay/MPAndroidChart#3032]
My app crashes when I do a lot of zooming on charts, I get this [bug](https://pastebin.com/UgXnUjvn) 
 
[Here](https://drive.google.com/open?id=0B7ArzBuNX7W9c3BwVjgwWTVERmM) is a video of me generating the bug

Here is a stackoverflow post that may be helpful in fixing this issue, though I don't know for sure.
http://stackoverflow.com/questions/6919292/pointerindex-out-of-range-android-multitouch

**Comment by sreejithbnaick** [comment]
This is one of the top crash for me. Library is causing internal view pager crash in my app.

```
Fatal Exception: java.lang.IllegalArgumentException: pointerIndex out of range
       at android.view.MotionEvent.nativeGetAxisValue(MotionEvent.java)
       at android.view.MotionEvent.getX(MotionEvent.java:2201)
       at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2066)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2504)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2965)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2965)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2965)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2965)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2965)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2965)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2965)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:446)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1848)
       at android.app.Activity.dispatchTouchEvent(Activity.java:3315)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:408)
       at android.view.View.dispatchPointerEvent(View.java:12015)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4855)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4638)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4169)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4222)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4188)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4315)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4196)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4372)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4169)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4222)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4188)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4196)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4169)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6743)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6717)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6663)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6846)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:325)
       at android.os.Looper.loop(Looper.java:142)
       at android.app.ActivityThread.main(ActivityThread.java:6809)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by sreejithbnaick** [comment]
![screenshot_2018-01-20_14-41-45](https://user-images.githubusercontent.com/4578153/35181865-3613a16a-fdf0-11e7-9b90-841d17b1f22c.png)

**Comment by vasiledoe** [comment]
any solutions?

**Comment by dedeTao** [comment]
have a new version to solve?

**Comment by jamesncl** [comment]
I've just come across this bug. It seems to be related to ViewPager. I've attached a minimal example Android Studio project (Kotlin) to replicate the issue:
[TestMpandroidchartBug.zip](https://github.com/PhilJay/MPAndroidChart/files/3035260/TestMpandroidchartBug.zip)

Basic steps to replicate are:

- Add a ViewPager to an activity (android.support.v4.view.ViewPager)
- Create a ViewPager adapter which shows a single fragment
- Add 2 charts with dummy data to the fragment
- Launch the app
- Pinch-zoom-in on both graphs so you can then pan the charts left and right
- Simultaneously pan left/right on both graphs at the same time with two fingers - the exception will be thrown after a short time (usually within a few seconds)

The only way I can find to resolve this is to not have multiple charts inside a ViewPager.

**Comment by b5prolh** [comment]
Maybe this is an issue related to viewpager.  Try creating an ViewPager that extend from ViewPager and put try catch on Ontouch event to avoid crash. Maybe it can't resolve the exception. But it will fix the crash bug when using this library in ViewPager
public class CpnViewPager extends ViewPager {
    public CpnViewPager(@NonNull Context context) {
        super(context);
    }

    public CpnViewPager(@NonNull Context context, @Nullable AttributeSet attrs) {
        super(context, attrs);
    }

    @SuppressLint("ClickableViewAccessibility")
    @Override
    public boolean onTouchEvent(MotionEvent ev) {
        try {
            return super.onTouchEvent(ev);
        } catch (IllegalArgumentException ex) {
            ex.printStackTrace();
        }
        return false;
    }

    @Override
    public boolean onInterceptTouchEvent(MotionEvent ev) {
        try {
            return super.onInterceptTouchEvent(ev);
        } catch (IllegalArgumentException ex) {
            ex.printStackTrace();
        }
        return false;
    }
}

**Comment by vuongphdev** [comment]
Maybe this is an issue related to viewpager. Try creating an ViewPager that extend from ViewPager and put try catch on Ontouch event to avoid crash. Maybe it can't resolve the exception. But it will fix the crash bug when using this library in ViewPager

> public class CpnViewPager extends ViewPager {
> public CpnViewPager(@nonnull Context context) {
> super(context);
> }
> 
> public CpnViewPager(@NonNull Context context, @Nullable AttributeSet attrs) {
>     super(context, attrs);
> }
> 
> @SuppressLint("ClickableViewAccessibility")
> @Override
> public boolean onTouchEvent(MotionEvent ev) {
>     try {
>         return super.onTouchEvent(ev);
>     } catch (IllegalArgumentException ex) {
>         ex.printStackTrace();
>     }
>     return false;
> }
> 
> @Override
> public boolean onInterceptTouchEvent(MotionEvent ev) {
>     try {
>         return super.onInterceptTouchEvent(ev);
>     } catch (IllegalArgumentException ex) {
>         ex.printStackTrace();
>     }
>     return false;
> }
> }
