### ISSUE TITLE
Out of memory on tablets

### ISSUE THREAD

**Issue by reybridge** [PhilJay/MPAndroidChart#306]
This only happens on tablets randomly at the moment a fragment with the chart is loaded. I don't know if some phones have this issue. I think it's because the large screen so the memory to handle the bitmap is over limit. Any solution?

here is the details:

java.lang.OutOfMemoryError
at android.graphics.Bitmap.nativeCreate(Native Method)
at android.graphics.Bitmap.createBitmap(Bitmap.java:810)
at android.graphics.Bitmap.createBitmap(Bitmap.java:787)
at android.graphics.Bitmap.createBitmap(Bitmap.java:754)
at com.github.mikephil.charting.charts.d.onSizeChanged(Unknown Source)
at android.view.View.sizeChange(View.java:14932)
at android.view.View.setFrame(View.java:14905)
at android.view.View.layout(View.java:14813)
at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
at android.view.View.layout(View.java:14817)
at android.view.ViewGroup.layout(ViewGroup.java:4631)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1660)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1436)
at android.view.View.layout(View.java:14817)
at android.view.ViewGroup.layout(ViewGroup.java:4631)
at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
at android.view.View.layout(View.java:14817)
at android.view.ViewGroup.layout(ViewGroup.java:4631)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
at android.view.View.layout(View.java:14817)
at android.view.ViewGroup.layout(ViewGroup.java:4631)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
at android.view.View.layout(View.java:14817)
at android.view.ViewGroup.layout(ViewGroup.java:4631)
at android.support.v4.view.ViewPager.onLayout(Unknown Source)
at android.view.View.layout(View.java:14817)
at android.view.ViewGroup.layout(ViewGroup.java:4631)
at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
at android.view.View.layout(View.java:14817)
at android.view.ViewGroup.layout(ViewGroup.java:4631)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
at android.view.View.layout(View.java:14817)
at android.view.ViewGroup.layout(ViewGroup.java:4631)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
at android.view.View.layout(View.java:14817)
at android.view.ViewGroup.layout(ViewGroup.java:4631)
at android.support.v4.widget.DrawerLayout.onLayout(Unknown Source)
at android.view.View.layout(View.java:14817)
at android.view.ViewGroup.layout(ViewGroup.java:4631)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
at android.view.View.layout(View.java:14817)
at android.view.ViewGroup.layout(ViewGroup.java:4631)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
at android.view.View.layout(View.java:14817)
at android.view.ViewGroup.layout(ViewGroup.java:4631)
at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:374)
at android.view.View.layout(View.java:14817)
at android.view.ViewGroup.layout(ViewGroup.java:4631)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
at android.view.View.layout(View.java:14817)
at android.view.ViewGroup.layout(ViewGroup.java:4631)
at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1983)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1740)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5600)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
at android.view.Choreographer.doCallbacks(Choreographer.java:574)
at android.view.Choreographer.doFrame(Choreographer.java:544)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5001)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:126)
at dalvik.system.NativeStart.main(Native Method)

**Comment by PhilJay** [comment]
Are you using a `ViewPager`? How are you handling the recreation / recycling of the `Fragments`?

**Comment by reybridge** [comment]
Yes, i am using a ViewPager. 
This is how i created the fragment which contains the ViewPager.

String backStateName = fragment.getClass().getName();
			Fragment checkFragment = mFragmentManager.findFragmentByTag(tag);
			if(checkFragment != null)
			{
				mFragmentManager.beginTransaction().remove(fragment).commit();
			}
			FragmentTransaction ft = mFragmentManager.beginTransaction();
		    ft.add(R.id.content_frame, fragment, tag);
		    ft.addToBackStack(backStateName);
		    ft.commit();

And this is in the custom ViewPager class.

public StatisticGraphFragment getItem(int position)
	{
		int currentMonth = Calendar.getInstance().get(Calendar.MONTH);
		int currentYear = Calendar.getInstance().get(Calendar.YEAR);
		int minMonth = histories.size() > 0 ? histories.get(histories.size()-1).getMonth()-1 : currentMonth;
		int minYear = histories.size() > 0 ? histories.get(histories.size()-1).getYear() : currentYear;
		int index = 0;
		for(int i=0;i<currentYear-minYear+1;i++)
		{
			int yTop = 11;
			int yBottom = 0;
			if(i == 0) yBottom = minMonth;
			if(currentYear == minYear) yTop = currentMonth;
			for(int y=yBottom;y<yTop+1;y++)
			{
				if(index == position)
				{
					Bundle bundle = new Bundle();
					bundle.putInt("month", y);
					bundle.putInt("year", minYear+i);
					bundle.putString("title", activity.getResources().getString(R.string.label_statistic));
					bundle.putInt("menu_state", Configurations.HEADER_STATE_OVERVIEW);
					StatisticGraphFragment fragment = new StatisticGraphFragment();
					fragment.setArguments(bundle);
					return fragment;
				}
				index++;
			}
		}

StatisticGraphFragment is the fragment which i put the chart layout.
		return null;
	}

**Comment by PhilJay** [comment]
And how many fragments do you have? How is your ViewPager configured`?

**Comment by reybridge** [comment]
This is how my custom ViewPager created in the onViewCreated method of StatisticGraphManagerFragment (as in the first sample code).

```
viewPager = (ViewPager)view.findViewById(R.id.view_pager);
		viewPager.setAdapter(pageAdapter);
		viewPager.setOffscreenPageLimit(pageAdapter.getCount()-1);
		viewPager.setCurrentItem(startPage, false);
```

I don't give a limit for the count of fragments, but when i get this OOM, there are 3 fragments in the ViewPager.

**Comment by vinaywadhwa** [comment]
I am having this same problem. Not on a tablet, on a Nexus 5 though. Happens rarely and randomly.

**Comment by AngeloAvv** [comment]
Same problem for me using a viewpager

**Comment by jemshit** [comment]
It happens in activity as well in my s5

**Comment by kristijanexads** [comment]
same for me, but also rarely and randomly, on S5, and on Galaxy Tab everything works great

**Comment by jaredsburrows** [comment]
What version?
