### ISSUE TITLE
Attempt to invoke virtual method 'com.github.mikephil.charting.components.Description com.github.mikephil.charting.charts.PieChart.getDescription()' on a null object reference

### ISSUE THREAD

**Issue by TariGit** [PhilJay/MPAndroidChart#3132]
Hi, Found an error with the asignation of PieGraph properties:

E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.ast.ctiproyect, PID: 22993
                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'com.github.mikephil.charting.components.Description com.github.mikephil.charting.charts.PieChart.getDescription()' on a null object reference
                                                                        at com.ast.ctiproyect.Fragments.FragmentGEN.PieGraphProperties(FragmentGEN.java:87)
                                                                        at com.ast.ctiproyect.Fragments.FragmentGEN$AsyncMenu.onPostExecute(FragmentGEN.java:205)
                                                                        at com.ast.ctiproyect.Fragments.FragmentGEN$AsyncMenu.onPostExecute(FragmentGEN.java:131)
                                                                        at android.os.AsyncTask.finish(AsyncTask.java:651)
                                                                        at android.os.AsyncTask.access$500(AsyncTask.java:180)
                                                                        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5458)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

- This method is called from the onPostExecute of an AsyncTask:

        public void PieGraphProperties() {
        GraphicCake.getDescription().setEnabled(false);
        GraphicCake.setHoleRadius(32f);
        GraphicCake.setHoleColor(Color.TRANSPARENT);
        GraphicCake.setTransparentCircleRadius(10);
        GraphicCake.setUsePercentValues(true);
        GraphicCake.setExtraOffsets(50, 10, 50, 10);
        GraphicCake.setRotationAngle(0);
        GraphicCake.animateY(2000);
        GraphicCake.setRotationEnabled(true);
        PieGraph.addDataCake(GraphicCake,xData,yData);
        Legend leg = GraphicCake.getLegend();
        leg.setForm(Legend.LegendForm.CIRCLE);
        leg.setXEntrySpace(7);
        leg.setYEntrySpace(5);
        leg.setEnabled(false);
        }

**Comment by EdwardQuixote** [comment]
@TariGit Hi,

Try setting up the Description as follows:
`Description descChartDescription = new Description();`
`descChartDescription.setEnabled(true);`
`pieChart.setDescription(descChartDescription);`

Do this before trying to get a reference to the `Description` object.
See if that works.
