### ISSUE TITLE
I got "Indexoutofboundsexception" in the last value of the bar

### ISSUE THREAD

**Issue by ghizoulo** [PhilJay/MPAndroidChart#3140]
I am using mpandroidChart to display a barChart.
I create xLabels of months values, but I don't always have all the months of a year.
In this example, I have only data from February to November.

```
for (Graphe1 graphe1 : data) {
            xLabels.add(Utils.getMonthValue(graphe1.getMois()));
        }
```

> Utils.getMonthValue takes month number and return month value
> For example: getMonthValue(01) returns "January"

And I have this code to set xAxis labels

```
xAxis.setValueFormatter(new IAxisValueFormatter() {

            @Override
            public String getFormattedValue(float value, AxisBase axis) {
                if(xLabels.size() > (int) value) {
                    return xLabels.get((int) value);
                } else
                    return "";
            }
        });
```
when I log over setValueFormatter function, value always takes even number like this:

> 05-25 08:35:40.771 24004-24004/ma.lmv.bi I/graphe1: value 0.0
> 05-25 08:35:40.772 24004-24004/ma.lmv.bi I/graphe1: value 2.0
> 05-25 08:35:40.772 24004-24004/ma.lmv.bi I/graphe1: value 4.0
> 05-25 08:35:40.772 24004-24004/ma.lmv.bi I/graphe1: value 6.0
> 05-25 08:35:40.772 24004-24004/ma.lmv.bi I/graphe1: value 8.0
> 05-25 08:35:40.772 24004-24004/ma.lmv.bi I/graphe1: value 10.0

[
![cedede](https://cloud.githubusercontent.com/assets/13001134/26443676/ed228df6-4128-11e7-90a9-8c90540705c5.PNG)
](url)

So the last value of the bar is November, when I click on it to display the marker, I got this exception:

```
FATAL EXCEPTION: main
                                                           Process: ma.lmv.bi, PID: 24004
                                                           java.lang.IndexOutOfBoundsException: Invalid index 10, size is 10
                                                               at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                               at java.util.ArrayList.get(ArrayList.java:308)
                                                               at ma.lmv.bi.GraphMarker.refreshContent(GraphMarker.java:48)
                                                               at com.github.mikephil.charting.charts.Chart.drawMarkers(Chart.java:744)
                                                               at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:268)
                                                               at android.view.View.draw(View.java:16184)
```

For the marker code, here it is:

```
if (e instanceof CandleEntry) {
            CandleEntry ce = (CandleEntry) e;
            tvContent.setText("" + Utils.formatNumber(ce.getHigh(), 0, true));
        } else {
            tvContent.setText("" + mXLabels.get((int)e.getX()) + " \n" + Utils.formatNumber(e.getY(), 0, true));
        }
```
Please If anyone can helps me with this issue. I will be very thankful

**Comment by ghizoulo** [comment]
I found the error , it was in the dataEntries. the data I got is from January to Octobre, I was setting the wrong value to Entry(x,y)
