### ISSUE TITLE
xiaomi 6 run MPAndroidChartDemo RuntimeException

### ISSUE THREAD

**Issue by q805699513** [PhilJay/MPAndroidChart#3299]
xiaomi 6 Mobile phone,MIUI optimization shut down everything normal, open MIUI optimization, start flash back

java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.xxmassdeveloper.mpchartexample/com.xxmassdeveloper.mpchartexample.notimportant.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.xxmassdeveloper.mpchartexample.notimportant.MainActivity" on path: DexPathList[[zip file "/data/app/com.xxmassdeveloper.mpchartexample-1/base.apk"],nativeLibraryDirectories=[/data/app/com.xxmassdeveloper.mpchartexample-1/lib/arm64, /data/app/com.xxmassdeveloper.mpchartexample-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2586)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2745)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1494)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6222)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:895)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:785)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.xxmassdeveloper.mpchartexample.notimportant.MainActivity" on path: DexPathList[[zip file "/data/app/com.xxmassdeveloper.mpchartexample-1/base.apk"],nativeLibraryDirectories=[/data/app/com.xxmassdeveloper.mpchartexample-1/lib/arm64, /data/app/com.xxmassdeveloper.mpchartexample-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1079)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2576)
	... 9 more

**Comment by q805699513** [comment]
app-release version Normal operation, test version exception
