### ISSUE TITLE
Fatal Exception: java.lang.NegativeArraySizeException: -4

### ISSUE THREAD

**Issue by harshvishu** [PhilJay/MPAndroidChart#3309]
```
Fatal Exception: java.lang.NegativeArraySizeException: -4
       at com.github.mikephil.charting.utils.Transformer.generateTransformedValuesLine(Transformer.java:178)
       at com.github.mikephil.charting.renderer.LineChartRenderer.drawValues(LineChartRenderer.java:547)
       at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:263)
       at android.view.View.draw(View.java:17291)
       at android.view.View.updateDisplayListIfDirty(View.java:16273)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3715)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3695)
       at android.view.View.updateDisplayListIfDirty(View.java:16236)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3715)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3695)
       at android.view.View.updateDisplayListIfDirty(View.java:16236)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3715)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3695)
       at android.view.View.updateDisplayListIfDirty(View.java:16236)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3715)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3695)
       at android.view.View.updateDisplayListIfDirty(View.java:16236)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3715)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3695)
       at android.view.View.updateDisplayListIfDirty(View.java:16236)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3715)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3695)
       at android.view.View.updateDisplayListIfDirty(View.java:16236)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3715)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3695)
       at android.view.View.updateDisplayListIfDirty(View.java:16236)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:652)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:658)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:766)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2830)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2629)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2236)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1275)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6439)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:943)
       at android.view.Choreographer.doCallbacks(Choreographer.java:755)
       at android.view.Choreographer.doFrame(Choreographer.java:690)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:929)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6334)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Device** : **ONEPLUS A5000**
**OS** : **7.1.1**

**Comment by tranbaothang1989** [comment]
This topic [#2077](https://github.com/PhilJay/MPAndroidChart/issues/2074) fixed my issue!
Check more [Update](https://github.com/PhilJay/MPAndroidChart/wiki/Setting-Data#the-order-of-entries):
