### ISSUE TITLE
Possible bug in v3.0.2

### ISSUE THREAD

**Issue by amiguels** [PhilJay/MPAndroidChart#3566]
I was using this library with version 3.0.0, with no major problems.

Today I changed to version 3.0.2, literaly only changed the version in Gradle.
I now crashes instantly, with the error shown bellow. Unfortunately I do not have the availability to track down the issue, I'll just go back to 3.0.0

Cheers!

`11-10 19:44:35.075 1561-1561/com.bla.bla D/AndroidRuntime: Shutting down VM
11-10 19:44:35.077 1561-1561/com.bla.bla E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: com.bla.bla, PID: 1561
                                                                         java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
                                                                             at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                             at java.util.ArrayList.get(ArrayList.java:308)
                                                                             at com.github.mikephil.charting.data.DataSet.getEntryForIndex(DataSet.java:286)
                                                                             at com.github.mikephil.charting.utils.Transformer.generateTransformedValuesLine(Transformer.java:184)
                                                                             at com.github.mikephil.charting.renderer.LineChartRenderer.drawValues(LineChartRenderer.java:547)
                                                                             at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:263)
                                                                             at android.view.View.draw(View.java:16184)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15180)
                                                                             at android.view.View.draw(View.java:15954)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                             at android.view.View.draw(View.java:15954)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                             at android.view.View.draw(View.java:15954)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                             at android.view.View.draw(View.java:16187)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15180)
                                                                             at android.view.View.draw(View.java:15954)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                             at android.view.View.draw(View.java:15954)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                             at android.view.View.draw(View.java:16187)
                                                                             at android.support.v4.view.ViewPager.draw(ViewPager.java:2443)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15180)
                                                                             at android.view.View.draw(View.java:15954)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                             at android.view.View.draw(View.java:15954)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                             at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1379)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                             at android.view.View.draw(View.java:15954)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                             at android.view.View.draw(View.java:15954)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                             at android.view.View.draw(View.java:15954)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                             at android.view.View.draw(View.java:15954)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                             at android.view.View.draw(View.java:15954)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                             at android.view.View.draw(View.java:16187)
                                                                             at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2690)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15180)
                                                                             at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
                                                                             at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
                                                                             at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
                                                                         	at and`

**Comment by almic** [comment]
fixed now in d67ea481af1e8528c617dfd404d0c7827b0134b2
