### ISSUE TITLE
 java.lang.ArithmeticException: divide by zero

### ISSUE THREAD

**Issue by datainvent** [PhilJay/MPAndroidChart#3571]
I am getting this exception while initializing the line chart graph. Following are the logs of crash. What could be the cause of this crash?

com.github.mikephil.charting.renderer.LineChartRenderer$DataSetImageCache.getBitmap(LineChartRenderer.java:819)
       at com.github.mikephil.charting.renderer.LineChartRenderer.drawCircles(LineChartRenderer.java:652)
       at com.github.mikephil.charting.renderer.LineChartRenderer.drawExtras(LineChartRenderer.java:570)
       at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:236)

**Comment by ako2345** [comment]
I've got the same problem.

**Comment by JaydipMeghapara** [comment]
Same problem is facing with me

**Comment by riyaistar** [comment]
I get the same error when there is a change in the orientation of the screen.
