### ISSUE TITLE
Time Chart exception occurred

### ISSUE THREAD

**Issue by rookiejj** [PhilJay/MPAndroidChart#3623]
There is new item named by Time Chart.
I tried this, but when I drag the bottom progressbar to 0 side and drag to right again, app is crashed.

error message below : 

FATAL EXCEPTION: main
                                                                                    Process: com.xxmassdeveloper.mpchartexample, PID: 18580
                                                                                    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
                                                                                        at java.util.ArrayList.get(ArrayList.java:411)
                                                                                        at com.github.mikephil.charting.data.DataSet.getEntryForIndex(DataSet.java:286)
                                                                                        at com.github.mikephil.charting.utils.Transformer.generateTransformedValuesLine(Transformer.java:184)
                                                                                        at com.github.mikephil.charting.renderer.LineChartRenderer.drawValues(LineChartRenderer.java:547)
                                                                                        at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:264)
                                                                                        at android.view.View.draw(View.java:18319)
                                                                                        at android.view.View.updateDisplayListIfDirty(View.java:17297)
                                                                                        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                                                        at android.view.View.updateDisplayListIfDirty(View.java:17260)
                                                                                        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                                                        at android.view.View.updateDisplayListIfDirty(View.java:17260)
                                                                                        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                                                        at android.view.View.updateDisplayListIfDirty(View.java:17260)
                                                                                        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                                                        at android.view.View.updateDisplayListIfDirty(View.java:17260)
                                                                                        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:666)
                                                                                        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:672)
                                                                                        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:780)
                                                                                        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3105)
                                                                                        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2901)
                                                                                        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2495)
                                                                                        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1502)
                                                                                        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7044)
                                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
                                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:702)
                                                                                        at android.view.Choreographer.doFrame(Choreographer.java:638)
                                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
                                                                                        at android.os.Handler.handleCallback(Handler.java:751)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:6646)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by almic** [comment]
fixed now in d67ea481af1e8528c617dfd404d0c7827b0134b2
