### ISSUE TITLE
Concurrent Modification Exception

### ISSUE THREAD

**Issue by eakteam** [PhilJay/MPAndroidChart#3702]
```
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.ArrayList$Itr.next(ArrayList.java:831)
       at com.github.mikephil.charting.renderer.LineChartRenderer.drawData(SourceFile:95)
       at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(SourceFile:232)
       at android.view.View.draw(View.java:17185)
       at android.view.View.updateDisplayListIfDirty(View.java:16167)
       at android.view.View.draw(View.java:16951)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.support.constraint.ConstraintLayout.dispatchDraw(SourceFile:1606)
       at android.view.View.updateDisplayListIfDirty(View.java:16162)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
       at android.view.View.updateDisplayListIfDirty(View.java:16130)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
       at android.view.View.updateDisplayListIfDirty(View.java:16130)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
       at android.view.View.updateDisplayListIfDirty(View.java:16130)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
       at android.view.View.updateDisplayListIfDirty(View.java:16130)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
       at android.view.View.updateDisplayListIfDirty(View.java:16130)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
       at android.view.View.updateDisplayListIfDirty(View.java:16130)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
       at android.view.View.updateDisplayListIfDirty(View.java:16130)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
       at android.view.View.updateDisplayListIfDirty(View.java:16130)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
       at android.view.View.updateDisplayListIfDirty(View.java:16130)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
       at android.view.View.updateDisplayListIfDirty(View.java:16130)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
       at android.view.View.updateDisplayListIfDirty(View.java:16130)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2800)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
       at android.view.Choreographer.doCallbacks(Choreographer.java:686)
       at android.view.Choreographer.doFrame(Choreographer.java:621)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by penn5** [comment]
Are you using threads in your application?

**Comment by eakteam** [comment]
Yes i'm using threads in my App

**Comment by penn5** [comment]
Is it possible for two threads to add points simultaneously in your app?

**Comment by eakteam** [comment]
I depends, i understand what is ConcurrentModificationException but how to fix inside library... Maybe with a CopyOnWriteArrayList<> , but how to make modification on the lib ?

**Comment by penn5** [comment]
I don't think you should meddle with the library - you should make a
wrapper function and have it synchronise.

**Comment by rangerzhou** [comment]
I also have this issue in version 3.1.0, so it is the lib's bug?
