### ISSUE TITLE
java.lang.NegativeArraySizeException: -2

### ISSUE THREAD

**Issue by Nima9Faraji** [PhilJay/MPAndroidChart#3719]
hello guys
i am following Getting Start and my code is :
Java :

`
       here is my code :

        ArrayList<Entry> entries = new ArrayList<>();
        entries.add(new Entry(4f, 0));
        entries.add(new Entry(8f, 1));
        entries.add(new Entry(6f, 2));
        entries.add(new Entry(2f, 3));
        entries.add(new Entry(18f, 4));
        entries.add(new Entry(9f, 5));

        ArrayList<String> labels = new ArrayList<String>();
        labels.add("1");
        labels.add("2");
        labels.add("3");
        labels.add("4");

        LineDataSet dataSet = new LineDataSet(entries, "Label");

        LineData lineData = new LineData(dataSet);
        chartUser.setData(lineData);
        chartUser.invalidate();
`

XML :
`<com.github.mikephil.charting.charts.LineChart 
                    android:id="@+id/chart_user" 
                    android:layout_width="match_parent" 
                    android:layout_height="200dp"/>`

i have Exception with this simple code ! and
the Exception Logcat is :

> java.lang.NegativeArraySizeException: -2
                                                                       at com.github.mikephil.charting.utils.Transformer.generateTransformedValuesLine(Transformer.java:178)
                                                                       at com.github.mikephil.charting.renderer.LineChartRenderer.drawValues(LineChartRenderer.java:547)
                                                                       at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:264)
                                                                       at android.view.View.draw(View.java:17071)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16053)
                                                                       at android.view.View.draw(View.java:16837)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                       at android.view.View.draw(View.java:17074)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16053)
                                                                       at android.view.View.draw(View.java:16837)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16048)
                                                                       at android.view.View.draw(View.java:16837)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                       at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1234)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16048)
                                                                       at android.view.View.draw(View.java:16837)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                       at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1367)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16048)
                                                                       at android.view.View.draw(View.java:16837)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16048)
                                                                       at android.view.View.draw(View.java:16837)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16048)
                                                                       at android.view.View.draw(View.java:16837)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16048)
                                                                       at android.view.View.draw(View.java:16837)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16048)
                                                                       at android.view.View.draw(View.java:16837)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                       at android.view.View.draw(View.java:17074)
                                                                       at com.android.internal.policy.DecorView.draw(DecorView.java:751)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16053)
                                                                       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:656)
                                                                       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:662)
                                                                       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:770)
                                                                       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2796)
                                                                       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2604)
                                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2211)
                                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
                                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6301)
                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:683)
                                                                       at android.view.Choreographer.doFrame(Choreographer.java:619)
                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
                                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
01-08 20:19:12.262 6010-6010/ir.ninesoft.fitshow E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

  anyone can help ?

**Comment by bkraszewski** [comment]
@Nima9Faraji Its required to have dataset sorted by x axis. Note that when you create new entry its actually Entry(x, y). Try switching constructor params and should be fine. Right now values 0, 1, 2 are on Y axis instead of X

**Comment by Silic0nS0ldier** [comment]
Just hit this and @bkraszewski's suggestion worked. (kinda obvious why it errored out when you think about it, though the specific exception that ends up getting thrown leaves a lot to be desired)

**Comment by almic** [comment]
lol
