### ISSUE TITLE
NPE when calling zoomAndCenterAnimated method.

### ISSUE THREAD

**Issue by bushmen** [PhilJay/MPAndroidChart#3725]
NullPointerException is being thrown when trying to call `Chart.zoomAndCenterAnimated`. This happens because in `AnimatedZoomJob.getInstance()` `YAxis` is never set.

noticed in latest version: commit 8fd1a86b0a33e886026e9fe79233f78d40028578

Logs:

`java.lang.NullPointerException: Attempt to read from field 'float com.github.mikephil.charting.components.AxisBase.mAxisRange' on a null object reference
                                                                                   at com.github.mikephil.charting.jobs.AnimatedZoomJob.onAnimationUpdate(AnimatedZoomJob.java:75)
                                                                                   at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1522)
                                                                                   at android.animation.ObjectAnimator.animateValue(ObjectAnimator.java:987)
                                                                                   at android.animation.ValueAnimator.animateBasedOnTime(ValueAnimator.java:1316)
                                                                                   at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1446)`

**Comment by bushmen** [comment]
@PhilJay can you please take a look at my PR, when you have some spare time? :)

**Comment by almic** [comment]
Fixed by #2856
