### ISSUE TITLE
MPChartExample Crash --IndexOutOfBoundsException

### ISSUE THREAD

**Issue by niulinguo** [PhilJay/MPAndroidChart#3755]
`com.xxmassdeveloper.mpchartexample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                  Process: com.xxmassdeveloper.mpchartexample, PID: 5684
                                                                                  java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
                                                                                      at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                                      at java.util.ArrayList.get(ArrayList.java:308)
                                                                                      at com.github.mikephil.charting.data.DataSet.getEntryForIndex(DataSet.java:286)
                                                                                      at com.github.mikephil.charting.utils.Transformer.generateTransformedValuesLine(Transformer.java:184)
                                                                                      at com.github.mikephil.charting.renderer.LineChartRenderer.drawValues(LineChartRenderer.java:547)
                                                                                      at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:264)
                                                                                      at android.view.View.draw(View.java:17469)
                                                                                      at android.view.View.updateDisplayListIfDirty(View.java:16464)
                                                                                      at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
                                                                                      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
                                                                                      at android.view.View.updateDisplayListIfDirty(View.java:16424)
                                                                                      at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
                                                                                      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
                                                                                      at android.view.View.updateDisplayListIfDirty(View.java:16424)
                                                                                      at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
                                                                                      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
                                                                                      at android.view.View.updateDisplayListIfDirty(View.java:16424)
                                                                                      at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
                                                                                      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
                                                                                      at android.view.View.updateDisplayListIfDirty(View.java:16424)
                                                                                      at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:325)
                                                                                      at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:331)
                                                                                      at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:366)
                                                                                      at android.view.ViewRootImpl.draw(ViewRootImpl.java:3134)
                                                                                      at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2933)
                                                                                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2522)
                                                                                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
                                                                                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7397)
                                                                                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
                                                                                      at android.view.Choreographer.doCallbacks(Choreographer.java:695)
                                                                                      at android.view.Choreographer.doFrame(Choreographer.java:631)
                                                                                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
                                                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                      at android.os.Looper.loop(Looper.java:158)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:7237)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
`

**Comment by SamYStudiO** [comment]
+1 same here

**Comment by MGaetan89** [comment]
Already reported in #2958

**Comment by almic** [comment]
fixed now in d67ea481af1e8528c617dfd404d0c7827b0134b2

**Comment by tahagit** [comment]
If you're using IAxisValueFormatter, just add this code inside that:

       IAxisValueFormatter formatter = new IAxisValueFormatter() {
                    @Override
                    public String getFormattedValue(float value, AxisBase axis) {
                        if (((int) value) < YOURLISTDATA.size()) {
                            return YOURLISTDATA.get((int) value);
                        } else {
                            return "0";
                        }

                    }
                };
