### ISSUE TITLE
BarBuffer ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by mbostic** [PhilJay/MPAndroidChart#3824]
I get an ArrayIndexOutOfBoundsException from BarBuffer.addBar() method:

```
java.lang.ArrayIndexOutOfBoundsException: length=8; index=8
	at com.github.mikephil.charting.buffer.BarBuffer.addBar(BarBuffer.java:37)
	at com.github.mikephil.charting.buffer.BarBuffer.feed(BarBuffer.java:80)
	at com.github.mikephil.charting.renderer.BarChartRenderer.drawDataSet(BarChartRenderer.java:142)
	at com.github.mikephil.charting.renderer.BarChartRenderer.drawData(BarChartRenderer.java:80)
	at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:232)
	at android.view.View.draw(View.java:16217)
	at android.view.View.updateDisplayListIfDirty(View.java:15214)
	at android.view.View.draw(View.java:15987)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
	at android.view.View.updateDisplayListIfDirty(View.java:15209)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3596)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3576)
	at android.view.View.updateDisplayListIfDirty(View.java:15174)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3596)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3576)
	at android.view.View.updateDisplayListIfDirty(View.java:15174)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3596)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3576)
	at android.view.View.updateDisplayListIfDirty(View.java:15174)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3596)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3576)
	at android.view.View.updateDisplayListIfDirty(View.java:15174)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3596)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3576)
	at android.view.View.updateDisplayListIfDirty(View.java:15174)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3596)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3576)
	at android.view.View.updateDisplayListIfDirty(View.java:15174)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3596)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3576)
	at android.view.View.updateDisplayListIfDirty(View.java:15174)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:283)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:289)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:324)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2651)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2470)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2103)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1139)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6064)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
	at android.view.Choreographer.doCallbacks(Choreographer.java:672)
	at android.view.Choreographer.doFrame(Choreographer.java:608)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
	at android.os.Handler.handleCallback(Handler.java:742)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:157)
	at android.app.ActivityThread.main(ActivityThread.java:5571)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
```

-I am using tabbed activity with two tabs. I have a bar chart only in second tab so exception is probably coming from there. 
-Exception only happens occasionally without obvious reason, so I cannot provide minimal reproduceable example..
-I get the data from Firebase. This tab calculates average times for a team of players and displays them in a bar chart.

```
public class StatisticsFragmentTeam extends AbstractStatisticsFragment{

    private BarChart chartTeam;
    List<String> players = new ArrayList<>();
    List<BarEntry> avgScores = new ArrayList<>();
    int playersCount = 0;

    public StatisticsFragmentTeam() {
        // Required empty public constructor
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        final View v = inflater.inflate(R.layout.statistics_fragment_team, container, false);

        chartTeam = (BarChart)v.findViewById(R.id.chartTeam);
        chartTeam.getXAxis().setAvoidFirstLastClipping(true);

        chartTeam.getAxisLeft().setAxisMinValue(0);
        chartTeam.getAxisLeft().setValueFormatter(new TimeAxisValueFormatter());
        chartTeam.getXAxis().setPosition(XAxis.XAxisPosition.BOTTOM);
        chartTeam.getXAxis().setAxisMinValue(-0.5f);
        chartTeam.getXAxis().setDrawGridLines(false);
        chartTeam.getXAxis().setValueFormatter(new IAxisValueFormatter() {
            @Override
            public String getFormattedValue(float value, AxisBase axis) {

                int val = (int)value;

                if(val >= players.size())
                    val = players.size() - 1;  //tryed to fix error this way, didn't work
                else if(val < 0)
                    val = 0;

                return players.get(val);
            }

        });

        chartTeam.getXAxis().setGranularity(1f);
        chartTeam.getLegend().setEnabled(true);
        chartTeam.getLegend().setPosition(Legend.LegendPosition.RIGHT_OF_CHART_INSIDE);
        chartTeam.getLegend().setTextSize(14);
        Description description = new Description();
        description.setText("");
        chartTeam.setDescription(description);

        chartTeam.getAxisRight().setEnabled(false);

        //final List<String> playerIds = new ArrayList<>();
        firebaseHelper.getFirebasePlayers().child(teamId).addValueEventListener(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot dataSnapshot) {
                players.clear();

                avgScores.clear();
                playersCount = 0;
                for(DataSnapshot ds : dataSnapshot.getChildren()){//for each player
                    players.add(ds.child("name").getValue(String.class));
                    final String playerId = ds.getKey();

                    getScores(playerId).addValueEventListener(new ValueEventListener() {
                                    @Override
                                    public void onDataChange(DataSnapshot dataSnapshot) {

                                        Float sum = 0f;
                                        int i = 0;
                                        for(DataSnapshot ds : dataSnapshot.getChildren()){//for each score
                                            sum += ds.getValue(Integer.class);
                                            i++;
                                        }

                                        if(i > 0) {
                                            Log.d("bar chart entry", playersCount + " " + sum / (float) i);
                                            avgScores.add(new BarEntry((float) playersCount++, sum / (float) i));
                                        }

                                    }

                                    @Override
                                    public void onCancelled(FirebaseError firebaseError) {

                                    }
                                });

                }

                final Handler handler = new Handler();
                handler.postDelayed(new Runnable() {
                    @Override
                    public void run() {

                        chartTeam.getXAxis().setAxisMaxValue(avgScores.size() - 0.5f);
                        BarData data = new BarData(new BarDataSet(avgScores, "Average time"));
                        data.setBarWidth(0.8f);
                        data.setValueTextSize(10);
                        data.setValueFormatter(new TimeValueFormatter());
                        chartTeam.setData(data);
                        chartTeam.invalidate();
                    }
                }, 200);
            }

            @Override
            public void onCancelled(FirebaseError firebaseError) {

            }
        });
        return v;
    }
}
```

**Comment by almic** [comment]
This has already been reported by multiple other issues, and the fix is currently being worked on.

Hey there! This issue is fairly old, and may no longer apply to the current library version. I'm closing this in order to clean up the issue tracker. The repository has been inactive for a long time and old issues may have existing answers or are no longer valid.

I've been working diligently to get to as many issues as I can, but I can no longer spend time writing a unique answer to each issue. This is especially true if that issue may no longer be applicable. If you think this was done by mistake, please search through all `open` and `closed` issues first, and then create a new one using the templates.

This is a copied and pasted response, and has been put on many other issues. So please, don't take this personally.

**Comment by itedevelopers** [comment]
Same issue: The exception only happens occasionally without obvious reason, so I cannot provide minimal reproducible example. Any solutions? 
I'm using the vastest version...

    2019-11-21 17:25:57.904 8625-8625/com.example.shems E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.matchup.shems, PID: 8625
    java.lang.ArrayIndexOutOfBoundsException: length=28; index=28
        at com.github.mikephil.charting.buffer.BarBuffer.addBar(BarBuffer.java:37)
        at com.github.mikephil.charting.buffer.BarBuffer.feed(BarBuffer.java:80)
        at com.github.mikephil.charting.renderer.BarChartRenderer.drawDataSet(BarChartRenderer.java:144)
        at com.github.mikephil.charting.renderer.BarChartRenderer.drawData(BarChartRenderer.java:82)
        at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:237)

**Comment by Dieseled-UP** [comment]
Hey wondering was this issue ever addressed by anyone, I am having the same problem and again same as others it is only happening every whack about and unable to reproduce manually.
```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=28; index=28
       at com.github.mikephil.charting.buffer.BarBuffer.addBar(BarBuffer.java:37)
       at com.github.mikephil.charting.buffer.BarBuffer.feed(BarBuffer.java:80)
       at com.github.mikephil.charting.renderer.BarChartRenderer.drawDataSet(BarChartRenderer.java:144)
       at com.github.mikephil.charting.renderer.BarChartRenderer.drawData(BarChartRenderer.java:82)
       at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:237)
       at android.view.View.draw(View.java:21875)
       at android.view.View.updateDisplayListIfDirty(View.java:20748)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4542)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4514)
       at android.view.View.updateDisplayListIfDirty(View.java:20703)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4542)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4514)
       at android.view.View.updateDisplayListIfDirty(View.java:20703)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4542)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4514)
       at android.view.View.updateDisplayListIfDirty(View.java:20703)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4542)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4514)
       at android.view.View.updateDisplayListIfDirty(View.java:20703)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4542)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4514)
       at android.view.View.updateDisplayListIfDirty(View.java:20703)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4542)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4514)
       at android.view.View.updateDisplayListIfDirty(View.java:20703)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4542)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4514)
       at android.view.View.updateDisplayListIfDirty(View.java:20703)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4542)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4514)
       at android.view.View.updateDisplayListIfDirty(View.java:20703)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4542)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4514)
       at android.view.View.updateDisplayListIfDirty(View.java:20703)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:725)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:731)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:840)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:3951)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3725)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3034)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1897)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8516)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:986)
       at android.view.Choreographer.doCallbacks(Choreographer.java:764)
       at android.view.Choreographer.doFrame(Choreographer.java:699)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:965)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7099)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```
If anyone has an answer or point me in the right direction would be much appreciated.
