### ISSUE TITLE
DrawHighlighted NullPointerException 

### ISSUE THREAD

**Issue by Simonida** [PhilJay/MPAndroidChart#3836]
I've got NullPointerException when programmatically setting Highlight using 
**highlightValues(Highlight[] highs)**

java.lang.NullPointerException: Attempt to invoke virtual method 'int com.github.mikephil.charting.highlight.Highlight.getDataSetIndex()' on a null object reference
at com.github.mikephil.charting.renderer.LineChartRenderer.drawHighlighted(LineChartRenderer.java:691)

**Comment by Pantsoffski** [comment]
I have the same error at at com.github.mikephil.charting.renderer.LineChartRenderer.drawHighlighted

**Comment by MiaShopgal** [comment]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.github.mikephil.charting.highlight.Highlight.getDataSetIndex()' on a null object reference
       at com.github.mikephil.charting.renderer.LineChartRenderer.drawHighlighted(LineChartRenderer.java:692)
       at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:250)
       at android.view.View.draw(View.java:20480)
       at android.view.View.updateDisplayListIfDirty(View.java:19425)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4443)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4423)
       at android.view.View.updateDisplayListIfDirty(View.java:19384)
       at android.view.View.draw(View.java:20203)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4459)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4245)
       at android.view.View.draw(View.java:20483)
       at android.widget.ScrollView.draw(ScrollView.java:2731)
       at android.view.View.updateDisplayListIfDirty(View.java:19425)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4443)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4423)
       at android.view.View.updateDisplayListIfDirty(View.java:19384)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4443)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4423)
       at android.view.View.updateDisplayListIfDirty(View.java:19384)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4443)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4423)
       at android.view.View.updateDisplayListIfDirty(View.java:19384)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4443)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4423)
       at android.view.View.updateDisplayListIfDirty(View.java:19384)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4443)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4423)
       at android.view.View.updateDisplayListIfDirty(View.java:19384)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4443)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4423)
       at android.view.View.updateDisplayListIfDirty(View.java:19384)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4443)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4423)
       at android.view.View.updateDisplayListIfDirty(View.java:19384)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4443)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4423)
       at android.view.View.updateDisplayListIfDirty(View.java:19384)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4443)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4423)
       at android.view.View.updateDisplayListIfDirty(View.java:19384)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:719)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:725)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:833)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:3567)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3354)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2889)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1843)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7978)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
       at android.view.Choreographer.doCallbacks(Choreographer.java:723)
       at android.view.Choreographer.doFrame(Choreographer.java:658)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:7000)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by MiaShopgal** [comment]
I found it's caused by myself!
I try to put multiple labels but the array contains a null object.
RF : https://stackoverflow.com/a/45276098/1083128

**Comment by Jitesh1720** [comment]
@MiaShopgal The solution from link works perfectly for multiple markerview displays but I'm still getting the error if I click on the point in the line chart.

**Comment by MiaShopgal** [comment]
@Jitesh1720 I could try to take a look at your problem if it's possible to put your project in a repo? 

> @MiaShopgal The solution from link works perfectly for multiple markerview displays but I'm still getting the error if I click on the point in the line chart.

**Comment by Jitesh1720** [comment]
@MiaShopgal @PhilJay  sorry but I can't do that coz it's company project. But I have many questions related to this library but not able to find answers.

1. I want to add x,y point on the graph, which graph I should use- LineGraph or Scatter?
2. How can I use drawable icon for the x,y instead of circle.
3. How can I use markerview with direction arrow (Means if there is no space on the left side then markerview should be on the right side)?
4. In my project, it is possible to have multiple points using the same x,y values. So how can I display multiple markerview for these points with the same x,y values?

I'm facing these issues for a long time in my project but unable to find any solution. 

By using the solution, multiple markerview displayed but they override each other So only one markerview visible to users and the crashing issue started if I click on highlighted point (x, y).

**Comment by DineshShelke** [comment]
The solution from link works perfectly for multiple markerview displays but I'm still getting the error if I click on the point in the line chart.
