### ISSUE TITLE
NullPointerException: VelocityTracker

### ISSUE THREAD

**Issue by abedsh** [PhilJay/MPAndroidChart#3881]
I received this error on a samsung running on Oreo

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.VelocityTracker.computeCurrentVelocity(int, float)' on a null object reference
       at com.github.mikephil.charting.listener.BarLineChartTouchListener.onTouch(Unknown Source:401)
       at com.github.mikephil.charting.charts.BarLineChartBase.onTouchEvent(Unknown Source:19)
       at android.view.View.dispatchTouchEvent(View.java:12534)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3153)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2829)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2844)
```

**Comment by MGaetan89** [comment]
I guess this is the same one as in #3880. Can you close it?
