### ISSUE TITLE
NullPointerException PieChartRenderer.drawExtras and PieChart.onDraw

### ISSUE THREAD

**Issue by jeremydu** [PhilJay/MPAndroidChart#3884]
Bonjour,

J'utilise cette librairie, mais j'ai un plantage régulier.
Voici le code d'erreur que me renvoie le playstore.
Je n'arrive pas a reproduire cette erreur.
Quelqu'un aurais une idée ??

java.lang.NullPointerException: 
  at com.github.mikephil.charting.renderer.PieChartRenderer.drawExtras (PieChartRenderer.java:638)
  at com.github.mikephil.charting.charts.PieChart.onDraw (PieChart.java:131)
  at android.view.View.draw (View.java:17320)
  at android.view.View.updateDisplayListIfDirty (View.java:16259)
  at android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:3874)
  at android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3854)
  at android.view.View.updateDisplayListIfDirty (View.java:16213)
  at android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:3874)
  at android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3854)
  at android.view.View.updateDisplayListIfDirty (View.java:16213)
  at android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:3874)
  at android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3854)
  at android.view.View.updateDisplayListIfDirty (View.java:16213)
  at android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:3874)
  at android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3854)
  at android.view.View.updateDisplayListIfDirty (View.java:16213)
  at android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:3874)
  at android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3854)
  at android.view.View.updateDisplayListIfDirty (View.java:16213)
  at android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:3874)
  at android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3854)
  at android.view.View.updateDisplayListIfDirty (View.java:16213)
  at android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:3874)
  at android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3854)
  at android.view.View.updateDisplayListIfDirty (View.java:16213)
  at android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:3874)
  at android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3854)
  at android.view.View.updateDisplayListIfDirty (View.java:16213)
  at android.view.ThreadedRenderer.updateViewTreeDisplayList (ThreadedRenderer.java:661)
  at android.view.ThreadedRenderer.updateRootDisplayList (ThreadedRenderer.java:667)
  at android.view.ThreadedRenderer.draw (ThreadedRenderer.java:775)
  at android.view.ViewRootImpl.draw (ViewRootImpl.java:3189)
  at android.view.ViewRootImpl.performDraw (ViewRootImpl.java:2982)
  at android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:2570)
  at android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1463)
  at android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:6983)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:907)
  at android.view.Choreographer.doCallbacks (Choreographer.java:709)
  at android.view.Choreographer.doFrame (Choreographer.java:644)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:893)
  at android.os.Handler.handleCallback (Handler.java:836)
  at android.os.Handler.dispatchMessage (Handler.java:103)
  at android.os.Looper.loop (Looper.java:203)
  at android.app.ActivityThread.main (ActivityThread.java:6251)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1063)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:924)

**Comment by jeremydu** [comment]
J'ai réussi a reproduire mais c'est aléatoire.
Voici la trace complète : 
03-24 17:57:54.802 8747-8747/com. E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: com., PID: 8747
                                                               java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.Reference.get()' on a null object reference
                                                                   at com.github.mikephil.charting.renderer.PieChartRenderer.drawExtras(PieChartRenderer.java:638)
                                                                   at com.github.mikephil.charting.charts.PieChart.onDraw(PieChart.java:131)
                                                                   at android.view.View.draw(View.java:18318)
                                                                   at android.view.View.updateDisplayListIfDirty(View.java:17296)
                                                                   at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                                   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                                   at android.view.View.updateDisplayListIfDirty(View.java:17259)
                                                                   at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                                   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                                   at android.view.View.updateDisplayListIfDirty(View.java:17259)
                                                                   at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                                   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                                   at android.view.View.updateDisplayListIfDirty(View.java:17259)
                                                                   at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                                   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                                   at android.view.View.updateDisplayListIfDirty(View.java:17259)
                                                                   at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                                   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                                   at android.view.View.updateDisplayListIfDirty(View.java:17259)
                                                                   at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                                   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                                   at android.view.View.updateDisplayListIfDirty(View.java:17259)
                                                                   at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                                   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                                   at android.view.View.updateDisplayListIfDirty(View.java:17259)
                                                                   at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                                   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                                   at android.view.View.updateDisplayListIfDirty(View.java:17259)
                                                                   at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:692)
                                                                   at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:698)
                                                                   at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:806)
                                                                   at android.view.ViewRootImpl.draw(ViewRootImpl.java:3128)
                                                                   at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2924)
                                                                   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2516)
                                                                   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1515)
                                                                   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7091)
                                                                   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
                                                                   at android.view.Choreographer.doCallbacks(Choreographer.java:702)
                                                                   at android.view.Choreographer.doFrame(Choreographer.java:638)
                                                                   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
                                                                   at android.os.Handler.handleCallback(Handler.java:751)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by jeremydu** [comment]
J'ai trouvé, en faite je cacher le layout dans lequel est présent le PieChart lors du scroll.
Celui était alimenté alors qu'il n'etait plus présent
