### ISSUE TITLE
Axis Formatter- IndexOutOfBoundsException when a method is called second time but works fine for the first time.

### ISSUE THREAD

**Issue by LameshRamdani** [PhilJay/MPAndroidChart#3905]
So i have an app where i have to select location names from a drop down.
Then a line graph is displayed where days are plotted on the x axis against some values on the y axis.
i can choose any items from the drop down and it works fine but when i re chooses an item that i once already chose i get an error.

For example:
-i choose the first item from the dropdown, line graph is displayed-works well
-i choose second item from drop down - displays new line graph -works well
-and here the problem when i choose back the first item from the dropdown i get IndexOutOfBoundsException from the formatter and app crashes

i have log everything to try find the problem but in vain.
i'm using a list in the formatter class. so i have match the list from the formatter class with the list that is setting the y values. Everything corresponds - the size & indexes are good.

Here is the error.
04-01 22:06:00.969 20279-20279/com.example.dell.googlemapapps E/X values: 3
04-01 22:06:00.970 20279-20279/com.example.dell.googlemapapps E/Y values: 3
04-01 22:06:00.971 20279-20279/com.example.dell.googlemapapps E/Formatter index:: 0.0 | X Axis list size: 4 | X Axis List value:Fri 30
04-01 22:06:00.973 20279-20279/com.example.dell.googlemapapps E/Formatter index:: 1.0 | X Axis list size: 4 | X Axis List value:Fri 30
04-01 22:06:00.975 20279-20279/com.example.dell.googlemapapps E/Formatter index:: 2.0 | X Axis list size: 4 | X Axis List value:Sat 31
04-01 22:06:00.977 20279-20279/com.example.dell.googlemapapps E/Formatter index:: 3.0 | X Axis list size: 4 | X Axis List value:Sun 01
04-01 22:06:00.983 20279-20279/com.example.dell.googlemapapps E/Formatter index:: 1.2 | X Axis list size: 4 | X Axis List value:Fri 30
04-01 22:06:00.984 20279-20279/com.example.dell.googlemapapps E/Formatter index:: 1.5 | X Axis list size: 4 | X Axis List value:Fri 30
04-01 22:06:00.986 20279-20279/com.example.dell.googlemapapps E/Formatter index:: 1.8000001 | X Axis list size: 4 | X Axis List value:Fri 30
04-01 22:06:00.991 20279-20279/com.example.dell.googlemapapps E/X values: 3
04-01 22:06:00.992 20279-20279/com.example.dell.googlemapapps E/Y values: 3
04-01 22:06:00.992 20279-20279/com.example.dell.googlemapapps E/Formatter index:: 0.0 | X Axis list size: 4 | X Axis List value:Fri 30
04-01 22:06:00.994 20279-20279/com.example.dell.googlemapapps E/Formatter index:: 1.0 | X Axis list size: 4 | X Axis List value:Fri 30
04-01 22:06:00.995 20279-20279/com.example.dell.googlemapapps E/Formatter index:: 2.0 | X Axis list size: 4 | X Axis List value:Sat 31
04-01 22:06:00.996 20279-20279/com.example.dell.googlemapapps E/Formatter index:: 3.0 | X Axis list size: 4 | X Axis List value:Sun 01
04-01 22:06:00.998 20279-20279/com.example.dell.googlemapapps E/Formatter index:: 1.2 | X Axis list size: 4 | X Axis List value:Fri 30
04-01 22:06:00.999 20279-20279/com.example.dell.googlemapapps E/Formatter index:: 1.5 | X Axis list size: 4 | X Axis List value:Fri 30
04-01 22:06:01.000 20279-20279/com.example.dell.googlemapapps E/Formatter index:: 1.8000001 | X Axis list size: 4 | X Axis List value:Fri 30
04-01 22:06:01.006 20279-20279/com.example.dell.googlemapapps E/X values: 3
04-01 22:06:01.006 20279-20279/com.example.dell.googlemapapps E/Y values: 3
04-01 22:06:01.007 20279-20279/com.example.dell.googlemapapps E/Formatter index:: 0.0 | X Axis list size: 4 | X Axis List value:Fri 30
04-01 22:06:01.008 20279-20279/com.example.dell.googlemapapps E/Formatter index:: 1.0 | X Axis list size: 4 | X Axis List value:Fri 30
04-01 22:06:01.009 20279-20279/com.example.dell.googlemapapps E/Formatter index:: 2.0 | X Axis list size: 4 | X Axis List value:Sat 31
04-01 22:06:01.010 20279-20279/com.example.dell.googlemapapps E/Formatter index:: 3.0 | X Axis list size: 4 | X Axis List value:Sun 01
04-01 22:06:01.011 20279-20279/com.example.dell.googlemapapps E/Formatter index:: 1.2 | X Axis list size: 4 | X Axis List value:Fri 30
04-01 22:06:01.012 20279-20279/com.example.dell.googlemapapps E/Formatter index:: 1.5 | X Axis list size: 4 | X Axis List value:Fri 30
04-01 22:06:01.013 20279-20279/com.example.dell.googlemapapps E/Formatter index:: 1.8000001 | X Axis list size: 4 | X Axis List value:Fri 30
04-01 22:06:01.027 20279-20279/com.example.dell.googlemapapps E/ViewRootImpl: sendUserActionEvent() returned.
04-01 22:06:01.031 20279-20279/com.example.dell.googlemapapps E/Formatter index:: 0.0 | X Axis list size: 3 | X Axis List value:Fri 30
04-01 22:06:01.033 20279-20279/com.example.dell.googlemapapps E/Formatter index:: 1.0 | X Axis list size: 3 | X Axis List value:Sat 31
04-01 22:06:01.034 20279-20279/com.example.dell.googlemapapps E/Formatter index:: 2.0 | X Axis list size: 3 | X Axis List value:Sun 01
04-01 22:06:01.043 20279-20279/com.example.dell.googlemapapps E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: com.example.dell.googlemapapps, PID: 20279
                                                                                java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
                                                                                    at java.util.ArrayList.get(ArrayList.java:411)
04-01 22:06:01.031 20279-20279/com.example.dell.googlemapapps E/Formatter index:: 0.0 | X Axis list size: 3 | X Axis List value:Fri 30
04-01 22:06:01.033 20279-20279/com.example.dell.googlemapapps E/Formatter index:: 1.0 | X Axis list size: 3 | X Axis List value:Sat 31
04-01 22:06:01.034 20279-20279/com.example.dell.googlemapapps E/Formatter index:: 2.0 | X Axis list size: 3 | X Axis List value:Sun 01
04-01 22:06:01.043 20279-20279/com.example.dell.googlemapapps E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: com.example.dell.googlemapapps, PID: 20279
                                                                                java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
                                                                                    at java.util.ArrayList.get(ArrayList.java:411)
                                                                                    at com.example.dell.AQMS.MyAxisValueFormatterDaily.getFormattedValue(MyAxisValueFormatterDaily.java:26)
                                                                                    at com.github.mikephil.charting.components.AxisBase.getFormattedLabel(AxisBase.java:472)
                                                                                    at com.github.mikephil.charting.components.AxisBase.getLongestLabel(AxisBase.java:458)
                                                                                    at com.github.mikephil.charting.renderer.XAxisRenderer.computeSize(XAxisRenderer.java:79)
                                                                                    at com.github.mikephil.charting.renderer.XAxisRenderer.computeAxisValues(XAxisRenderer.java:74)
                                                                                    at com.github.mikephil.charting.renderer.XAxisRenderer.computeAxis(XAxisRenderer.java:67)
                                                                                    at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:209)
                                                                                    at android.view.View.draw(View.java:18398)
                                                                                    at android.view.View.updateDisplayListIfDirty(View.java:17376)
                                                                                    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3952)
                                                                                    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3932)
                                                                                    at android.view.View.updateDisplayListIfDirty(View.java:17339)
                                                                                    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3952)
                                                                                    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3932)
                                                                                    at android.view.View.updateDisplayListIfDirty(View.java:17339)
                                                                                    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3952)
                                                                                    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3932)
                                                                                    at android.view.View.updateDisplayListIfDirty(View.java:17339)
                                                                                    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3952)
                                                                                    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3932)
                                                                                    at android.view.View.updateDisplayListIfDirty(View.java:17339)
                                                                                    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3952)
                                                                                    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3932)
                                                                                    at android.view.View.updateDisplayListIfDirty(View.java:17339)
                                                                                    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3952)
                                                                                    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3932)
                                                                                    at android.view.View.updateDisplayListIfDirty(View.java:17339)
                                                                                    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3952)
                                                                                    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3932)
                                                                                    at android.view.View.updateDisplayListIfDirty(View.java:17339)
                                                                                    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3952)
                                                                                    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3932)
                                                                                    at android.view.View.updateDisplayListIfDirty(View.java:17339)
                                                                                    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3952)
                                                                                    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3932)
                                                                                    at android.view.View.updateDisplayListIfDirty(View.java:17339)
                                                                                    at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:722)
                                                                                    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:728)
                                                                                    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:836)
                                                                                    at android.view.ViewRootImpl.draw(ViewRootImpl.java:3168)
                                                                                    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2964)
                                                                                    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2552)
                                                                                    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1537)
                                                                                    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
                                                                                    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:959)
                                                                                    at android.view.Choreographer.doCallbacks(Choreographer.java:734)
                                                                                    at android.view.Choreographer.doFrame(Choreographer.java:670)
                                                                                    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:945)
                                                                                    at android.os.Handler.handleCallback(Handler.java:751)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
04-01 22:06:01.043 20279-20279/com.example.dell.googlemapapps E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)

-------------------------------------------------------------------------------------------------------------------
04-01 22:06:01.031 20279-20279/com.example.dell.googlemapapps E/Formatter index:: 0.0 | X Axis list size: 3 | X Axis List value:Fri 30
04-01 22:06:01.033 20279-20279/com.example.dell.googlemapapps E/Formatter index:: 1.0 | X Axis list size: 3 | X Axis List value:Sat 31
04-01 22:06:01.034 20279-20279/com.example.dell.googlemapapps E/Formatter index:: 2.0 | X Axis list size: 3 | X Axis List value:Sun 01
04-01 22:06:01.043 20279-20279/com.example.dell.googlemapapps E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: com.example.dell.googlemapapps, PID: 20279
                                                                                java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
                                                                                    at java.util.ArrayList.get(ArrayList.java:411)

I think i should have got only these 3 logs in my logcat, i dont know why there are so many other logs(with data created during the previous item that was selected from the dropdown) in the error.
As you see the index is only 0,1,2 but in the error it is saying index is 3.

Codes in formatter class.

  @Override
    public String getFormattedValue(float value, AxisBase axis) {
        // "value" represents the position of the label on the axis (x or y)
        Log.e("Formatter Value:", value+" | X Axis list size: "+mValues.size()+" | X Axis List value:"+mValues.get((int)value));

        return mValues.get((int)value);
    }

Can someone help.

**Comment by almic** [comment]
First guess: You are not notifying the dataset or chart about the changes to your data, causing the IndexOutOfBoundsException.

Second guess: Your chart is not being properly resized, assuming the second chart changes the max ranges. Best solution is to first make sure that `mValues` is never called with a value outside it's range.

This initial step, not calling `mValues.get()` with a value you can determine will be outside it's index range, is trivial. I bet if you tried that before posting this issue, you would've realized the problem and not had to come here.
