### ISSUE TITLE
Zoom bug in v3.0.3

### ISSUE THREAD

**Issue by vasiledoe** [PhilJay/MPAndroidChart#3907]
I have 2 BarChart on the same page, both zoomed in, now I put one finger on one chart and second finger to the other chart and try to zoom out. It crashes with this stack trace:

`    Process: com.path.sadow, PID: 28936
    java.lang.IllegalArgumentException: pointerIndex out of range
        at android.view.MotionEvent.nativeGetAxisValue(Native Method)
        at android.view.MotionEvent.getX(MotionEvent.java:2286)
        at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2066)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2368)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2841)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2841)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2841)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2841)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2841)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2841)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2841)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2841)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2841)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
        at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2823)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1848)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3047)
        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
        at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2784)
        at android.view.View.dispatchPointerEvent(View.java:10229)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5403)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5239)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4679)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4732)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4698)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4840)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4706)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4897)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4679)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4732)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4698)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4706)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4679)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7376)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7254)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7215)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7486)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
        at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
        at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
        at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7450)
        at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7513)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
    	at android.view.Choreographer.doCal`

**Comment by MGaetan89** [comment]
This was already reported in #3032.
Can you close this issue to group all related information in one place?

**Comment by vasiledoe** [comment]
Here the problem is a bit different, multi touch zoom is working fine for 1 chart but if try to do it for 2 charts it crashes

**Comment by almic** [comment]
The underlying cause is the same, the animated zoom class *was* bugged. The current Master branch has this bug fixed, a release will be coming soon with this fix in place.
