### ISSUE TITLE
crash:java.lang.IllegalArgumentException: pointerIndex out of range

### ISSUE THREAD

**Issue by dedeTao** [PhilJay/MPAndroidChart#3909]
i am a chinese,English is not good,sorry,there is the crash log:

E/CrashReport: java.lang.IllegalArgumentException: pointerIndex out of range
                                                                  at android.view.MotionEvent.nativeGetAxisValue(Native Method)
                                                                  at android.view.MotionEvent.getX(MotionEvent.java:2139)
                                                                  at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2092)
                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2212)
                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                  at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:414)
                                                                  at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1810)
                                                                  at android.app.Activity.dispatchTouchEvent(Activity.java:3196)
                                                                  at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
                                                                  at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:376)
                                                                  at android.view.View.dispatchPointerEvent(View.java:10177)
                                                                  at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4496)
                                                                  at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4361)
                                                                  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3901)
                                                                  at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3954)
                                                                  at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3920)
                                                                  at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4047)
                                                                  at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3928)
                                                                  at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4104)
                                                                  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3901)
                                                                  at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3954)
                                                                  at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3920)
                                                                  at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3928)
                                                                  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3901)
                                                                  at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6272)
                                                                  at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6246)
                                                                  at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6207)
                                                                  at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6378)
                                                                  at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:187)
                                                                  at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                  at android.os.MessageQueue.next(MessageQueue.java:323)
                                                                  at android.os.Looper.loop(Looper.java:142)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:6337)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

**Comment by dedeTao** [comment]
use the lastest version

**Comment by dedeTao** [comment]
Two fingers up and down the y axis，the chart must be crash

**Comment by MGaetan89** [comment]
This was already reported in #3032.
Can you close this issue to group all related information in one place?

**Comment by dedeTao** [comment]
yes
