### ISSUE TITLE
ANR crash on zoom lineChart

### ISSUE THREAD

**Issue by surcreak** [PhilJay/MPAndroidChart#3932]
traces：
DALVIK THREADS (94):
"main" prio=5 tid=1 Suspended
  | group="main" sCount=1 dsCount=0 obj=0x74a9d000 self=0xf4c27800
  | sysTid=13535 nice=0 cgrp=default sched=0/0 handle=0xf73b9bec
  | state=S schedstat=( 126983628377 7521673827 28857 ) utm=12534 stm=203 core=4 HZ=100
  | stack=0xff7d0000-0xff7d2000 stackSize=8MB
  | held mutexes=
  at com.github.mikephil.charting.data.Entry.getX(Entry.java:80)
  at com.github.mikephil.charting.data.DataSet.getEntryIndex(DataSet.java:302)
  at com.github.mikephil.charting.data.DataSet.getEntryForXValue(DataSet.java:273)
  at com.github.mikephil.charting.renderer.BarLineScatterCandleBubbleRenderer$XBounds.set(BarLineScatterCandleBubbleRenderer.java:88)
  at com.github.mikephil.charting.renderer.LineChartRenderer.drawLinear(LineChartRenderer.java:314)
  at com.github.mikephil.charting.renderer.LineChartRenderer.drawDataSet(LineChartRenderer.java:116)
  at com.github.mikephil.charting.renderer.LineChartRenderer.drawData(LineChartRenderer.java:98)
  at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:232)
  at android.view.View.draw(View.java:15268)
  at android.view.View.updateDisplayListIfDirty(View.java:14204)
  at android.view.View.getDisplayList(View.java:14226)
  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
  at android.view.View.updateDisplayListIfDirty(View.java:14164)
  at android.view.View.getDisplayList(View.java:14226)
  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
  at android.view.View.updateDisplayListIfDirty(View.java:14164)
  at android.view.View.getDisplayList(View.java:14226)
  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
  at android.view.View.updateDisplayListIfDirty(View.java:14164)
  at android.view.View.getDisplayList(View.java:14226)
  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
  at android.view.View.updateDisplayListIfDirty(View.java:14164)
  at android.view.View.getDisplayList(View.java:14226)
  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
  at android.view.View.updateDisplayListIfDirty(View.java:14164)
  at android.view.View.getDisplayList(View.java:14226)
  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
  at android.view.View.updateDisplayListIfDirty(View.java:14164)
  at android.view.View.getDisplayList(View.java:14226)
  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
  at android.view.View.updateDisplayListIfDirty(View.java:14164)
  at android.view.View.getDisplayList(View.java:14226)
  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
  at android.view.View.updateDisplayListIfDirty(View.java:14164)
  at android.view.View.getDisplayList(View.java:14226)
  at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:273)
  at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:279)
  at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:318)
  at android.view.ViewRootImpl.draw(ViewRootImpl.java:2542)
  at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2358)
  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1988)
  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1067)
  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5897)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
  at android.view.Choreographer.doCallbacks(Choreographer.java:580)
  at android.view.Choreographer.doFrame(Choreographer.java:550)
  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:135)
  at android.app.ActivityThread.main(ActivityThread.java:5292)
  at java.lang.reflect.Method.invoke!(Native method)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

**Comment by almic** [comment]
When *zooming*? This may be related to the NPE when doing certain animated zooms. This issue has already been reported, so I'm closing for a duplicate.
