### ISSUE TITLE
Getting crash when trying to change the dataset of barchart.

### ISSUE THREAD

**Issue by parthanjaria** [PhilJay/MPAndroidChart#3940]
Initially i have an array-list of 73(at x-axis) set in the bar chart.

Then i change the array-list to 13(at x-axis) and that time i get crash. can you help me out with why it is happening.

Here is the written code : 

`private void setUpBarChart(int type) {
        barChartDataSet = new BarChartDataSet(type);

        BarDataSet dataSet = new BarDataSet(barChartDataSet.getBarEntries(), "Stats");
        dataSet.setColor(ContextCompat.getColor(getContext(), R.color.bright_sky_blue));
        dataSet.setValueTextColor(ContextCompat.getColor(getContext(), R.color.greyish_brown));

        IValueFormatter intValueFormatter = new IValueFormatter() {
            @Override
            public String getFormattedValue(float value, Entry entry, int dataSetIndex,
                                            ViewPortHandler viewPortHandler) {
                int val = Math.round(value);
                if (val > 0) {
                    return UnitsManager.formatRupeeToMyCurrency(val);
                } else {
                    return "";
                }
            }
        };

        dataSet.setValueFormatter(intValueFormatter);
        BarData data = new BarData(dataSet);

        barChart.setData(data);
        barChart.setDrawGridBackground(false);

        barChart.getAxisRight().setEnabled(false);
        barChart.getAxisRight().setDrawGridLines(false);
        Description desc = new Description();
        desc.setText("");
        barChart.setDescription(desc);
        barChart.getLegend().setEnabled(false);

        YAxis yAxis = barChart.getAxisLeft();

        yAxis.setSpaceBottom(4);
        yAxis.setLabelCount(3, true);

        yAxis.setAxisMinimum(0);
        yAxis.setGridColor(ContextCompat.getColor(getContext(), R.color.black_5));
        yAxis.setDrawAxisLine(false);
        yAxis.setGridLineWidth(1f);

        yAxis.setValueFormatter(new IAxisValueFormatter() {
            @Override
            public String getFormattedValue(float value, AxisBase axis) {
                if (value > 10) {
                    return UnitsManager.formatRupeeToMyCurrency(value);
                } else if (value > 0) {
                    // Earlier only one decimal was being shown
                    return UnitsManager.formatRupeeToMyCurrency(value);
                } else {
                    return "";
                }
            }
        });

        XAxis xAxis = barChart.getXAxis();

        xAxis.setDrawGridLines(false);
        xAxis.setAxisLineColor(ContextCompat.getColor(getContext(), R.color.black_5));
        xAxis.setAxisLineWidth(1.0f);
        xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);
        IAxisValueFormatter valueFormatter = new IAxisValueFormatter() {
            @Override
            public String getFormattedValue(float value, AxisBase axis) {
                int index = (int) value;
                return barChartDataSet.getLabelForIndex(index); // getting crash at this line
            }
        };
        xAxis.setValueFormatter(valueFormatter);
        barChart.setDrawBorders(false);

        barChart.invalidate();
        barChart.setOnChartValueSelectedListener(this);
        Handler handler = new Handler() {
            @Override
            public void handleMessage(Message msg) {
                super.handleMessage(msg);
                float width = layoutProfileStats.getWidth();
                int size = barChartDataSet.getNoOfValuesInXAxis()>=7?7: (int) barChartDataSet.getNoOfValuesInXAxis();
                float scale = ((width * barChartDataSet.getNoOfValuesInXAxis()) / size) / width;
                barChart.setScaleYEnabled(false);
                barChart.setScaleXEnabled(true);
                barChart.zoom(scale, 1, width * scale, 0);
                barChart.highlightValue(barChartDataSet.getBarEntries().size() - 1, 0);
            }
        };
        handler.postDelayed(null, 100);
    }`

I call this method the number of times i wish to change the data, accordingly the data is changed. if i don't write this code : 'xAxis.setValueFormatter(valueFormatter);' then i don't get any error.

**Comment by MGaetan89** [comment]
What is the stacktrace you are receiving?

**Comment by parthanjaria** [comment]
`04-12 10:05:33.100 32291-32291/com.sharesmile.share E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sharesmile.share, PID: 32291
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.sharesmile.share.profile.stats.BarChartEntry.getLabel()' on a null object reference
        at com.sharesmile.share.profile.stats.BarChartDataSet.getLabelForIndex(BarChartDataSet.java:68)
        at com.sharesmile.share.profile.ProfileFragment$4.getFormattedValue(ProfileFragment.java:371)
        at com.github.mikephil.charting.components.AxisBase.getFormattedLabel(AxisBase.java:472)
        at com.github.mikephil.charting.components.AxisBase.getLongestLabel(AxisBase.java:458)
        at com.github.mikephil.charting.renderer.XAxisRenderer.computeSize(XAxisRenderer.java:79)
        at com.github.mikephil.charting.renderer.XAxisRenderer.computeAxisValues(XAxisRenderer.java:74)
        at com.github.mikephil.charting.renderer.XAxisRenderer.computeAxis(XAxisRenderer.java:67)
        at com.github.mikephil.charting.charts.BarLineChartBase.notifyDataSetChanged(BarLineChartBase.java:331)
        at com.github.mikephil.charting.charts.Chart.setData(Chart.java:304)
        at com.sharesmile.share.profile.ProfileFragment.setUpBarChart(ProfileFragment.java:326)
        at com.sharesmile.share.profile.ProfileFragment.onMyStatsClick(ProfileFragment.java:283)
        at com.sharesmile.share.profile.ProfileFragment$$ViewBinder$4.doClick(ProfileFragment$$ViewBinder.java:79)
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
        at android.view.View.performClick(View.java:5640)
        at android.view.View$PerformClick.run(View.java:22455)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6165)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)`

getting error in the like i have commented.

it runs fine when i remove the axis formatted from x-axis. and it happens because i want to change the no of values in x-axis. for eg: initially there were 10 values in x-axis, now there are only 5.

**Comment by almic** [comment]
Looks like your data set becomes `null` at some point between creating it, and updating it. I would suggest creating a separate ValueFormatter class entirely, and passing the `barChartDataSet` to it and saving it there, so that it isn't lost in the background. The problem may be that the inline class called `valueFormatter` doesn't know about `barChartDataSet` or it's value.

The problem is definitely somewhere in this code, last I checked DataSet's don't randomly turn themselves into `null`.
