### ISSUE TITLE
sometimes is found a error java.lang.NegativeArraySizeException

### ISSUE THREAD

**Issue by anthonyY** [PhilJay/MPAndroidChart#3953]
java.lang.NegativeArraySizeException: -4
at com.github.mikephil.charting.utils.Transformer.generateTransformedValuesLine(Transformer.java:178)
at com.github.mikephil.charting.renderer.LineChartRenderer.drawValues(LineChartRenderer.java:547)
at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:264)

I hope you can fixed it ! Thank you!

**Comment by almic** [comment]
"Sometimes" doesn't help debug this, and neither does truncating the full stack trace...

However, looks like you are passing min and max visibility values the wrong way. This is likely caused by passing a min X/Y visibility range that is GREATER than the max X/Y visibility range, specifically the min range - max range is coming out as -2.

Please make sure the min is actually smaller than the max 👍

**Comment by varunrau** [comment]
@almic I'm consistently seeing this issue as well. In my case, I'm not setting the visibility range, instead relying on the calculation done in `BarLineScatterCandleBubbleRenderer`. 

Here's an example of the data I'm passing in that reproduces this crash reliably.

```
[{"x":1,"y":375},{"x":1,"y":376},{"x":750,"y":376},{"x":750,"y":375},{"x":2,"y":378},{"x":2,"y":373},{"x":188,"y":94},{"x":188,"y":657},{"x":6,"y":361},{"x":6,"y":390},{"x":667,"y":180},{"x":667,"y":571},{"x":121,"y":712},{"x":121,"y":39},{"x":582,"y":15}]
```

Note: that if I sort this data by x, then I get around the crash. Unfortunately, that doesn't work for me since in my dataset the order the lines are connected is important.

This is the full stack trace:

```
12-18 22:01:24.342 30855 30855 D AndroidRuntime: Shutting down VM
12-18 22:01:24.353 30855 30855 E AndroidRuntime: FATAL EXCEPTION: main
12-18 22:01:24.353 30855 30855 E AndroidRuntime: Process: com.blockchain, PID: 30855
12-18 22:01:24.353 30855 30855 E AndroidRuntime: java.lang.NegativeArraySizeException: -16
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at com.github.mikephil.charting.utils.Transformer.generateTransformedValuesLine(Transformer.java:178)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at com.github.mikephil.charting.renderer.LineChartRenderer.drawValues(LineChartRenderer.java:547)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at com.github.mikephil.charting.renderer.CombinedChartRenderer.drawValues(CombinedChartRenderer.java:96)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:264)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.View.draw(View.java:20207)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19082)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19042)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19042)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19042)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19042)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19042)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19042)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19042)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19042)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19042)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19042)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3311)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3115)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2484)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:696)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
12-18 22:01:24.353 30855 30855 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
12-18 22:01:24.370  1859  2686 W ActivityManager:   Force finishing activity com.blockchain/.MainActivity
12-18 22:01:24.403 30855 30855 I Process : Sending signal. PID: 30855 SIG: 9
```
