### ISSUE TITLE
ArrayIndexOutOfBoundsException,thanks for your help

### ISSUE THREAD

**Issue by Messiahfy** [PhilJay/MPAndroidChart#3964]
When I call pieChart.getData().getDataSet().addEntry(new PieEntry(11,"xxxx"));
There is an error thar is 
java.lang.ArrayIndexOutOfBoundsException: length=6; index=6
        at com.github.mikephil.charting.renderer.PieChartRenderer.drawDataSet(PieChartRenderer.java:245)
        at com.github.mikephil.charting.renderer.PieChartRenderer.drawData(PieChartRenderer.java:148)
        at com.github.mikephil.charting.charts.PieChart.onDraw(PieChart.java:126)
        at android.view.View.draw(View.java:19145)
        at android.view.View.updateDisplayListIfDirty(View.java:18095)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4200)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4180)
        at android.view.View.updateDisplayListIfDirty(View.java:18054)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4200)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4180)
        at android.view.View.updateDisplayListIfDirty(View.java:18054)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4200)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4180)
        at android.view.View.updateDisplayListIfDirty(View.java:18054)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4200)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4180)
        at android.view.View.updateDisplayListIfDirty(View.java:18054)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4200)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4180)
        at android.view.View.updateDisplayListIfDirty(View.java:18054)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4200)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4180)
        at android.view.View.updateDisplayListIfDirty(View.java:18054)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4200)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4180)
        at android.view.View.updateDisplayListIfDirty(View.java:18054)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:652)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:658)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:766)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3027)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2822)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2375)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1414)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6801)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1026)
        at android.view.Choreographer.doCallbacks(Choreographer.java:838)
        at android.view.Choreographer.doFrame(Choreographer.java:769)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1012)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6684)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

**Comment by almic** [comment]
Looks like the chart and the dataset don't agree on the number of entries. I would start by loading the value from `getDataSet()` directly into it's own variable called `set`, and the adding entries. Once you finish adding the entries, pack them into a new PieData called `data`, and then call `pieChart.setData(data)`.

You may have to call `notifyDataChanged()` and `notifyDataSetChanged()` on the chart and data object respectively. If you still get this error after doing that, open a new issue with the code you are calling, and put the stack trace in a gist (press the + at the top of the website), so that the issue page isn't full of spam.
