### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by choangkute** [PhilJay/MPAndroidChart#4033]
I got this trouble. But i don't know how to solve it. Here my code. Thanks !
```
java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
                      at com.github.mikephil.charting.renderer.PieChartRenderer.drawDataSet(PieChartRenderer.java:245)
                      at com.github.mikephil.charting.renderer.PieChartRenderer.drawData(PieChartRenderer.java:148)
                      at com.github.mikephil.charting.charts.PieChart.onDraw(PieChart.java:126)
                      at android.view.View.draw(View.java:17071)
                      at android.view.View.updateDisplayListIfDirty(View.java:16053)
                      at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)
                      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)
                      at android.view.View.updateDisplayListIfDirty(View.java:16016)
                      at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)
                      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)
                      at android.view.View.updateDisplayListIfDirty(View.java:16016)
                      at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)
                      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)
                      at android.view.View.updateDisplayListIfDirty(View.java:16016)
                      at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)
                      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)
                      at android.view.View.updateDisplayListIfDirty(View.java:16016)
                      at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)
                      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)
                      at android.view.View.updateDisplayListIfDirty(View.java:16016)
                      at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)
                      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)
                      at android.view.View.updateDisplayListIfDirty(View.java:16016)
                      at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)
                      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)
                      at android.view.View.updateDisplayListIfDirty(View.java:16016)
                      at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:656)
                      at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:662)
                      at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:770)
                      at android.view.ViewRootImpl.draw(ViewRootImpl.java:2796)
                      at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2604)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2211)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6301)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:683)
                      at android.view.Choreographer.doFrame(Choreographer.java:619)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6077)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

```
```
pieChart.animateY(500, Easing.EasingOption.EaseInCubic);
        PieDataSet dataSet = new PieDataSet(datapie, "Tên nhóm");
        dataSet.setSliceSpace(3f);
        dataSet.setSelectionShift(5f);
        dataSet.setColors(ColorTemplate.JOYFUL_COLORS);

        PieData data = new PieData(dataSet);
        data.setValueTextSize(10f);
        data.setValueTextColor(Color.BLACK);
        data.notifyDataChanged();

        pieChart.setData(data);
        data.notifyDataChanged();
        pieChart.notifyDataSetChanged();
        pieChart.invalidate();
```

**Comment by almic** [comment]
This is a well known issue, having been reported a number of times already. If you had tried searching existing issues, I'm sure you would've found them. Closed for being a duplicate.
