### ISSUE TITLE
refresh combinechart crashed!

### ISSUE THREAD

**Issue by DreamerLeon** [PhilJay/MPAndroidChart#4042]
UncaughtException detected: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
        at java.util.ArrayList.get(ArrayList.java:308)
        at com.github.mikephil.charting.data.DataSet.getEntryForIndex(DataSet.java:286)
        at com.github.mikephil.charting.utils.Transformer.generateTransformedValuesLine(Transformer.java:184)
        at com.github.mikephil.charting.renderer.LineChartRenderer.drawValues(LineChartRenderer.java:547)
        at com.github.mikephil.charting.renderer.CombinedChartRenderer.drawValues(CombinedChartRenderer.java:96)
        at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:264)
        at android.view.View.draw(View.java:16535)
        at android.view.View.updateDisplayListIfDirty(View.java:15525)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3702)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3682)
        at android.view.View.updateDisplayListIfDirty(View.java:15485)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3702)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3682)
        at android.view.View.updateDisplayListIfDirty(View.java:15485)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3702)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3682)
        at android.view.View.updateDisplayListIfDirty(View.java:15485)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3702)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3682)
        at android.view.View.updateDisplayListIfDirty(View.java:15485)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3702)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3682)
        at android.view.View.updateDisplayListIfDirty(View.java:15485)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3702)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3682)
        at android.view.View.updateDisplayListIfDirty(View.java:15485)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3702)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3682)
        at android.view.View.updateDisplayListIfDirty(View.java:15485)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3702)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3682)
        at android.view.View.updateDisplayListIfDirty(View.java:15485)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3702)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3682)
        at android.view.View.updateDisplayListIfDirty(View.java:15485)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2967)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2779)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2397)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1268)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6638)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:926)
        at android.view.Choreographer.doCallbacks(Choreographer.java:717)
        at android.view.Choreographer.doFrame(Choreographer.java:652)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:912)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5678)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by almic** [comment]
Oof, this issue gets spammed a lot here. Clearly a rampant bug! However, it duplicates about 10 other open issues practically word-for-word and with an identical stack trace.
