### ISSUE TITLE
IndexOutOfBoundsException Invalid Index 0, size 0 in LegendRenderer

### ISSUE THREAD

**Issue by athathdev** [PhilJay/MPAndroidChart#4085]
I am getting the following errors. These are NOT THE SAME as other outofboundsexceptions.
`java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
                                                                                            
at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                                            at java.util.ArrayList.get(ArrayList.java:308)
                                                                                            at com.github.mikephil.charting.renderer.LegendRenderer.renderLegend(LegendRenderer.java:377)
                                                                                            at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:267)
                                                                                            at android.view.View.draw(View.java:17526)
                                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16519)
                                                                                            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3910)`

The calculatedLabelSizes arraylist is having zero length. No mistakes in my code, I copied it as it is from [https://github.com/laxmimerit/Real-Time-Accelerometer-Data-Plot/blob/master/app/src/main/java/com/example/mbreath/realtimeaccelerometer/MainActivity.java](url).
 I am not able to find out why. Please help. Thanks in advance!

**Comment by exoji2e** [comment]
I experience the same error when using a thread to inject database data into a my graphs. The problem is due to MPAndroidChart not beeing threadsafe. In other words; when another thread manipulates the graph, while the UI-thread (Main thread) is handling an event caused by user interaction, nothing is guaranteed about the internal data inside the graph, since another thread is manipulating it.

To solve the problem you should let the UI-thread update the graph for you. Include all the code that manipulates your graph-object inside a Runnable and post it to the graph. My Kotlin-code looks like this: `graph.post{Push2Plot.setPlot(readings, graph, start, end)}`.  In java you need some boilerplate-code. You can read more [here](https://stackoverflow.com/questions/12850143/android-basics-running-code-in-the-ui-thread)

**Comment by exoji2e** [comment]
@athathdev please let me know if this helped you solve your problem.

**Comment by y4233640** [comment]
@exoji2e You solved my problem perfectly.Thank you!
