### ISSUE TITLE
NegativeArraySizeException

### ISSUE THREAD

**Issue by ZhangKuixun** [PhilJay/MPAndroidChart#4141]
Process: com.xxmassdeveloper.mpchartexample, PID: 32589
    java.lang.NegativeArraySizeException: -20
    at com.github.mikephil.charting.utils.Transformer.generateTransformedValuesLine(Transformer.java:179)
    at com.github.mikephil.charting.renderer.LineChartRenderer.drawValues(LineChartRenderer.java:549)
    at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:278)
    at android.view.View.draw(View.java:17070)
    at android.view.View.updateDisplayListIfDirty(View.java:16052)
    at android.view.View.draw(View.java:16836)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
    at android.view.View.draw(View.java:17073)
    at android.view.View.updateDisplayListIfDirty(View.java:16052)
    at android.view.View.draw(View.java:16836)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
    at android.view.View.updateDisplayListIfDirty(View.java:16047)
    at android.view.View.draw(View.java:16836)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
    at android.view.View.draw(View.java:17073)
    at com.android.internal.widget.ActionBarOverlayLayout.draw(ActionBarOverlayLayout.java:500)
    at android.view.View.updateDisplayListIfDirty(View.java:16052)
    at android.view.View.draw(View.java:16836)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
    at android.view.View.draw(View.java:17073)
    at com.android.internal.policy.DecorView.draw(DecorView.java:751)
    at android.view.View.updateDisplayListIfDirty(View.java:16052)
    at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:656)
    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:662)
    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:770)
    at android.view.ViewRootImpl.draw(ViewRootImpl.java:2796)
    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2604)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2211)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6301)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
    at android.view.Choreographer.doCallbacks(Choreographer.java:683)
    at android.view.Choreographer.doFrame(Choreographer.java:619)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6077)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

I used RealmWikiExample page, entry and exit of this page, fifth false reports.
Transformer.class:
    public float[] **generateTransformedValuesLine**(ILineDataSet data,
                                                 float phaseX, float phaseY,
                                                 int min, int max) {

        final int count = ((int) ((max - min) * phaseX) + 1) * 2;

        if (valuePointsForGenerateTransformedValuesLine.length != count) {
            **valuePointsForGenerateTransformedValuesLine = new float[count];**//error
        }
        float[] valuePoints = valuePointsForGenerateTransformedValuesLine;

        for (int j = 0; j < count; j += 2) {

            Entry e = data.getEntryForIndex(j / 2 + min);

            if (e != null) {
                valuePoints[j] = e.getX();
                valuePoints[j + 1] = e.getY() * phaseY;
            } else {
                valuePoints[j] = 0;
                valuePoints[j + 1] = 0;
            }
        }

        getValueToPixelMatrix().mapPoints(valuePoints);

        return valuePoints;
    }

**Comment by tgvoskuilen** [comment]
I'm seeing this too. Any resolution/workaround?

**Comment by andreas-eberle** [comment]
Try sorting the data in ascending order on the x-axis. See #3719
