### ISSUE TITLE
NPE on candlestick chart when zoomAndCenterAnimated is called

### ISSUE THREAD

**Issue by itsyourapp** [PhilJay/MPAndroidChart#4146]
**Summary**
Hi, I've seen this issue for BarChart and PieChart but not yet for CandleStickChart. When I call zoomAndCenterAnimated after setting a CandleData, the library crashes with a NPE. Stack trace at the bottom.

**Expected Behavior**
The library should zoom and center with animation and not crash.

**Device (please complete the following information):**
 - Device: Nexus 5
 - Android Version API 28
 - Library Version 3.0.3

**Additional Context**
java.lang.NullPointerException: Attempt to read from field 'float com.github.mikephil.charting.components.AxisBase.mAxisRange' on a null object reference
        at com.github.mikephil.charting.jobs.AnimatedZoomJob.onAnimationUpdate(AnimatedZoomJob.java:75)
        at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1547)
        at android.animation.ObjectAnimator.animateValue(ObjectAnimator.java:987)
        at android.animation.ValueAnimator.animateBasedOnTime(ValueAnimator.java:1339)
        at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1471)
        at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
        at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
        at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:693)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

I have a custom chart that inherits from CandleStickChart with the following setData method:

```
fun setData(yVals1: List<CandleEntry>) {
        val set1 = CandleDataSet(yVals1, "Data Set")
        set1.setDrawIcons(false)
        set1.axisDependency = YAxis.AxisDependency.LEFT
        set1.shadowColor = Color.DKGRAY
        set1.shadowWidth = 0.7f
        set1.decreasingColor = Color.RED
        set1.decreasingPaintStyle = Paint.Style.FILL
        set1.increasingColor = Color.rgb(122, 242, 84)
        set1.increasingPaintStyle = Paint.Style.FILL
        set1.neutralColor = Color.BLUE
        data = CandleData(set1)
        invalidate()
        zoomAndCenterAnimated(2f, 1f, 0f, center.y, YAxis.AxisDependency.RIGHT, 1000)
    }
```

**Comment by Androneilz** [comment]
I also have the same issue, on any device, latest version 3.0.3. 

This issue was raised previously in issues #3725 and #2856 and was claimed to be fixed, but is definitely still an issue. I'm having to use the standard zoom() method, which does work, but without animation looks really awful! 

Please advise if this will be fixed, or if there is a workaround.

**Comment by almic** [comment]
Should be fixed in the latest commit, until a new release is created you can just use the latest `-SNAPSHOT` version like this

```gradle
dependencies {
    implementation 'com.github.philjay:mpandroidchart:-SNAPSHOT'
}
```

**Comment by Androneilz** [comment]
I tried this but no luck. Apologies if I'm missing something obvious:

Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.github.philjay:mpandroidchart:-SNAPSHOT
