### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'int com.github.mikephil.charting.interfaces.datasets.IDataSet.getEntryIndex(com.github.mikephil.charting.data.Entry)' on a null object reference

### ISSUE THREAD

**Issue by nanhou** [PhilJay/MPAndroidChart#4147]
Hi @PhilJay I got this error when using Line chart.
 java.lang.NullPointerException: Attempt to invoke interface method 'int com.github.mikephil.charting.interfaces.datasets.IDataSet.getEntryIndex(com.github.mikephil.charting.data.Entry)' on a null object reference
        at com.github.mikephil.charting.charts.Chart.drawMarkers(Chart.java:732)
        at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:271)
        at android.view.View.draw(View.java:16217)
        at android.view.View.updateDisplayListIfDirty(View.java:15214)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3596)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3576)
        at android.view.View.updateDisplayListIfDirty(View.java:15174)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3596)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3576)
        at android.view.View.updateDisplayListIfDirty(View.java:15174)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3596)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3576)
        at android.view.View.updateDisplayListIfDirty(View.java:15174)
        at android.view.View.draw(View.java:15987)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
        at android.view.View.draw(View.java:16220)
        at android.widget.ScrollView.draw(ScrollView.java:1712)
        at android.view.View.updateDisplayListIfDirty(View.java:15214)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3596)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3576)
        at android.view.View.updateDisplayListIfDirty(View.java:15174)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3596)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3576)
        at android.view.View.updateDisplayListIfDirty(View.java:15174)
        at android.view.View.draw(View.java:15987)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
        at android.support.constraint.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1966)
        at android.view.View.draw(View.java:16220)
        at android.view.View.updateDisplayListIfDirty(View.java:15214)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3596)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3576)
        at android.view.View.updateDisplayListIfDirty(View.java:15174)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3596)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3576)
        at android.view.View.updateDisplayListIfDirty(View.java:15174)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3596)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3576)
        at android.view.View.updateDisplayListIfDirty(View.java:15174)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:283)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:289)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:324)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2651)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2470)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2103)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1139)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6064)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
        at android.view.Choreographer.doCallbacks(Choreographer.java:672)
        at android.view.Choreographer.doFrame(Choreographer.java:608)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
        at android.os.Handler.handleCallback(Handler.java:742)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5653)
        at java.lang.reflect.Method.invoke(Native Method)
    	at com.android.internal.os.

**Comment by natykn** [comment]
this answer worked for me https://github.com/PhilJay/MPAndroidChart/pull/3145#issuecomment-307109432

**Comment by alejouribesanchez** [comment]
> this answer worked for me [#3145 (comment)](https://github.com/PhilJay/MPAndroidChart/pull/3145#issuecomment-307109432)

That answer also worked for me
