### ISSUE TITLE
Get Null Pointer In While I Use In Kotlin

### ISSUE THREAD

**Issue by pankajjangid** [PhilJay/MPAndroidChart#4165]
tvContent.text = "x: " + xAxisValueFormatter.getFormattedValue(e!!.x, null) + ", y: " + format.format(e.y.toDouble())

Getting Error 

System.err: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter axis
        at com.android.smarthomesolutions.ui.activity.MarketTrendDetailActivity$CategoryBarChartXaxisFormatter.getFormattedValue(MarketTrendDetailActivity.kt)
        at com.android.smarthomesolutions.chart_custom.XYMarkerView.refreshContent(XYMarkerView.kt:38)
        at com.github.mikephil.charting.charts.CombinedChart.drawMarkers(CombinedChart.java:265)
        at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:271)
        at android.view.View.draw(View.java:17083)
        at android.view.View.updateDisplayListIfDirty(View.java:16065)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3752)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3732)
        at android.view.View.updateDisplayListIfDirty(View.java:16028)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3752)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3732)
        at android.view.View.updateDisplayListIfDirty(View.java:16028)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3752)
07-26 15:11:33.609 5322-5322/com.android.smarthomesolutions W/System.err:     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3732)
        at android.view.View.updateDisplayListIfDirty(View.java:16028)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3752)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3732)
        at android.view.View.updateDisplayListIfDirty(View.java:16028)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3752)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3732)
        at android.view.View.updateDisplayListIfDirty(View.java:16028)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3752)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3732)
        at android.view.View.updateDisplayListIfDirty(View.java:16028)
07-26 15:11:33.610 5322-5322/com.android.smarthomesolutions W/System.err:     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3752)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3732)
        at android.view.View.updateDisplayListIfDirty(View.java:16028)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3752)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3732)
        at android.view.View.updateDisplayListIfDirty(View.java:16028)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:657)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:663)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:771)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2808)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2616)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2223)
07-26 15:11:33.611 5322-5322/com.android.smarthomesolutions W/System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1258)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6348)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
        at android.view.Choreographer.doCallbacks(Choreographer.java:683)
        at android.view.Choreographer.doFrame(Choreographer.java:619)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by almic** [comment]
sorry but this issue tracker is not the place to ask for programming help. Questions like this belong on stackoverflow.

Closing old issue. If anyone still has this question please open a new one.
