### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by KORuL** [PhilJay/MPAndroidChart#4177]
I got this error when i try add different data in async 

E/Graphics: Async
    java.lang.NullPointerException: Attempt to invoke virtual method 'int com.github.mikephil.charting.data.BarData.getDataSetCount()' on a null object reference
        at com.github.mikephil.charting.renderer.BarChartRenderer.initBuffers(BarChartRenderer.java:61)
        at com.github.mikephil.charting.renderer.CombinedChartRenderer.initBuffers(CombinedChartRenderer.java:82)
        at com.github.mikephil.charting.charts.BarLineChartBase.notifyDataSetChanged(BarLineChartBase.java:326)
        at com.github.mikephil.charting.charts.Chart.setData(Chart.java:304)
        at com.github.mikephil.charting.charts.CombinedChart.setData(CombinedChart.java:94)
        at ru.hintsolutions.diabets.menu.graphics.GraphicsFragment$showAllGraphContentAsyncTask.doInBackground(GraphicsFragment.kt:843)
        at ru.hintsolutions.diabets.menu.graphics.GraphicsFragment$showAllGraphContentAsyncTask.doInBackground(GraphicsFragment.kt:600)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
E/UncaughtException: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.github.mikephil.charting.data.BarData.getDataSetCount()' on a null object reference
        at com.github.mikephil.charting.renderer.BarChartRenderer.drawData(BarChartRenderer.java:75)
        at com.github.mikephil.charting.renderer.CombinedChartRenderer.drawData(CombinedChartRenderer.java:89)
        at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:232)
        at android.view.View.draw(View.java:16532)
        at android.view.View.updateDisplayListIfDirty(View.java:15485)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3719)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3699)
        at android.view.View.updateDisplayListIfDirty(View.java:15436)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3719)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3699)
        at android.view.View.updateDisplayListIfDirty(View.java:15436)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3719)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3699)
        at android.view.View.updateDisplayListIfDirty(View.java:15436)
        at android.view.View.draw(View.java:16286)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
        at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1366)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
        at android.view.View.draw(View.java:16544)
        at android.view.View.updateDisplayListIfDirty(View.java:15485)
        at android.view.View.draw(View.java:16286)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
        at android.view.View.updateDisplayListIfDirty(View.java:15477)
        at android.view.View.draw(View.java:16286)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
        at android.view.View.updateDisplayListIfDirty(View.java:15477)
        at android.view.View.draw(View.java:16286)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
        at android.view.View.updateDisplayListIfDirty(View.java:15477)
        at android.view.View.draw(View.java:16286)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
        at android.view.View.updateDisplayListIfDirty(View.java:15477)
        at android.view.View.draw(View.java:16286)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
        at com.android.internal.policy.PhoneWindow$DecorView.dispatchDraw(PhoneWindow.java:2825)
        at android.view.View.draw(View.java:16544)
        at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2806)
        at android.view.View.updateDisplayListIfDirty(View.java:15485)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:286)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:292)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:327)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3036)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2840)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2449)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1335)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6804)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:894)
        at android.view.Choreographer.doCallbacks(Choreographer.java:696)
        at android.view.Choreographer.doFrame(Choreographer.java:631)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5896)
        at java.lang.reflect.Method.invoke(Native Method)
    	at com.android.internal.os.ZygoteInit$Meth
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ru.hintsolutions.diabets, PID: 23553
    java.lang.NullPointerException: Attempt to invoke virtual method 'int com.github.mikephil.charting.data.BarData.getDataSetCount()' on a null object reference
        at com.github.mikephil.charting.renderer.BarChartRenderer.drawData(BarChartRenderer.java:75)
        at com.github.mikephil.charting.renderer.CombinedChartRenderer.drawData(CombinedChartRenderer.java:89)
        at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:232)
        at android.view.View.draw(View.java:16532)
        at android.view.View.updateDisplayListIfDirty(View.java:15485)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3719)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3699)
        at android.view.View.updateDisplayListIfDirty(View.java:15436)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3719)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3699)
        at android.view.View.updateDisplayListIfDirty(View.java:15436)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3719)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3699)
        at android.view.View.updateDisplayListIfDirty(View.java:15436)
        at android.view.View.draw(View.java:16286)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
        at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1366)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
        at android.view.View.draw(View.java:16544)
        at android.view.View.updateDisplayListIfDirty(View.java:15485)
        at android.view.View.draw(View.java:16286)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
        at android.view.View.updateDisplayListIfDirty(View.java:15477)
        at android.view.View.draw(View.java:16286)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
        at android.view.View.updateDisplayListIfDirty(View.java:15477)
        at android.view.View.draw(View.java:16286)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
        at android.view.View.updateDisplayListIfDirty(View.java:15477)
        at android.view.View.draw(View.java:16286)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
        at android.view.View.updateDisplayListIfDirty(View.java:15477)
        at android.view.View.draw(View.java:16286)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
        at com.android.internal.policy.PhoneWindow$DecorView.dispatchDraw(PhoneWindow.java:2825)
        at android.view.View.draw(View.java:16544)
        at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2806)
        at android.view.View.updateDisplayListIfDirty(View.java:15485)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:286)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:292)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:327)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3036)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2840)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2449)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1335)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6804)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:894)
        at android.view.Choreographer.doCallbacks(Choreographer.java:696)
        at android.view.Choreographer.doFrame(Choreographer.java:631)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5896)
    	at java.lang.reflect.Method.i
I/Process: Sending signal. PID: 23553 SIG: 9
Disconnected from the target VM, address: 'localhost:8610', transport: 'socket'

**Comment by almic** [comment]
This should be a problem on your end, as the chart object is going `null` before the chart can render, so you need to make sure the chart isn't being destroyed or passed as null before you set it.
