### ISSUE TITLE
App Crash 

### ISSUE THREAD

**Issue by HashWaney** [PhilJay/MPAndroidChart#4185]
me: FATAL EXCEPTION: main
                  Process: com.xxmassdeveloper.mpchartexample, PID: 16192
                  java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
                      at java.util.ArrayList.get(ArrayList.java:411)
                      at com.github.mikephil.charting.data.DataSet.getEntryForIndex(DataSet.java:294)
                      at com.github.mikephil.charting.utils.Transformer.generateTransformedValuesLine(Transformer.java:184)
                      at com.github.mikephil.charting.renderer.LineChartRenderer.drawValues(LineChartRenderer.java:549)
                      at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:278)
                      at android.view.View.draw(View.java:17256)
                      at android.view.View.updateDisplayListIfDirty(View.java:16221)
                      at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3758)
                      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3738)
                      at android.view.View.updateDisplayListIfDirty(View.java:16184)
                      at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3758)
                      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3738)
                      at android.view.View.updateDisplayListIfDirty(View.java:16184)
                      at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3758)
                      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3738)
                      at android.view.View.updateDisplayListIfDirty(View.java:16184)
                      at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3758)
                      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3738)
                      at android.view.View.updateDisplayListIfDirty(View.java:16184)
                      at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:677)
                      at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:683)
                      at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:797)
                      at android.view.ViewRootImpl.draw(ViewRootImpl.java:3000)
                      at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2794)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2382)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1372)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6782)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:933)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:742)
                      at android.view.Choreographer.doFrame(Choreographer.java:674)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:919)
                      at android.os.Handler.handleCallback(Handler.java:761)
                      at android.os.Handler.dispatchMessage(Handler.java:98)
                      at android.os.Looper.loop(Looper.java:156)
                      at android.app.ActivityThread.main(ActivityThread.java:6595)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by anandwana001** [comment]
Could you please also comment your code here?

**Comment by HashWaney** [comment]
Ofcourse，when i choose the Time Chart， i change the progress from 1500 to 0,then app crash

**Comment by TheNetStriker** [comment]
I've got the same error, but with "Invalid index 30, size is 30". My Application displays realtime data with 30 datapoints. The oldest point get's removed and a new one is added. Most of the time it works, but sometimes this crash happens.

**Comment by tahagit** [comment]
If you're using IAxisValueFormatter, just add this code inside that:

       IAxisValueFormatter formatter = new IAxisValueFormatter() {
                    @Override
                    public String getFormattedValue(float value, AxisBase axis) {
                        if (((int) value) < YOURLISTDATA.size()) {
                            return YOURLISTDATA.get((int) value);
                        } else {
                            return "0";
                        }

                    }
                };
