### ISSUE TITLE
 java.lang.ArrayIndexOutOfBoundsException: length=1; index=1

### ISSUE THREAD

**Issue by abandom** [PhilJay/MPAndroidChart#4245]
java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
        at com.github.mikephil.charting.renderer.XAxisRenderer.drawLabels(XAxisRenderer.java:189)
        at com.github.mikephil.charting.renderer.XAxisRenderer.renderAxisLabels(XAxisRenderer.java:129)
        at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:268)
        at android.view.View.draw(View.java:18493)
        at android.view.View.updateDisplayListIfDirty(View.java:17471)
        at android.view.View.draw(View.java:18255)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3946)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3732)
        at android.view.View.updateDisplayListIfDirty(View.java:17466)
        at android.view.View.draw(View.java:18255)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3946)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3732)
        at android.view.View.draw(View.java:18496)
        at android.view.View.updateDisplayListIfDirty(View.java:17471)
        at android.view.View.draw(View.java:18255)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3946)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3732)
        at android.view.View.updateDisplayListIfDirty(View.java:17466)
        at android.view.View.draw(View.java:18255)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3946)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3732)
        at android.view.View.updateDisplayListIfDirty(View.java:17466)
        at android.view.View.draw(View.java:18255)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3946)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3732)
        at android.view.View.updateDisplayListIfDirty(View.java:17466)
        at android.view.View.draw(View.java:18255)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3946)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3732)
        at android.view.View.updateDisplayListIfDirty(View.java:17466)
        at android.view.View.draw(View.java:18255)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3946)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3732)
        at android.view.View.draw(View.java:18496)
        at com.android.internal.policy.DecorView.draw(DecorView.java:975)
        at android.view.View.updateDisplayListIfDirty(View.java:17471)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:713)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:719)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:827)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3187)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2974)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2562)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1553)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7252)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:930)
        at android.view.Choreographer.doCallbacks(Choreographer.java:705)
        at android.view.Choreographer.doFrame(Choreographer.java:640)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:916)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6832)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1543)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1431)

**Comment by almic** [comment]
Should be fixed in the latest commit, until a new release is created you can just use the latest `-SNAPSHOT` version like this

```gradle
dependencies {
    implementation 'com.github.philjay:mpandroidchart:-SNAPSHOT'
}
```
