### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

### ISSUE THREAD

**Issue by RavenGluttonous** [PhilJay/MPAndroidChart#4246]
Hello, when I reset the list in lineChart, when I assign the graph again, the java.lang.IndexOutOfBoundsException: Index: 0, Size: 0 
problem occurs because getEntryForIndex(int index); 
this method is done in the BaseDataSet class. No data size is judged during data processing

**Comment by RavenGluttonous** [comment]
Sorry, I just said that there is a problem. It may be caused by the getEntryForIndex(int index) method in the LineChartRenderer class. The result is java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

**Comment by gonini** [comment]
is same?
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.github.mikephil.charting.data.DataSet.getEntryForIndex(DataSet.java:286)
        at com.github.mikephil.charting.utils.Transformer.generateTransformedValuesLine(Transformer.java:184)
        at com.github.mikephil.charting.renderer.LineChartRenderer.drawValues(LineChartRenderer.java:547)
        at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:264)
        at android.view.View.draw(View.java:19123)
        at android.view.View.updateDisplayListIfDirty(View.java:18073)
        at android.view.View.draw(View.java:18851)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4214)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4000)
        at android.view.View.updateDisplayListIfDirty(View.java:18064)
        at android.view.View.draw(View.java:18851)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4214)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4000)
        at android.view.View.draw(View.java:19126)
        at android.widget.ScrollView.draw(ScrollView.java:1739)
        at android.view.View.updateDisplayListIfDirty(View.java:18073)
        at android.view.View.draw(View.java:18851)

**Comment by smworks** [comment]
I'm getting same error as @gonini 
This is because I add my custom LineDataSet with no data. If I don't add my LineDataSet chart is just single color circle. So how else am I supposed to display an empty graph with proper axis formatting but without data?

**Comment by rubinovk** [comment]
Same issue

**Comment by almic** [comment]
Should be fixed in the latest commit, until a new release is created you can just use the latest `-SNAPSHOT` version like this

```gradle
dependencies {
    implementation 'com.github.philjay:mpandroidchart:-SNAPSHOT'
}
```

**Comment by tahagit** [comment]
If you're using IAxisValueFormatter, just add this code inside that:

       IAxisValueFormatter formatter = new IAxisValueFormatter() {
                    @Override
                    public String getFormattedValue(float value, AxisBase axis) {
                        if (((int) value) < YOURLISTDATA.size()) {
                            return YOURLISTDATA.get((int) value);
                        } else {
                            return "0";
                        }

                    }
                };
