### ISSUE TITLE
NullPointerException in PieChartRenderer.drawData

### ISSUE THREAD

**Issue by tererecool** [PhilJay/MPAndroidChart#4261]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isMutable()' on a null object reference
       at android.graphics.Canvas.(Canvas.java:130)
       at com.github.mikephil.charting.renderer.PieChartRenderer.drawData(SourceFile:136)
       at com.github.mikephil.charting.charts.PieChart.onDraw(SourceFile:126)
       at android.view.View.draw(View.java:17320)
       at android.view.View.updateDisplayListIfDirty(View.java:16259)
       at android.view.View.draw(View.java:17070)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3890)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676)
       at android.view.View.draw(View.java:17332)
       at android.view.View.updateDisplayListIfDirty(View.java:16259)
       at android.view.View.draw(View.java:17070)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3890)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676)
       at android.view.View.draw(View.java:17332)
       at android.view.View.updateDisplayListIfDirty(View.java:16259)
       at android.view.View.draw(View.java:17070)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3890)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676)
       at android.view.View.draw(View.java:17332)
       at android.view.View.updateDisplayListIfDirty(View.java:16259)
       at android.view.View.draw(View.java:17070)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3890)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676)
       at android.view.View.draw(View.java:17332)
       at android.view.View.updateDisplayListIfDirty(View.java:16259)
       at android.view.View.draw(View.java:17070)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3890)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676)
       at android.view.View.draw(View.java:17332)
       at android.support.v4.widget.NestedScrollView.draw(SourceFile:1819)
       at android.view.View.updateDisplayListIfDirty(View.java:16259)
       at android.view.View.draw(View.java:17070)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3890)
       at android.support.design.widget.CoordinatorLayout.drawChild(SourceFile:1254)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676)
       at android.view.View.updateDisplayListIfDirty(View.java:16251)
       at android.view.View.draw(View.java:17070)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3890)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676)
       at android.view.View.draw(View.java:17332)
       at android.view.View.updateDisplayListIfDirty(View.java:16259)
       at android.view.View.draw(View.java:17070)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3890)
       at android.support.v4.widget.DrawerLayout.drawChild(SourceFile:1366)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676)
       at android.view.View.draw(View.java:17332)
       at android.view.View.updateDisplayListIfDirty(View.java:16259)
       at android.view.View.draw(View.java:17070)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3890)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676)
       at android.view.View.updateDisplayListIfDirty(View.java:16251)
       at android.view.View.draw(View.java:17070)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3890)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676)
       at android.view.View.updateDisplayListIfDirty(View.java:16251)
       at android.view.View.draw(View.java:17070)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3890)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676)
       at android.view.View.updateDisplayListIfDirty(View.java:16251)
       at android.view.View.draw(View.java:17070)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3890)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676)
       at android.view.View.draw(View.java:17332)
       at android.view.View.updateDisplayListIfDirty(View.java:16259)
       at android.view.View.draw(View.java:17070)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3890)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676)
       at com.android.internal.policy.DecorView.dispatchDraw(DecorView.java:924)
       at android.view.View.draw(View.java:17332)
       at com.android.internal.policy.DecorView.draw(DecorView.java:910)
       at android.view.View.updateDisplayListIfDirty(View.java:16259)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:661)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:667)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:775)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:3188)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2981)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2569)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1462)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6965)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:907)
       at android.view.Choreographer.doCallbacks(Choreographer.java:709)
       at android.view.Choreographer.doFrame(Choreographer.java:644)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:893)
       at android.os.Handler.handleCallback(Handler.java:836)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6280)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

Seen on Android 7. 
Maybe the weekReference gets cleared before accessing it? It would be strange, but what else?

```
if (mDrawBitmap == null
                || (mDrawBitmap.get().getWidth() != width)
                || (mDrawBitmap.get().getHeight() != height)) {

            if (width > 0 && height > 0) {

                mDrawBitmap = new WeakReference<Bitmap>(Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_4444));
                mBitmapCanvas = new Canvas(mDrawBitmap.get());
            } else
                return;
        }
```

**Comment by almic** [comment]
Should be fixed in the latest commit, until a new release is created you can just use the latest `-SNAPSHOT` version like this

```gradle
dependencies {
    implementation 'com.github.philjay:mpandroidchart:-SNAPSHOT'
}
```
