### ISSUE TITLE
Null Pointer When Adding Colors Within Fragment

### ISSUE THREAD

**Issue by troy21688** [PhilJay/MPAndroidChart#4271]
I have a Fragment and I am calling the below methods:

        barColors.add(ContextCompat.getColor(getActivity().getApplicationContext(),R.color.bar_one));
        barColors.add(ContextCompat.getColor(getActivity().getApplicationContext(), R.color.bar_two));
        barColors.add(ContextCompat.getColor(getActivity().getApplicationContext(), R.color.bar_three));
        barColors.add(ContextCompat.getColor(getActivity().getApplicationContext(), R.color.bar_four));
        barColors.add(ContextCompat.getColor(getActivity().getApplicationContext(), R.color.bar_five));

Every once in a while I am receiving the below error, and I am unsure why:

`    java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.ContextWrapper.getApplicationContext()' on a null object reference
        at com.troychuinard.livevotingudacity.Fragment.PollFragment.updatePollResultAnswersDynamically(PollFragment.java:355)
        at com.troychuinard.livevotingudacity.Fragment.PollFragment.access$1300(PollFragment.java:63)
        at com.troychuinard.livevotingudacity.Fragment.PollFragment$3.onDataChange(PollFragment.java:304)
        at com.google.firebase.database.obfuscated.zzap.zza(com.google.firebase:firebase-database@@16.0.2:75)
        at com.google.firebase.database.obfuscated.zzca.zza(com.google.firebase:firebase-database@@16.0.2:63)
        at com.google.firebase.database.obfuscated.zzcd$1.run(com.google.firebase:firebase-database@@16.0.2:55)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

**Comment by almic** [comment]
@troy21688 sorry but this issue tracker is not the place to ask for programming help. Questions like this belong on stackoverflow.
