### ISSUE TITLE
java.lang.NegativeArraySizeException: -1360

### ISSUE THREAD

**Issue by boatt** [PhilJay/MPAndroidChart#4290]
java.lang.NegativeArraySizeException: -1360
    at com.github.mikephil.charting.utils.Transformer.generateTransformedValuesCandle(Transformer.java:197)
    at com.github.mikephil.charting.renderer.CandleStickChartRenderer.drawValues(CandleStickChartRenderer.java:366)
    at com.github.mikephil.charting.renderer.CombinedChartRenderer.drawValues(CombinedChartRenderer.java:96)
    at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:286)
    at android.view.View.draw(View.java:19314)
    at android.view.View.updateDisplayListIfDirty(View.java:18250)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4252)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4232)
    at android.view.View.updateDisplayListIfDirty(View.java:18209)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4252)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4232)
    at android.view.View.updateDisplayListIfDirty(View.java:18209)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4252)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4232)
    at android.view.View.updateDisplayListIfDirty(View.java:18209)

**Comment by almic** [comment]
Please follow the instructions in the templates. I cannot help you if you don't actually explain what is happening and what should happen.
