### ISSUE TITLE
    java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference

### ISSUE THREAD

**Issue by Hellogark** [PhilJay/MPAndroidChart#4335]
I have tried like 3-4 tutorials of how to draw a line chart, i can drag a horizontal bar chart, the line chart code is similar as bar chart one except for valueformatter. Once i got the line chart get drawn but not anymore.
here is the error log 
`I/Choreographer: Skipped 102 frames!  The application may be doing too much work on its main thread.
E/libEGL: call to OpenGL ES API with no current context (logged once per thread)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.edmol.webview, PID: 15983
    java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
        at android.view.GLES20Canvas.drawText(GLES20Canvas.java:928)
        at com.github.mikephil.charting.renderer.DataRenderer.drawValue(DataRenderer.java:152)
        at com.github.mikephil.charting.renderer.LineChartRenderer.drawValues(LineChartRenderer.java:569)
        at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:278)
        at android.view.View.draw(View.java:16202)
        at android.view.View.updateDisplayListIfDirty(View.java:15122)
        at android.view.View.getDisplayList(View.java:15145)
        at android.view.View.draw(View.java:15923)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
        at android.view.View.updateDisplayListIfDirty(View.java:15117)
        at android.view.View.getDisplayList(View.java:15145)
        at android.view.View.draw(View.java:15923)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
        at android.view.View.updateDisplayListIfDirty(View.java:15117)
        at android.view.View.getDisplayList(View.java:15145)
        at android.view.View.draw(View.java:15923)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
        at android.view.View.updateDisplayListIfDirty(View.java:15117)
        at android.view.View.getDisplayList(View.java:15145)
        at android.view.View.draw(View.java:15923)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
        at android.view.View.draw(View.java:16205)
        at android.widget.FrameLayout.draw(FrameLayout.java:592)
        at android.widget.ScrollView.draw(ScrollView.java:2486)
        at android.view.View.updateDisplayListIfDirty(View.java:15122)
        at android.view.View.getDisplayList(View.java:15145)
        at android.view.View.draw(View.java:15923)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
        at android.support.constraint.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2023)
        at android.view.View.updateDisplayListIfDirty(View.java:15117)
        at android.view.View.getDisplayList(View.java:15145)
        at android.view.View.draw(View.java:15923)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
        at android.view.View.updateDisplayListIfDirty(View.java:15117)
        at android.view.View.getDisplayList(View.java:15145)
        at android.view.View.draw(View.java:15923)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
        at android.view.View.updateDisplayListIfDirty(View.java:15117)
        at android.view.View.getDisplayList(View.java:15145)
        at android.view.View.draw(View.java:15923)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
        at android.view.View.updateDisplayListIfDirty(View.java:15117)
        at android.view.View.getDisplayList(View.java:15145)
        at android.view.View.draw(View.java:15923)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
        at android.view.View.updateDisplayListIfDirty(View.java:15117)
        at android.view.View.getDisplayList(View.java:15145)
        at android.view.View.draw(View.java:15923)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
        at android.view.View.draw(View.java:16205)
        at android.widget.FrameLayout.draw(FrameLayout.java:592)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2923)
        at android.view.View.updateDisplayListIfDirty(View.java:15122)
        at android.view.View.getDisplayList(View.java:15145)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:275)
    	at android.view.ThreadedRende
I/Process: Sending signal. PID: 15983 SIG: 9
Application terminated.`

OnCreate i'm linking the chart with the chart xml, and then executing the method to generate the chart
`   chart = (LineChart)findViewById(R.id.line);

        grafLinea(chart);`

Here is the lineChart method 
` public void grafLinea(LineChart chart){

            LineDataSet dataSet = new LineDataSet(getDataset(), "Gasto de Agua");

            ArrayList<ILineDataSet> dataSet1 = new ArrayList<>();
            dataSet1.add(dataSet);
            dataSet.setDrawFilled(true);
            dataSet.setHighlightEnabled(true); // allow highlighting for DataSet

            // set this to false to disable the drawing of highlight indicator (lines)
            dataSet.setDrawHighlightIndicators(true);
            dataSet.setHighLightColor(Color.BLACK);
            dataSet.setColors(ColorTemplate.COLORFUL_COLORS);

            Collections.sort(getDataset(), new EntryXComparator());
            LineData lineData = new LineData(dataSet1);
            lineData.setValueFormatter(new EjeX(getEjeXValores()));
            lineData.setValueTextSize(12f);

            chart.setData(lineData);
            chart.animateXY(2000, 2000);
            Description desc = new Description();
            desc.setText("Gasto de agua");
            chart.setDescription(desc);
            chart.setOnChartGestureListener(com.example.edmol.webview.webView.this);
            chart.setOnChartValueSelectedListener(com.example.edmol.webview.webView.this);
            chart.setDragEnabled(true);
            chart.setScaleEnabled(true);
            chart.setPinchZoom(true);
            chart.invalidate();

    }`

getDataset method just add entries to an arraylist<Entry> and return the entries.

**Comment by Hellogark** [comment]
Well, it seems that `lineData.setValueFormatter(new EjeX(getEjeXValores()));` was the problem, used 
this ` XAxis axisX = chart.getXAxis();
        axisX.setGranularity(1f);
        axisX.setValueFormatter(formatter);` Instead.

formatter class
` IAxisValueFormatter formatter = new IAxisValueFormatter() {

        @Override
        public String getFormattedValue(float value, AxisBase axis) {
            return meses[(int) value];
        }

        // we don't draw numbers, so no decimal digits needed

        public int getDecimalDigits() {  return 0; }
    };`
