### ISSUE TITLE
BarDataSet ArithmeticException divide by zero in getColor

### ISSUE THREAD

**Issue by felipecastilhos** [PhilJay/MPAndroidChart#4367]
I'm getting this error when my chart try to get color. I think its better if the chart to handle this kind of error instead to delegate to me to always send any color in the array. Its not fail proof. I can help with this issue if its needed. Here is my stacktrace:

```
Fatal Exception: java.lang.ArithmeticException: divide by zero
       at com.github.mikephil.charting.data.BaseDataSet.getColor(BaseDataSet.java:144)
       at com.github.mikephil.charting.renderer.BarChartRenderer.drawDataSet(BarChartRenderer.java:163)
       at com.github.mikephil.charting.renderer.BarChartRenderer.drawData(BarChartRenderer.java:80)
       at com.github.mikephil.charting.renderer.CombinedChartRenderer.drawData(CombinedChartRenderer.java:89)
       at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:231)
       at android.view.View.draw(View.java:20229)
       at android.view.View.updateDisplayListIfDirty(View.java:19104)
       at android.view.View.draw(View.java:19957)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
       at android.view.View.updateDisplayListIfDirty(View.java:19095)
       at android.view.View.draw(View.java:19957)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
       at android.view.View.updateDisplayListIfDirty(View.java:19095)
       at android.view.View.draw(View.java:19957)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
       at android.view.View.draw(View.java:20232)
       at android.view.View.updateDisplayListIfDirty(View.java:19104)
       at android.view.View.draw(View.java:19957)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
       at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:4820)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
       at android.view.View.draw(View.java:20232)
       at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4219)
       at android.view.View.updateDisplayListIfDirty(View.java:19104)
       at android.view.View.draw(View.java:19957)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
       at android.view.View.draw(View.java:20232)
       at android.view.View.updateDisplayListIfDirty(View.java:19104)
       at android.view.View.draw(View.java:19957)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
       at android.view.View.draw(View.java:20232)
       at android.view.View.updateDisplayListIfDirty(View.java:19104)
       at android.view.View.draw(View.java:19957)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
       at android.view.View.draw(View.java:20232)
       at android.view.View.updateDisplayListIfDirty(View.java:19104)
       at android.view.View.draw(View.java:19957)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1246)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
       at android.view.View.updateDisplayListIfDirty(View.java:19095)
       at android.view.View.draw(View.java:19957)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
       at android.view.View.updateDisplayListIfDirty(View.java:19095)
       at android.view.View.draw(View.java:19957)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
       at android.view.View.updateDisplayListIfDirty(View.java:19095)
       at android.view.View.draw(View.java:19957)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
       at android.view.View.updateDisplayListIfDirty(View.java:19095)
       at android.view.View.draw(View.java:19957)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
       at android.view.View.updateDisplayListIfDirty(View.java:19095)
       at android.view.View.draw(View.java:19957)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
       at android.view.View.draw(View.java:20232)
       at com.android.internal.policy.DecorView.draw(DecorView.java:791)
       at android.view.View.updateDisplayListIfDirty(View.java:19104)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:3323)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3120)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2489)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1464)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7220)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1004)
       at android.view.Choreographer.doCallbacks(Choreographer.java:816)
       at android.view.Choreographer.doFrame(Choreographer.java:751)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:990)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:198)
       at android.app.ActivityThread.main(ActivityThread.java:6732)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by cagneymoreau** [comment]
i too deployed an app that allowed dataset.getcolor() to be zero. 
agree this should be fixed in library
