### ISSUE TITLE
IndexOutOfBoundsExeption

### ISSUE THREAD

**Issue by Kwangjin-Lee** [PhilJay/MPAndroidChart#4381]
I am using v3.0.3 and I found an exception.

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:411)
	at com.github.mikephil.charting.data.DataSet.getEntryForIndex(Unknown Source)
	at com.github.mikephil.charting.utils.Transformer.generateTransformedValuesLine(Unknown Source)
	at com.github.mikephil.charting.renderer.LineChartRenderer.drawValues(Unknown Source)
	at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(Unknown Source)
	at android.view.View.draw(View.java:17083)
	at android.view.View.updateDisplayListIfDirty(View.java:16065)
	at android.view.View.draw(View.java:16849)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3768)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3554)
	at android.view.View.updateDisplayListIfDirty(View.java:16060)
	at android.view.View.draw(View.java:16849)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3768)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3554)
......

**Comment by tahagit** [comment]
If you are using IAxisValueFormatter just add this code inside that:
         IAxisValueFormatter formatter = new IAxisValueFormatter() {
                    @Override
                    public String getFormattedValue(float value, AxisBase axis) {
                        if (((int) value) < YOURLISTDATA.size()) {
                            return YOURLISTDATA.get((int) value);
                        } else {
                            return "0";
                        }

                    }
                };

> I am using v3.0.3 and I found an exception.
> 
> java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
> at java.util.ArrayList.get(ArrayList.java:411)
> at com.github.mikephil.charting.data.DataSet.getEntryForIndex(Unknown Source)
> at com.github.mikephil.charting.utils.Transformer.generateTransformedValuesLine(Unknown Source)
> at com.github.mikephil.charting.renderer.LineChartRenderer.drawValues(Unknown Source)
> at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(Unknown Source)
> at android.view.View.draw(View.java:17083)
> at android.view.View.updateDisplayListIfDirty(View.java:16065)
> at android.view.View.draw(View.java:16849)
> at android.view.ViewGroup.drawChild(ViewGroup.java:3768)
> at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3554)
> at android.view.View.updateDisplayListIfDirty(View.java:16060)
> at android.view.View.draw(View.java:16849)
> at android.view.ViewGroup.drawChild(ViewGroup.java:3768)
> at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3554)
> ......

**Comment by tahagit** [comment]
> I am using v3.0.3 and I found an exception.
> 
> java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
> at java.util.ArrayList.get(ArrayList.java:411)
> at com.github.mikephil.charting.data.DataSet.getEntryForIndex(Unknown Source)
> at com.github.mikephil.charting.utils.Transformer.generateTransformedValuesLine(Unknown Source)
> at com.github.mikephil.charting.renderer.LineChartRenderer.drawValues(Unknown Source)
> at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(Unknown Source)
> at android.view.View.draw(View.java:17083)
> at android.view.View.updateDisplayListIfDirty(View.java:16065)
> at android.view.View.draw(View.java:16849)
> at android.view.ViewGroup.drawChild(ViewGroup.java:3768)
> at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3554)
> at android.view.View.updateDisplayListIfDirty(View.java:16060)
> at android.view.View.draw(View.java:16849)
> at android.view.ViewGroup.drawChild(ViewGroup.java:3768)
> at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3554)
> ......


If you are using IAxisValueFormatter just add this code inside that:
  `       IAxisValueFormatter formatter = new IAxisValueFormatter() {
                    @Override
                    public String getFormattedValue(float value, AxisBase axis) {
                        if (((int) value) < YOURLISTDATA.size()) {
                            return YOURLISTDATA.get((int) value);
                        } else {
                            return "0";
                        }

                    }
                };`

**Comment by tahagit** [comment]
If you're using IAxisValueFormatter, just add this code inside that:
`
       IAxisValueFormatter formatter = new IAxisValueFormatter() {
                    @Override
                    public String getFormattedValue(float value, AxisBase axis) {
                        if (((int) value) < YOURLISTDATA.size()) {
                            return YOURLISTDATA.get((int) value);
                        } else {
                            return "0";
                        }

                    }
                };
`

**Comment by tahagit** [comment]
> I am using v3.0.3 and I found an exception.
> 
> java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
> at java.util.ArrayList.get(ArrayList.java:411)
> at com.github.mikephil.charting.data.DataSet.getEntryForIndex(Unknown Source)
> at com.github.mikephil.charting.utils.Transformer.generateTransformedValuesLine(Unknown Source)
> at com.github.mikephil.charting.renderer.LineChartRenderer.drawValues(Unknown Source)
> at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(Unknown Source)
> at android.view.View.draw(View.java:17083)
> at android.view.View.updateDisplayListIfDirty(View.java:16065)
> at android.view.View.draw(View.java:16849)
> at android.view.ViewGroup.drawChild(ViewGroup.java:3768)
> at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3554)
> at android.view.View.updateDisplayListIfDirty(View.java:16060)
> at android.view.View.draw(View.java:16849)
> at android.view.ViewGroup.drawChild(ViewGroup.java:3768)
> at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3554)
> ......

If you're using IAxisValueFormatter, just add this code inside that:

       IAxisValueFormatter formatter = new IAxisValueFormatter() {
                    @Override
                    public String getFormattedValue(float value, AxisBase axis) {
                        if (((int) value) < YOURLISTDATA.size()) {
                            return YOURLISTDATA.get((int) value);
                        } else {
                            return "0";
                        }

                    }
                };

**Comment by Kwangjin-Lee** [comment]
@tahagit I'm not using IAxisValueFormatter.
