### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by tianshaokai** [PhilJay/MPAndroidChart#4471]
04-01 15:46:38.081 14003-14003/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xxmassdeveloper.mpchartexample, PID: 14003
    java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
        at java.util.ArrayList.get(ArrayList.java:308)
        at com.github.mikephil.charting.data.DataSet.getEntryForIndex(DataSet.java:294)
        at com.github.mikephil.charting.renderer.CandleStickChartRenderer.drawDataSet(CandleStickChartRenderer.java:73)
        at com.github.mikephil.charting.renderer.CandleStickChartRenderer.drawData(CandleStickChartRenderer.java:52)
        at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:237)
        at android.view.View.draw(View.java:15261)
        at android.view.View.updateDisplayListIfDirty(View.java:14197)
        at android.view.View.getDisplayList(View.java:14219)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3392)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3371)
        at android.view.View.updateDisplayListIfDirty(View.java:14157)
        at android.view.View.getDisplayList(View.java:14219)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3392)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3371)
        at android.view.View.updateDisplayListIfDirty(View.java:14157)
        at android.view.View.getDisplayList(View.java:14219)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3392)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3371)
        at android.view.View.updateDisplayListIfDirty(View.java:14157)
        at android.view.View.getDisplayList(View.java:14219)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3392)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3371)
        at android.view.View.updateDisplayListIfDirty(View.java:14157)
        at android.view.View.getDisplayList(View.java:14219)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3392)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3371)
        at android.view.View.updateDisplayListIfDirty(View.java:14157)
        at android.view.View.getDisplayList(View.java:14219)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3392)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3371)
        at android.view.View.updateDisplayListIfDirty(View.java:14157)
        at android.view.View.getDisplayList(View.java:14219)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:273)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:279)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:314)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2583)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2396)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2026)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1104)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5962)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:794)
        at android.view.Choreographer.doCallbacks(Choreographer.java:607)
        at android.view.Choreographer.doFrame(Choreographer.java:577)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:780)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5315)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
04-01 15:46:38.101 2416-4942/? W/ActivityManager:   Force finishing activity 1 com.xxmassdeveloper.mpchartexample/.CandleStickChartActivity

**Comment by erfinbadrian** [comment]
+1 i got this problem also

**Comment by 512guanguan** [comment]
Similar problem has been bugging me for months!
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.get(ArrayList.java:437)
at com.github.mikephil.charting.data.DataSet.getEntryForIndex(DataSet.java:286)
at com.github.mikephil.charting.utils.Transformer.generateTransformedValuesLine(Transformer.java:184)
at com.github.mikephil.charting.renderer.LineChartRenderer.drawValues(LineChartRenderer.java:547)
at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:263)
at android.view.View.draw(View.java:21651)
at android.view.View.updateDisplayListIfDirty(View.java:20511)
at android.view.View.draw(View.java:21378)
at android.view.ViewGroup.drawChild(ViewGroup.java:4605)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4364)
at android.view.View.updateDisplayListIfDirty(View.java:20502)
at android.view.View.draw(View.java:21378)
at android.view.ViewGroup.drawChild(ViewGroup.java:4605)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4364)
at android.view.View.updateDisplayListIfDirty(View.java:20502)
at android.view.View.draw(View.java:21378)
at android.view.ViewGroup.drawChild(ViewGroup.java:4605)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4364)
at android.view.View.draw(View.java:21654)
at android.view.View.updateDisplayListIfDirty(View.java:20511)
at android.view.View.draw(View.java:21378)
at android.view.ViewGroup.drawChild(ViewGroup.java:4605)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4364)
at android.view.View.draw(View.java:21654)
at androidx.viewpager.widget.ViewPager.draw(ViewPager.java:2426)
at android.view.View.updateDisplayListIfDirty(View.java:20511)
at android.view.View.draw(View.java:21378)
at android.view.ViewGroup.drawChild(ViewGroup.java:4605)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4364)
at android.view.View.draw(View.java:21654)
at android.view.View.updateDisplayListIfDirty(View.java:20511)
at android.view.View.draw(View.java:21378)
at android.view.ViewGroup.drawChild(ViewGroup.java:4605)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4364)
at android.view.View.draw(View.java:21654)
at android.view.View.updateDisplayListIfDirty(View.java:20511)
at android.view.View.draw(View.java:21378)
at android.view.ViewGroup.drawChild(ViewGroup.java:4605)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4364)
at android.view.View.updateDisplayListIfDirty(View.java:20502)
at android.view.View.draw(View.java:21378)
at android.view.ViewGroup.drawChild(ViewGroup.java:4605)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4364)
at android.view.View.draw(View.java:21654)
at android.view.View.updateDisplayListIfDirty(View.java:20511)
at android.view.View.draw(View.java:21378)
at android.view.ViewGroup.drawChild(ViewGroup.java:4605)
at android.widget.ListView.drawChild(ListView.java:3736)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4364)
at android.widget.AbsListView.dispatchDraw(AbsListView.java:2798)
at android.widget.ListView.dispatchDraw(ListView.java:3731)
at android.view.View.draw(View.java:21654)
at android.widget.AbsListView.draw(AbsListView.java:4608)
at android.view.View.updateDisplayListIfDirty(View.java:20511)
at android.view.View.draw(View.java:21378)
at android.view.ViewGroup.drawChild(ViewGroup.java:4605)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4364)
at android.view.View.updateDisplayListIfDirty(View.java:20502)
at android.view.View.draw(View.java:21378)
at android.view.ViewGroup.drawChild(ViewGroup.java:4605)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4364)
at android.view.View.draw(View.java:21654)
at android.view.View.updateDisplayListIfDirty(View.java:20511)
at android.view.View.draw(View.java:21378)
at android.view.ViewGroup.drawChild(ViewGroup.java:4605)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4364)
at android.view.View.updateDisplayListIfDirty(View.java:20502)
at android.view.View.draw(View.java:21378)
at android.view.ViewGroup.drawChild(ViewGroup.java:4605)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4364)
at android.view.View.updateDisplayListIfDirty(View.java:20502)
at android.view.View.draw(View.java:21378)
at android.view.ViewGroup.drawChild(ViewGroup.java:4605)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4364)
at android.view.View.draw(View.java:21654)
at com.android.internal.policy.DecorView.draw(DecorView.java:1005)
at android.view.View.updateDisplayListIfDirty(View.java:20511)
at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:584)
at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:590)
at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:668)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:3892)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3700)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2989)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1876)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8167)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1057)
at android.view.Choreographer.doCallbacks(Choreographer.java:875)
at android.view.Choreographer.doFrame(Choreographer.java:776)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
at android.os.Handler.handleCallback(Handler.java:900)
at android.os.Handler.dispatchMessage(Handler.java:103)
at android.os.Looper.loop(Looper.java:219)
at android.app.ActivityThread.main(ActivityThread.java:8349)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
