### ISSUE TITLE
version 3.1.0 saveToGallery bug

### ISSUE THREAD

**Issue by zhiwo** [PhilJay/MPAndroidChart#4565]
java.lang.IllegalArgumentException: width and height must be > 0
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1013)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:980)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:930)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:891)
        at com.github.mikephil.charting.charts.Chart.getChartBitmap(Chart.java:1441)
        at com.github.mikephil.charting.charts.Chart.saveToGallery(Chart.java:1549)
        at com.github.mikephil.charting.charts.Chart.saveToGallery(Chart.java:1599)
        at com.rybt.qhsf.EchartActivity$1.onPermissionGranted(EchartActivity.java:116)
        at com.rybt.qhsf.common.MPermissionUtils.requestPermissions(MPermissionUtils.java:52)
        at com.rybt.qhsf.common.MPermissionUtils.requestPermissionsResult(MPermissionUtils.java:23)
        at com.rybt.qhsf.EchartActivity.onButterKnifeChartDownload(EchartActivity.java:111)
        at com.rybt.qhsf.EchartActivity_ViewBinding$1.doClick(EchartActivity_ViewBinding.java:43)
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)

**Comment by FDassatti** [comment]
same here...
