### ISSUE TITLE
NullPointerException occuring only sometimes when using HorizontalBarChart

### ISSUE THREAD

**Issue by reuniware** [PhilJay/MPAndroidChart#4613]
**Summary**
When using HorizontalBarChart, there is a NullPointerException occurring sometimes.

**Expected Behavior**
Expected the chart to be drawn everytime the page is shown. Actually it works one time out of 5 in my code.

**Device (please complete the following information):**
 - Device: Samsung Galaxy A3
 - Android Version 8.0.0 (Knox 3.1, API level 25)
 - Library Version 3.1.0

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.activity.screen, PID: 8271
    java.lang.NullPointerException: Attempt to read from null array
        at com.github.mikephil.charting.renderer.HorizontalBarChartRenderer.drawDataSet(HorizontalBarChartRenderer.java:104)
        at com.github.mikephil.charting.renderer.BarChartRenderer.drawData(BarChartRenderer.java:82)
        at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:237)
        at android.view.View.draw(View.java:20370)
        at android.view.View.updateDisplayListIfDirty(View.java:19315)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
        at android.view.View.updateDisplayListIfDirty(View.java:19274)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
        at android.view.View.updateDisplayListIfDirty(View.java:19274)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
        at android.view.View.updateDisplayListIfDirty(View.java:19274)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
        at android.view.View.updateDisplayListIfDirty(View.java:19274)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
        at android.view.View.updateDisplayListIfDirty(View.java:19274)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
        at android.view.View.updateDisplayListIfDirty(View.java:19274)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:800)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3501)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3288)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2823)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1785)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7832)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)`

**Comment by reuniware** [comment]
My issue is solved. It was due to calls from a Thread. Now I have put the calls outside of any thread and it seems ok ! :)
