### ISSUE TITLE
Caused by: java.lang.NullPointerException: Attempt to read from field 'float com.github.mikephil.charting.components.LegendEntry.formSize' on a null object reference

### ISSUE THREAD

**Issue by jiaoheyan** [PhilJay/MPAndroidChart#4631]
Caused by: java.lang.NullPointerException: Attempt to read from field 'float com.github.mikephil.charting.components.LegendEntry.formSize' on a null object reference
	at com.github.mikephil.charting.components.Legend.getMaximumEntryWidth(Legend.java:249)
	at com.github.mikephil.charting.components.Legend.calculateDimensions(Legend.java:867)
	at com.github.mikephil.charting.renderer.LegendRenderer.computeLegend(LegendRenderer.java:220)
	at com.github.mikephil.charting.charts.BarLineChartBase.notifyDataSetChanged(BarLineChartBase.java:335)
	at com.github.mikephil.charting.charts.Chart.onSizeChanged(Chart.java:1689)
	at com.github.mikephil.charting.charts.BarLineChartBase.onSizeChanged(BarLineChartBase.java:1640)
	at android.view.View.sizeChange(View.java:17975)
	at android.view.View.setFrame(View.java:17937)
	at android.view.View.layout(View.java:17829)
	at android.view.ViewGroup.layout(ViewGroup.java:5754)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1971)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1737)
	at android.view.View.layout(View.java:17838)
	at android.view.ViewGroup.layout(ViewGroup.java:5754)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1735)
	at android.view.View.layout(View.java:17838)
	at android.view.ViewGroup.layout(ViewGroup.java:5754)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1735)
	at android.view.View.layout(View.java:17838)
	at android.view.ViewGroup.layout(ViewGroup.java:5754)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1735)
	at android.view.View.layout(View.java:17838)
	at android.view.ViewGroup.layout(ViewGroup.java:5754)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1735)
	at android.view.View.layout(View.java:17838)
	at android.view.ViewGroup.layout(ViewGroup.java:5754)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
	at android.support.v4.widget.NestedScrollView.onLayout(NestedScrollView.java:1670)
	at android.view.View.layout(View.java:17838)
	at android.view.ViewGroup.layout(ViewGroup.java:5754)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1189)
	at android.view.View.layout(View.java:17838)
	at android.view.ViewGroup.layout(ViewGroup.java:5754)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
	at android.view.View.layout(View.java:17838)
	at android.view.ViewGroup.layout(ViewGroup.java:5754)
	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1172)
	at android.view.View.layout(View.java:17838)
	at android.view.ViewGroup.layout(ViewGroup.java:5754)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1735)
	at android.view.View.layout(View.java:17838)
	at android.view.ViewGroup.layout(ViewGroup.java:5754)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
	at android.view.View.layout(View.java:17838)
	at android.view.ViewGroup.layout(ViewGroup.java:5754)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1735)
	at android.view.View.layout(View.java:17838)
	at android.view.ViewGroup.layout(ViewGroup.java:5754)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
	at android.view.View.layout(View.java:17838)
	at android.view.ViewGroup.layout(ViewGroup.java:5754)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1735)
	at android.view.View.layout(View.java:17838)
	at android.view.ViewGroup.layout(ViewGroup.java:5754)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:751)
	at android.view.View.layout(View.java:17838)
	at android.view.ViewGroup.layout(ViewGroup.java:5754)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2711)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2384)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1462)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6965)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:907)
	at android.view.Choreographer.doCallbacks(Choreographer.java:709)
	at android.view.Choreographer.doFrame(Choreographer.java:644)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:893)
	at android.os.Handler.handleCallback(Handler.java:836)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6251)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
java.lang.NullPointerException: Attempt to read from field 'float com

**Comment by FangWW** [comment]
**user  com.github.mikephil.charting.charts.BubbleChart**


1 com.github.mikephil.charting.components.Legend.float getMaximumEntryWidth(android.graphics.Paint)(Unknown Source:16)
--
2 com.github.mikephil.charting.components.Legend.void calculateDimensions(android.graphics.Paint,com.github.mikephil.charting.utils.ViewPortHandler)(Unknown Source:39)
3 com.github.mikephil.charting.renderer.LegendRenderer.void computeLegend(com.github.mikephil.charting.data.ChartData)(Unknown Source:489)
4 com.github.mikephil.charting.charts.BarLineChartBase.void notifyDataSetChanged()(Unknown Source:99)
5 com.github.mikephil.charting.charts.Chart.void onSizeChanged(int,int,int,int)(Unknown Source:91)
6 com.github.mikephil.charting.charts.BarLineChartBase.void onSizeChanged(int,int,int,int)(Unknown Source:46)

**Comment by 4sskick** [comment]
did it solved? please tell me what's wrong & how to solve it
