### ISSUE TITLE
ArrayIndexOutOfBoundsException in CircleBuffer when using LineChart

### ISSUE THREAD

**Issue by XDex** [PhilJay/MPAndroidChart#464]
Hi! I'm having the following exception when updating data in a LineChart:
```java
03-23 11:59:07.155    2167-2167/com.dekart.android_telemetry E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.dekart.android_telemetry, PID: 2167
    java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
            at com.github.mikephil.charting.buffer.CircleBuffer.addCircle(CircleBuffer.java:15)
            at com.github.mikephil.charting.buffer.CircleBuffer.feed(CircleBuffer.java:27)
            at com.github.mikephil.charting.renderer.LineChartRenderer.drawCircles(LineChartRenderer.java:482)
            at com.github.mikephil.charting.renderer.LineChartRenderer.drawData(LineChartRenderer.java:93)
            at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:202)
            at android.view.View.draw(View.java:14489)
            at android.view.View.getDisplayList(View.java:13386)
            at android.view.View.getDisplayList(View.java:13428)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
            at android.view.View.getDisplayList(View.java:13324)
            at android.view.View.getDisplayList(View.java:13428)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
            at android.view.View.getDisplayList(View.java:13324)
            at android.view.View.getDisplayList(View.java:13428)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
            at android.view.View.getDisplayList(View.java:13324)
            at android.view.View.getDisplayList(View.java:13428)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
            at android.view.View.getDisplayList(View.java:13324)
            at android.view.View.getDisplayList(View.java:13428)
            at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1577)
            at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1451)
            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2377)
            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2249)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1879)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5600)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
            at android.view.Choreographer.doCallbacks(Choreographer.java:574)
            at android.view.Choreographer.doFrame(Choreographer.java:544)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5140)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
            at dalvik.system.NativeStart.main(Native Method)
```
Relevant onCreate() code:
```java
            mChart = (LineChart) findViewById(R.id.line_chart);
            ArrayList<Entry> ch1_vals = new ArrayList<>();

            ch1_vals.add(new Entry(0, mCounterCh1++));

            LineDataSet ch1_set = new LineDataSet(ch1_vals, "Channel 1");

            ArrayList<LineDataSet> dataSets = new ArrayList<>();
            dataSets.add(ch1_set);

            ArrayList<String> xVals = new ArrayList<>();
            xVals.add(new DateTime().toString());
            mLineData = new LineData(xVals, dataSets);
            mChart.setData(mLineData);
            mChart.animateX(1000);
```
Relevant update() code:
```java
        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                mLineData.addXValue(new DateTime().toString());
                mLineData.addEntry(new Entry(ByteBuffer.wrap(ch_1_bytes).getInt(), mCounterCh1++), CH1_DATASET_INDEX);
                mChart.invalidate();
            }
        });
```
Am I doing something wrong here or is it a bug?

**Comment by XDex** [comment]
My bad - I forgot to add a call to notifyDataSetChanged() before calling invalidate().
