### ISSUE TITLE
I am getting  java.lang.NegativeArraySizeException: -20 

### ISSUE THREAD

**Issue by rakesharyais** [PhilJay/MPAndroidChart#4771]
I am passing the data in loop after  every 10 seconds and the graph is ploting correctly for the first 4 times and the 5th time i get  java.lang.NegativeArraySizeException: -20 .
please give you inputs .

below is the stack trace :
Process: com.harman.sleepbuds, PID: 7808
    java.lang.NegativeArraySizeException: -20
        at com.github.mikephil.charting.utils.Transformer.generateTransformedValuesLine(Transformer.java:178)
        at com.github.mikephil.charting.renderer.LineChartRenderer.drawValues(LineChartRenderer.java:549)
        at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:278)
        at android.view.View.draw(View.java:21861)
        at android.view.View.updateDisplayListIfDirty(View.java:20734)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4530)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4502)
        at android.view.View.updateDisplayListIfDirty(View.java:20689)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4530)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4502)
        at android.view.View.updateDisplayListIfDirty(View.java:20689)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4530)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4502)
        at android.view.View.updateDisplayListIfDirty(View.java:20689)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4530)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4502)
        at android.view.View.updateDisplayListIfDirty(View.java:20689)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4530)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4502)
        at android.view.View.updateDisplayListIfDirty(View.java:20689)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4530)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4502)
        at android.view.View.updateDisplayListIfDirty(View.java:20689)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:725)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:731)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:840)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3909)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3683)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2991)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1850)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8455)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6981)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

**Comment by rakesharyais** [comment]
I was not sorting the data before passing it to LineDataSet .
after sorting i am not getting the issue

**Comment by shodow** [comment]
```
List<Entry> entries = ...;
Collections.sort(entries, new EntryXComparator());
```
The reason why this is required is because the library uses binary search algorithms for better performance only working on sorted lists.

**Comment by oneAcorn** [comment]
You might want to take a look at this library [XFree-MPAndroidChart](https://github.com/oneAcorn/XFree-MPAndroidChart) which is based on MPAndroidChart and allows unsorted data
