### ISSUE TITLE
LineChart initialization error

### ISSUE THREAD

**Issue by cdeange** [PhilJay/MPAndroidChart#492]
at com.github.mikephil.charting.charts.BarLineChartBase.getScaleX(BarLineChartBase.java:1071)
	  at android.view.View.setScaleX(View.java:10246)
	  at android.view.View.<init>(View.java:4172)
	  at android.view.ViewGroup.<init>(ViewGroup.java:491)
	  at android.view.ViewGroup.<init>(ViewGroup.java:487)
	  at android.view.ViewGroup.<init>(ViewGroup.java:483)
	  at com.github.mikephil.charting.charts.Chart.<init>(Chart.java:154)
	  at com.github.mikephil.charting.charts.BarLineChartBase.<init>(BarLineChartBase.java:118)
	  at com.github.mikephil.charting.charts.LineChart.<init>(LineChart.java:29)
	  at java.lang.reflect.Constructor.newInstance(Constructor.java:-1)
	  at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
	  at android.view.LayoutInflater.createView(LayoutInflater.java:607)
	  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
	  at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
	  at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
	  at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
	  at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	  at [REDACTED].onCreateView([REDACTED].java:44)

This happens when you have elevation/scale/translation/rotation set as an XML attribute on the LineChart.

**Comment by PhilJay** [comment]
Could you post your xml file?

**Comment by cdeange** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/viewer_root"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

    <com.github.mikephil.charting.charts.LineChart
        android:id="@+id/viewer_graph"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:elevation="8dp"/>

</RelativeLayout>
```

**Comment by PhilJay** [comment]
Did you  provide a background or OutlineProvider that shapes the shadow?

**Comment by cdeange** [comment]
Nope, just specifying the `android:elevation` attribute is enough to make it crash. The View constructor calls `setScaleX`, which in turn calls `getScaleX`, which fails because BarLineChartBase's `mViewPortHandler` hasn't been initialized yet.

**Comment by PhilJay** [comment]
Try providing those things, does it still crash?

**Comment by cdeange** [comment]
It makes no difference (also you can't specify an OutlineProvider in XML, since this crash is happening on layout inflation).
