### ISSUE TITLE
java.lang.OutOfMemory: PieChartRenderer

### ISSUE THREAD

**Issue by gustavocnp95** [PhilJay/MPAndroidChart#4935]
Version: com.github.PhilJay:MPAndroidChart:v3.0.3

We are catching in Firebase the following below. We have no idea why.
We searched in issues if someone was facing the same and we find some people having the same trouble but with the class LineChartRenderer and anothers. 

The exception ocurred on Android 4, API Level 19.

We looked into release 3.1.0, class PieChartRenderer, to try to see if here was any modification that would resolve our problem, but nothing was found. 

Can you help us?

```
Fatal Exception: java.lang.OutOfMemoryError
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:924)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:897)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:864)
       at com.github.mikephil.charting.renderer.PieChartRenderer.drawData(PieChartRenderer.java:135)
       at com.github.mikephil.charting.charts.PieChart.onDraw(PieChart.java:126)
       at android.view.View.draw(View.java:14681)
       at android.view.View.getDisplayList(View.java:13575)
       at android.view.View.getDisplayList(View.java:13617)
       at android.view.View.draw(View.java:14395)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3237)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3074)
       at android.view.View.getDisplayList(View.java:13570)
       at android.view.View.getDisplayList(View.java:13617)
       at android.view.View.draw(View.java:14395)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3237)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3074)
       at android.view.View.getDisplayList(View.java:13570)
       at android.view.View.getDisplayList(View.java:13617)
       at android.view.View.draw(View.java:14395)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3237)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3074)
       at android.view.View.draw(View.java:14684)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at android.view.View.getDisplayList(View.java:13575)
       at android.view.View.getDisplayList(View.java:13617)
       at android.view.View.draw(View.java:14395)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3237)
       at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:4820)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3074)
       at android.view.View.draw(View.java:14684)
       at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4219)
       at android.view.View.getDisplayList(View.java:13575)
       at android.view.View.getDisplayList(View.java:13617)
       at android.view.View.draw(View.java:14395)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3237)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3074)
       at android.view.View.getDisplayList(View.java:13570)
       at android.view.View.getDisplayList(View.java:13617)
       at android.view.View.draw(View.java:14395)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3237)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1246)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3074)
       at android.view.View.getDisplayList(View.java:13570)
       at android.view.View.getDisplayList(View.java:13617)
       at android.view.View.draw(View.java:14395)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3237)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1246)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3074)
       at android.view.View.getDisplayList(View.java:13570)
       at android.view.View.getDisplayList(View.java:13617)
       at android.view.View.draw(View.java:14395)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3237)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3074)
       at android.view.View.getDisplayList(View.java:13570)
       at android.view.View.getDisplayList(View.java:13617)
       at android.view.View.draw(View.java:14395)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3237)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3074)
       at android.view.View.getDisplayList(View.java:13570)
       at android.view.View.getDisplayList(View.java:13617)
       at android.view.View.draw(View.java:14395)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3237)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3074)
       at android.view.View.getDisplayList(View.java:13570)
       at android.view.View.getDisplayList(View.java:13617)
       at android.view.View.draw(View.java:14395)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3237)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1246)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3074)
       at android.view.View.getDisplayList(View.java:13570)
       at android.view.View.getDisplayList(View.java:13617)
       at android.view.View.draw(View.java:14395)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3237)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3074)
       at android.view.View.getDisplayList(View.java:13570)
       at android.view.View.getDisplayList(View.java:13617)
       at android.view.View.draw(View.java:14395)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3237)
       at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1426)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3074)
       at android.view.View.getDisplayList(View.java:13570)
       at android.view.View.getDisplayList(View.java:13617)
       at android.view.View.draw(View.java:14395)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3237)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3074)
       at android.view.View.draw(View.java:14684)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at android.view.View.getDisplayList(View.java:13575)
       at android.view.View.getDisplayList(View.java:13617)
       at android.view.View.draw(View.java:14395)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3237)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3074)
       at android.view.View.getDisplayList(View.java:13570)
       at android.view.View.getDisplayList(View.java:13617)
       at android.view.View.draw(View.java:14395)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3237)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3074)
       at android.view.View.getDisplayList(View.java:13570)
       at android.view.View.getDisplayList(View.java:13617)
       at android.view.View.draw(View.java:14395)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3237)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3074)
       at android.view.View.getDisplayList(View.java:13570)
       at android.view.View.getDisplayList(View.java:13617)
       at android.view.View.draw(View.java:14395)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3237)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3074)
       at android.view.View.draw(View.java:14684)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2474)
       at android.view.View.getDisplayList(View.java:13575)
       at android.view.View.getDisplayList(View.java:13617)
       at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1577)
       at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1451)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2543)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2409)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1998)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1062)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5996)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
       at android.view.Choreographer.doCallbacks(Choreographer.java:574)
       at android.view.Choreographer.doFrame(Choreographer.java:544)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5590)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by Faltenreich** [comment]
The same happens for me with a LineChart on a Samsung Galaxy Note Edge with Android 6.0 (SDK 23).

```
java.lang.OutOfMemoryError: 
  at dalvik.system.VMRuntime.newNonMovableArray (Native Method)
  at android.graphics.Bitmap.nativeCreate (Native Method)
  at android.graphics.Bitmap.createBitmap (Bitmap.java:975)
  at android.graphics.Bitmap.createBitmap (Bitmap.java:946)
  at android.graphics.Bitmap.createBitmap (Bitmap.java:913)
  at com.github.mikephil.charting.renderer.LineChartRenderer.drawData (LineChartRenderer.java:87)
  at com.github.mikephil.charting.renderer.CombinedChartRenderer.drawData (CombinedChartRenderer.java:89)
  at com.github.mikephil.charting.charts.BarLineChartBase.onDraw (BarLineChartBase.java:237)
  at android.view.View.draw (View.java:17469)
  at android.view.View.updateDisplayListIfDirty (View.java:16464)
  at android.view.View.draw (View.java:17238)
  at android.view.ViewGroup.drawChild (ViewGroup.java:3921)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:3711)
  at android.view.View.draw (View.java:17472)
  at android.view.View.updateDisplayListIfDirty (View.java:16464)
  at android.view.View.draw (View.java:17238)
  at android.view.ViewGroup.drawChild (ViewGroup.java:3921)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:3711)
  at android.view.View.updateDisplayListIfDirty (View.java:16459)
  at android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:3905)
  at android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3885)
  at android.view.View.updateDisplayListIfDirty (View.java:16424)
  at android.view.View.draw (View.java:17238)
  at android.view.ViewGroup.drawChild (ViewGroup.java:3921)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:3711)
  at android.view.View.updateDisplayListIfDirty (View.java:16459)
  at android.view.View.draw (View.java:17238)
  at android.view.ViewGroup.drawChild (ViewGroup.java:3921)
  at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild (CoordinatorLayout.java:1277)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:3711)
  at android.view.View.updateDisplayListIfDirty (View.java:16459)
  at android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:3905)
  at android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3885)
  at android.view.View.updateDisplayListIfDirty (View.java:16424)
  at android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:3905)
  at android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3885)
  at android.view.View.updateDisplayListIfDirty (View.java:16424)
  at android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:3905)
  at android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3885)
  at android.view.View.updateDisplayListIfDirty (View.java:16424)
  at android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:3905)
  at android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3885)
  at android.view.View.updateDisplayListIfDirty (View.java:16424)
  at android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:3905)
  at android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3885)
  at android.view.View.updateDisplayListIfDirty (View.java:16424)
  at android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:3905)
  at android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3885)
  at android.view.View.updateDisplayListIfDirty (View.java:16424)
  at android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:3905)
  at android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3885)
  at android.view.View.updateDisplayListIfDirty (View.java:16424)
  at android.view.ThreadedRenderer.updateViewTreeDisplayList (ThreadedRenderer.java:325)
  at android.view.ThreadedRenderer.updateRootDisplayList (ThreadedRenderer.java:331)
  at android.view.ThreadedRenderer.draw (ThreadedRenderer.java:366)
  at android.view.ViewRootImpl.draw (ViewRootImpl.java:3134)
  at android.view.ViewRootImpl.performDraw (ViewRootImpl.java:2933)
  at android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:2522)
  at android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1437)
  at android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:7397)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:920)
  at android.view.Choreographer.doCallbacks (Choreographer.java:695)
  at android.view.Choreographer.doFrame (Choreographer.java:631)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:906)
  at android.os.Handler.handleCallback (Handler.java:739)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:158)
  at android.app.ActivityThread.main (ActivityThread.java:7225)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1230)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)
```
