### ISSUE TITLE
NullPointerException: ...'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference

### ISSUE THREAD

**Issue by panovvitalik** [PhilJay/MPAndroidChart#5014]
**Summary**
09-23 21:47:31.659 26167 26167 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
09-23 21:47:31.659 26167 26167 E AndroidRuntime: 	at com.github.mikephil.charting.renderer.PieChartRenderer.drawExtras(PieChartRenderer.java:669)
09-23 21:47:31.659 26167 26167 E AndroidRuntime: 	at com.github.mikephil.charting.charts.PieChart.onDraw(PieChart.java:137)
09-23 21:47:31.659 26167 26167 E AndroidRuntime: 	at android.view.View.draw(View.java:21440)
09-23 21:47:31.659 26167 26167 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20317)
09-23 21:47:31.659 26167 26167 E AndroidRuntime: 	at android.view.View.draw(View.java:21172)
09-23 21:47:31.659 26167 26167 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
09-23 21:47:31.659 26167 26167 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
09-23 21:47:31.659 26167 26167 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20308)
09-23 21:47:31.659 26167 26167 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4372)
09-23 21:47:31.659 26167 26167 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4345)
09-23 21:47:31.659 26167 26167 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20277)
09-23 21:47:31.659 26167 26167 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4372)
09-23 21:47:31.659 26167 26167 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4345)
09-23 21:47:31.659 26167 26167 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20277)
09-23 21:47:31.659 26167 26167 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4372)
09-23 21:47:31.659 26167 26167 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4345)
09-23 21:47:31.659 26167 26167 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20277)
09-23 21:47:31.659 26167 26167 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4372)
09-23 21:47:31.659 26167 26167 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4345)

**Expected Behavior**

**Possible Solution**

**Device (please complete the following information):**
 - Device: [e.g. Google Pixel]
 - Android Version 10
 - Library Version com.github.PhilJay:MPAndroidChart:v3.1.0

**Additional Context**

ADD A REWARD using [Speed](speedoss.com) to SOLVE this issue QUICKLY and SUPPORT this project.

**Comment by bobekos** [comment]
reference to #3470
