### ISSUE TITLE
LineChart - NegativeArraySizeException still exist in the latest version

### ISSUE THREAD

**Issue by ArcherEmiya05** [PhilJay/MPAndroidChart#5103]
I am trying to use LineChart as I managed to work with Pie, Candle, and Radar already I thought this simple one would not give much of a problem but it turns out to be the worse. The issue was still there even after using `Collections.sort(entries, new EntryXComparator());` as mention [here](https://github.com/PhilJay/MPAndroidChart/issues/2074#issuecomment-238458565) the `NegativeArraySizeException` was still occurred. The X Axis value is already sorted as this is what the `entries.toString()` shows in the log.

`[Entry, x: 0.0 y: 2.26943828E11, Entry, x: 1.0 y: 2.2894551E11, Entry, x: 2.0 y: 2.30067159E11, Entry, x: 3.0 y: 2.31227146E11, Entry, x: 4.0 y: 2.34851287E11, Entry, x: 5.0 y: 2.39578956E11, Entry, x: 6.0 y: 2.42177851E11, Entry, x: 7.0 y: 2.44676346E11, Entry, x: 8.0 y: 2.47293231E11, Entry, x: 9.0 y: 2.4787565E11, Entry, x: 10.0 y: 2.48892932E11, Entry, x: 11.0 y: 2.51660091E11, Entry, x: 12.0 y: 2.53427466E11, Entry, x: 13.0 y: 2.56441631E11, Entry, x: 14.0 y: 2.59416916E11, Entry, x: 15.0 y: 2.6602301E11, Entry, x: 16.0 y: 2.68422726E11, Entry, x: 17.0 y: 2.70717043E11, Entry, x: 18.0 y: 2.72702554E11, Entry, x: 19.0 y: 2.75132809E11, Entry, x: 20.0 y: 2.77427094E11, Entry, x: 21.0 y: 2.79084335E11, Entry, x: 22.0 y: 2.81087115E11, Entry, x: 23.0 y: 2.80602411E11, Entry, x: 24.0 y: 2.81022005E11, Entry, x: 25.0 y: 2.82968818E11, Entry, x: 26.0 y: 2.84027716E11]`

So what exactly is missing here? This is my code looks like

```
List<ILineDataSet> lineDataSetList = new ArrayList<>();
for (int i = 0; i < assetList.size(); i++){
ArrayList<Entry> values = new ArrayList<>();
                        ArrayList<Long> timeStamps = new ArrayList<>();

                        JSONArray array = response.getJSONObject("data").getJSONArray("values");

                        for (int j = 0; j < array.length(); j++) {

                            JSONArray objects = array.getJSONArray(j);

                            values.add(new Entry(j, (float) objects.getDouble(1)));

                            timeStamps.add(objects.getLong(0));

                        }

                        chart.getXAxis().setValueFormatter(new ValueFormatter() {

                            final SimpleDateFormat formatter = new SimpleDateFormat("MM/dd/yy", Locale.getDefault());

                            @Override
                            public String getFormattedValue(float value) {
                                if ((int) value > timeStamps.size() - 1)
                                    value = timeStamps.size() - 1;

                                return formatter.format(new Date(timeStamps.get((int) value)));
                            }

                        });

                        chart.getXAxis().setGranularity(1f); // minimum axis-step (interval) is 1

                        // Create a custom MarkerView (extend MarkerView) and specify the layout to use for it
                        CustomMarkerView mv = new CustomMarkerView(context, R.layout.radar_markerview, timeStamps);
                        mv.setChartView(chart); // For bounds control
                        chart.setMarker(mv); // Set the marker to the chart

                        int[] colors = ColorTemplate.PASTEL_COLORS;

                        Log.wtf("WTF", values.toString());

                        LineDataSet lineDataSet = new LineDataSet(values, asset.getSymbol());
                        lineDataSet.setAxisDependency(YAxis.AxisDependency.LEFT);
                        lineDataSet.setColor(colors[finalIndex % colors.length]);
                        lineDataSet.setCircleColor(Color.WHITE);
                        lineDataSet.setLineWidth(2f);
                        lineDataSet.setCircleRadius(3f);
                        lineDataSet.setFillAlpha(65);
                        lineDataSet.setFillColor(ColorTemplate.getHoloBlue());
                        lineDataSet.setHighLightColor(Color.rgb(244, 117, 117));
                        lineDataSet.setDrawCircleHole(false);

                        lineDataSetList.add(lineDataSet);
}
```

Then after the loop setting the data to LineChart

```
// create a data object with the data sets
                LineData data = new LineData(lineDataSetList);
                data.setValueTextColor(Color.WHITE);
                data.setValueTextSize(9f);

                chart.setData(data);
                chart.notifyDataSetChanged();
                chart.invalidate();

                // get the legend (only possible after setting data)
                Legend l = chart.getLegend();

                // modify the legend ...
                l.setForm(Legend.LegendForm.LINE);
                l.setTextSize(11f);
                l.setTextColor(Color.WHITE);
                l.setVerticalAlignment(Legend.LegendVerticalAlignment.BOTTOM);
                l.setHorizontalAlignment(Legend.LegendHorizontalAlignment.LEFT);
                l.setOrientation(Legend.LegendOrientation.HORIZONTAL);
                l.setDrawInside(false);

                chart.animateX(1500);
```
As you can see there could be 1 or more line to be display, but as the graph seems to prepare the data to display (showing grid lines already) all of a sudden it crash with the said exception.

Stacktrace
```
2021-03-04 02:00:00.138 18203-18203/com.app.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.app.app, PID: 18203
    java.lang.NegativeArraySizeException: -6
        at com.github.mikephil.charting.j.g.b(Transformer.java:178)
        at com.github.mikephil.charting.i.h.e(LineChartRenderer.java:549)
        at com.github.mikephil.charting.charts.b.onDraw(BarLineChartBase.java:278)
        at android.view.View.draw(View.java:19218)
        at android.view.View.updateDisplayListIfDirty(View.java:18168)
        at android.view.View.draw(View.java:18946)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
        at android.view.View.updateDisplayListIfDirty(View.java:18159)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4224)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4204)
        at android.view.View.updateDisplayListIfDirty(View.java:18127)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4224)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4204)
        at android.view.View.updateDisplayListIfDirty(View.java:18127)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4224)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4204)
        at android.view.View.updateDisplayListIfDirty(View.java:18127)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4224)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4204)
        at android.view.View.updateDisplayListIfDirty(View.java:18127)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4224)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4204)
        at android.view.View.updateDisplayListIfDirty(View.java:18127)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4224)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4204)
        at android.view.View.updateDisplayListIfDirty(View.java:18127)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4224)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4204)
        at android.view.View.updateDisplayListIfDirty(View.java:18127)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4224)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4204)
        at android.view.View.updateDisplayListIfDirty(View.java:18127)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4224)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4204)
        at android.view.View.updateDisplayListIfDirty(View.java:18127)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4224)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4204)
        at android.view.View.updateDisplayListIfDirty(View.java:18127)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4224)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4204)
        at android.view.View.updateDisplayListIfDirty(View.java:18127)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:685)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:691)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:799)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3056)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2851)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2404)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6886)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1029)
        at android.view.Choreographer.doCallbacks(Choreographer.java:841)
        at android.view.Choreographer.doFrame(Choreographer.java:772)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1015)
        at android.os.Handler.handleCallback(Handler.java:794)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6651)
2021-03-04 02:00:00.138 18203-18203/com.app.app E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
```

**Comment by Krishnakant-android** [comment]
Hi, 
Could you check the X and Y value. It should not be negative if are you showing x and Y positive point. Just check with X > 0.0 
or Y> 0.0  when Added to your list and also check X and Y axis list should be same size. could be work.

**Comment by ArcherEmiya05** [comment]
Already fixed this, unfortunately the `lineDataSetList` is empty thus chart dataset throws error as well since there is no data. I also change its datatype to `List<LineDataSet> lineDataSetList = new ArrayList<>();` then pass it as an array for varargs param of `LineData` like this `LineData data = new LineData(lineDataSetList.toArray(new LineDataSet[0]));`. Just make sure the data in `chart.setData(data);` is not null or empty and the X-Axis of entry is sorted to avoid NegativeArraySizeException.
