### ISSUE TITLE
Dynamically add many values to the chart

### ISSUE THREAD

**Issue by davix10** [PhilJay/MPAndroidChart#5134]
- Device: [e.g. Nvida Shield]
 - Android Version [e.g. 6.0]
 - Library Version (e.g. v3.1.0)

I receive data from bluetooth at a frequency of 100 Hz and then I plot them on the graph in the same way as explained on the example of the dynamic graph but after a few seconds the app crashes with this message:

`2021-05-03 11:28:24.611 30962-30962/com.ot.ealgo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ot.ealgo, PID: 30962
    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:411)
        at com.github.mikephil.charting.renderer.LegendRenderer.renderLegend(LegendRenderer.java:377)
        at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:281)
        at android.view.View.draw(View.java:17067)
        at android.view.View.updateDisplayListIfDirty(View.java:16049)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)
        at android.view.View.updateDisplayListIfDirty(View.java:16012)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)
        at android.view.View.updateDisplayListIfDirty(View.java:16012)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)
        at android.view.View.updateDisplayListIfDirty(View.java:16012)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)
        at android.view.View.updateDisplayListIfDirty(View.java:16012)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)
        at android.view.View.updateDisplayListIfDirty(View.java:16012)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)
        at android.view.View.updateDisplayListIfDirty(View.java:16012)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)
        at android.view.View.updateDisplayListIfDirty(View.java:16012)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:656)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:662)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:770)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2944)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2752)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2345)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1343)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6526)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
        at android.view.Choreographer.doCallbacks(Choreographer.java:683)
        at android.view.Choreographer.doFrame(Choreographer.java:619)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6120)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)`

can't handle all these values? can I proceed in any way?

Thank you

**Comment by bobasaurus** [comment]
I have the same issue, have not found a fix yet.
