### ISSUE TITLE
LineChart - probably bug introduced with 2.0.9

### ISSUE THREAD

**Issue by MFlisar** [PhilJay/MPAndroidChart#529]
I just tried the same chart with version 2.0.8 and 2.0.9. In the old version, everything works perfectly but in the new version, it crashes with the appended exception. I never had problems with the old version before... Are there any major changes that I have to take care off in my code that could make the new version not compatible any more?

    java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
		at java.util.ArrayList.get(ArrayList.java:310)
		at com.github.mikephil.charting.buffer.CircleBuffer.feed(CircleBuffer.java:26)
		at com.github.mikephil.charting.renderer.LineChartRenderer.drawCircles(LineChartRenderer.java:492)
		at com.github.mikephil.charting.renderer.LineChartRenderer.drawExtras(LineChartRenderer.java:458)
		at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:236)
		at android.view.View.draw(View.java:15507)
		at android.view.View.getDisplayList(View.java:14401)
		at android.view.View.getDisplayList(View.java:14443)
		at android.view.View.draw(View.java:15221)
		at android.view.ViewGroup.drawChild(ViewGroup.java:3340)
		at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3176)
		at android.view.View.getDisplayList(View.java:14396)
		at android.view.View.getDisplayList(View.java:14443)
		at android.view.View.draw(View.java:15221)
		at android.view.ViewGroup.drawChild(ViewGroup.java:3340)
		at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3176)
		at android.view.View.getDisplayList(View.java:14396)
		at android.view.View.getDisplayList(View.java:14443)
		at android.view.View.draw(View.java:15221)
		at android.view.ViewGroup.drawChild(ViewGroup.java:3340)
		at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3176)
		at android.view.View.getDisplayList(View.java:14396)
		at android.view.View.getDisplayList(View.java:14443)
		at android.view.View.draw(View.java:15221)
		at android.view.ViewGroup.drawChild(ViewGroup.java:3340)
		at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3176)
		at android.view.View.draw(View.java:15510)
		at android.support.v4.view.ViewPager.draw(ViewPager.java:2176)
		at android.view.View.getDisplayList(View.java:14401)
		at android.view.View.getDisplayList(View.java:14443)
		at android.view.View.draw(View.java:15221)
		at android.view.ViewGroup.drawChild(ViewGroup.java:3340)
		at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3176)
		at android.view.View.getDisplayList(View.java:14396)
		at android.view.View.getDisplayList(View.java:14443)
		at android.view.View.draw(View.java:15221)
		at android.view.ViewGroup.drawChild(ViewGroup.java:3340)
		at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3176)
		at android.view.View.getDisplayList(View.java:14396)
		at android.view.View.getDisplayList(View.java:14443)
		at android.view.View.draw(View.java:15221)
		at android.view.ViewGroup.drawChild(ViewGroup.java:3340)
		at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3176)
		at android.view.View.getDisplayList(View.java:14396)
		at android.view.View.getDisplayList(View.java:14443)
		at android.view.View.draw(View.java:15221)
		at android.view.ViewGroup.drawChild(ViewGroup.java:3340)
		at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3176)
		at android.view.View.getDisplayList(View.java:14396)
		at android.view.View.getDisplayList(View.java:14443)
		at android.view.View.draw(View.java:15221)
		at android.view.ViewGroup.drawChild(ViewGroup.java:3340)
		at android.support.v4.widget.SlidingPaneLayout.drawChild(SlidingPaneLayout.java:1010)
		at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3176)
		at android.view.View.draw(View.java:15510)
		at android.support.v4.widget.SlidingPaneLayout.draw(SlidingPaneLayout.java:1152)
		at android.view.View.getDisplayList(View.java:14401)
		at android.view.View.getDisplayList(View.java:14443)
		at android.view.View.draw(View.java:15221)
		at android.view.ViewGroup.drawChild(ViewGroup.java:3340)
		at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1060)
		at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3176)
		at android.view.View.getDisplayList(View.java:14396)
		at android.view.View.getDisplayList(View.java:14443)
		at android.view.View.draw(View.java:15221)
		at android.view.ViewGroup.drawChild(ViewGroup.java:3340)
		at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3176)
		at android.view.View.getDisplayList(View.java:14396)
		at android.view.View.getDisplayLi

**Comment by PhilJay** [comment]
Looking into it.

**Comment by PhilJay** [comment]
Can you provide your setup? How many values are you exactly plotting when the error occurs?

**Comment by MFlisar** [comment]
I will try to create a manageable test data set and provide you with it...

**Comment by MFlisar** [comment]
I just tested a little bit and I think I found out what exactly is causing the problem. I think, it's combining `LineDataSets` with at least one `LineDataSet` that does not have any entries... As soon as I add a `LineDataSet` that does not have any entry, the graph throws an exception...

Please tell me if this info let's you recreate the problem, otherwise I will offer a complete example...

**Comment by PhilJay** [comment]
So you have 2 datasets? One containing data and one is empty but still added to the chart?

**Comment by MFlisar** [comment]
And here's my setup

    public static LineChart createLineChart(Activity activity, LinearLayout llParent, LineChart lineChart, ChartData data, Integer heightInDpForNotEmptyData, Integer heightInDpForEmptyData, boolean forceStartAtZero, boolean showLegend)
    {
        if (lineChart != null)
            llParent.removeView(lineChart);
        lineChart = new LineChart(activity);

        lineChart.setDescription("");
        lineChart.setNoDataText(MainApp.get().getString(R.string.no_data_available));
        lineChart.getPaint(Chart.PAINT_INFO).setColor(Color.RED);

        lineChart.setHighlightEnabled(true);
        lineChart.setTouchEnabled(true);
        lineChart.setDragEnabled(true);
        lineChart.setScaleEnabled(true);
        lineChart.setPinchZoom(true);

        lineChart.getAxisLeft().setStartAtZero(forceStartAtZero);
        lineChart.getAxisRight().setStartAtZero(forceStartAtZero);
        lineChart.getAxisRight().setDrawLabels(false);
        lineChart.getXAxis().setPosition(XAxis.XAxisPosition.BOTTOM);

        lineChart.getAxisLeft().setTextColor(Functions.getDefaultTextColor(activity));
        lineChart.getXAxis().setTextColor(Functions.getDefaultTextColor(activity));

        lineChart.setDrawGridBackground(false);

        lineChart.animateXY(1000, 1000);

        MyMarkerView mv = new MyMarkerView(activity, R.layout.custom_marker_view);
        lineChart.setMarkerView(mv);

        if (data != null)
        {
            lineChart.setData((LineData) data);
            if (showLegend)
                lineChart.getLegend().setTextColor(Functions.getDefaultTextColor(activity));
            else
                lineChart.getLegend().setEnabled(false);
        }

        int h = heightInDpForNotEmptyData != null ? (lineChart.isEmpty() ? (int)Functions.convertDpToPixel(heightInDpForEmptyData, activity) : (int)Functions.convertDpToPixel(heightInDpForNotEmptyData, activity)) : LinearLayout.LayoutParams.MATCH_PARENT;
        llParent.addView(lineChart, new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT, h));
        return lineChart;
    }

**Comment by MFlisar** [comment]
And yes, that's exactly what I have...

**Comment by MFlisar** [comment]
Actually, I thought that empty datasets were shown in the legend, but they weren't. They were anyway ignored. For me, checking for an empty dataset before adding it to the chart solves the problem so far without any difference to version 2.0.8...

**Comment by PhilJay** [comment]
Allright, I think I found something. Please give it a try.

**Comment by avafab** [comment]
Hi Phil,
it seems that the problem is still there, I got the same error with 2.0.9, switching back to 2.0.8 solved the issue.

```
04-19 13:17:41.447  18788-18788/com.avafab.cycletime E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.avafab.cycletime, PID: 18788
    java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
            at java.util.ArrayList.get(ArrayList.java:310)
            at com.github.mikephil.charting.buffer.CircleBuffer.feed(CircleBuffer.java:26)
            at com.github.mikephil.charting.renderer.LineChartRenderer.drawCircles(LineChartRenderer.java:492)
            at com.github.mikephil.charting.renderer.LineChartRenderer.drawExtras(LineChartRenderer.java:458)
            at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:236)
            at android.view.View.draw(View.java:15114)
            at android.view.View.updateDisplayListIfDirty(View.java:14048)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.View.draw(View.java:14838)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.updateDisplayListIfDirty(View.java:14043)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.View.draw(View.java:14838)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.draw(View.java:15117)
            at android.support.v4.view.ViewPager.draw(ViewPager.java:2176)
            at android.view.View.updateDisplayListIfDirty(View.java:14048)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.View.draw(View.java:14838)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.updateDisplayListIfDirty(View.java:14043)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.View.draw(View.java:14838)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.updateDisplayListIfDirty(View.java:14043)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.View.draw(View.java:14838)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.updateDisplayListIfDirty(View.java:14043)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.View.draw(View.java:14838)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.updateDisplayListIfDirty(View.java:14043)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.View.draw(View.java:14838)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.draw(View.java:15117)
            at com.android.internal.widget.ActionBarOverlayLayout.draw(ActionBarOverlayLayout.java:501)
            at android.view.View.updateDisplayListIfDirty(View.java:14048)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.View.draw(View.java:14838)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.draw(View.java:15117)
            at android.widget.FrameLayout.draw(FrameLayout.java:592)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2595)
            at android.view.View.updateDisplayListIfDirty(View.java:14048)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:266)
            at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:272)
            at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:311)
            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2492)
            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2337)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1968)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1054)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5779)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
            at android.view.Choreo
```

**Comment by Jerome67000** [comment]
Hi,

Thanks for the great work at your lib. I have the same error and backing to 2.0.8 resolve the problem, thanks for the temp bug fix !
