### ISSUE TITLE
Update Chart

### ISSUE THREAD

**Issue by 79144876** [PhilJay/MPAndroidChart#536]
HI!
I have use your code at last year.
And today ,i have try to use jar file to my project.
Then,i found that your API change ?
such as this：
```
    /**
     * set line chart view
     */
    private void setupLineChartView() {

        mChart = (LineChart) findViewById(R.id.book_detail_line_chart);
        mChart.setOnChartValueSelectedListener(this);
        mChart.getXLabels().setPosition(XLabels.XLabelPosition.BOTTOM);


        // if enabled, the chart will always start at zero on the y-axis
        mChart.setStartAtZero(true);

        // disable the drawing of values into the chart
        mChart.setDrawYValues(false);

        mChart.setDrawBorder(true);
        mChart.setBorderPositions(new BarLineChartBase.BorderPosition[]{
                BarLineChartBase.BorderPosition.BOTTOM,
                BarLineChartBase.BorderPosition.TOP,
                BarLineChartBase.BorderPosition.LEFT,
                BarLineChartBase.BorderPosition.RIGHT,
        });

        // no description text
        mChart.setDescription("");
        mChart.setNoDataTextDescription("");

        // // enable / disable grid lines
        // mChart.setDrawVerticalGrid(false);
        // mChart.setDrawHorizontalGrid(false);
        //
        // enable / disable grid background
        mChart.setDrawGridBackground(false);

        // mChart.setDrawXLegend(false);
        // mChart.setDrawYLegend(false);

        // enable value highlighting
        mChart.setHighlightEnabled(true);

        // enable touch gestures
        mChart.setTouchEnabled(true);

        // enable scaling and dragging
        mChart.setDragEnabled(true);
        mChart.setScaleEnabled(true);

        // if disabled, scaling can be done on x- and y-axis separately
        mChart.setPinchZoom(true);

        YLabels y = mChart.getYLabels();
        y.setTextColor(Color.WHITE);
        y.setLabelCount(6);

        XLabels x = mChart.getXLabels();
        x.setTextColor(Color.WHITE);
        // set an alternative background color
//        mChart.setBackgroundColor(Color.RED);

        // create a custom MarkerView (extend MarkerView) and specify the layout
        // to use for it
        MyMarkerView mv = new MyMarkerView(this, R.layout.custom_marker_view);

        // define an offset to change the original position of the marker
        // (optional)
        mv.setOffsets(-mv.getMeasuredWidth() / 2, -mv.getMeasuredHeight());

        // set the marker to the chart
        mChart.setMarkerView(mv);

        // enable/disable highlight indicators (the lines that indicate the
        // highlighted Entry)
        mChart.setHighlightIndicatorEnabled(false);

        // add data
        setLineChartData();
    }
```

i have no idea about how to fix my old code to your new code ?

**Comment by PhilJay** [comment]
Have a look at the [documentation](https://github.com/PhilJay/MPAndroidChart/wiki).

There you should find the things you need. Biggest changes are
 - `YLabels` now called `YAxis` (same goes for x-labels)
 - Grid lines, and range of the chart now controlled via axis
 - More customization through the data objects

**Comment by 79144876** [comment]
ok, will try update it latter.and then i will ask you.
Thanks.

**Comment by 79144876** [comment]
Hi, i have update my code and then i have two problem.
1.how to set x Label value's space? i have try to use 'setSpaceBetweenLabels' but now working .
2.how to set the x an y labels all data in screen ?
   X: I have one moth data, x labels is daily(30 days) , i need draw full data in (visible) screen,but now just only show 10 days, and i need scroll x labels to the left )
   Y:like X, i need scroll to top and then view will show top value.
 i need all data in my visible rect screen, how to set it ???
Here is my code:

```
 private void setupLineChartView() {
        mChart = (LineChart) findViewById(R.id.book_detail_line_chart);
        mChart.setDrawGridBackground(false);
        mChart.setBackgroundColor(getResources().getColor(R.color.transparent));
        XAxis xAxis = mChart.getXAxis();
        xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);
        xAxis.setDrawGridLines(false);
        xAxis.setDrawAxisLine(true);
        xAxis.setAdjustXLabels(false);
        xAxis.setGridLineWidth(2);
        xAxis.setSpaceBetweenLabels(1);
        YAxis leftAxis = mChart.getAxisLeft();
        leftAxis.setStartAtZero(true);
        YAxis rightAxis = mChart.getAxisRight();
        rightAxis.setDrawGridLines(true);
        rightAxis.setDrawLabels(false);
        mChart.setDescription("");
        // get the legend (only possible after setting data)
        Legend l = mChart.getLegend();
        l.setEnabled(false);
        l.setXEntrySpace(3);
        mChart.invalidate();
        setLineChartData();
    }
```

```
  int count = 30;
        ArrayList<Entry> yVals = new ArrayList<Entry>();
        final ArrayList<String> xVals = new ArrayList<String>();
        for (int i = 0; i < count; i++) {
            xVals.add("" + (i + 1));
            yVals.add(new Entry(i, i));
        }
        final String lable = getString(R.string.book_detail_line_lable);
        LineDataSet set1 = new LineDataSet(yVals, lable);
        set1.setLineWidth(1.75f);
        set1.setCircleSize(3f);
        set1.setColor(Color.WHITE);
        set1.setCircleColor(Color.WHITE);
        set1.setHighLightColor(Color.WHITE);
        set1.setDrawValues(false);
        final LineData data = new LineData(xVals, set1);
         mChart.setData(data);;//set a default data first
```

Thanks.

**Comment by 79144876** [comment]
HI .
Any idea ?
Thanks .

**Comment by 79144876** [comment]
```
04-15 09:14:35.389  26000-26000/com.eusoft.recite.fr D/AndroidRuntime﹕ Shutting down VM
04-15 09:14:35.389  26000-26000/com.eusoft.recite.fr W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x41695ba8)
04-15 09:14:35.481  26000-26000/com.eusoft.recite.fr E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.eusoft.recite.fr, PID: 26000
    java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
            at java.util.ArrayList.get(ArrayList.java:310)
            at com.github.mikephil.charting.buffer.CircleBuffer.feed(CircleBuffer.java:26)
            at com.github.mikephil.charting.renderer.LineChartRenderer.drawCircles(LineChartRenderer.java:492)
            at com.github.mikephil.charting.renderer.LineChartRenderer.drawExtras(LineChartRenderer.java:458)
            at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:236)
```

**Comment by 79144876** [comment]
Hi.I'm sorry. I have fixed my problem!
Thanks.
