### ISSUE TITLE
PieChartRenderer.drawExtras(PieChartRenderer.java:669) NullPointerException in Android 9

### ISSUE THREAD

**Issue by huize** [PhilJay/MPAndroidChart#5406]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.Reference.get()' on a null object reference
       at com.github.mikephil.charting.renderer.PieChartRenderer.drawExtras(PieChartRenderer.java:669)
       at com.github.mikephil.charting.charts.PieChart.onDraw(PieChart.java:137)
       at android.view.View.draw(View.java:21868)
       at android.view.View.updateDisplayListIfDirty(View.java:20741)
       at android.view.View.draw(View.java:21594)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4558)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4333)
       at android.view.View.updateDisplayListIfDirty(View.java:20727)
       at android.view.View.draw(View.java:21594)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4558)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4333)
       at android.view.View.updateDisplayListIfDirty(View.java:20727)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4542)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4514)
       at android.view.View.updateDisplayListIfDirty(View.java:20696)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4542)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4514)
       at android.view.View.updateDisplayListIfDirty(View.java:20696)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4542)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4514)
       at android.view.View.updateDisplayListIfDirty(View.java:20696)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4542)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4514)
       at android.view.View.updateDisplayListIfDirty(View.java:20696)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4542)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4514)
       at android.view.View.updateDisplayListIfDirty(View.java:20696)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4542)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4514)
       at android.view.View.updateDisplayListIfDirty(View.java:20696)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4542)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4514)
       at android.view.View.updateDisplayListIfDirty(View.java:20696)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:725)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:731)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:840)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:3949)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3723)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3034)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1897)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8514)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
       at android.view.Choreographer.doCallbacks(Choreographer.java:761)
       at android.view.Choreographer.doFrame(Choreographer.java:696)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7076)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by PhilJay** [comment]
The 4.0 rewrite resolves this: The offscreen bitmap and its canvas are null-safe throughout the pie renderer, so this NPE cannot occur.

4.0 is a full rewrite in Kotlin. Install instructions and the full list of changes are in the release notes: https://github.com/PhilJay/MPAndroidChart/releases/tag/v4.0.0-beta01
