### ISSUE TITLE
数组越界了

### ISSUE THREAD

**Issue by tomKitty888888** [PhilJay/MPAndroidChart#5407]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.eps168.app, PID: 25241
    java.lang.IndexOutOfBoundsException: Index: 0, Size: 1
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.github.mikephil.charting.renderer.LegendRenderer.renderLegend(LegendRenderer.java:377)
        at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:281)
        at android.view.View.draw(View.java:22672)
        at android.view.View.updateDisplayListIfDirty(View.java:21543)
        at android.view.View.draw(View.java:22403)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4534)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4295)
        at android.view.View.draw(View.java:22675)
        at android.view.View.updateDisplayListIfDirty(View.java:21543)
        at android.view.View.draw(View.java:22403)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4534)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4295)
        at android.view.View.updateDisplayListIfDirty(View.java:21534)
        at android.view.View.draw(View.java:22403)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4534)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4295)
        at android.view.View.updateDisplayListIfDirty(View.java:21534)
        at android.view.View.draw(View.java:22403)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4534)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4295)
        at android.view.View.draw(View.java:22675)
        at android.view.View.updateDisplayListIfDirty(View.java:21543)
        at android.view.View.draw(View.java:22403)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4534)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4295)
        at android.view.View.updateDisplayListIfDirty(View.java:21534)
        at android.view.View.draw(View.java:22403)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4534)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4295)
        at android.view.View.updateDisplayListIfDirty(View.java:21534)
        at android.view.View.draw(View.java:22403)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4534)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4295)
        at android.view.View.updateDisplayListIfDirty(View.java:21534)
        at android.view.View.draw(View.java:22403)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4534)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4295)
        at android.view.View.updateDisplayListIfDirty(View.java:21534)
        at android.view.View.draw(View.java:22403)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4534)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4295)
        at android.view.View.draw(View.java:22675)
        at com.android.internal.policy.DecorView.draw(DecorView.java:916)
        at android.view.View.updateDisplayListIfDirty(View.java:21543)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:540)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:616)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:4462)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4190)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3350)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2167)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8832)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1120)
        at android.view.Choreographer.doCallbacks(Choreographer.java:926)
        at android.view.Choreographer.doFrame(Choreographer.java:859)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1105)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7897)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:558)
E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)

**Comment by PhilJay** [comment]
This is fixed in **4.0.0-beta01**: The horizontal branch of the legend renderer read `calculatedLabelSizes` without a bound check. It measures the label instead when the cached sizes are shorter than the entries, which happens when you assign `legend.entries` or change the orientation after the last measuring pass.

4.0 is a full rewrite in Kotlin. Install instructions and the full list of changes are in the release notes: https://github.com/PhilJay/MPAndroidChart/releases/tag/v4.0.0-beta01
