### ISSUE TITLE
java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by heroleon** [PhilJay/MPAndroidChart#5421]
FATAL EXCEPTION: main
                                                                                                    Process: com.lotus.trackreport, PID: 12011
                                                                                                    java.lang.IndexOutOfBoundsException: Index: 3138, Size: 0
                                                                                                    	at java.util.ArrayList.get(ArrayList.java:437)
                                                                                                    	at com.github.mikephil.charting.data.DataSet.getEntryForIndex(DataSet.java:294)
                                                                                                    	at com.github.mikephil.charting.renderer.LineChartRenderer.drawLinear(LineChartRenderer.java:393)
                                                                                                    	at com.github.mikephil.charting.renderer.LineChartRenderer.drawDataSet(LineChartRenderer.java:119)
                                                                                                    	at com.github.mikephil.charting.renderer.LineChartRenderer.drawData(LineChartRenderer.java:101)
                                                                                                    	at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:237)
                                                                                                    	at android.view.View.draw(View.java:23073)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21930)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4728)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4701)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21884)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4728)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4701)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21884)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4728)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4701)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21884)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4728)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4701)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21884)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4728)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4701)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21884)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4728)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4701)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21884)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4728)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4701)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21884)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4728)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4701)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21884)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4728)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4701)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21884)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4728)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4701)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21884)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4728)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4701)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21884)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4728)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4701)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21884)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4728)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4701)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21884)
                                                                                                    	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:564)
                                                                                                    	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:570)
                                                                                                    	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:658)
                                                                                                    	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5794)
                                                                                                    	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5476)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4453)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2837)

**Comment by Dalton-47** [comment]
This issue is on your end and seems like your dataset is not returning anything since the arrayList size is zero.

**Comment by erickjhorman** [comment]
Accessing an item from a zero length array list or index doesn't match the current length of arraylist.

**Comment by PhilJay** [comment]
Closing for lack of a reproducible case. Much of the rendering was rewritten since. 4.0.0-beta01 is out: https://github.com/PhilJay/MPAndroidChart/releases/tag/v4.0.0-beta01 Please open a new issue with a sample if you still see this on 4.0.
