### ISSUE TITLE
使用implementation ("com.github.PhilJay:MPAndroidChart:v3.0.2")报错

### ISSUE THREAD

**Issue by chinakaifa** [PhilJay/MPAndroidChart#5437]
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
                                                                                                    	at com.github.mikephil.charting.utils.Utils.drawXAxisValue(Utils.java:564)
                                                                                                    	at com.github.mikephil.charting.renderer.XAxisRenderer.drawLabel(XAxisRenderer.java:231)
                                                                                                    	at com.github.mikephil.charting.renderer.XAxisRenderer.drawLabels(XAxisRenderer.java:225)
                                                                                                    	at com.github.mikephil.charting.renderer.XAxisRenderer.renderAxisLabels(XAxisRenderer.java:130)
                                                                                                    	at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:251)
                                                                                                    	at android.view.View.draw(View.java:23073)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21930)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4728)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4701)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21884)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4728)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4701)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21884)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4728)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4701)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21884)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4728)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4701)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21884)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4728)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4701)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21884)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4728)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4701)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21884)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4728)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4701)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21884)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4728)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4701)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21884)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4728)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4701)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21884)
                                                                                                    	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:564)
                                                                                                    	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:570)
                                                                                                    	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:658)
                                                                                                    	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5794)
                                                                                                    	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5476)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4453)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2837)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10520)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1623)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:1141)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:1012)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1585)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:955)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:206)
                                                                                                    	at android.os.Looper.loop(Looper.java:296)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:9000)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:569)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:976)

**Comment by PhilJay** [comment]
The 4.0 rewrite resolves this: Formatters return a non-null `String` in Kotlin, and `IndexAxisValueFormatter` returns an empty string out of range, so the library can no longer produce the null behind this crash.

4.0 is a full rewrite in Kotlin. Install instructions and the full list of changes are in the release notes: https://github.com/PhilJay/MPAndroidChart/releases/tag/v4.0.0-beta01
