### ISSUE TITLE
com.github.mikephil.charting.renderer.BarChartRenderer.drawDataSet(BarChartRenderer.java:139)

### ISSUE THREAD

**Issue by shashankneosoft** [PhilJay/MPAndroidChart#5458]
Crash on below line

      Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.github.mikephil.charting.buffer.BarBuffer.setPhases(float, float)' on a null object reference
       at com.github.mikephil.charting.renderer.BarChartRenderer.drawDataSet(BarChartRenderer.java:139)
       at com.github.mikephil.charting.renderer.BarChartRenderer.drawData(BarChartRenderer.java:82)
       at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:237)
       at android.view.View.draw(View.java:24218)
       at android.view.View.updateDisplayListIfDirty(View.java:23036)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4628)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4601)
       at android.view.View.updateDisplayListIfDirty(View.java:22987)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4628)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4601)
       at android.view.View.updateDisplayListIfDirty(View.java:22987)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4628)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4601)
       at android.view.View.updateDisplayListIfDirty(View.java:22987)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4628)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4601)
       at android.view.View.updateDisplayListIfDirty(View.java:22987)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4628)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4601)
       at android.view.View.updateDisplayListIfDirty(View.java:22987)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4628)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4601)
       at android.view.View.updateDisplayListIfDirty(View.java:22987)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4628)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4601)
       at android.view.View.updateDisplayListIfDirty(View.java:22987)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4628)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4601)
       at android.view.View.updateDisplayListIfDirty(View.java:22987)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4628)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4601)
       at android.view.View.updateDisplayListIfDirty(View.java:22987)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4628)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4601)
       at android.view.View.updateDisplayListIfDirty(View.java:22987)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4628)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4601)
       at android.view.View.updateDisplayListIfDirty(View.java:22987)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4628)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4601)
       at android.view.View.updateDisplayListIfDirty(View.java:22987)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:713)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:719)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:821)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:5552)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5214)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4257)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2758)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10201)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1544)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1553)
       at android.view.Choreographer.doCallbacks(Choreographer.java:1109)
       at android.view.Choreographer.doFrame(Choreographer.java:994)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1527)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:257)
       at android.os.Looper.loop(Looper.java:368)
       at android.app.ActivityThread.main(ActivityThread.java:8826)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2977)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10289)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1634)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1643)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:1172)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:1076)

**Comment by PhilJay** [comment]
This is fixed in **4.0.0-beta01**: The bar renderers rebuild their buffers when the buffers no longer fit the data, so changing the data without calling `notifyDataSetChanged()` no longer throws here.

4.0 is a full rewrite in Kotlin. Install instructions and the full list of changes are in the release notes: https://github.com/PhilJay/MPAndroidChart/releases/tag/v4.0.0-beta01
