### ISSUE TITLE
com.github.mikephil.charting.renderer.BarChartRenderer.drawValues(BarChartRenderer.java:266)

### ISSUE THREAD

**Issue by shashankneosoft** [PhilJay/MPAndroidChart#5459]
Crashing on below line

      Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'float[] com.github.mikephil.charting.buffer.AbstractBuffer.buffer' on a null object reference in method 'void com.github.mikephil.charting.renderer.BarChartRenderer.drawValues(android.graphics.Canvas)'
       at com.github.mikephil.charting.renderer.BarChartRenderer.drawValues(BarChartRenderer.java:266)
       at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:278)
       at android.view.View.draw(View.java:23993)
       at android.view.View.updateDisplayListIfDirty(View.java:22862)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5342)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5314)
       at android.view.View.updateDisplayListIfDirty(View.java:22809)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5342)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5314)
       at android.view.View.updateDisplayListIfDirty(View.java:22809)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5342)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5314)
       at android.view.View.updateDisplayListIfDirty(View.java:22809)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5342)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5314)
       at android.view.View.updateDisplayListIfDirty(View.java:22809)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5342)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5314)
       at android.view.View.updateDisplayListIfDirty(View.java:22809)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5342)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5314)
       at android.view.View.updateDisplayListIfDirty(View.java:22809)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5342)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5314)
       at android.view.View.updateDisplayListIfDirty(View.java:22809)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5342)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5314)
       at android.view.View.updateDisplayListIfDirty(View.java:22809)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5342)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5314)
       at android.view.View.updateDisplayListIfDirty(View.java:22809)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5342)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5314)
       at android.view.View.updateDisplayListIfDirty(View.java:22809)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5342)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5314)
       at android.view.View.updateDisplayListIfDirty(View.java:22809)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5342)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5314)
       at android.view.View.updateDisplayListIfDirty(View.java:22809)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:602)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:608)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:684)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:5550)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5250)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4280)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2948)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10675)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1111)
       at android.view.Choreographer.doCallbacks(Choreographer.java:866)
       at android.view.Choreographer.doFrame(Choreographer.java:797)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1095)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8855)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by PhilJay** [comment]
This is fixed in **4.0.0-beta01**: Same cause as #5458 and fixed with it: the renderer rebuilds its buffers when they no longer match the data.

4.0 is a full rewrite in Kotlin. Install instructions and the full list of changes are in the release notes: https://github.com/PhilJay/MPAndroidChart/releases/tag/v4.0.0-beta01
