### ISSUE TITLE
PieChartRenderer crash

### ISSUE THREAD

**Issue by Blodgard** [PhilJay/MPAndroidChart#554]
I've received a lot of report from my users.
The problem that they faced is this.

java.lang.IllegalArgumentException: width and height must be > 0
at android.graphics.Bitmap.createBitmap(Bitmap.java:922)
at android.graphics.Bitmap.createBitmap(Bitmap.java:901)
at android.graphics.Bitmap.createBitmap(Bitmap.java:868)
at com.github.mikephil.charting.renderer.PieChartRenderer.drawData(PieChartRenderer.java:79)
at com.github.mikephil.charting.charts.PieChart.onDraw(PieChart.java:96)
at android.view.View.draw(View.java:15423)
at android.view.View.getDisplayList(View.java:14317)
at android.view.View.getDisplayList(View.java:14359)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3296)
at android.view.View.getDisplayList(View.java:14254)
at android.view.View.getDisplayList(View.java:14359)
at android.view.View.draw(View.java:15137)
at android.view.ViewGroup.drawChild(ViewGroup.java:3322)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3158)
at android.view.View.getDisplayList(View.java:14312)
at android.view.View.getDisplayList(View.java:14359)
at android.view.View.draw(View.java:15137)
at android.view.ViewGroup.drawChild(ViewGroup.java:3322)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3158)
at android.view.View.draw(View.java:15426)
at android.view.View.getDisplayList(View.java:14317)
at android.view.View.getDisplayList(View.java:14359)
at android.view.View.draw(View.java:15137)
at android.view.ViewGroup.drawChild(ViewGroup.java:3322)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3158)
at android.view.View.getDisplayList(View.java:14312)
at android.view.View.getDisplayList(View.java:14359)
at android.view.View.draw(View.java:15137)
at android.view.ViewGroup.drawChild(ViewGroup.java:3322)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3158)
at android.view.View.getDisplayList(View.java:14312)
at android.view.View.getDisplayList(View.java:14359)
at android.view.View.draw(View.java:15137)
at android.view.ViewGroup.drawChild(ViewGroup.java:3322)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3158)
at android.view.View.draw(View.java:15426)
at android.view.View.getDisplayList(View.java:14317)
at android.view.View.getDisplayList(View.java:14359)
at android.view.View.draw(View.java:15137)
at android.view.ViewGroup.drawChild(ViewGroup.java:3322)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3158)
at android.view.View.draw(View.java:15426)
at android.widget.FrameLayout.draw(FrameLayout.java:472)
at android.view.View.getDisplayList(View.java:14317)
at android.view.View.getDisplayList(View.java:14359)
at android.view.View.draw(View.java:15137)
at android.view.ViewGroup.drawChild(ViewGroup.java:3322)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3158)
at android.view.View.draw(View.java:15426)
at android.support.v7.internal.widget.ActionBarOverlayLayout.draw(ActionBarOverlayLayout.java:509)
at android.view.View.getDisplayList(View.java:14317)
at android.view.View.getDisplayList(View.java:14359)
at android.view.View.draw(View.java:15137)
at android.view.ViewGroup.drawChild(ViewGroup.java:3322)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3158)
at android.view.View.getDisplayList(View.java:14312)
at android.view.View.getDisplayList(View.java:14359)
at android.view.View.draw(View.java:15137)
at android.view.ViewGroup.drawChild(ViewGroup.java:3322)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3158)
at android.view.View.getDisplayList(View.java:14312)
at android.view.View.getDisplayList(View.java:14359)
at android.view.View.draw(View.java:15137)
at android.view.ViewGroup.drawChild(ViewGroup.java:3322)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3158)
at android.view.View.getDisplayList(View.java:14312)
at android.view.View.getDisplayList(View.java:14359)
at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1585)
at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1457)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:2779)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2645)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2213)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1256)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6649)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:813)
at android.view.Choreographer.doCallbacks(Choreographer.java:613)
at android.view.Choreographer.doFrame(Choreographer.java:583)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:799)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:146)
at android.app.ActivityThread.main(ActivityThread.java:5653)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
at dalvik.system.NativeStart.main(Native Method)

**Comment by Blodgard** [comment]
mDrawBitmap = Bitmap.createBitmap((int) mViewPortHandler.getChartWidth(),
                    (int) mViewPortHandler.getChartHeight(), Bitmap.Config.ARGB_8888);

This is the line that cause the crash

**Comment by Blodgard** [comment]
Seem that onSizeChanged in the Chart class isn't called when my device is in landscape mode.
landscape mode -> portrait mode, onSizeChanged called
portrait mode -> landscape mode, onSizeChanged not called

**Comment by PhilJay** [comment]
I just pushed a little fix, if you want you can try the latest master commit and see if it works now.
