### ISSUE TITLE
Throws exception after update to 2.0.9 

### ISSUE THREAD

**Issue by draco1023** [PhilJay/MPAndroidChart#588]
ChartData is empty, not null.
Exception message:

`java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
            at java.util.ArrayList.get(ArrayList.java:306)
            at com.github.mikephil.charting.buffer.CircleBuffer.feed(CircleBuffer.java:26)
            at com.github.mikephil.charting.renderer.LineChartRenderer.drawCircles(LineChartRenderer.java:492)
            at com.github.mikephil.charting.renderer.LineChartRenderer.drawExtras(LineChartRenderer.java:458)
            at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:236)
            at android.view.View.draw(View.java:13458)
            at android.view.View.getDisplayList(View.java:12409)
            at android.view.View.getDisplayList(View.java:12453)
            at android.view.View.draw(View.java:13182)
            at android.view.ViewGroup.drawChild(ViewGroup.java:2929)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2799)
            at android.view.View.getDisplayList(View.java:12407)
            at android.view.View.getDisplayList(View.java:12453)
            at android.view.View.draw(View.java:13182)
            at android.view.ViewGroup.drawChild(ViewGroup.java:2929)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2799)
            at android.view.View.draw(View.java:13461)
            at android.support.v4.view.ViewPager.draw(ViewPager.java:2176)
            at android.view.View.getDisplayList(View.java:12409)
            at android.view.View.getDisplayList(View.java:12453)
            at android.view.View.draw(View.java:13182)
            at android.view.ViewGroup.drawChild(ViewGroup.java:2929)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2799)
            at android.view.View.getDisplayList(View.java:12407)
            at android.view.View.getDisplayList(View.java:12453)
            at android.view.View.draw(View.java:13182)
            at android.view.ViewGroup.drawChild(ViewGroup.java:2929)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2799)
            at android.view.View.getDisplayList(View.java:12407)
            at android.view.View.getDisplayList(View.java:12453)
            at android.view.View.draw(View.java:13182)
            at android.view.ViewGroup.drawChild(ViewGroup.java:2929)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2799)
            at android.view.View.getDisplayList(View.java:12407)
            at android.view.View.getDisplayList(View.java:12453)
            at android.view.View.draw(View.java:13182)
            at android.view.ViewGroup.drawChild(ViewGroup.java:2929)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2799)
            at android.view.View.draw(View.java:13461)
            at android.widget.FrameLayout.draw(FrameLayout.java:467)
            at android.view.View.getDisplayList(View.java:12409)
            at android.view.View.getDisplayList(View.java:12453)
            at android.view.View.draw(View.java:13182)
            at android.view.ViewGroup.drawChild(ViewGroup.java:2929)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2799)
            at android.view.View.getDisplayList(View.java:12407)
            at android.view.View.getDisplayList(View.java:12453)
            at android.view.View.draw(View.java:13182)
            at android.view.ViewGroup.drawChild(ViewGroup.java:2929)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2799)
            at android.view.View.getDisplayList(View.java:12407)
            at android.view.View.getDisplayList(View.java:12453)
            at android.view.View.draw(View.java:13182)
            at android.view.ViewGroup.drawChild(ViewGroup.java:2929)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2799)
            at android.view.View.getDisplayList(View.java:12407)
            at android.view.View.getDisplayList(View.java:12453)
            at android.view.View.draw(View.java:13182)
            at android.view.ViewGroup.drawChild(ViewGroup.java:2929)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2799)
            at android.view.View.draw(View.java:13461)
            at android.widget.FrameLayout.draw(FrameLayout.java:467)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2183)
            at android.view.View.getDisplayList(View.java:12409)
            at android.view.View.getDisplayList(View.java:12453)
            at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1144)
            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2147)
            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2019)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1830)
            at android.view.ViewR`

**Comment by PhilJay** [comment]
This issue is known and soon fixed, thank you!
