### ISSUE TITLE
Have you declared this activity in androidmanifest.xml

### ISSUE THREAD

**Issue by rayrose344** [PhilJay/MPAndroidChart#591]
I was trying to implement pie chart from your mpchart example in Android Studio .. I am using the anim , layout and menu folder of your mpchart example and the following java files -- ChartItem , CubicLineChartActivity , DemoBase , DrawChartActivity , MainActivity , MyEasingFunction , MyMarkerView , MyValueFormatter , PieChartActivity , PieChartFrag , PieChartItem and SimpleFragment . Now , I have commented out the places in the switch case in the mainactivity where any chart other than piechart is used ... So , when I run the app , only piechart is shown in the initial menu , but when I click on it the app crashes and shows the follwing error in logcat ---

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.codemasterzz.medapp/com.codemasterzz.medapp.PieChartActivity}: java.lang.RuntimeException: Font asset not found OpenSans-Regular.ttf
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.RuntimeException: Font asset not found OpenSans-Regular.ttf
            at android.graphics.Typeface.createFromAsset(Typeface.java:190)
            at com.codemasterzz.medapp.PieChartActivity.onCreate(PieChartActivity.java:60)
            at android.app.Activity.performCreate(Activity.java:5937)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

Now , I have searched the error of Activity not found and saw that the problem is in the adnroidmanifest.xml ... So , my androidmanifest.xml is as follows ---

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.codemasterzz.medapp"
    android:versionCode="40"
    android:versionName="2.1.0" >

    <uses-sdk
        android:minSdkVersion="8"
        android:targetSdkVersion="21" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

    <application
        android:allowBackup="true"
        android:hardwareAccelerated="true"
        android:icon="@drawable/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/AppTheme" >
        <activity
            android:name="com.codemasterzz.medapp.MainActivity"
            android:label="@string/app_name" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity android:name="PieChartActivity"/>
    </application>

</manifest>

I am working on api 21 and graddle version is 2.2.1 

My intention is to show a pie chart with some values fetched from my sqlite database ... I am using your jar file too ...

**Comment by PhilJay** [comment]
This is not an issue related to the library.
I suggest you read this article on how to work with Android `Activity`: http://developer.android.com/guide/components/activities.html

**Comment by rayrose344** [comment]
Thanks .
