### ISSUE TITLE
NullPointerException with scrollview - pie chart - (updated)

### ISSUE THREAD

**Issue by smemamian** [PhilJay/MPAndroidChart#720]
Hi

I would like to use pie chart in a scrollview but I get NPE error .

https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/res/layout/activity_piechart.xml

https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/PieChartActivity.java

Error : 

06-07 11:05:27.251    4553-4553/... E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NullPointerException
            at com.github.mikephil.charting.renderer.PieChartRenderer.drawHole(PieChartRenderer.java:275)
            at com.github.mikephil.charting.renderer.PieChartRenderer.drawExtras(PieChartRenderer.java:240)
            at com.github.mikephil.charting.charts.PieChart.onDraw(PieChart.java:101)
            at android.view.View.draw(View.java:14180)
            at android.view.View.getDisplayList(View.java:13118)
            at android.view.View.getDisplayList(View.java:13162)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3006)
            at android.view.View.getDisplayList(View.java:13056)
            at android.view.View.getDisplayList(View.java:13162)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3006)
            at android.view.View.getDisplayList(View.java:13056)
            at android.view.View.getDisplayList(View.java:13162)
            at android.view.View.draw(View.java:13896)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3024)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2893)
            at android.view.View.draw(View.java:14183)
            at android.widget.FrameLayout.draw(FrameLayout.java:467)
            at android.widget.ScrollView.draw(ScrollView.java:2386)
            at android.view.View.getDisplayList(View.java:13118)
            at android.view.View.getDisplayList(View.java:13162)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3006)
            at android.view.View.getDisplayList(View.java:13056)
            at android.view.View.getDisplayList(View.java:13162)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3006)
            at android.view.View.getDisplayList(View.java:13056)
            at android.view.View.getDisplayList(View.java:13162)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3006)
            at android.view.View.getDisplayList(View.java:13056)
            at android.view.View.getDisplayList(View.java:13162)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3006)
            at android.view.View.getDisplayList(View.java:13056)
            at android.view.View.getDisplayList(View.java:13162)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3006)
            at android.view.View.getDisplayList(View.java:13056)
            at android.view.View.getDisplayList(View.java:13162)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3006)
            at android.view.View.getDisplayList(View.java:13056)
            at android.view.View.getDisplayList(View.java:13162)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3006)
            at android.view.View.getDisplayList(View.java:13056)
            at android.view.View.getDisplayList(View.java:13162)
            at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1198)
            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2431)
            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2303)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2109)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1179)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4861)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
            at android.view.Choreographer.doCallbacks(Choreographer.java:562)
            at android.view.Choreographer.doFrame(Choreographer.java:532)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
            at android.os.Handler.handleCallback(Handler.java:725)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5293)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
            at dalvik.system.NativeStart.main(Native Method)

My layout :

     <?xml version="1.0" encoding="utf-8"?>
    <ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

    <com.github.mikephil.charting.charts.PieChart
        android:id="@+id/chart1"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_above="@+id/seekBar1" />

    <SeekBar
        android:id="@+id/seekBar2"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:layout_alignParentLeft="true"
        android:layout_margin="8dp"
        android:layout_toLeftOf="@+id/tvYMax"
        android:layout_marginRight="5dp"
        android:max="200"
        android:paddingBottom="12dp" />

    <SeekBar
        android:id="@+id/seekBar1"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_above="@+id/seekBar2"
        android:layout_margin="8dp"
        android:layout_marginBottom="35dp"
        android:layout_toLeftOf="@+id/tvXMax"
        android:layout_marginRight="5dp"
        android:max="25"
        android:paddingBottom="12dp" />

    <TextView
        android:id="@+id/tvXMax"
        android:layout_width="50dp"
        android:layout_height="wrap_content"
        android:layout_alignBottom="@+id/seekBar1"
        android:layout_alignParentRight="true"
        android:text="500"
        android:layout_marginBottom="15dp"
        android:layout_marginRight="10dp"
        android:gravity="right"
        android:textAppearance="?android:attr/textAppearanceMedium" />

    <TextView
        android:id="@+id/tvYMax"
        android:layout_width="50dp"
        android:layout_height="wrap_content"
        android:layout_alignBottom="@+id/seekBar2"
        android:layout_alignParentRight="true"
        android:text="500"
        android:layout_marginBottom="15dp"
        android:layout_marginRight="10dp"
        android:gravity="right"
        android:textAppearance="?android:attr/textAppearanceMedium" />

    </RelativeLayout>

    </LinearLayout>

    </ScrollView>

**Comment by PhilJay** [comment]
If no attribute is set, the chart will now have a height of 50dp.
