### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by EfiMIsh** [PhilJay/MPAndroidChart#724]
Hi,

I have the following problem when doing fling on the chart:

 java.lang.OutOfMemoryError: Failed to allocate a 4994508 byte allocation with 1481188 free bytes and 1446KB until OOM
            at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
            at android.graphics.Bitmap.nativeCreate(Native Method)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:817)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:794)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:761)
            at com.github.mikephil.charting.renderer.LineChartRenderer.drawData(LineChartRenderer.java:85)
            at com.github.mikephil.charting.renderer.CombinedChartRenderer.drawData(CombinedChartRenderer.java:86)
            at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:213)
            at android.view.View.draw(View.java:15114)

Can you please help me?

Thanks in advance,

Efi M.

**Comment by chiahan1123** [comment]
Hi,

I have also encounter the OOM issue when running monkey test.  The following is the stack trace

2015-09-16 18:59:53 // Short Msg: java.lang.OutOfMemoryError
2015-09-16 18:59:53 // Long Msg: java.lang.OutOfMemoryError: Failed to allocate a 2414892 byte allocation with 616552 free bytes and 602KB until OOM
2015-09-16 18:59:53 // Build Label: samsung/kltezt/klte:5.0/LRX21T/G900IZTU1BOE1:user/release-keys
2015-09-16 18:59:53 // Build Changelist: G900IZTU1BOE1
2015-09-16 18:59:53 // Build Time: 1431306085000
2015-09-16 18:59:53 // java.lang.OutOfMemoryError: Failed to allocate a 2414892 byte allocation with 616552 free bytes and 602KB until OOM
2015-09-16 18:59:53 //  at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
2015-09-16 18:59:53 //  at android.graphics.Bitmap.nativeCreate(Native Method)
2015-09-16 18:59:53 //  at android.graphics.Bitmap.createBitmap(Bitmap.java:939)
2015-09-16 18:59:53 //  at android.graphics.Bitmap.createBitmap(Bitmap.java:912)
2015-09-16 18:59:53 //  at android.graphics.Bitmap.createBitmap(Bitmap.java:879)
2015-09-16 18:59:53 //  at com.github.mikephil.charting.renderer.LineChartRenderer.drawData(LineChartRenderer.java:85)
2015-09-16 18:59:53 //  at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:230)
2015-09-16 18:59:53 //  at android.view.View.draw(View.java:16060)
2015-09-16 18:59:53 //  at android.view.View.updateDisplayListIfDirty(View.java:14991)
2015-09-16 18:59:53 //  at android.view.View.getDisplayList(View.java:15014)
2015-09-16 18:59:53 //  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3661)
2015-09-16 18:59:53 //  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3640)
2015-09-16 18:59:53 //  at android.view.View.updateDisplayListIfDirty(View.java:14951)
2015-09-16 18:59:53 //  at android.view.View.getDisplayList(View.java:15014)
2015-09-16 18:59:53 //  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3661)
2015-09-16 18:59:53 //  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3640)
2015-09-16 18:59:53 //  at android.view.View.updateDisplayListIfDirty(View.java:14951)
2015-09-16 18:59:53 //  at android.view.View.getDisplayList(View.java:15014)
2015-09-16 18:59:53 //  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3661)
2015-09-16 18:59:53 //  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3640)
2015-09-16 18:59:53 //  at android.view.View.updateDisplayListIfDirty(View.java:14951)
2015-09-16 18:59:53 //  at android.view.View.getDisplayList(View.java:15014)
2015-09-16 18:59:53 //  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3661)
2015-09-16 18:59:53 //  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3640)
2015-09-16 18:59:53 //  at android.view.View.updateDisplayListIfDirty(View.java:14951)
2015-09-16 18:59:53 //  at android.view.View.getDisplayList(View.java:15014)
2015-09-16 18:59:53 //  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3661)
2015-09-16 18:59:53 //  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3640)
2015-09-16 18:59:53 //  at android.view.View.updateDisplayListIfDirty(View.java:14951)
2015-09-16 18:59:53 //  at android.view.View.getDisplayList(View.java:15014)
2015-09-16 18:59:53 //  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3661)
2015-09-16 18:59:53 //  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3640)
2015-09-16 18:59:53 //  at android.view.View.updateDisplayListIfDirty(View.java:14951)
2015-09-16 18:59:53 //  at android.view.View.getDisplayList(View.java:15014)
2015-09-16 18:59:53 //  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3661)
2015-09-16 18:59:53 //  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3640)
2015-09-16 18:59:53 //  at android.view.View.updateDisplayListIfDirty(View.java:14951)
2015-09-16 18:59:53 //  at android.view.View.getDisplayList(View.java:15014)
2015-09-16 18:59:53 //  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3661)
2015-09-16 18:59:53 //  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3640)
2015-09-16 18:59:53 //  at android.view.View.updateDisplayListIfDirty(View.java:14951)
2015-09-16 18:59:53 //  at android.view.View.getDisplayList(View.java:15014)
2015-09-16 18:59:53 //  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3661)
2015-09-16 18:59:53 //  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3640)
2015-09-16 18:59:53 //  at android.view.View.updateDisplayListIfDirty(View.java:14951)
2015-09-16 18:59:53 //  at android.view.View.getDisplayList(View.java:15014)
2015-09-16 18:59:53 //  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3661)
2015-09-16 18:59:53 //  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3640)
2015-09-16 18:59:53 //  at android.view.View.updateDisplayListIfDirty(View.java:14951)
2015-09-16 18:59:53 //  at android.view.View.getDisplayList(View.java:15014)
2015-09-16 18:59:53 //  at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:275)
2015-09-16 18:59:53 //  at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:281)
2015-09-16 18:59:53 //  at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:320)
2015-09-16 18:59:53 //  at android.view.ViewRootImpl.draw(ViewRootImpl.java:2741)
2015-09-16 18:59:53 //  at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2573)
2015-09-16 18:59:53 //  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2165)
2015-09-16 18:59:53 //  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1180)
2015-09-16 18:59:53 //  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6558)
2015-09-16 18:59:53 //  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
2015-09-16 18:59:53 //  at android.view.Choreographer.doCallbacks(Choreographer.java:590)
2015-09-16 18:59:53 //  at android.view.Choreographer.doFrame(Choreographer.java:560)
2015-09-16 18:59:53 //  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
2015-09-16 18:59:53 //  at android.os.Handler.handleCallback(Handler.java:739)
2015-09-16 18:59:53 //  at android.os.Handler.dispatchMessage(Handler.java:95)
2015-09-16 18:59:53 //  at android.os.Looper.loop(Looper.java:145)
2015-09-16 18:59:53 //  at android.app.ActivityThread.main(ActivityThread.java:5832)
2015-09-16 18:59:53 //  at java.lang.reflect.Method.invoke(Native Method)
2015-09-16 18:59:53 //  at java.lang.reflect.Method.invoke(Method.java:372)
2015-09-16 18:59:53 //  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
2015-09-16 18:59:53 //  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
2015-09-16 18:59:53 // 
2015-09-16 18:59:53     // Injection Failed
2015-09-16 18:59:53 ** Monkey aborted due to error.
2015-09-16 18:59:53 Events injected: 6471

Can you help on this issue?

Thanks,
Eric

**Comment by jaredsburrows** [comment]
@EfiMIsh @chiahan1123 What versions?
