### ISSUE TITLE
calcMinMax

### ISSUE THREAD

**Issue by yanglichuan** [PhilJay/MPAndroidChart#771]
public boolean removeEntry(T e) {

        if (e == null)
            return false;

        // remove the entry
        boolean removed = mYVals.remove(e);

        if (removed) {

            float val = e.getVal();
            mYValueSum -= val;

            calcMinMax(mLastStart, mLastEnd);
        }

        return removed;
    }

when remove ok， mYVals  size -1

but when calcMinMax  ,hanppen error

error info :+1: 

06-16 17:26:00.851: E/AndroidRuntime(1517): Process: com.xxmassdeveloper.mpchartexample, PID: 1517
06-16 17:26:00.851: E/AndroidRuntime(1517): java.lang.IndexOutOfBoundsException: Invalid index 9, size is 9
06-16 17:26:00.851: E/AndroidRuntime(1517): 	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
06-16 17:26:00.851: E/AndroidRuntime(1517): 	at java.util.ArrayList.get(ArrayList.java:308)
06-16 17:26:00.851: E/AndroidRuntime(1517): 	at com.github.mikephil.charting.data.DataSet.calcMinMax(DataSet.java:130)
06-16 17:26:00.851: E/AndroidRuntime(1517): 	at com.github.mikephil.charting.data.DataSet.removeEntry(DataSet.java:494)
06-16 17:26:00.851: E/AndroidRuntime(1517): 	at com.github.mikephil.charting.data.DataSet.removeEntry(DataSet.java:509)
06-16 17:26:00.851: E/AndroidRuntime(1517): 	at com.github.mikephil.charting.data.ChartData.removeEntry(ChartData.java:694)
06-16 17:26:00.851: E/AndroidRuntime(1517): 	at com.xxmassdeveloper.mpchartexample.LineChartActivity1.removeLastEntry(LineChartActivity1.java:325)
06-16 17:26:00.851: E/AndroidRuntime(1517): 	at com.xxmassdeveloper.mpchartexample.LineChartActivity1.initData(LineChartActivity1.java:172)
06-16 17:26:00.851: E/AndroidRuntime(1517): 	at com.xxmassdeveloper.mpchartexample.LineChartActivity1.access$0(LineChartActivity1.java:171)

**Comment by yanglichuan** [comment]
hi !   you do not give me  the resolvation?
why close it? where is wrong?
