### ISSUE TITLE
java.lang.IllegalArgumentException: width and height must be > 0

### ISSUE THREAD

**Issue by wsk900906** [PhilJay/MPAndroidChart#825]
This problem only happened in some devices.
The full exception:
```
java.lang.IllegalArgumentException: width and height must be > 0
	at android.graphics.Bitmap.createBitmap(Bitmap.java:807)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:786)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:753)
	at com.github.mikephil.charting.renderer.LineChartRenderer.drawData(LineChartRenderer.java:79)
	at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:218)
	at android.view.View.draw(View.java:14467)
	at android.view.View.getDisplayList(View.java:13364)
	at android.view.View.getDisplayList(View.java:13406)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
	at android.view.View.getDisplayList(View.java:13302)
	at android.view.View.getDisplayList(View.java:13406)
	at android.view.View.draw(View.java:14184)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
	at android.view.View.draw(View.java:14470)
	at android.widget.FrameLayout.draw(FrameLayout.java:472)
	at android.widget.ScrollView.draw(ScrollView.java:1603)
	at android.view.View.getDisplayList(View.java:13364)
	at android.view.View.getDisplayList(View.java:13406)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
	at android.view.View.getDisplayList(View.java:13302)
	at android.view.View.getDisplayList(View.java:13406)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
	at android.view.View.getDisplayList(View.java:13302)
	at android.view.View.getDisplayList(View.java:13406)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
	at android.view.View.getDisplayList(View.java:13302)
	at android.view.View.getDisplayList(View.java:13406)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
	at android.view.View.getDisplayList(View.java:13302)
	at android.view.View.getDisplayList(View.java:13406)
	at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1570)
	at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1449)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2424)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2296)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1926)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1015)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5717)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
	at android.view.Choreographer.doFrame(Choreographer.java:544)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5137)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:801)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:617)
	at dalvik.system.NativeStart.main(Native Method)
```
Here is how do I use your library:
I create a LinearLayout in my activity and add LineChart programmatically into this LinearLayout.
and then initial style&data to LineChart.

I have checked the history issues someone post the similar issue. But I used the release was after Apr this year(I think this release has fixed that problem). What should I do to fix it problem?
Thank you!

**Comment by wsk900906** [comment]
find the solution has been fixed in https://github.com/PhilJay/MPAndroidChart/issues/554.

Very Thank You!
