### ISSUE TITLE
Toggle lines with enabled marker causes crash

### ISSUE THREAD

**Issue by silva96** [PhilJay/MPAndroidChart#898]
When you enable a marker and start togling lines in a chart, suddenly the app crashes without apparent reason. 

Please see this video: https://www.youtube.com/watch?v=mLWn1Rgitak

Here is the logcat:

```java
07-27 11:23:09.427    2330-2330/cl.tidchile.agrovva E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: cl.tidchile.agrovva, PID: 2330
    java.lang.IndexOutOfBoundsException: Invalid index 3, size is 3
            at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
            at java.util.ArrayList.get(ArrayList.java:308)
            at com.github.mikephil.charting.data.ChartData.getEntryForHighlight(ChartData.java:475)
            at com.github.mikephil.charting.charts.Chart.drawMarkers(Chart.java:567)
            at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:241)
            at android.view.View.draw(View.java:15249)
            at android.view.View.draw(View.java:15158)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3407)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3200)
            at android.view.View.draw(View.java:15156)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3407)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3200)
            at android.view.View.draw(View.java:15252)
            at android.support.v4.view.ViewPager.draw(ViewPager.java:2176)
            at android.view.View.buildDrawingCacheImpl(View.java:14495)
            at android.view.View.buildDrawingCache(View.java:14357)
            at android.view.View.updateDisplayListIfDirty(View.java:14166)
            at android.view.View.getDisplayList(View.java:14207)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3391)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3370)
            at android.view.View.updateDisplayListIfDirty(View.java:14145)
            at android.view.View.getDisplayList(View.java:14207)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3391)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3370)
            at android.view.View.updateDisplayListIfDirty(View.java:14145)
            at android.view.View.getDisplayList(View.java:14207)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3391)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3370)
            at android.view.View.updateDisplayListIfDirty(View.java:14145)
            at android.view.View.getDisplayList(View.java:14207)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3391)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3370)
            at android.view.View.updateDisplayListIfDirty(View.java:14145)
            at android.view.View.getDisplayList(View.java:14207)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3391)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3370)
            at android.view.View.updateDisplayListIfDirty(View.java:14145)
            at android.view.View.getDisplayList(View.java:14207)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3391)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3370)
            at android.view.View.updateDisplayListIfDirty(View.java:14145)
            at android.view.View.getDisplayList(View.java:14207)
            at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:273)
            at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:279)
            at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:318)
            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2560)
            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2382)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2012)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1084)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5990)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
            at android.view.Choreographer.doCallbacks(Choreographer.java:580)
            at android.view.Choreographer.doFrame(Choreographer.java:550)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5343)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
```

**Comment by PhilJay** [comment]
Can you show your code of toggling the datasets?

**Comment by c-castillo** [comment]
That was the solution, it worked.

Thanks a lot!

**Comment by c-castillo** [comment]
@PhilJay are you planning to release a 2.1.3 version anytime soon?

**Comment by PhilJay** [comment]
Yes, I am. There are some minor things that still need fixing, but I am thinking about releasing this weekend.

**Comment by PhilJay** [comment]
v2.1.3

**Comment by ElenaLee** [comment]
The ios-charts has the same error.When set the combined chart a marker,the application crash at the "getEntryForHighlight" method. the error log is  "Index out of range".

**Comment by Wicked0ne** [comment]
I'm getting this on version v2.2.5. Possible regression?


```java
Process: my.package.name, PID: 11155
Theme: themes:{default=, iconPack:com.sikebox.retrorika.material.icons}
java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
   at java.util.ArrayList.get(ArrayList.java:310)
   at com.github.mikephil.charting.data.ChartData.getEntryForHighlight(ChartData.java:479)
   at com.github.mikephil.charting.charts.Chart.drawMarkers(Chart.java:692)
   at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:286)
   at android.view.View.draw(View.java:16187)
   at android.view.View.updateDisplayListIfDirty(View.java:15184)
   at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
   at android.view.View.updateDisplayListIfDirty(View.java:15144)
   at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
   at android.view.View.updateDisplayListIfDirty(View.java:15144)
   at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
   at android.view.View.updateDisplayListIfDirty(View.java:15144)
   at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
   at android.view.View.updateDisplayListIfDirty(View.java:15144)
   at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
   at android.view.View.updateDisplayListIfDirty(View.java:15144)
   at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
   at android.view.View.updateDisplayListIfDirty(View.java:15144)
   at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
   at android.view.View.updateDisplayListIfDirty(View.java:15144)
   at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:282)
   at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:288)
   at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:323)
   at android.view.ViewRootImpl.draw(ViewRootImpl.java:2623)
   at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2442)
   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2075)
   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1115)
   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6023)
   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
   at android.view.Choreographer.doCallbacks(Choreographer.java:670)
   at android.view.Choreographer.doFrame(Choreographer.java:606)
   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
   at android.os.Handler.handleCallback(Handler.java:739)
   at android.os.Handler.dispatchMessage(Handler.java:95)
   at android.os.Looper.loop(Looper.java:148)
   at android.app.ActivityThread.main(ActivityThread.java:5461)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
   at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:134)
```
