### ISSUE TITLE
MPAndroidChart: java.lang.OutOfMemoryError at Galaxy S4 

### ISSUE THREAD

**Issue by yeongthai** [PhilJay/MPAndroidChart#932]
I got an error report which is OutOfMemoryError from Galaxy S4 device. I did some testing for the graph on OnePlus, S3, S6 Edge and Sony Z3. These devices have no issue with graph.  is anyone know what is the issue on this report? Thanks!

ava.lang.OutOfMemoryError
at android.graphics.Bitmap.nativeCreate(Native Method)
at android.graphics.Bitmap.createBitmap(Bitmap.java:903)
at android.graphics.Bitmap.createBitmap(Bitmap.java:880)
at android.graphics.Bitmap.createBitmap(Bitmap.java:847)
at com.github.mikephil.charting.renderer.LineChartRenderer.drawData(LineChartRenderer.java:85)
at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:213)
at android.view.View.draw(View.java:15303)
at android.view.View.getDisplayList(View.java:14197)
at android.view.View.getDisplayList(View.java:14239)
at android.view.View.draw(View.java:15017)
at android.view.ViewGroup.drawChild(ViewGroup.java:3298)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3135)
at android.view.View.draw(View.java:15306)
at android.view.View.getDisplayList(View.java:14197)
at android.view.View.getDisplayList(View.java:14239)
at android.view.View.draw(View.java:15017)
at android.view.ViewGroup.drawChild(ViewGroup.java:3298)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3135)
at android.view.View.getDisplayList(View.java:14192)
at android.view.View.getDisplayList(View.java:14239)
at android.view.View.draw(View.java:15017)
at android.view.ViewGroup.drawChild(ViewGroup.java:3298)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3135)
at android.view.View.draw(View.java:15306)
at android.widget.FrameLayout.draw(FrameLayout.java:472)
at android.widget.ScrollView.draw(ScrollView.java:2164)
at android.view.View.getDisplayList(View.java:14197)
at android.view.View.getDisplayList(View.java:14239)
at android.view.View.draw(View.java:15017)
at android.view.ViewGroup.drawChild(ViewGroup.java:3298)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3135)
at android.view.View.draw(View.java:15306)
at android.view.View.getDisplayList(View.java:14197)
at android.view.View.getDisplayList(View.java:14239)
at android.view.View.draw(View.java:15017)
at android.view.ViewGroup.drawChild(ViewGroup.java:3298)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3135)
at android.view.View.getDisplayList(View.java:14192)
at android.view.View.getDisplayList(View.java:14239)
at android.view.View.draw(View.java:15017)
at android.view.ViewGroup.drawChild(ViewGroup.java:3298)
at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1060)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3135)
at android.view.View.draw(View.java:15306)
at android.view.View.getDisplayList(View.java:14197)
at android.view.View.getDisplayList(View.java:14239)
at android.view.View.draw(View.java:15017)
at android.view.ViewGroup.drawChild(ViewGroup.java:3298)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3135)
at android.view.View.getDisplayList(View.java:14192)
at android.view.View.getDisplayList(View.java:14239)
at android.view.View.draw(View.java:15017)
at android.view.ViewGroup.drawChild(ViewGroup.java:3298)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3135)
at android.view.View.draw(View.java:15306)
at com.android.internal.widget.ActionBarOverlayLayout.draw(ActionBarOverlayLayout.java:445)
at android.view.View.getDisplayList(View.java:14197)
at android.view.View.getDisplayList(View.java:14239)
at android.view.View.draw(View.java:15017)
at android.view.ViewGroup.drawChild(ViewGroup.java:3298)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3135)
at android.view.View.draw(View.java:15306)
at android.widget.FrameLayout.draw(FrameLayout.java:472)
at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2568)
at android.view.View.getDisplayList(View.java:14197)
at android.view.View.getDisplayList(View.java:14239)
at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1570)
at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1449)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:2705)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2571)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2143)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1236)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6471)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:803)
at android.view.Choreographer.doCallbacks(Choreographer.java:603)
at android.view.Choreographer.doFrame(Choreographer.java:573)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:789)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:157)
at android.app.ActivityThread.main(ActivityThread.java:5356)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
at dalvik.system.NativeStart.main(Native Method)

**Comment by PhilJay** [comment]
Well, the chart draws some things on a bitmap and then draws the bitmap.
There is obviously not enough memory on your device at time of chart render to do that, thats why it crashes.

**Comment by jaredsburrows** [comment]
@yeongthai What version?

**Comment by ablenesi** [comment]
@jaredsburrows v2.1.0  affects multiple users even Samsung S5 , note 3.

**Comment by jaredsburrows** [comment]
@ablenesi Try upgrading to the latest - `compile 'com.github.PhilJay:MPAndroidChart:v2.2.4'`.
