### ISSUE TITLE
Exception in linechart

### ISSUE THREAD

**Issue by pk178** [PhilJay/MPAndroidChart#940]
Hi,

I got an exception in linechart, the exceptio occurs randomly, this is the exception :

    java.lang.NullPointerException
            at com.github.mikephil.charting.renderer.LineChartRenderer.drawLinear(LineChartRenderer.java:296)
            at com.github.mikephil.charting.renderer.LineChartRenderer.drawDataSet(LineChartRenderer.java:121)
            at com.github.mikephil.charting.renderer.LineChartRenderer.drawData(LineChartRenderer.java:98)
            at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:230)
            at android.view.View.draw(View.java)
            at android.view.View.getDisplayList(View.java)
            at android.view.View.getDisplayList(View.java)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java)
            at android.view.View.getDisplayList(View.java)
            at android.view.View.getDisplayList(View.java)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java)
            at android.view.View.getDisplayList(View.java)
            at android.view.View.getDisplayList(View.java)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java)
            at android.view.View.getDisplayList(View.java)
            at android.view.View.getDisplayList(View.java)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java)
            at android.view.View.getDisplayList(View.java)
            at android.view.View.getDisplayList(View.java)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java)
            at android.view.View.getDisplayList(View.java)
            at android.view.View.getDisplayList(View.java)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java)
            at android.view.View.getDisplayList(View.java)
            at android.view.View.getDisplayList(View.java)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java)
            at android.view.View.getDisplayList(View.java)
            at android.view.View.getDisplayList(View.java)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java)
            at android.view.View.getDisplayList(View.java)
            at android.view.View.getDisplayList(View.java)
            at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java)
            at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java)
            at android.view.ViewRootImpl.draw(ViewRootImpl.java)
            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java)
            at android.view.Choreographer.doCallbacks(Choreographer.java)
            at android.view.Choreographer.doFrame(Choreographer.java)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java)
            at android.os.Handler.handleCallback(Handler.java)
            at android.os.Handler.dispatchMessage(Handler.java)
            at android.os.Looper.loop(Looper.java)
            at android.app.ActivityThread.main(ActivityThread.java)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
            at dalvik.system.NativeStart.main(Native Method)

This is my setup code for graph : 

ecgLineDataSet = new LineDataSet(null, "ECG Dataset");

1. Init dataset :
        ecgLineDataSet.enableDashedLine(1f, 1f, 0f);
        ecgLineDataSet.setColor(Color.BLACK);
        ecgLineDataSet.setCircleColor(Color.BLACK);
        ecgLineDataSet.setLineWidth(1f);
        ecgLineDataSet.setCircleSize(3f);
        ecgLineDataSet.setDrawCircleHole(false);
        ecgLineDataSet.setValueTextSize(9f);
        ecgLineDataSet.setFillAlpha(65);
        ecgLineDataSet.setFillColor(Color.BLACK);
        ecgLineDataSet.setDrawValues(false);
        ecgLineDataSet.setDrawCircles(false);

        ecgData = new LineData();
        ecgData.addDataSet(ecgLineDataSet);
..
2. Update linedata every 5ms :

ecgData.addXValue(time + "");
            ecgData.addEntry(new Entry((float) value, ecgCounter), 0);

3. Move chart to make realtime update :

mChart.setVisibleXRangeMaximum(120);
                mChart.moveViewToX(mChart.getData().getXValCount() - 121);
                mChart.notifyDataSetChanged();

I don't know why, pls help me to find where can make exception :(

**Comment by PhilJay** [comment]
dont do this:

mChart.moveViewToX(mChart.getData().getXValCount() - 121);
mChart.notifyDataSetChanged();

do this:

mChart.notifyDataSetChanged();
mChart.moveViewToX(mChart.getData().getXValCount() - 121);

**Comment by pk178** [comment]
Thanks for reply,

I tried, but didn't success, that exception still occurs,.

I have to left a try..catch into "com.github.mikephil.charting.charts.BarLineChartBase.onDraw" : 

try{
            mRenderer.drawData(canvas);
        }catch (Exception ex){

        }

**Comment by Awais16** [comment]
@pk178 not sure but you are probably doing to much work on ui.
i fixed it using 

view.post(new Runnable() {
            @Override
            public void run() {
                addXleroMeterEntry(x,y,z,time);
            }
        });

probably bad solution.
