### ISSUE TITLE
LegendRenderer hitting an ArrayIndexOutOfBoundsException 

### ISSUE THREAD

**Issue by rtatavarty** [PhilJay/MPAndroidChart#947]
Encountered a crash when setting legend position to BELOW_CHART_CENTER for a PieChart.
However, there is no crash if this setting is removed.
Number of entries are 5. The Chart settings are as follows:

<pre>
<code>
		 pieChart.setHoleRadius(80f);
		 pieChart.setTransparentCircleRadius(80f);
		 pieChart.setCenterText("TOP RESULTS");
		 pieChart.setCenterTextColor(Color.rgb(221,221,221));
		 pieChart.setCenterTextSize(17.78f);
		 pieChart.setCenterTextWordWrapEnabled(true);
		 pieChart.setCenterTextTypeface(regular);
		 pieChart.setNoDataText("");
		 pieChart.setDrawCenterText(true);
		 pieChart.setDrawSliceText(false);
		 pieChart.setDescription("");
		 pieChart.setDrawHoleEnabled(true);
		 pieChart.setHoleColorTransparent(true);
		 pieChart.getLegend().setWordWrapEnabled(true);
		 pieChart.getLegend().setFormSize(12);
		 pieChart.getLegend().setTextSize(12);
		 pieChart.getLegend().setTextColor(Color.rgb(221,221,221));
		 pieChart.getLegend().setTypeface(regular);
		//  pieChart.getLegend().setPosition(LegendPosition.BELOW_CHART_CENTER);  // error causing setting.
		 pieChart.getLegend().setMaxSizePercent(0.5f);
</code>
</pre>

The backtrace is as follows:

<pre>
<code>
 java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
 	at com.github.mikephil.charting.renderer.LegendRenderer.renderLegend(LegendRenderer.java:239)
 	at com.github.mikephil.charting.charts.PieChart.onDraw(PieChart.java:114)
 	at android.view.View.draw(View.java:15231)
 	at android.view.View.updateDisplayListIfDirty(View.java:14167)
 	at android.view.View.getDisplayList(View.java:14189)
 	at android.view.View.draw(View.java:14959)
 	at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
 	at android.view.View.updateDisplayListIfDirty(View.java:14162)
 	at android.view.View.getDisplayList(View.java:14189)
 	at android.view.View.draw(View.java:14959)
 	at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
 	at android.widget.ListView.drawChild(ListView.java:3396)
 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
 	at android.widget.AbsListView.dispatchDraw(AbsListView.java:2603)
 	at android.widget.ListView.dispatchDraw(ListView.java:3391)
 	at android.view.View.draw(View.java:15234)
 	at android.widget.AbsListView.draw(AbsListView.java:4110)
 	at android.view.View.updateDisplayListIfDirty(View.java:14167)
 	at android.view.View.getDisplayList(View.java:14189)
 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
 	at android.view.View.updateDisplayListIfDirty(View.java:14127)
 	at android.view.View.getDisplayList(View.java:14189)
 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
 	at android.view.View.updateDisplayListIfDirty(View.java:14127)
 	at android.view.View.getDisplayList(View.java:14189)
 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
 	at android.view.View.updateDisplayListIfDirty(View.java:14127)
 	at android.view.View.getDisplayList(View.java:14189)
 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
 	at android.view.View.updateDisplayListIfDirty(View.java:14127)
 	at android.view.View.getDisplayList(View.java:14189)
 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
 	at android.view.View.updateDisplayListIfDirty(View.java:14127)
 	at android.view.View.getDisplayList(View.java:14189)
 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
 	at android.view.View.updateDisplayListIfDirty(View.java:14127)
 	at android.view.View.getDisplayList(View.java:14189)
 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
 	at android.view.View.updateDisplayListIfDirty(View.java:14127)
 	at android.view.View.getDisplayList(View.java:14189)
 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
 	at android.view.View.updateDisplayListIfDirty(View.java:14127)
 	at android.view.View.getDisplayList(View.java:14189)
 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:273)
 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:279)
 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:318)
 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2530)
 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2352)
 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1982)
 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
 	at andr
</code>
</pre>

Appreciate the good work!
Regards!

**Comment by nepeee** [comment]
Change LegendRenderer.java (line 231) from this:
                int lineIndex = 0;

                for (int i = 0, count = labels.length; i < count; i++) {
                    if (calculatedLabelBreakPoints[i]) {
                        posX = originPosX;
                        posY += labelLineHeight + labelLineSpacing;
                    }

                    if (posX == originPosX && legendPosition == Legend.LegendPosition.BELOW_CHART_CENTER) {
                        posX += (direction == Legend.LegendDirection.RIGHT_TO_LEFT ? calculatedLineSizes[lineIndex].width : -calculatedLineSizes[lineIndex].width) / 2.f;
                        lineIndex++;
                    }

                    boolean drawingForm = colors[i] != ColorTemplate.COLOR_SKIP;
                    boolean isStacked = labels[i] == null; // grouped forms have null labels


to this:
                int lineIndex = 0;
                if (legendPosition == Legend.LegendPosition.BELOW_CHART_CENTER) {
                    posX += (direction == Legend.LegendDirection.RIGHT_TO_LEFT ? calculatedLineSizes[lineIndex].width : -calculatedLineSizes[lineIndex].width) / 2.f;
                    lineIndex++;
                }

                for (int i = 0, count = labels.length; i < count; i++) {
                    if (calculatedLabelBreakPoints[i]) {
                        posX = originPosX;
                        posY += labelLineHeight + labelLineSpacing;
                    
                        if (legendPosition == Legend.LegendPosition.BELOW_CHART_CENTER) {
                            posX += (direction == Legend.LegendDirection.RIGHT_TO_LEFT ? calculatedLineSizes[lineIndex].width : -calculatedLineSizes[lineIndex].width) / 2.f;
                            lineIndex++;
                        }
                    }

                    boolean drawingForm = colors[i] != ColorTemplate.COLOR_SKIP;
                    boolean isStacked = labels[i] == null; // grouped forms have null labels

**Comment by PhilJay** [comment]
This is now fixed, also, read the bottom few lines of this: 
https://github.com/PhilJay/MPAndroidChart/wiki/Dynamic-&-Realtime-Data
