### ISSUE TITLE
Crash on Chart.onSizeChanged

### ISSUE THREAD

**Issue by slai47** [PhilJay/MPAndroidChart#997]
java.lang.OutOfMemoryError: Failed to allocate a 4592652 byte allocation with 4449944 free bytes and 4MB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:939)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:912)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:879)
       at com.github.mikephil.charting.charts.Chart.onSizeChanged(Chart.java:1518)
       at android.view.View.sizeChange(View.java:16658)
       at android.view.View.setFrame(View.java:16631)
       at android.view.View.layout(View.java:16546)
       at android.view.ViewGroup.layout(ViewGroup.java:5303)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2102)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1956)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1865)
       at android.view.View.layout(View.java:16550)
       at android.view.ViewGroup.layout(ViewGroup.java:5303)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
       at android.view.View.layout(View.java:16550)
       at android.view.ViewGroup.layout(ViewGroup.java:5303)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2102)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1956)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1865)
       at android.view.View.layout(View.java:16550)
at android.view.ViewGroup.layout(ViewGroup.java:5303)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
       at android.widget.ScrollView.onLayout(ScrollView.java:2284)
       at android.view.View.layout(View.java:16550)
       at android.view.ViewGroup.layout(ViewGroup.java:5303)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
       at android.view.View.layout(View.java:16550)
       at android.view.ViewGroup.layout(ViewGroup.java:5303)
       at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1626)
       at android.view.View.layout(View.java:16550)
       at android.view.ViewGroup.layout(ViewGroup.java:5303)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2102)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1956)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1865)
       at android.view.View.layout(View.java:16550)
       at android.view.ViewGroup.layout(ViewGroup.java:5303)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
       at android.view.View.layout(View.java:16550)
       at android.view.ViewGroup.layout(ViewGroup.java:5303)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2102)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1956)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1865)
       at android.view.View.layout(View.java:16550)
       at android.view.ViewGroup.layout(ViewGroup.java:5303)
       at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:907)
       at android.view.View.layout(View.java:16550)
       at android.view.ViewGroup.layout(ViewGroup.java:5303)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
       at android.view.View.layout(View.java:16550)
at android.view.ViewGroup.layout(ViewGroup.java:5303)
       at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:907)
       at android.view.View.layout(View.java:16550)
       at android.view.ViewGroup.layout(ViewGroup.java:5303)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
       at android.view.View.layout(View.java:16550)
       at android.view.ViewGroup.layout(ViewGroup.java:5303)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2102)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1956)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1865)
       at android.view.View.layout(View.java:16550)
       at android.view.ViewGroup.layout(ViewGroup.java:5303)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
       at android.view.View.layout(View.java:16550)
       at android.view.ViewGroup.layout(ViewGroup.java:5303)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2102)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1956)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1865)
       at android.view.View.layout(View.java:16550)
       at android.view.ViewGroup.layout(ViewGroup.java:5303)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
       at android.view.View.layout(View.java:16550)
       at android.view.ViewGroup.layout(ViewGroup.java:5303)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2308)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2021)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1180)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6558)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
       at android.view.Choreographer.doCallbacks(Choreographer.java:590)
       at android.view.Choreographer.doFrame(Choreographer.java:560)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
       at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5832)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

I'm experiencing this issue on my app WoT Community Assistant. Mostly Samsung and Asus issues. I am loading up a lot of graphs but this seems to cause issues a lot. Any ideas?

**Comment by PhilJay** [comment]
Update to latest version
